### ISSUE TITLE
Process was not started by this object, so requested information cannot be determined

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2666] opened 2015-04-13 15:34 UTC
What does this exception mean:
```
ScErrUnexpectedCommandException (SCERR10016): Starting Images in default failed due to an unexpected problem.
 Version: 2.0.3121.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.InvalidOperationException: Process was not started by this object, so requested information cannot be determined.
 at System.Diagnostics.Process.EnsureState(State state)
 at System.Diagnostics.Process.get_ExitCode()
 at Starcounter.Server.DatabaseEngine.CreateEngineProcessTerminated(Process engineProcess, Database database, UInt32 errorCode, Exception serverException) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3121.3\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:line 726
 at Starcounter.Server.Commands.StartExecutableCommandProcessor.CreateExceptionIfCodeHostTerminated(Process codeHostProcess, Database database, Exception ex) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3121.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 206
 at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__4(CommandTask task) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3121.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 171
 at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass1.<WithinTask>b__0(CommandTask t) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3121.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
 at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3121.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
 at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3121.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
 HResult=-2146233079

```

**Comment by dan31** [comment] 2015-04-13 15:45
@alemoi, @per-samuelsson – can you take a look?
@miyconst, how often does that happen?

**Comment by miyconst** [comment] 2015-04-13 16:03
@dan31 the exception happens when I rename *.json files.

I assume that there is some code generator which does not recognize new file name.
If I open the json file and press Ctrl + S a couple more time, the code re-generates and the exception goes away.

It also happens when Working directory is set to a non existing directory.

Anyway, the exception should be more informative.

**Comment by per-samuelsson** [comment] 2015-04-14 07:32
Not sure whats causing this, but it appears that it's a monitoring thing that occur when an application is about to start, but fails somewhere in the bootstrapping of the code host.

> Anyway, the exception should be more informative.

Yes, of course. But this error is not really one we expect, so I'd like to find the reason to it. The failure occurs when the admin server library tries to create an informative exception that are to describe the failing code host.

> It also happens when Working directory is set to a non existing directory

I'll elaborate a little to see if I can provoke it. Thanks.

**Comment by per-samuelsson** [comment] 2015-04-16 07:27
> I'll elaborate a little to see if I can provoke it.

I have now spent time both testing hands-on, without being able to reproduce this, and read throughly about the Process class and reviewed our code. I really can't find anything that we seem to do "wrong", and hence I can't understand how this can happen.

What I'm planning to do now is to add a few extra calls in a few places, and to finally guard for this to happen, and use a dedicated error code for this particular scenario. Then we can see if it happens again, and if so, maybe I can give it another round at that point.

**Comment by per-samuelsson** [comment] 2015-04-16 08:34
@miyconst 

BTW, when/if you experience this again, can you take a look in the log for any recent warnings or errors? 

Either an error stating something like *When asked to shut down, the user code process agreed to shut down, but the process...*, and/or a warning like *User code process takes longer than expected to exit* is of interest. 

Thanks!

**Comment by per-samuelsson** [comment] 2015-04-16 09:56
OK, so now I've pushed a few tweaks that will hopefully improve the experience here, they are in **develop** within this https://github.com/Starcounter/Starcounter/commit/373f5139a0a3c2b0895de34f4fb6cc3050a6a508 merge. I'll also merge it to **next** eventually.

I'll keep this issue open for some time, to see if I can get any more feedback as per request, and to see if the problem seem to remain.

**Comment by miyconst** [comment] 2015-04-17 07:53
@per-samuelsson with the new SC build I also could not reproduce the bug. I will write here if it happens again.

**Comment by per-samuelsson** [comment] 2015-04-17 08:08
> @per-samuelsson with the new SC build I also could not reproduce the bug.

Nice. Then my tweaks might actually worked. Thanks for reporting.

> I will write here if it happens again.

Good. I'll close this issue for now then. When/if you repost, I will reopen it.

**Closed by per-samuelsson** 2015-04-17 08:08 UTC
Labels: bug, Newbie issues, question
