### ISSUE TITLE
ScErrOutOfMemoryAbort, when delete data.

### ISSUE THREAD

**Issue by JingkunLi** [Starcounter/Starcounter#798] opened 2013-08-19 14:26 UTC
When delete data I got ScErrOutOfMemoryAbort .

  Db.SlowSQL("DELETE FROM WebPlayer");

There are 5 Million rows in the table, and Memory usage is only 10%.

```
 2013-08-19 T 16:18:45 ScErrOutOfMemoryAbort (SCERR8005): The transaction was aborted because of a failure to allocate memory.
Version: 2.0.744.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8005.
   at Starcounter.Db.Delete(IObjectProxy proxy)
   at Starcounter.Query.Sql.SqlProcessor.ProcessDelete(String statement, Object[] values)
   at Starcounter.Query.Sql.SqlProcessor.ProcessDQuery(String statement, Object[] values)
   at Starcounter.Db.SlowSQL(String query, Object[] values)
   at NewPokerDemo.Program.<>c__DisplayClass3f.<DeleteFromTable>b__3e() in d:\NewPokerDemo\NewPokerDemoSrv\Program.cs:line 380
   at Starcounter.Db.Transaction(Action action)
   at NewPokerDemo.Program.<Main>b__11(String tablename) in d:\NewPokerDemo\NewPokerDemoSrv\Program.cs:line 125
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Internal.HandlersManagement.RunDelegate(Request r, Response& resource)
   at Starcounter.Internal.Web.AppRestServer.HandleRequest(Request request)

```

**Comment by dan31** [comment] 2016-11-20 15:12
I have ran the following code, getting 8 out of 16 Gb consumed. I cannot confirm the issue is reproduced in any context, neither it has been over the last 2 years. I am closing the issue at this late date.

```
using System;
using Starcounter;
using System.Diagnostics;

namespace SCTest003 {
    [Database]
    public class Person {
        public string FirstName;
        public string LastName;
    }

    class Program {
        static void Main () {
            Db.Transact (() => {
                Db.SlowSQL ("DELETE FROM SCTest003.Person");
            });
            Debug.WriteLine ("Cleanup done!");
            for (int i = 0; i < 10000000; ++i) {
                Db.Transact (() => {
                    var p = new Person ();
                    p.FirstName = "John";
                    p.LastName = "Doe";
                });
                if (i % 100000 == 0)
                    Debug.WriteLine ($"{i}");
            }
            Db.Transact (() => {
                Db.SlowSQL ("DELETE FROM SCTest003.Person");
            });
            Debug.WriteLine ("Cleanup done again!");
        }
    }
}
```

**Closed by dan31** 2016-11-20 15:12 UTC
Labels: Bluestar, document, enhancement, stability issue, test, Wiki

**Comment by dan31** [comment] 2016-11-20 17:06
Increasing the limit to 100'000'000, I've managed to populate them all, but then the last transaction with ```Db.SlowSQL``` has failed with the other message:

```
Additional information: ScErrMemoryLimitReachedAbort (SCERR8036): The transaction was aborted because limit reached on limited memory resource.
```

I guess this is related to a "size of transaction" and is expected behavior. What is desired there is a fine explanation to the behavior. A special issue is created for that: https://github.com/Starcounter/Starcounter/issues/3958.
