### ISSUE TITLE
Fix debug nightly SQL processor tests

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2907] opened 2015-09-25 08:29 UTC
Fails on MultithreadedTest. Not sure if its my latest changes that caused, since on my computer multithreaded unit test in debug always fails. I will review my changes and see if I find something. 

https://scbuildserver/viewLog.html?buildId=30677&buildTypeId=Starcounter_Develop_Nightly_Debug&tab=buildLog

**Comment by alemoi** [comment] 2015-09-25 19:40
Disabling usage of in-memory LLVM does not help here.
Question to @k-rus: why `SqlProcessor.scsql_dump_memory_leaks()` is only checked for Debug build? Does it only work only in Debug?

**Comment by k-rus** [comment] 2015-09-30 10:26
The test can be run only in Debug configuration. The test uses [_CrtDumpMemoryLeaks](https://msdn.microsoft.com/en-us/library/d41t22sb.aspx?f=255&MSPPError=-2147217396). Failing the test means that there is a potential memory leak, which our users might suffer.

**Comment by k-rus** [comment] 2015-09-30 10:31
See also #1578

**Comment by alemoi** [comment] 2016-06-01 16:04
This is still an issue even for sequential SQL test (`SequentialTest()`):
```
[16:24:43][Step 1/1] --- Running unit tests in: C:\BuildAgent\work\sc-develop-nightly-debug-527/Level1/bin/Debug\Starcounter.SqlProcessor.Tests.exe
[16:24:43][Step 1/1] NUnit-Console version 2.6.2.12296
[16:24:43][Step 1/1] Copyright (C) 2002-2012 Charlie Poole.
[16:24:43][Step 1/1] Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
[16:24:43][Step 1/1] Copyright (C) 2000-2002 Philip Craig.
[16:24:43][Step 1/1] All Rights Reserved.
[16:24:43][Step 1/1] 
[16:24:43][Step 1/1] Runtime Environment - 
[16:24:43][Step 1/1]    OS Version: Microsoft Windows NT 6.2.9200.0
[16:24:43][Step 1/1]   CLR Version: 2.0.50727.8009 ( Net 3.5 )
[16:24:43][Step 1/1] 
[16:24:43][Step 1/1] ProcessModel: Default    DomainUsage: Single
[16:24:43][Step 1/1] Execution Runtime: net-3.5
[16:24:44][Step 1/1] ***** Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.SequentialTest
[16:24:44][Step 1/1] Detected memory leaks!
[16:24:44][Step 1/1] Dumping objects ->
[16:24:44][Step 1/1] {227} normal block at 0x000000001BBB2860, 16 bytes long.
[16:24:44][Step 1/1]  Data: < C              > A8 43 F6 EE FA 7F 00 00 00 00 00 00 00 00 00 00 
[16:24:44][Step 1/1] {226} normal block at 0x000000001BB09860, 80 bytes long.
[16:24:44][Step 1/1]  Data: <`       `       > 60 98 B0 1B 00 00 00 00 60 98 B0 1B 00 00 00 00 
[16:24:44][Step 1/1] Object dump complete.
[16:24:44][Step 1/1] ***** Starcounter.SqlProcessor.Tests.PerformanceTest.PerformanceTests
[16:24:50][Step 1/1] Performed query: SELECT a FROM account a
[16:24:50][Step 1/1] 100000 iterations in 5072 ms, 50,72 mcs.
[16:24:50][Step 1/1] ***** Starcounter.SqlProcessor.Tests.SqlProcessorTests.HelloProcessor
[16:24:50][Step 1/1] ***** Starcounter.SqlProcessor.Tests.SqlProcessorTests.SqlSyntax
[16:24:50][Step 1/1] 
[16:24:50][Step 1/1] Tests run: 4, Errors: 0, Failures: 1, Inconclusive: 0, Time: 5,29911 seconds
[16:24:50][Step 1/1]   Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
[16:24:50][Step 1/1] 
[16:24:50][Step 1/1] Errors and Failures:
[16:24:50][Step 1/1] 1) Test Failure : Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.SequentialTest
[16:24:50][Step 1/1]      Expected: 0
[16:24:50][Step 1/1]   But was:  1
[16:24:50][Step 1/1] 
[16:24:50][Step 1/1] at Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.SequentialTest() in C:\BuildAgent\work\sc-develop-nightly-debug-527\Level1\src\Starcounter.SqlProcessor.Tests\MultiThreadedMemoryLeakTests.cs:line 80
[16:24:50][Step 1/1] 
```

I looked at the code and its very primitive and uses internal native calls to `scsql_process_query` which maybe uses Bison underneath that causes memory leak, but this is just a guess:
```
        public static unsafe Exception CallSqlProcessor(String query) {
            uint err = scsql_process_query(query);
            if (err == 0)
                return null;
            Exception ex = GetSqlException(err, query);
            Debug.Assert(err == (uint)ex.Data[ErrorCode.EC_TRANSPORT_KEY]);
            Debug.Assert(err < 10000);
            // create the exception
            scsql_free_memory();
            Debug.Assert(err == (uint)ex.Data[ErrorCode.EC_TRANSPORT_KEY]);
            Debug.Assert(err < 10000);
            return ex;
        }
```

Assigning to @k-rus because you are probably the best person to investigate this.
Its a hinder for the develop debug build project to succeed.

I made one more isolation test, I run it completely separate on the machine (independent from other unit tests):
```
"c:\Program Files (x86)\NUnit 2.6.2\bin\nunit-console.exe" C:\BuildAgent\work\sc-develop-nightly-debug-528/Level1/bin/Debug\Starcounter.SqlProcessor.Tests.exe /labels
```
And it still fails on `Assert.AreEqual(0, SqlProcessor.scsql_dump_memory_leaks());`, so something must be in these native SQL calls, that's my assumption.

**Comment by k-rus** [comment] 2016-06-03 15:53
Can @2114 be a reason?

**Comment by k-rus** [comment] 2016-06-05 08:00
This is duplicate of #1578

**Comment by alemoi** [comment] 2016-06-07 14:18
Thanks for finding the duplicate. I didn't investigate deeper but are you sure that code generation is used for that unit test?

**Comment by alemoi** [comment] 2016-06-14 00:41
> Can #2114 be a reason?

To be sure that codegen is not used for this test I simply renamed scllvm.dll and clang++.exe - the test runs ok without them, so they are not used. I see there are some memory allocations in `scsql_process_query`, maybe something is not freed there?

CC @k-rus 
Not setting the label showstopper but its quite high prio because all debug builds are failing because of this.

**Comment by k-rus** [comment] 2016-07-09 11:37
> Not setting the label showstopper but its quite high prio because all debug builds are failing because of this.

As you can see the problem has existed for two years already. Thus it is not easy to say what are the problems with it. I think now native test of SQL parser in Bluestar replicates the managed test and checks memory leaking, thus this failing test can be disabled in the nightly debug project. I think it is still good to keep in other builds, where it doesn't fail, since it doesn't check memory leak.

**Comment by alemoi** [comment] 2016-09-21 12:41
@k-rus are you going to disable this test?

**Comment by k-rus** [comment] 2016-09-21 14:37
We don't know what is the source or sources of the problem. Originally there were some leakage in other tests. I didn't look to the current state of the problem. So far this was not a concern to investigate the potential memory leaking in 2.x. If so, then the test can be disabled.

**Comment by k-rus** [comment] 2016-09-21 15:05
I am not a right person do decide, but imho the test can be disabled.

**Comment by dan31** [comment] 2016-09-21 15:15
Well, if this memory leak takes place every time QP is invoked, this requires investigation. @k-rus, does it? 2.x will be run for quite some time by current users, linear memory leaks aren't an option. I cannot derive from this issue (and 3 accompanied issues) if this occurs every call (linear memory leak) or just at a startup time (constant memory leak). Both are not good, but you understand that the former is severe.

I am also not sure if the _Crt function is used correctly. @alemoi, how come is this there in June 2016: "CLR Version: 2.0.50727.8009 ( Net 3.5 )"?

**Comment by alemoi** [comment] 2016-09-21 15:25
> I am also not sure if the _Crt function is used correctly. @alemoi, how come is this there in June 2016: "CLR Version: 2.0.50727.8009 ( Net 3.5 )"?

@dan31 you are talking about old NUnit here I suppose. I can upgrade to the newest version and see if it helps.

**Comment by alemoi** [comment] 2016-09-21 22:04
After updating NUnit to the latest version, the problem is still reproducible, here is the log:
```
[23:49:22][Step 1/1] --- Running NUnit test: "c:\nunit\NUnit-3.4.1\bin\nunit3-console.exe" Starcounter.SqlProcessor.Tests.exe --labels=All --where:cat!=LongRunning
[23:49:22][Step 1/1] NUnit Console Runner 3.4.1 
[23:49:22][Step 1/1] Copyright (C) 2016 Charlie Poole
[23:49:22][Step 1/1] 
[23:49:22][Step 1/1] Runtime Environment
[23:49:22][Step 1/1]    OS Version: Microsoft Windows NT 10.0.10586.0
[23:49:22][Step 1/1]   CLR Version: 4.0.30319.42000
[23:49:22][Step 1/1] 
[23:49:22][Step 1/1] Test Files
[23:49:22][Step 1/1]     Starcounter.SqlProcessor.Tests.exe
[23:49:22][Step 1/1] 
[23:49:22][Step 1/1] Test Filters
[23:49:22][Step 1/1]     Where: cat!=LongRunning
[23:49:22][Step 1/1] 
[23:49:22][Step 1/1] Starcounter.SqlProcessor.Tests.exe
[23:49:22][Starcounter.SqlProcessor.Tests.exe] Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.MultithreadedTest
[23:49:22][Step 1/1] Detected memory leaks!
[23:49:22][Step 1/1] Dumping objects ->
[23:49:22][Step 1/1] {250} normal block at 0x000000001D2C56A0, 16 bytes long.
[23:49:22][Step 1/1]  Data: < 3]S            > C8 33 5D 53 F9 7F 00 00 00 00 00 00 00 00 00 00 
[23:49:22][Step 1/1] {249} normal block at 0x000000001B8BC520, 80 bytes long.
[23:49:22][Step 1/1]  Data: <                > 20 C5 8B 1B 00 00 00 00 20 C5 8B 1B 00 00 00 00 
[23:49:22][Step 1/1] Object dump complete.
[23:49:22][Step 1/1] => Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.MultithreadedTest
[23:49:22]
[Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.MultithreadedTest]   Expected: 0
  But was:  1
[23:49:22]
[Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.MultithreadedTest]    at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.MultithreadedTest() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-daily-debug-135\Level1\src\Starcounter.SqlProcessor.Tests\MultiThreadedMemoryLeakTests.cs:line 68
[23:49:22][Starcounter.SqlProcessor.Tests.exe] Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.SequentialTest
[23:49:22][Step 1/1] Detected memory leaks!
[23:49:22][Step 1/1] Dumping objects ->
[23:49:22][Step 1/1] {250} normal block at 0x000000001D2C56A0, 16 bytes long.
[23:49:22][Step 1/1]  Data: < 3]S            > C8 33 5D 53 F9 7F 00 00 00 00 00 00 00 00 00 00 
[23:49:22][Step 1/1] {249} normal block at 0x000000001B8BC520, 80 bytes long.
[23:49:22][Step 1/1]  Data: <                > 20 C5 8B 1B 00 00 00 00 20 C5 8B 1B 00 00 00 00 
[23:49:22][Step 1/1] Object dump complete.
[23:49:22][Step 1/1] => Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.SequentialTest
[23:49:22]
[Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.SequentialTest]   Expected: 0
  But was:  1
[23:49:22]
[Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.SequentialTest]    at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at Starcounter.SqlProcessor.Tests.MultiThreadedMemoryLeakTests.SequentialTest() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-daily-debug-135\Level1\src\Starcounter.SqlProcessor.Tests\MultiThreadedMemoryLeakTests.cs:line 80
[23:49:22][Starcounter.SqlProcessor.Tests.exe] Starcounter.SqlProcessor.Tests.SqlProcessorTests.HelloProcessor
```

**Comment by k-rus** [comment] 2016-09-22 06:03
> Well, if this memory leak takes place every time QP is invoked, this requires investigation. @k-rus, does it?

Originally, the memory leak was in another test not related to QP. Since then architecture of calling QP has changed, so actually this QP test can be leaking as well. Note, that it does not mean if QP is leaking or not. It was not the case, when the problem was observed with leaking.

**Comment by dan31** [comment] 2016-09-27 07:51
@k-rus so you mean shortly: the test leaks?

**Comment by k-rus** [comment] 2016-09-27 08:16
Originally SQL tests didn't leak, but some other tests were leaking, which might mean that Starcounter was/is leaking somewhere outside SQL. Now, SQL tests might leaking due to architecture of new SQL changed, so the test became meaningless. The last change was possible, since the original leakage was never found and solved.

**Comment by k-rus** [comment] 2016-10-26 09:53
I looked into this problem. Now the test really fails on the memory leak test. Something is allocated outside parser, i.e., in the kernel, which is noticed by the memory leak function. This problem appeared due to #1578, which was never fixed. I can confirm that the parser does not leak at the moment and since we are not working on the parser in develop, I suggest to disable the memory leak test. What do you think?
Another solution is to adjust memory leak check to see only allocations in the parser, which imho does not worth the effort.
Should I disable the test? I need prompt answer while I am on develop. @dan31

**Comment by dan31** [comment] 2016-10-26 14:30
As there is no evidence where the leak comes from, we can disable it and investigate in the furure.

**Comment by k-rus** [comment] 2016-10-26 14:36
> As there is no evidence where the leak comes from, we can disable it and investigate in the furure.

Thanks.

There is no leak here. The issue is #1578 for investigating potential leak outside the parser/QP.

**Comment by k-rus** [comment] 2016-10-26 15:06
I pushed the fix. However, there some problems with the build configuration of Daily Debug. I disabled KitchenSink test, which was enabled there, but it is some other problem.
@alemoi Can you investigate?

**Comment by k-rus** [comment] 2016-10-26 15:27
Another problem I cannot merge develop into pnext due to conflicts in scllvm and scnetworkgateway. @alemoi Can you look into them too?

**Comment by alemoi** [comment] 2016-10-26 16:18
> @alemoi Can you look into them too?

Sure. Changes are merged into pnext.

**Comment by k-rus** [comment] 2016-10-27 10:15
> I pushed the fix. However, there some problems with the build configuration of Daily Debug. I disabled KitchenSink test, which was enabled there, but it is some other problem.
> @alemoi Can you investigate?

Develop Daily Debug is still failing.

Develop Nightly Debug is failing on KitchenSink.

**Comment by alemoi** [comment] 2016-10-27 11:32
> Develop Daily Debug is still failing.

This one is fixed.

> Develop Nightly Debug is failing on KitchenSink.

This one I am going to fix.

**Comment by alemoi** [comment] 2016-10-27 11:56
Should be fixed now, let's see in the coming nightly.

**Closed** 2016-10-27 13:45 UTC
Labels: High prio
