### ISSUE TITLE
Question: How to add a unitTest Project

### ISSUE THREAD

**Issue by binte** [Starcounter/Starcounter#3112] opened 2015-11-26 14:48 UTC
Hello guys! 

I created a project which is supposed to test our application. I added a reference to the project where the database is located, but it doesn't work. I keep getting this exception: 

Result Message:	
System.Exception : ScErrThreadNotAttached (SCERR1004): The operation failed because the current thread wasn't attached to the scheduler.
Version: 2.0.3226.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1004.

Can someone help me to fix this?

Thanks in advance!

**Comment by per-samuelsson** [comment] 2015-11-26 16:17
@binte 

Welcome here!

We'll gladly help, but I think we'll need a clearer picture of the setup. You have two projects - one Starcounter application project, and then some other project where you want to implement tests? Is that right?

Can you maybe describe the structure and/or show some code?

For example, can you open a command prompt, browse to the solution directory and do

```cmd
C:\YourSolutionDir>tree | clip
```
and paste it here?

**Comment by per-samuelsson** [comment] 2015-11-26 16:18
> System.Exception : ScErrThreadNotAttached (SCERR1004): The operation failed because the current thread wasn't attached to the scheduler.

Also, when exactly do you get this? Is that when running your Starcounter project?

**Comment by binte** [comment] 2015-11-26 16:57
@per-samuelsson thanks for the reply! 

In the solution I have a Starcounter application project and, as you said, a project that will test the application. 

I got no output when I used that command! 

I got that error when I run or debug the unit test (I am using xunit for unit testing), whenever I query the Starcounter database.

**Comment by per-samuelsson** [comment] 2015-11-26 17:04
>  I got no output when I used that command!

You mean `tree | clip`? Try just `tree`. That one displays a tree. Then `tree I clip` does the same, but sends the output to the clipboard. After that you can do "paste", to paste it.

But you dont have to now, I get the picture better.

> I got that error when I run or debug the unit test (I am using xunit for unit testing), whenever I query the Starcounter database.

I think this is what doesn't work. Starcounter works a little differently. You run queries *within* a Starcounter application: applications are **hosted**. Are you hosting your second project (the one that is not a Starcounter application)? How did you create that? As a standard C# console application?

If you can provide some code, showing the line that fails, and explain where the source file of that line reside within these two projects, I can probably help you better!

**Comment by per-samuelsson** [comment] 2015-11-27 05:29
On a more general note, Starcounter applications and unit testing currently really dont go hand in hand. We have that story to investigate in our backlog. Maybe this can be the initiator to get that going.

Interested in getting involved? ;)

At the heart of the problem lies the fact that Starcounter applications are ***server applications***. The live in, and depend on, a runtime *host*. And in the current version of Starcounter, booting up the host to support unit tests to run *inside of it* is not trivial. The host is an orchestrated process, managed by yet other components, forming the application platform.

Now I'm just guessing, but based on what you described above, it looks like you try to run unit testing on a library using just one of the standard (xunit) runners. How they normally operate is that they load any library, detect tests, and run them *inside the runner process*. That process could be either standalone or some IDE, like Visual Studio. None of which are hosts that can support to run Starcounter applications. And hence, when you run queies, the Starcounter environment is not the expected, and you'd see that kind of failure.

Unfortunally, we don't have any real quick fix for this case. On idea could be to setup the test project to use some kind of client API of hours, calling into the Starcounter host and evaluating the results within the tests. But its certainly not optimal, and it will still not work for a test-on-every-compilation flow, because of how Starcounter applications have to be (re-)bootstrapped inside the code host.

Does that make any sense to you? Are my guesses off? I really hope this all doesn't discourage you, as we really want to make progress for these kind of cases. We expect that you certainly wont be the only one that would want to do something like this.

**Comment by binte** [comment] 2015-11-27 12:47
@per-samuelsson,

thanks for the detailed explanation! The test project was created as a class library, and the line that fails is a query to our DB, in a file inside that class library. And you guessed well, that's precisely the way we have it setup in here. We thought about using a workaround, creating an intermediate Starcounter project, with a reference for our main Starcounter project, that will have handlers for each DB query, and we will invoke these handlers from our test project.

**Comment by per-samuelsson** [comment] 2015-11-27 13:21
> We thought about using a workaround, creating an intermediate Starcounter project, with a reference for our main Starcounter project, that will have handlers for each DB query, and we will invoke these handlers from our test project.

Cool. Let us know if there's anything we can do to help!

Also, I've raised this issue internally, and also proposed a possible way forward. 

In short, I'm thinking we can write our custom `xunit` runner, maybe based on this [cool AssemblyRunner facade](https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility/Runners/AssemblyRunner.cs.) they expose, and with the help of thatt, we can discover and trigger all unit tests to run when our host bootstrap a Starcounter application (or a dependent library) with a reference to the `xunit` abstractions. 

Don't dare to promise anything, but I can keep you in the loop for sure!

And as always, all feedback is very welcome!

**Comment by binte** [comment] 2015-11-27 13:46
Yes, please do keep me posted about further developments! But for now I think the workaround I proposed will suffice. 

Thanks one more time!

**Comment by per-samuelsson** [comment] 2016-01-12 12:16
> In short, I'm thinking we can write our custom `xunit` runner, maybe based on this [cool AssemblyRunner facade](https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility/Runners/AssemblyRunner.cs) they expose, and with the help of thatt, we can discover and trigger all unit tests to run when our host bootstrap a Starcounter application (or a dependent library) with a reference to the `xunit` abstractions.

We've spent some time disucssing this internally, and also done some progress, trying different prototypes. Now there is a spike at [feature/unittests](https://github.com/Starcounter/Starcounter/tree/feature/unittests) branch. Its a bit ugly, contains a hack to get around some weird thing, but it works. I've ran a couple of hosted unit tests to test it out.

I've done the implementation so that whenever an application loads in the code host, the host will look for a certain pattern, trying to find a library containing tests for the application. The pattern is currently `Path.ChangeExtention([full_path_to_exe], ".Tests.dll")`. If such library exist, the host discovers unit tests in it and execute them. If any of them fail, the host reject the application.

So from the users point of view, you have your standard application, and next to it you would normally create a "Starcounter library", and name it [AppProjectName].Tests, like:

```
App.csproj
App.Tests.csproj
```

In the `App.Tests.csproj`, you would go about referencing `xunit` NuGet package and write your tests.

Not at all sure this model is what we'll end up with, and also, we could of course consider supporting more test frameworks than `xunit`. But the spike at least show a pattern that works.

We still don't want to promise anything, and we are busy on the roadmap right now, but just thought we'd let you know whats going on.

As always, any feedback is very welcome!

**Comment by k-rus** [comment] 2016-01-12 12:22
@per-samuelsson Will or have you written few internal regression tests using your package?

**Comment by mtornwall** [comment] 2016-01-17 18:03
> I've done the implementation so that whenever an application loads in the code host, the host will look for a certain pattern, trying to find a library containing tests for the application. The pattern is currently Path.ChangeExtention([full_path_to_exe], ".Tests.dll"). If such library exist, the host discovers unit tests in it and execute them. If any of them fail, the host reject the application.

@per-samuelsson I have some qualms about this approach. There's just too much "magic" going on -- since tests will touch the database, possibly in a rather destructive manner, I must be *absolutely certain* that no testing code *ever* gets deployed to and run on a production machine. The suggested method, in which I assume the application project would reference the test project in order for the test assembly to be placed in a location where it is visible to the code host, runs a high risk of accidentally deploying the tests alongside the main application.

Personally, I'd prefer the following project structure:

1. The `Application1` and `Application2` projects contain the main application code for two different applications.
2. The `Application1.Tests` and `Application2.Tests` projects reference the aforementioned application assemblies and host their respective test cases.
3. A special "test executive" Starcounter application references the test assemblies. When loaded into the code host, it discovers and executes the test cases.

This has the benefit of delegating the responsibility of test execution to a separate application, so that test code and application code remain clearly separated.

**Comment by per-samuelsson** [comment] 2016-01-18 07:03
Thanks for the feedback @mtornwall.

> [...] in which I assume the application project would reference the test project in order for the test assembly to be placed in a location where it is visible to the code host, runs a high risk of accidentally deploying the tests alongside the main application in my opinion.

No, the application project does not reference the tests. The code host match on a naming pattern, as I describe above.

> This has the benefit of delegating the responsibility of test execution to a separate application, so that test code and application code remain clearly separated.

I don't really see the benefit of having to introduce a separate extra application. Would that application have to explicitly trigger the tests do you mean?

I can see your point that maybe it's more "magic" than what is good, in the way I proposed it. So some kind of explicit runner is probably a better choice. Either as a dedicated tool (like `startest --console Application1.Tests.dll`), or that we could have tests supported in the bootstrapping tools like `star`, so that you could trigger tests by applying some extra switch when booting the application inside the code host, like `star --runtests App.exe`. This would start the application after tests have (successfully) ran.

The alternative could be to have it in `staradmin` instead (or in parallel), like `staradmin test App.exe`. You still would have to bootstrap the executable first, however, since there are basically no testing you could do without having the application run in the code host.

**Comment by per-samuelsson** [comment] 2016-01-18 07:05
> @per-samuelsson Will or have you written few internal regression tests using your package?

No, I haven't, and no, I don't plan to. This is not in any main branch, remember. It's just a spike in an isolated branch, to see what alternatives we have and testing stuff out.

**Comment by mtornwall** [comment] 2016-01-18 09:14
@per-samuelsson 

> No, the application project does not reference the tests. The code host match on a naming pattern, as I describe above.

Ah, sorry, I read that part too quickly. :-)

> I don't really see the benefit of having to introduce a separate extra application. Would that application have to explicitly trigger the tests do you mean?

The "extra application" could just as well come in the form of a built-in feature in `star` or `staradmin`, like you proposed. I agree that there is no direct benefit to having another application to start.

> I can see your point that maybe it's more "magic" than what is good, in the way I proposed it. So some kind of explicit runner is probably a better choice. Either as a dedicated tool (like startest --console Application1.Tests.dll), or that we could have tests supported in the bootstrapping tools like star, so that you could trigger tests by applying some extra switch when booting the application inside the code host, like star --runtests App.exe. This would start the application after tests have (successfully) ran.

This sounds like an excellent solution to me. As long as I must opt in to running the tests I'm happy.

**Comment by per-samuelsson** [comment] 2016-01-18 09:20
> As long as I must explicitly opt in to running the tests I'm happy.

Yeah, the more I think of it, the more sense that makes. Thanks for taking the time to point this out to us. I'll make sure we respect this once we make it into a final implementation.

**Comment by jedynykaban** [comment] 2016-01-21 11:10
Joining to discussion from outside, i work with SC 1.3, and at the begining would like to have (and ask for or ask for description "how") possibililty to mock Starcouter's object with popular testing framework (ex. i use NSubstitute for NUnit). Basically what i'm expecting to allow behave starcouter objects in this context similar to POCO. With well-difined interface to repository layer, i hope i'll be able to make some particular (parametrized) unit test, but without possiblity of Starcounter's database classes/objects (those which derived from Something) i'm stuck... at the begining.

**Comment by per-samuelsson** [comment] 2016-03-02 11:39
@jedynykaban 

Sorry we haven't replied to that earlier.

As far as I know, there has been no real use cases with that kind of mocking, and I think the reason is that it can't be done easily like 100% accurately, mainly because of the native nature of Starcounter, which build on hosting of user applications (or "user code" more generally, and more accurate to the situation in 1.3 and any version < 2.x).

Substitution with something like `NSubstitute` (and similar/related frameworks, like `Moq`) has no real built-in feature that collide with Starcounter, but there are features of Starcounter (like the feature we refer to as "weaving", allowing you to define your database classes as simple POCO's) that are not so obvious, and that you need to factor in when using those.

Also, we currently have no real way to run Starcounter user applications outside the Starcounter host, and the reason for that is simply that we haven't spent any time thinking about such alternative.

With all that being said, we do get closer to the day where we'll support "hosted unit testing" for Starcounter applications, which this issue is originally about. My guess is (but I can't promise) that some kind of support will be present in upcoming 2.2 or 2.3/4. When we decide on that for sure, we'll keep you updated on it, and I'll also make sure to consider the whole mocking area when designing it, to see if we can somehow fit that in. Because it would for sure make sense to do so.

I hope that could give some insight that was useful to you. And either way, please get back with your questions/thoughts/ideas and we'll make sure trying to answer them to the best of our ability.

**Comment by per-samuelsson** [comment] 2016-09-09 07:31
Unit test support coming up: #3831. Closing this one in favor of that. Please redirect any further questions / comments to that issue.

**Closed by per-samuelsson** 2016-09-09 07:31 UTC
Labels: question
