### ISSUE TITLE
TurboText collation for Types

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#2160] opened 2014-07-14 10:37 UTC
### Indexing and querying on Types

The new type system to be used by @eriohl dynamic type system will be supported by the new query engine in a new way. The types will be availably to the query engine and according to the following requirements:

1. Can be freely indexed
2. Can be part of any other index
3. Supports for hierarchical indexes
4. Can be used as a column
5. Supports select on base types or exact types
6. Can be mapped to non inheriting SQL tables
7. Is compact
8. Allows for *infinite* growth of base type siblings after the creation of the index
9. Does not require a new type for the mapped paradigm (that is why string is used)
10. Does not add complexity to the query optimiser
11. Does not add complexity for the index system
12. Can be used as a URI fragment (is URL safe)

### Solution

Fortunately the solution to the above requirements are fairly simple. TurboText fits the bill. The new type system will allow a new ```TypeID``` property from database objects. The ```TypeID``` property will act as a string and will support hierarchical indices using the standard TurboText index. The way this will be achieved is using a special collation optimised for the task.

The accompanying ```TypeID``` is intended to have the following characteristics:

### Example using a type hierarchy
This is an example of a ```TypeID```:

```
      PhysicalObject ("/1/x")
          Axe ("/1/1/x")
          House ("/1/h/x")
          Wand ("/1/w/x")
      Event ("/e/x")
          Meeting ("/e/1/x")
          Trade ("/e/t/x")
          Call ("/e/c/x")
          Murder ("/e/m/x")
      Agent ("/a/x")
          Person ("/a/1/x")
          Company ("/a/c/x")
          Robot ("/a/r/x")
      Relation ("/r/x")
          Customer ("/r/1/x")
          User ("/r/u/x")      
      Animal ("/n/x")
          AfricanElephant ("/n/1/x")
          Ape ("/n/a/x")
          Aardvark ("/n/r/x")
          Albatross ("/n/l/x")
          Alligator ("/n/i/x")
          Ant ("/n/n/x")
          Antelope ("/n/t/x")
          Aardwolf ("/n/d/x")
          Alpaca ("/n/p/x")
          Anole ("/n/o/x")
          Anaconda ("/n/c/x")
          Avocet ("/n/e/x")
          Arab ("/n/f/x")
          Armadillo ("/n/m/x")
          Anteater ("/n/h/x")
          AyeAye ("/n/u/x")
          Ainu ("/n/s/x")
          Akita ("/n/ak/x")
```

This is the desired collation:

```
Written     TurboText encoding                         
------------------------------------------------
/           0        
a           10000
c           10001
d           10010
e           10011
f           10100
h           10101
i           10110
l           10111
m           11000
n           11001
o           11010
r           11011
s           11100
t           11101
u           11110
w           11111
```

### What is stored?

The type value is stored as the very first value in the tuple of the database object. It will be stored physically using the new collection. The initial slash, the ```1``` and the ```x``` are there to make the string URL friendly and are not part of the stored string. The trailing slash is stored however (important for ```LIKE``` hierarchical queries).

### Padded characters to make the string URI friendly

The ```1``` is inserted to avoid more than one subsequent ```/```. The ```x``` is added to the end to avoid URIs ending with a slash. 

### TurboText encoding details

The TurboText collection supports bits that are not used in comparison and sorting (called DP bits). These are not used in the type collation.

**Comment by eriohl** [comment] 2015-02-05 12:02
> There seems to be a problem comparing longer strings using the standard compare function. Example: "~simpleuniqueindex~". Seems like the prefix length stored is a bit larger then is should be. Working around the problem now by only using only sort strings which seems to work properly.

Turned out to be my bad. Under certain circumstances the encoded typeid was truncated loosing the last byte when stored causing the problem. Fixed now in 2279+.

**Comment by k-rus** [comment] 2015-03-25 08:33
I am wonder about kernel assumption on encoded TypeId using the collation. Are null values or empty strings allowed?

**Comment by k-rus** [comment] 2015-03-25 08:35
> I am wonder about kernel assumption on encoded TypeId using the collation. Are null values or empty strings allowed?

I am wonder about it as I need to understand how type terminator is going to be implemented.
(I know that `TypeId` is renamed to `SetSpecifier`)

**Comment by eriohl** [comment] 2015-03-25 10:36
> I am wonder about kernel assumption on encoded TypeId using the collation. Are null values or empty strings allowed?

Null values are allowed. Then the record will belong to no set. Default is null.

Empty strings I think is not allowed since the set specifier needs to start and end with a ~. This is an encoder issue however.

**Comment by warpech** [comment] 2015-06-01 13:00
Example of select:

```C#
// Get all children and grandchildren of all society object nodes in hierarchy
var all = Db.SQL("SELECT E FROM Entity WHERE TypeID LIKE ?", "/f/q/%" );
```

**Comment by k-rus** [comment] 2015-08-04 07:10
I am wonder which encoding is implemented in TurboText for TypeId? This is important, since meta-layer needs to generate proper set specifiers.
@linkdata Can you point to specification or source file, which describes the encoding? I need to know supported characters and the order.

**Comment by linkdata** [comment] 2015-08-04 07:22
For TurboText3, in `level0\src\Turbotext\TurboTextGenerator\Collations\Collation_X_TypeID.xml`.
For TurboText4, in `level0\src\turbotext4\src\generator\Collations\Collation_X_TypeID.xml`.

**Comment by k-rus** [comment] 2015-08-04 07:23
> For TurboText3, in level0\src\Turbotext\TurboTextGenerator\Collations\Collation_X_TypeID.xml.
> For TurboText4, in level0\src\turbotext4\src\generator\Collations\Collation_X_TypeID.xml.

Thank you. Which one is used in pnext? Or is there difference between the versions, which affects me?

**Comment by linkdata** [comment] 2015-08-04 07:31
The collation definition files are identical. Both TT3 and TT4 should be built for `pnext`, which generates the `TurboText_x-tid_3.dll` and `TurboText_x-tid_4.dll` libraries. Which one is used depends on the kernel code that loads it. I *think* it's defined in `level0\src\include\sccorever.h`. @eriohl would know for sure.

**Comment by eriohl** [comment] 2015-08-04 09:53
STAR_SETSPEC_STRING_FORMAT in sccorever.h = TurboText_x-tid_3.DLL

There is some compatibility issue with TT4 (can't remember what exactly) so it is never used.

**Comment by eriohl** [comment] 2015-09-10 14:41
Kernel needs to be aware of the encoding for index selection index. So changing the encoding may now break the kernel. Maybe move encoder/decoder into the kernel instead?

(It assumes that 0 is separator and 1 bit in length while all other characters are 6 bits.)

**Comment by dan31** [comment] 2015-09-22 07:31
@eriohl @linkdata Because this is a special type of encoding (for sets), maybe we can make only this encoding be a special case and encapsulate its processing completely into the kernel?

**Comment by linkdata** [comment] 2015-09-22 10:32
Sure. The type encoding doesn't need the special features that TT offers. It takes a bit more work than simply making an XML file for TT, but it's very stand-alone and a nice little bite-sized project.

**Comment by eriohl** [comment] 2015-09-23 06:23
(Kernel) client needs still be able to work with the formatter since it needs to be able to encode search strings and encode raw output. It think it probably advantages if it has the same interface as the TT formatter. So I'm not entirely sure how much benefit is would bring.

**Comment by eriohl** [comment] 2015-09-23 06:27
On a separate note it might be a good idea to look into switching to TT4. Certainly a good thing to do while we still need not worry about data compatibility.

Can't exactly remember what the problems with switching was but at least kernel no longer uses fragmented strings so we could use the compare functions generated for the formatter now.

**Comment by linkdata** [comment] 2015-09-23 07:23
The fragmentation handling was the problem, as it required maintaining state outside of the compare function. TT4 is API compatible with TT3, so it should be a drop-in replacement. TT4 also has a C++ wrapper that will handle cross platform differences for shared libraries and that can load either TT3 or TT4 libraries.

**Comment by eriohl** [comment] 2015-12-22 18:13
TT formatter for set specifier does not support infinite character (tested only TT3 now but I case this is probably the case for TT4 as well.)

**Comment by Starcounter-Jack** [comment] 2015-12-23 01:40
Oops. Forgot about this when I had the heureka moment. Let's just add it.

**Comment by eriohl** [comment] 2016-01-14 08:16
Well... Getting to a point now where we really need this with the infinite character addressed....

**Comment by dan31** [comment] 2016-01-14 10:17
@linkdata Can you have a look? We aren't yet making test runs on
replicator  expecting pnext further fixes, so you should have capacity to
go into this issue.

**Comment by linkdata** [comment] 2016-01-14 14:20
Yep, I will get right on this.

**Comment by linkdata** [comment] 2016-01-20 08:09
I'm scratching my head trying to figure out what the problem is here. Could you elaborate on what you mean by this:
> TT formatter for set specifier does not support infinite character (tested only TT3 now but I case this is probably the case for TT4 as well.)

**Comment by linkdata** [comment] 2016-01-20 08:17
Ah, ok, now I remember. I'll add it to the collation, but it'll bloat it a bit per code point (literally).

**Comment by linkdata** [comment] 2016-01-20 09:00
Ok, push to pnext. The collation encoding now has the infinite character. I had to rebalance the encoding to get it in there, so it now encodes `a` to `d` in 2 bits less but everything else uses one more bit.

**Comment by linkdata** [comment] 2016-01-20 09:58
I had to pull it, since it caused `metalayer_functest` to fail. Turns out the kernel isn't using TT to decode the X-tid strings, but has it's own decoder which makes assumptions that are no longer true. We need to fix the kernel to either use TT for decoding or change the custom reader (`index_group_setspec_index_handle::key_reader`) before pushing it again.
@eriohl Please let me know when I can push.

**Comment by eriohl** [comment] 2016-01-20 10:32
```index_group_setspec_index_handle::key_reader``` assumes that set specifier is encoded a certain way (1 + 5 and the separator has the value 0). Would be better to use the decoder obviously but should it call the decoder to read each character this would add a lot of overhead obviously, so I don't think this is a very good idea.

It seems to me that having a smaller size of certain characters shouldn't compensate for the other ones being larger since all characters other then the delimiter should occurs as often in set specifier (then some set specifiers will be used more then others of course but I don't think it will be possible for the metadata layer to determine how many records will be contained at a set on table creation). Is this really a good trade-off compared to say using 11111 as infinity character?

**Comment by linkdata** [comment] 2016-01-20 10:44
We need statistics on the Society Objects tree to make informed decisions on that (see last paragraph in my comment (here)[https://github.com/Starcounter/Starcounter/issues/2160#issuecomment-65634106]).

My reasoning is that most levels of the tree will have a fairly small number of items in them, and then it makes sense to encode lower values in less space.

From the collation's point of view, it's perfectly fine to replace `_` with the infinity character in the existing set, but that means you can't to straightforward five-bits-at-a-time encoding/decoding (values 0...30 would be data, 31 would be infinity char).

The proposed encoding looks like this in bit format:
```
 00 - path sep
 01 - XX characters a ... d
 10 - XXXXX characters e ... underscore
 11 - infinity
```

**Comment by eriohl** [comment] 2016-01-20 11:20
> We need statistics on the Society Objects tree to make informed decisions on that (see last paragraph in my comment here).

> My reasoning is that most levels of the tree will have a fairly small number of items in them, and then it makes sense to encode lower values in less space.

Then you are assuming that all data models would be based on SO. I'm don't actually know if this is reasonable for SO but I think that most data models has a pretty flat hierarchy.

> From the collation's point of view, it's perfectly fine to replace _ with the infinity character in the existing set, but that means you can't to straightforward five-bits-at-a-time encoding/decoding (values 0...30 would be data, 31 would be infinity char).

I don't understand what you mean.

Anyway: Push this into a separate branch. Then I'll adapt the key reader and merge this into main. Ok?

**Comment by linkdata** [comment] 2016-01-20 11:45
Ok. If you think it'll be better, we can encode for even spread. This makes it so that only the path separator incurs a single bit penalty, but without the possible win if most levels have few items:

```
 00 - pathsep
 01 - XXXX first 16 chars
 10 - XXXX last 16 chars
 11 - infinity
```

**Comment by linkdata** [comment] 2016-01-20 11:56
I've pushed the even-spread version into the branch `issue/2160/tt4-x-tid`.

**Comment by eriohl** [comment] 2016-01-20 14:13
Not really what I argued for. (But fixed character size certainly makes adopting the key reader easier.)

**Comment by eriohl** [comment] 2016-01-20 16:24
Key reader fixed and merged into pnext.

**Comment by eriohl** [comment] 2016-05-09 11:04
This is all working now so closing issue.

**Closed by eriohl** 2016-05-09 11:04 UTC
Labels: Bluestar, Kernel, NewSQL, TurboText

**Comment by bigwad** [comment] 2016-06-09 13:14
Some changes has been done recently:

- encoding

bits | symbol
---------------|----------------
00 | ~
00001..11110 | a ..w
11111 | infinite char

- leading separator is not required. trailing separator is still required.
- empty element is permitted

Thus very first setcpec lexicographically is "~"
The next sibling to "~" is "a~"
The first descendant from "~" is "~~"
Similarly, the first descendant to "a~" is "a~~"

**Comment by eriohl** [comment] 2016-06-09 14:51
Different characters to choose from for the set specifier then? Affects set specifier generation then I suppose?

cc @k-rus @alexanderstc

**Comment by bigwad** [comment] 2016-06-09 14:53
Already posted number of issues in level0 issue tracker

**Comment by k-rus** [comment] 2016-06-30 16:24
It will be great if TT coalition for types provide an API that the metalayer doesn't need to know details of the algorithm. Like what is next symbol and how to get the first symbol on next level. Having knowledge about symbols in two components is error prone potentially. Thus can TT coalition for types provide the additional two API functions?

**Comment by bigwad** [comment] 2016-07-01 08:59
@alexanderstc already asked about it [here](https://git.starcounter.org/BlueStar/level0/issues/67#note_587). Although I expect some minor issues, seems he has a good point to start off from.

Besides that, I see you might have some wrong assumptions about setspec collation and how it affects the kernel. 
Neither collation itself nor the kernel has the notion of 'first', 'last', 'next' and 'level'. Kernel just assumes that if two entities (indexes in our case: index_1 and index_2) are marked with two setspec's (setspec_1 and setspec_2 respectively), where setspec_1 is a prefix of setspec_2, then those entities as "derived" in some sense, thus building the hierarchy. You see, even an ordinary strings could be used as setspec according to this requirement. Nothing at all special with setspec collation regarding it, no 'first', 'last', 'next' or 'level'. The only reason to introduce dedicated collation is to increase encoding efficiency for this very specific case.

Now to the API. Given setspec collation, metalayer should be able to determine exactly two things:
1. Set of acceptable symbols.
2. Symbol to use as a separator to form the hierarchy (selection of which is actually arbitrary but it's wise to select the shortest symbol in collation).

Both are easily discoverable in runtime using existing API (probably with some minor fixes). Or alternatively, it could be done in compile time by including the generated source file with setspec collation table. Then it's totally up to the metalyer how to combine symbols in the most efficient way. Nobody else cares.
