### ISSUE TITLE
Non-starcounter json treated as TypedJSON

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3793] opened 2016-08-18 09:49 UTC
Problem
---

1. Add an existing JSON file to starcounter project
1. SC tries to compile it and build probably fails
1. It's because the file has build action 'TypedJSON' by default. You can change it in file properties -> Build action set to 'None'
1. It can be hugely confusing for user (build errors not always event hint that they come from starcounter, for user it can be 'error out of nowhere')

Proposed solution
---

If it's possible, don't make 'TypedJSON' default action for JSON. If not, tackle the issue in docs / add clearer hints in error description

**Comment by chrhol** [comment] 2016-08-18 10:10
Duplicate of #3075. I will close this one in favor of that one. As you noted though, the proposed change there has not been implemented yet.

**Closed by chrhol** 2016-08-18 10:10 UTC
Labels: duplicate, Typed JSON
