### ISSUE TITLE
Specification wiki page for dynamic types gone?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#2582] opened 2015-02-24 08:33 UTC
The wiki page I've been working on to write a specification for the multi-level dynamic types seem to be gone?

The link to it should be:
https://github.com/Starcounter/Starcounter/wiki/Under-the-hood:-the-VMDBMS-dynamic-type-system

It's referenced several time from #2544.

**Comment by per-samuelsson** [comment] 2015-02-24 08:42
If I clone the wiki locally, I can see that it disappear after this commit: 68a7849d54a736fb9b36973bc9d6c3f0b8a518cf. 

The weird thing is that it doesn't show in the history / file tree as being removed; it just don't exist after that merge. We should really check other stuff havent dissapeared as well.

**Comment by per-samuelsson** [comment] 2015-02-24 08:48
I have temporary re-added the last content i could find in the repo to page https://github.com/Starcounter/Starcounter/wiki/TEMP---Dynamic-Type-System.

**Comment by per-samuelsson** [comment] 2015-02-24 09:56
@chrhol, can you take a look at this, to see if you can understand what has happened?

**Comment by chrhol** [comment] 2015-02-24 11:41
I have no idea what happened. The only thing I can think of that I cloned the wiki and edited the file directly and then pushed it, but there were no conflicts or anything. I did not use the webinterface.

It's really strange, the file is just gone.

**Comment by chrhol** [comment] 2015-02-24 12:18
I guess the strange merge is the first one (25980ba90b5e511ab955f64b64da97dd508c9059) that merge should have included the newly created page.

I did a small test doing the same thing again, but then everything was merged correctly. Quite scary that you cannot be sure that everything gets merged ok.

**Comment by per-samuelsson** [comment] 2015-02-24 13:49
Really weird. How can we go further with this then? I mean, we really must understand what has happened here, don't we? Otherwise we can risk to loose stuff without knowing it.

And also, what should we do to "revert"? Should I just add the specific page again (copying content from history), and hope it was the only thing that disappeared?

**Comment by dan31** [comment] 2015-02-24 21:26
This reminded me of the case I read in Sep 2014: http://blog.screensteps.com/recovering-from-a-disastrous-git-rebase-mistake (another guy have had exactly the same problem and resolution). @chrhol and @per-samuelsson, maybe you can take a glimpse? Whatsoever, the funny thing about that issue is that real reason remains uncertain. Also the issue seems to be a feature, according to a discussion in Russian there: http://habrahabr.ru/post/236351.

**Comment by per-samuelsson** [comment] 2015-02-25 09:43
I have now readded the content that was last known in the repo, under the same original link. I've also deleted the temporary page.

Feel free to close this issue whenever you feel applicable.

**Comment by chrhol** [comment] 2015-03-02 11:33
Could the problem maybe be with the name of the file? I've been playing around a little after reading the links from @dan31 and what happened earlier and I see that I'm not actually allowed to create a file including `:` in the name in windows. And when I try to pull the repository fresh I also get an error for this file and it actually tries to delete it, I have it as removed in mystaged changes and cannot do anything.

**Comment by chrhol** [comment] 2015-03-02 12:08
I think this is likely. Last time I had autocommit merged changes on, but this time I unclicked it so I had time to see that it could not clone the file succesfully.

**Comment by per-samuelsson** [comment] 2015-03-02 12:17
> I think this is likely.

Great, really nice you found this! Then we at least know what happened, and what we must try to avoid in the future. Let's discuss it briefly at the office tomorrow, to see if we should set up some "guard".

**Comment by per-samuelsson** [comment] 2015-03-02 12:18
> Let's discuss it briefly at the office tomorrow, to see if we should set up some "guard".

Maybe @parherman could even spend some time trying to investigate a little further and then decide if we need to take any action?

**Comment by parherman** [comment] 2015-03-02 13:31
The problem is the the wiki engine, gollum, creating file names based on titles of the wiki pages created in the editor. Its a know issue (https://github.com/gollum/gollum/issues/180) and the 'fix' from the developers of gollums point of view seem to be: dont use `\ / : * ? " < > |` in the title if you want to clone the wiki on Windows!

**Comment by parherman** [comment] 2015-03-02 13:56
I changed the title: https://github.com/Starcounter/Starcounter/wiki/Under-the-hood;-the-VMDBMS-dynamic-type-system

**Comment by chrhol** [comment] 2016-10-03 12:52
Resolved and not really relevant any more. Closing.

**Closed by chrhol** 2016-10-03 12:52 UTC
Labels: bug, Wiki
