### ISSUE TITLE
cmake generated solution for Level0 always build 8 projects

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2694] opened 2015-04-29 07:53 UTC
I was happy that cmake generated solution was building only projects, which were modified. However, it is not so anymore. If I build solution using F5 two times in a row, it builds 8 project on second time, while I expect no projects to be built, since no changes. Here is output in VS:
> 1>------ Skipped Build: Project: RUN_TESTS, Configuration: Debug x64 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: SC_BEHEMOTH_INPUT, Configuration: Debug x64 ------
3>------ Build started: Project: TURBOTEXT_GENERATOR, Configuration: Debug x64 ------
4>------ Build started: Project: TURBOTEXT_LANG_en-GB, Configuration: Debug x64 ------
5>------ Build started: Project: TURBOTEXT_LANG_nb-NO, Configuration: Debug x64 ------
6>------ Build started: Project: TURBOTEXT_LANG_ru-RU, Configuration: Debug x64 ------
7>------ Build started: Project: TURBOTEXT_LANG_sv-SE, Configuration: Debug x64 ------
8>------ Build started: Project: TURBOTEXT_LANG_x-tid, Configuration: Debug x64 ------
9>------ Build started: Project: Starcounter.UriMatcher, Configuration: Debug x64 ------
10>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug x64 ------
10>Project not selected to build for this solution configuration 
========== Build: 8 succeeded, 0 failed, 84 up-to-date, 2 skipped ==========

I see two tasks in this issue:
- [ ] Fix that the generated solution does not build unchanged projects
- [ ] Prevent from getting this problem again

**Comment by parherman** [comment] 2015-04-29 08:35
Hello @k-rus

These projects are generator projects that generate files and they do their own checks to see if they need to run or not. For instants, if SC_BEHEMOTH_INPUT is generating files it will output "Running behemothrcc" to the log.

I will look into adding a "No changes detected, will not run message" so that this behavior is more clear

**Comment by k-rus** [comment] 2015-04-29 08:48
Thank you for clarification! Indeed the projects seem to skip the actual building process. My main surprise was that the behaviour was cleaner before.
I guess a cleaner solution would be possible in future.
I think this issue can be closed for now.

**Comment by parherman** [comment] 2015-04-29 09:06
Oki, I will close this!

**Closed by parherman** 2015-04-29 09:06 UTC
Labels: bug, Infrastructure

**Comment by k-rus** [comment] 2015-04-29 09:09
> Thank you for clarification! Indeed the projects seem to skip the actual building process. My main surprise was that the behaviour was cleaner before.
> I guess a cleaner solution would be possible in future.

It would be correct to rephrase:

Is it possible to make a clean solution that the projects are not called to build if no changes? I think there was some another issue where there was comment about behemoth project, right?

**Comment by parherman** [comment] 2015-04-29 10:46
Yes this was brought up in https://github.com/Starcounter/CompanyTrack/issues/10#issuecomment-73957705 where some actual unnecessary rebuilds were reduced

Right now in the case of SC_BEHEMOTH_INPUT we use a [add_custom_command](http://www.cmake.org/cmake/help/v3.2/command/add_custom_command.html) with a DEPENDS on the files that should be monitored for changes in the CMakeLists.txt, and then cmake will generate a msbuild solution/project that looks like this.

**Comment by k-rus** [comment] 2015-04-29 11:32
> Right now in the case of SC_BEHEMOTH_INPUT we use a add_custom_command with a DEPENDS on the files that should be monitored for changes in the CMakeLists.txt, and then cmake will generate a msbuild solution/project that looks like this.

I don't have knowledge to judge this decision. I just want to have a nice developer experience and I am curious: Why did this behaviour appear recently? Earlier only projects with actual changes were called to build.

And I will repeat my question:

> Is it possible to make a clean solution that the projects are not called to build if no changes?

**Comment by parherman** [comment] 2015-04-29 11:54
> Why did this behavior appear recently?

I'm not sure why I did not appear right away, since its been noticed/appeared long before in the in the issue i linked to. I believe it appears here right away! I will try and see if I can reproduce that here

I'm not sure we can make it a lot better without making a msbuild specific solution
