### ISSUE TITLE
starcounter server crashes on start

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3515] opened 2016-04-19 10:18 UTC
ver 2.2.1811
Can't start server from the tray
![image](https://cloud.githubusercontent.com/assets/2953584/14635922/d40943e6-0628-11e6-8d26-a45bace99c34.png)

```
20160419T030734 Warning sc://ie11win10/personal/networkgateway Starcounter - Gateway XML: MaximumReceiveContentLength parameter exceeds maximum value. Current value is set to 2096936.
20160419T030734 Critical sc://ie11win10/personal/networkgateway Starcounter - Assertion failed (!"Reached maximum number of tries in wait for suspended workers.") at OurSources\\gateway.cpp:2949 (Data 0).\n    00007FFD1EA311E9 sccoredbg!do_handle_assertion_failed : assert-win.cpp (76)\n    00007FFD1EA31039 sccoredbg!handle_assertion_failed : sccoredbg.cpp (29)\n    00007FF6F9CA8EBA scnetworkgateway!starcounter::network::Gateway::WaitAllWorkersSuspended : gateway.cpp (2949)\n    00007FF6F9C9B213 scnetworkgateway!starcounter::network::Gateway::AddNewCodehost : gateway.cpp (1929)\n    00007FF6F9CA5999 scnetworkgateway!starcounter::network::RegisterNewCodehost : gateway.cpp (1469)\n    00007FF6F9CAFCE1 scnetworkgateway!starcounter::network::RegisteredUri::RunHandlers : http_proto.cpp (162)\n    00007FF6F9CAF5DA scnetworkgateway!starcounter::network::HttpProto::HttpUriDispatcher : http_proto.cpp (779)\n    00007FF6F9CAFB3B scnetworkgateway!starcounter::network::OuterUriProcessData : http_proto.cpp (1060)\n    00007FF6F9C9559B scnetworkgateway!starcounter::network::GatewayWorker::RunReceiveHandlers : worker.hpp (538)\n    00007FF6F9CB8189 scnetworkgateway!starcounter::network::GatewayWorker::WorkerRoutine : worker.cpp (1788)\n    00007FF6F9C9DDA8 scnetworkgateway!starcounter::network::GatewayWorkerRoutine : gateway.cpp (3125)\n    00007FFD52262D92 KERNEL32!\n    00007FFD54919F64 ntdll!\n\n
20160419T030734 Critical sc://ie11win10/personal/administrator Starcounter - System.Exception: ScErrUnspecified (SCERR999): An unspecified error caused the operation to fail. System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host\r\n   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)\r\n   at Starcounter.NodeTask.PerformSyncRequest() in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-280\\Level1\\src\\Starcounter.Internal\\Rest\\NodeTask.cs:line 514\r\nVersion: 2.2.1811.\r\nHelp page: https://github.com/Starcounter/Starcounter/wiki/SCERR999.\r\n   at Starcounter.Internal.AppsBootstrapper.RegisterNewCodehostInGateway() in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-280\\Level1\\src\\Starcounter.Apps.JsonPatch\\AppsBootstrapper.cs:line 59\r\n   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedulers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTimeoutMinutes, String dbName, Boolean noNetworkGateway) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-280\\Level1\\src\\Starcounter.Apps.JsonPatch\\AppsBootstrapper.cs:line 132\r\n   at StarcounterInternal.Bootstrap.Control.Setup(String[] args) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-280\\Level1\\src\\Starcounter.Bootstrap\\Control.cs:line 223\r\n   at StarcounterInternal.Bootstrap.Control.Main(String[] args) in C:\\TeamCity\\TeamCity9\\buildAgent\\work\\sc-develop-nightly-280\\Level1\\src\\Starcounter.Bootstrap\\Control.cs:line 55\r\nHResult=-2146233088\r\nHelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR999\r\n
20160419T030734 Error sc://ie11win10/personal/service Starcounter - ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated.
20160419T030734 Error sc://ie11win10/personal/service Starcounter - Process exitcode: 1070
```

cc @alemoi

**Comment by k-rus** [comment] 2016-04-19 10:30
See also #3513 and [this comment](https://github.com/Starcounter/Starcounter/issues/3513#issuecomment-211806482)

**Comment by alemoi** [comment] 2016-04-19 11:15
The problem should be fixed now. If not, please reopen the issue. Thanks for reporting!

**Comment by bigwad** [comment] 2016-04-19 11:31
Sorry, I don't understand what do you mean by "now". 
I reported the issue with latest stable - 2.2.1811
Latest Nightly(2.2.1813) crashes in the same way.

If you believe you have fixed it, I think it has to be uploaded and promoted as the new stable.

**Comment by alemoi** [comment] 2016-04-19 11:53
> Sorry, I don't understand what do you mean by "now". 

That means that I pushed to develop/pnext.

> If you believe you have fixed it, I think it has to be uploaded and promoted as the new stable.

Yes, I think it actually should be.

**Comment by dan31** [comment] 2016-04-19 12:01
@alemoi do you mean that we need to cancel 2.2.1811 and make a Stable some new version that contains a fix? Would this version work with old 2-workers configured gateway conf file normally? If so, I suggest you to make a surgery urgently on a download server and other places and replace 2.2.1811 with the version containing the fix. You don't need to promote it to me.

**Comment by alemoi** [comment] 2016-04-19 20:19
I rewrote the original code and tested it, on several machines with number of workers 8. Could not reproduce the hang. Now default number of workers is back to 2 since I consider the issue fixed. If you experience the problem again, please reopen the issue.

**Closed by alemoi** 2016-04-19 20:19 UTC
