### ISSUE TITLE
Internal URI matcher code generation error!

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2793] opened 2015-07-02 13:56 UTC
Suddenly, without any noticable errors or difference in behaviour I get this error message when trying to view a page in my Starcounter app (it is running with the launcher).

System.Exception: Error code=0x7B. Internal URI matcher code generation error!
Version: 2.0.3226.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR123.
   at Starcounter.Rest.PortUris.GenerateUriMatcher(UInt16 port, UserHandlerInfo[] allUserHandlers, Int32 numRegisteredHandlers) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Rest\PortUris.cs:line 143
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1049
   at Starcounter.Self.DoSelfNodeCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Node\Self.cs:line 396
   at PolyjuiceNamespace.Polyjuice.MappingHandler(Request req, List`1 mappedHandlersList, String stringParam) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter\Apps\PolyJuice.cs:line 302
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 203
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 97
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 349
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR123

More information about this error may be available in the server error log.

**Comment by Ripipip** [comment] 2015-07-02 14:11
Okay the problem is that I added this handler. Any idea why it would cause this error? 

            Handle.GET("/adfenix/ImportClassifiedAdURLs", (Request r) =>
            {
                Response response = 0;
                response.HeadersDictionary["Location"] = "http://www.adfenix.com";
                response.StatusCode = 302;
                QueryResultRows<IObjectView> Variable1 = Db.SQL<IObjectView>("SELECT Url,PublicationOwner.Domain FROM classifiedad");
                string url= "";
                string PublicationOwnerDomain = "";
                foreach (IObjectView a in Variable1)
                {
                    if (a.GetString(0) != "")
                    {
                        url = a.GetString(0);
                        PublicationOwnerDomain = a.GetString(1);
                        File.AppendAllText(@"C:\Logs\" + PublicationOwnerDomain + ".txt", url + Environment.NewLine);
                    }
                }
                return response;
            }, new HandlerOptions() { SkipMiddlewareFilters = true });

**Comment by alemoi** [comment] 2015-07-02 16:46
Thank you for reporting! How many handlers do you have on your port?

**Comment by Ripipip** [comment] 2015-07-02 17:18
90 in adfenix and then the other apps; Launcher, Signin and Useradmin

**Comment by Ripipip** [comment] 2015-07-30 11:21
This error is stupid. It comes up now and then and forces us to make strange workarounds. 

For example: 
(1) works perfectly but (2) does not work
1. Handle.GET("/adfenix/test/any/view/{?}", (string id, Request request) =>
2. Handle.GET("/adfenix/atest/any/view/{?}", (string id, Request request) =>

**Comment by dan31** [comment] 2015-07-30 13:18
@alemoi, any good ideas? Looks like @Ripipip's case is 100% reproducible.

**Comment by alemoi** [comment] 2015-07-30 14:51
I have the file with URI from @Ripipip that reproduces the error. We just need to sit on it. Sorry, for delay @Ripipip

**Comment by alemoi** [comment] 2015-07-31 15:19
We have identified the issue with the help of @Starcounter-Jack 
The fix will be available with the following nightly build! Thank you for the bug report @Ripipip!

**Comment by dan31** [comment] 2015-08-13 17:42
@Ripipip, does it work for you well?

**Comment by dan31** [comment] 2016-01-15 12:09
@Ripipip can we close this one?

**Comment by alemoi** [comment] 2016-01-15 12:51
Yes, this one is resolved. I was just waiting for confirmation.

**Closed by alemoi** 2016-01-15 12:51 UTC
Labels: bug
