### ISSUE TITLE
Partial class does not generate properties

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3166] opened 2015-12-10 09:16 UTC
Related to this issue #3160 I created a partial class with an attribute ```[Page_json.Products]```. If this class is in the same file as the ```Page``` I can access the properties i defined in the JSON file but if I move this class into a seperate file (Products.cs) the properties are not generated anymore.

You can test it with this project: [test project](https://github.com/jwillmer/StarcounterModelChangeEventTestProject)

**Comment by per-samuelsson** [comment] 2015-12-10 14:01
@jwillmer 

Thanks for reporting this.

I'm not sure, but I think its by design that code behind classes have to be in the code-behind file. Otherwise, the parser/compiler won't find them. @chrhol, can you confirm?

**Comment by per-samuelsson** [comment] 2015-12-11 12:24
I talked to @chrhol - he confirms what I wrote above. And in the light of all the things we have to do right now, and that we are low in resources, its unlikely we'll try to come up with some improvement in the close future. I'll close this one b/c of that. Let us know if you think that is very wrong, @jwillmer.

**Closed by per-samuelsson** 2015-12-11 12:24 UTC
Labels: question, Typed JSON

**Comment by jwillmer** [comment] 2015-12-11 14:10
I think it is not a showstopper but I think it is a strange behaviour. Is it only because you implemented it that way or is this behaviour equal with other implementations in .NET? 
I just assumed that it is a bug because I do not get any warning then I put the attribute on a class that is not in the same file.
