### ISSUE TITLE
Building apps without Visual Studio produces a wall of warnings

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2896] opened 2015-09-17 17:54 UTC
We are giving a 1.5 hour workshop in October 2015 (CodeNight). It would be great get everyone in the room up and running Starcounter, without having to bother with installation of Visual Studio. This is especially important to appeal to the "hacker" community.

A goal is to compile Starcounter InvoiceDemo (http://starcounter.io/tutorials/) on a fresh Windows 10 installation (a VM of such may be obtained from here https://dev.modern.ie/tools/vms/)

After trying to do so, I came upon such obstacles:
1. `msbuild` comes preinstalled in Windows 10, but is not available in PATH. This can be fixed by calling `set PATH=%PATH%;C:\Windows\Microsoft.NET\Framework\v4.0.30319` (warning: such change in cmd is not persistent)
2. Trying to run `msbuild InvoiceDemo1.csproj` (downloaded as ZIP from https://github.com/Starcounter/InvoiceDemo/archive/master.zip) results in a wall of warnings:

```
c:\Users\IEUser\Downloads\InvoiceDemo-master\src\InvoiceDemo1>msbuild InvoiceDemo.csproj
Microsoft (R) Build Engine version 4.6.79.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 9/17/2015 7:50:22 PM.
Project "c:\Users\IEUser\Downloads\InvoiceDemo-master\src\InvoiceDemo1\InvoiceDemo.csproj" on node 1 (default targets).
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(983,5): warning MSB3644: The reference assemblie
s for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for thi
s framework version or retarget your application to a version of the framework for which you have the SDK or Targeting
Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of
 reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [c:\Users\IE
User\Downloads\InvoiceDemo-master\src\InvoiceDemo1\InvoiceDemo.csproj]
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3270: There was a mismatch b
etween the processor architecture of the project being built "AMD64" and the processor architecture of the reference "C
:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll", "x86". This mismatch may cause runtime failures. Please con
sider changing the targeted processor architecture of your project through the Configuration Manager so as to align the
 processor architectures between your project and references, or take a dependency on references with a processor archi
tecture that matches the targeted processor architecture of your project. [c:\Users\IEUser\Downloads\InvoiceDemo-master
\src\InvoiceDemo1\InvoiceDemo.csproj]
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the i
nput files.
GenerateTypedJSONCode:
Skipping target "GenerateTypedJSONCode" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  InvoiceDemo -> c:\Users\IEUser\Downloads\InvoiceDemo-master\src\InvoiceDemo1\bin\Debug\InvoiceDemo.exe
Done Building Project "c:\Users\IEUser\Downloads\InvoiceDemo-master\src\InvoiceDemo1\InvoiceDemo.csproj" (default targe
ts).


Build succeeded.

"c:\Users\IEUser\Downloads\InvoiceDemo-master\src\InvoiceDemo1\InvoiceDemo.csproj" (default target) (1) ->
(GetReferenceAssemblyPaths target) ->
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(983,5): warning MSB3644: The reference assembl
ies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for t
his framework version or retarget your application to a version of the framework for which you have the SDK or Targetin
g Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place
of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [c:\Users\
IEUser\Downloads\InvoiceDemo-master\src\InvoiceDemo1\InvoiceDemo.csproj]


"c:\Users\IEUser\Downloads\InvoiceDemo-master\src\InvoiceDemo1\InvoiceDemo.csproj" (default target) (1) ->
(ResolveAssemblyReferences target) ->
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3270: There was a mismatch
 between the processor architecture of the project being built "AMD64" and the processor architecture of the reference
"C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll", "x86". This mismatch may cause runtime failures. Please c
onsider changing the targeted processor architecture of your project through the Configuration Manager so as to align t
he processor architectures between your project and references, or take a dependency on references with a processor arc
hitecture that matches the targeted processor architecture of your project. [c:\Users\IEUser\Downloads\InvoiceDemo-mast
er\src\InvoiceDemo1\InvoiceDemo.csproj]

    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.15
```

And now a pleasant surprise. **The app actually works!** Confirmed with InvoiceDemo 1, 2 and 3.

![image](https://cloud.githubusercontent.com/assets/566463/9941326/e7dd769c-5d74-11e5-9165-340d88480907.png)

The problem is, how to get rid of the yellow warnings?

If user needs to perform a series of setup actions, this should ideally be done by installer, or as a bat script that I can put on GitHub.

**Comment by warpech** [comment] 2015-09-17 17:55
@Starcounter-Jack suggested that @chrhol may be able to help

**Comment by dan31** [comment] 2015-09-17 18:44
Quite flawless! What about trying this instead?

> c:\Windows\Microsoft.NET\Framework64\v4.0.30319\

We require x64.

**Comment by dan31** [comment] 2015-09-17 18:45
Also I see it seeks for .NET v.4.5. Can you check that the project is set to the very latest .NET available?

**Comment by chrhol** [comment] 2015-09-18 07:29
We have had these warnings for quite some time. The problem lies with the Visual Studio Extension since VS is run as a x86 process.

What we need to do is go through all shared dll's (that is shared between VS and SC) and either move unsafe/unmanaged code or rewrite it to not use unsafe/unmanaged code. Then we can properly set the platform to AnyCPU instead of specifying either x86 or x64

There is an really old issue concerning this: #36. What priority should this have @dan31

**Comment by chrhol** [comment] 2015-09-18 07:31
No I'm a little bit wrong :) It's not only the extension. The buildtask for TypedJson is also the cause

**Comment by warpech** [comment] 2015-09-18 07:49
To give you more information about the VM setup, this is the setup as Windows 10 VM sees it:

![image](https://cloud.githubusercontent.com/assets/566463/9954552/4ff04d84-5dea-11e5-8aec-c10095ba472b.png)

Interestingly, my everyday Windows 8.1 VM with exactly the same config and VS2013 installed does not show these warnings.

**Comment by chrhol** [comment] 2015-09-18 07:55
Oh sorry, I didn't read the warnings correctly. Sorry, I'm a bit tired :) This are not the same as the issue I linked.

Then it looks like it's some problem with installed .Net framework. Will you be in the office today?

**Comment by chrhol** [comment] 2015-09-18 12:17
So from what I found is that what is needed to get rid of these warnings are .Net Framework 4.5 SDK, that can be obtained from https://msdn.microsoft.com/en-us/windows/desktop/hh852363.aspx.

Just unclick every other option, the download size is about 70 mb.

I wonder if this is needed beacuse the project uses the VS extension. I will try to edit the project and see what happens.

**Comment by chrhol** [comment] 2015-09-21 07:02
No, the cause is not our extension. Even with it removed from the project you get the same warnings. Lets discuss how we want to handle this in the morning meeting.

**Comment by dan31** [comment] 2015-09-22 06:29
@warpech, setting project's .net framework version to 4.6 doesn't help on your VM?

**Comment by warpech** [comment] 2015-09-23 15:27
@chrhol I confirm installing .Net Framework 4.5 SDK helped.

@dan31 you mean changing `InvoiceDemo1.csproj` to have `<TargetFrameworkVersion>v4.6</TargetFrameworkVersion>`?

No, that just changed the first warning to say:

```
warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found.
```

Where do we go from here? Is there a way we could not have the code that produces warnings if .Net Framework 4.5 SDK is not installed?

**Comment by dan31** [comment] 2015-10-06 15:40
I'm thinking, would we do any harm if we add ```PATH=%PATH%;C:\Windows\Microsoft.NET\Framework\v4.0.30319``` in the installer.

**Comment by dan31** [comment] 2015-10-06 16:30
Everything is shipped in this Win-10 VM. This seems minimally possible:
```set PATH=%PATH%;C:\Windows\Microsoft.NET\Framework64\v4.0.30319```
```msbuild -p:FrameworkPathOverride="c:\Windows\Microsoft.NET\Framework64\v4.0.30319" InvoiceDemo.csproj```
Please note who's making demos: Framework __64__
```PathOverride``` there appears to be inevitable.

```
C:\Users\IEUser\Desktop\InvoiceDemo-master\src\InvoiceDemo2>msbuild -p:FrameworkPathOverride="c:\Windows\Microsoft.NET\Framework64\v4.0.30319" InvoiceDemo.csproj
Microsoft (R) Build Engine version 4.6.79.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 10/6/2015 6:08:05 PM.
Project "C:\Users\IEUser\Desktop\InvoiceDemo-master\src\InvoiceDemo2\InvoiceDemo.csproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "bin\Debug\".
  Creating directory "obj\x64\Debug\".
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the i
nput files.
GenerateTypedJSONCode:
  Creating obj\x64\Debug\InvoicePage.json.g.cs
apa  Creating obj\x64\Debug\InvoicesPage.json.g.cs
apa  Creating obj\x64\Debug\MasterPage.json.g.cs
apaCoreCompile:
  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Csc.exe /noconfig /unsafe+ /nowarn:1701,1702 /nostdlib+ /platform:x64
   /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+ /reference:c:\Windows\Microsoft.NET\Framework64\v4.0
  .30319\Microsoft.CSharp.dll /reference:c:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll /reference:"C:\Pr
  ogram Files\Starcounter\2.1.69\Public Assemblies\Starcounter.dll" /reference:"C:\Program Files\Starcounter\2.1.69\Pub
  lic Assemblies\Starcounter.Internal.dll" /reference:"C:\Program Files\Starcounter\2.1.69\Public Assemblies\Starcounte
  r.Logging.dll" /reference:"C:\Program Files\Starcounter\2.1.69\Public Assemblies\Starcounter.XSON.dll" /reference:c:\
  Windows\Microsoft.NET\Framework64\v4.0.30319\System.Core.dll /reference:c:\Windows\Microsoft.NET\Framework64\v4.0.303
  19\System.dll /debug+ /debug:full /filealign:512 /optimize- /out:obj\x64\Debug\InvoiceDemo.exe /subsystemversion:6.00
   /target:exe /warnaserror- /utf8output Database.cs InvoicePage.json.cs InvoicesPage.json.cs MasterPage.json.cs Progra
  m.cs Properties\AssemblyInfo.cs "C:\Users\IEUser\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
   obj\x64\Debug\InvoicePage.json.g.cs obj\x64\Debug\InvoicesPage.json.g.cs obj\x64\Debug\MasterPage.json.g.cs
CopyFilesToOutputDirectory:
  Copying file from "obj\x64\Debug\InvoiceDemo.exe" to "bin\Debug\InvoiceDemo.exe".
  InvoiceDemo -> C:\Users\IEUser\Desktop\InvoiceDemo-master\src\InvoiceDemo2\bin\Debug\InvoiceDemo.exe
  Copying file from "obj\x64\Debug\InvoiceDemo.pdb" to "bin\Debug\InvoiceDemo.pdb".
Done Building Project "C:\Users\IEUser\Desktop\InvoiceDemo-master\src\InvoiceDemo2\InvoiceDemo.csproj" (default targets
).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.23
```

So one can include some ```build_demo.bat``` along with the demo project which sets ```PATH```, invokes ```msbuild``` with the given override and then leaves ```cmd``` for the presenter to do ```star``` and stuff.

There is better option, however – http://source.roslyn.io/#MSBuildProperty=FrameworkPathOverride, so: paste this override just into the csproj and have the right PATH by a means of the installer. I did the former in .csproj:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <FrameworkPathOverride>c:\Windows\Microsoft.NET\Framework64\v4.0.30319</FrameworkPathOverride>
  </PropertyGroup>
```
After adding so, ```msbuild``` works alone with no override in command prompt. This should be done smarter, so that we don't do overrides on normal machines. Conditionals can be done like explained http://source.roslyn.io/#MSBuildProperty=FrameworkPathOverride . @chrhol, maybe you can volunteer sometime for those particular .csproj to find a right way with conditionals? We can even include that in a template eventually. We shall also add some smart override to ```PATH``` in the installer with @andwah and @alemoi, if you guys see no clear objections. Then everything will work out of the box on a clean Win-10 machine, which is __awesome__.

**Comment by warpech** [comment] 2015-10-09 14:33
I confirm the Dan's solution works, so in the worst case I will use `bat` files for CodeNight.

Remember we are speaking about users without Visual Studio, so for them `csproj` files are only something they can supply as a parameter to `msbuild`, but not actually something that is easily created or edited.

1. @chrhol would it be possible for you to add conditional FrameworkPathOverride to csproj template?
2. @andwah, @alemoi should and can PATH override be added to the installer?

**Comment by alemoi** [comment] 2015-10-09 17:40
Sure, I will add "C:\Windows\Microsoft.NET\Framework64\v4.0.30319" to PATH environment variable, we already add StarcounterBin to it.

**Comment by alemoi** [comment] 2015-10-09 22:10
Number 2 should be now fixed via 61f024d5d7d6c035119bbef9c088bd19c9b1554c
Available in this nightly.

**Comment by warpech** [comment] 2015-10-12 07:02
I confirm `msbuild` is now in PATH.

Current state:

InvoiceDemo compiles with msbuild on a fresh Windows 10 image with a single warning:

```
"C:\Users\IEUser\Downloads\InvoiceDemo-master\src\InvoiceDemo1\InvoiceDemo.csproj" (default target) (1) ->
(GetReferenceAssemblyPaths target) ->
  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Common.targets(983,5): warning MSB3644: The reference assem
blies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for
 this framework version or retarget your application to a version of the framework for which you have the SDK or Target
ing Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in plac
e of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\User
s\IEUser\Downloads\InvoiceDemo-master\src\InvoiceDemo1\InvoiceDemo.csproj]

    1 Warning(s)
    0 Error(s)
```

![image](https://cloud.githubusercontent.com/assets/566463/10422809/bc6f0206-70bf-11e5-92fe-8ee6d82c6fbd.png)

@chrhol is it possible to get rid of this last warning based on @dan31 instructions?

**Comment by chrhol** [comment] 2015-10-12 07:27
> @chrhol is it possible to get rid of this last warning based on @dan31 instructions?

Probably. I will look into it today

**Comment by dan31** [comment] 2015-10-12 10:10
@chrhol, please note that having such a ```FrameworkOverride``` in the InvoiceDemo csproj (and in our VS templates) with a direct path might be too brutal. It is okay with system ```PATH```, but with the csproj a thinner approach like from http://source.roslyn.io/#MSBuildProperty=FrameworkPathOverride might be more appropriate.

**Comment by chrhol** [comment] 2015-10-12 12:11
I've pushed some changes based on the findings from @dan31 to the project-files for InvoiceDemo1, 2 and 3.

I've tested it on a clean Win10 VM and it seems to be working. @warpech, please let me know if something is not working as it should. I will wait and see that everything is ok before I make this change to our existing project-templates.

The following code-snippet has been added:

```xml
<PropertyGroup>
  <!-- If the tools for .Net 4.5 are not available (since they are separated from the 
	runtime for 4.5) we override the path to the framework to use to .NET 4.0
	to avoid compiler warnings when compiling on installations without VS installed.
		 
    The override needs to be set before the targets files are imported and getting the 
	path to the tools needs to be called after setting build and platform configurations.
  -->
  <TargetFrameworkToolsPath>$([Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries(.NetFramework, $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget)))</TargetFrameworkToolsPath>
  <DotNet40FrameworkPath Condition="'$(TargetFrameworkToolsPath)'==''">$([Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToDotNetFramework(Microsoft.Build.Utilities.TargetDotNetFrameworkVersion.Version40))</DotNet40FrameworkPath>
  <FrameworkPathOverride Condition="'$(TargetFrameworkToolsPath)'==''">$(DotNet40FrameworkPath)</FrameworkPathOverride>
</PropertyGroup>
```

**Comment by dan31** [comment] 2015-10-12 15:01
@chrhol looks like exactly what the doctor has prescribed, awesome! :+1:
@per-samuelsson, do you think we can use that one in our VS templates?

**Comment by chrhol** [comment] 2016-10-10 08:03
Old issue. @dan31: Should we still add the snippet above to our VS templates?

**Comment by chrhol** [comment] 2016-12-16 12:18
This feels more like a hack than a solution we want to incorporate in our VS templates. If someone does not agree, just reopen it and I will do it.

**Closed by chrhol** 2016-12-16 12:18 UTC
Labels: CodeNight
