### ISSUE TITLE
pnext: debug build of starcounter fails on profiler in URI matcher

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3332] opened 2016-02-02 08:45 UTC
I installed Starcounter from locally build in Debug configuration. After obtaining latest changes I cannot create any database. I get the following exception:

```bash
>staradmin start db
Starting default (creating database ..)

[09:43:21, Starcounter.Server.Commands (scadminserver)]
ScErrServerCommandFailed (SCERR10011): The operation "Creating database Default"
 failed.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.

[09:43:21, Starcounter.Server.Commands (scadminserver)]
ScErrUnexpectedCommandException (SCERR10016): Creating database Default failed d
ue to an unexpected problem.
Version: 2.0.0.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Starcounter.Profiler.get_Current() in C:\GitRepositories\Starcounter\Level
1\src\Starcounter.Internal\Profiler\Profiler.cs:line 318
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPt
r methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\G
itRepositories\Starcounter\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.c
s:line 70
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(Str
ing methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 po
rtNumber, Response& resp) in C:\GitRepositories\Starcounter\Level1\src\Starcount
er.Rest\UriManagedHandlersCodegen.cs:line 1114
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relat
iveUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOp
tions handlerOptions, Request req) in C:\GitRepositories\Starcounter\Level1\src\
Starcounter.Internal\Rest\Self.cs:line 392
   at Starcounter.Self.POST(String uri, String body, Byte[] bodyBytes, Dictionar
y`2 headersDictionary, UInt16 port, HandlerOptions ho) in C:\GitRepositories\Sta
rcounter\Level1\src\Starcounter.Internal\Rest\Self.cs:line 155
   at Starcounter.Server.PublicModelProvider.AddDatabase(Database database) in C
:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\PublicModelPr
ovider.cs:line 66
   at Starcounter.Server.Commands.CreateDatabaseCommandProcessor.Execute() in C:
\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\Commands\Proce
ssors\CreateDatabaseCommandProcessor.cs:line 39
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandS
tatusChangedCallback notifyStatusChangedCallback) in C:\GitRepositories\Starcoun
ter\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 298
HResult=-2146233080
```

Can anyone try to reproduce it?

The steps:

1. Build Level0 and Level1 in Debug configuration
2. Install Starcounter (I install into the output folder of Level1)
3. Start a default database, which does not exist yet: `staradmin start db`

**Comment by k-rus** [comment] 2016-02-02 08:55
I run a person build and this problem was reproduced, see [this](https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=733#_focus=8822)

cc @chrhol @alemoi

**Comment by alemoi** [comment] 2016-02-02 09:57
Thanks for reporting! The change is mine, but i didn't experience this problem neither on my nor on build machines.

**Comment by alemoi** [comment] 2016-02-02 09:58
Will try to reproduce using your scenario.

**Comment by alemoi** [comment] 2016-02-02 10:05
I think I know the reason: there is an illigal call to Self while not being on scheduler in PublicModelProvider.cs
I will fix that.

**Comment by alemoi** [comment] 2016-02-02 10:37
Thanks for reporting @k-rus The issue should be fixed now. There were a couple of illegal (because calling code is not on scheduler) Self calls in Starcounter.Server which I replaced with Http calls instead. CCing @andwah and @per-samuelsson so they know about this change: d459fc6d155fb74bf0b1f5a96b4d91f4247b8457 and fcbf147caf6733f7b5cb935eb9c9c3585fdaadd5

**Closed** 2016-02-02 11:24 UTC
Labels: P/SHOWSTOPPER

**Comment by k-rus** [comment] 2016-02-02 14:32
> on build machines.

You cannot see it on build machines, because they don't run Starcounter built in Debug configuration. Thus I created issue #3333 to do so.
