### ISSUE TITLE
Assertion failure in scllvm

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3913] opened 2016-10-27 14:33 UTC
I have local build of Starcounter from latest sources of Level0 and Level1 branch develop. When I run `QueryProcessingTest` I get assertion failure in scllvm:
![scllvmassertionfailure](https://cloud.githubusercontent.com/assets/1726044/19771351/f0a8b39e-9c62-11e6-8318-4855bcc146a2.png)

The source line for the assertion is different than in #3906

cc @alemoi

**Comment by k-rus** [comment] 2016-10-27 14:34
In the command line I find this error:

>'clang++' is not recognized as an internal or external command,
operable program or batch file.

**Comment by alemoi** [comment] 2016-10-27 15:03
Are you running query processing test the same way as on build servers? I guess the executable should be in the Level0 output folder, which should contain `scllvm.dll` and `clang++.exe`

**Comment by alemoi** [comment] 2016-10-27 15:17
Here is an example of successful test run in develop:
https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=12401#_focus=6795

Do you run it by some other means?

**Comment by k-rus** [comment] 2016-10-27 15:17
> Are you running query processing test the same way as on build servers? I guess the executable should be in the Level0 output folder, which should contain scllvm.dll and clang++.exe

I run it as I was doing many years, i.e., by calling the batch file from the build folder.

Who should put the files in the output folder? It should not be done manually, since the folder is automatically created by VS. 

There was no such requirement before and it worked. I don't really know when it became broken. It is also no in the instructions.

**Comment by alemoi** [comment] 2016-10-27 15:22
Sorry, I know only the way how build server runs this test automatically and its hard for me to track the specifics. Here is the tonight's nightly running this test successfully: 
https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=12401#_
How can I help you make it run?

**Comment by k-rus** [comment] 2016-10-27 15:28
> Sorry, I know only the way how build server runs this test automatically and its hard for me to track the specifics.

I run in the same way as on the build server, but without Starcounter installation, which was always hard requirements from me.

I have no idea how to make my build working. No installation of Starcounter should be required. No manual copies of files into output folder should be required.

**Comment by k-rus** [comment] 2016-10-27 15:33
> No installation of Starcounter should be required.

Installing Starcounter form local build does not help. I believe installation should fail if files are missing? Do we have something like this?

**Comment by k-rus** [comment] 2016-10-27 15:36
Actually Level0 build folder contains the required files.

**Comment by alemoi** [comment] 2016-10-27 15:36
Are you running the queryprocessing_test.bat batch from the output directory? 
Do you see the clang++.exe and scllvm.dll files?
Do you have CopyDependenciesLocal.csproj running for you (it copies all files from Level0 bin)?

**Comment by k-rus** [comment] 2016-10-27 15:38
I will investigate further. Probably building Level1 didn't work correctly as we experienced this before.

**Comment by alemoi** [comment] 2016-10-27 15:39
> I will investigate further. Probably building Level1 didn't work correctly as we experienced this before.

Yeah, just let me know how it goes!

**Comment by k-rus** [comment] 2016-10-27 16:23
The files are in both Level0 and Level1 output folder. Do you require setting STARCOUNTER_BIN variable? I guess. Actually installation of Starcounter and starting new CMD helped.

Now I get very strange warnings:

```
eab5f4d5eaf733b6241ed6159fa3e41903f66c7ed4b476b32f4f1d80999c905d.cpp:1231:1: warning:
      'register' storage class specifier is deprecated and incompatible with
      C++1z [-Wdeprecated-register]
```
I've got many of them.

**Comment by k-rus** [comment] 2016-10-27 16:30
some more, but not all:
```
a4b4b0e572122ebd659954e455fbcc5c1b140542bfb751076d4b77081cf3a826.cpp:1271:1: warning:
      'register' storage class specifier is deprecated and incompatible with
      C++1z [-Wdeprecated-register]
register uint8_t toReadFromNextBuffer = bitindexAfterRead - REGISTER_SIZE;
^~~~~~~~~
a4b4b0e572122ebd659954e455fbcc5c1b140542bfb751076d4b77081cf3a826.cpp:1283:1: warning:
      'register' storage class specifier is deprecated and incompatible with
      C++1z [-Wdeprecated-register]
register REGISTER next = buffer;
^~~~~~~~~
a4b4b0e572122ebd659954e455fbcc5c1b140542bfb751076d4b77081cf3a826.cpp:1290:1: warning:
      'register' storage class specifier is deprecated and incompatible with
      C++1z [-Wdeprecated-register]
register REGISTER ret = buffer;
```

**Comment by alemoi** [comment] 2016-10-27 16:33
> The files are in both Level0 and Level1 output folder. Do you require setting STARCOUNTER_BIN variable? I guess. Actually installation of Starcounter and starting new CMD helped.

Strange, the Python related stuff should not require `StarcounterBin`. Maybe some other code.

> eab5f4d5eaf733b6241ed6159fa3e41903f66c7ed4b476b32f4f1d80999c905d.cpp:1231:1: warning:
      'register' storage class specifier is deprecated and incompatible with
      C++1z [-Wdeprecated-register]

These are the warnings from clang++ compiler for the generated code, because of new C++ I suppose. Is it the code you generate?

**Comment by k-rus** [comment] 2016-10-27 16:52
> The files are in both Level0 and Level1 output folder. Do you require setting STARCOUNTER_BIN variable? I guess. Actually installation of Starcounter and starting new CMD helped.
> Strange, the Python related stuff should not require StarcounterBin. Maybe some other code.

It is clang++ related stuff. See OP, i.e., `clang++.exe` is not found.



> These are the warnings from clang++ compiler for the generated code, because of new C++ I suppose. Is it the code you generate?

There is no code gen in SQL in develop. So it is definitely related to the kernel. I am wonder if it is possible that those lines are also on the build server, but not put in the build log.

**Comment by alemoi** [comment] 2016-10-27 18:49
I specifically tried to reproduce your case by deleting all develop binaries and removing Starcounter, so that there is no `StarcounterBin`, then I built binaries and started ` queryprocessing_test.bat` from bin/debug, and test succeeded:
```
c:\github\Starcounter\Level1\bin\Debug>echo %starcounterbin%
%starcounterbin%

c:\github\Starcounter\Level1\bin\Debug>queryprocessing_test.bat

c:\github\Starcounter\Level1\bin\Debug>IF "" == "False" GOTO :EOF

c:\github\Starcounter\Level1\bin\Debug>SET DB_DIR=.db

c:\github\Starcounter\Level1\bin\Debug>SET DB_OUT_DIR=.db.output

c:\github\Starcounter\Level1\bin\Debug>SET DB_NAME=QUERYPROCESSINGTEST

c:\github\Starcounter\Level1\bin\Debug>SET TEST_NAME=QueryProcessingTest

c:\github\Starcounter\Level1\bin\Debug>staradmin kill all

c:\github\Starcounter\Level1\bin\Debug>IF EXIST .db (
RMDIR .db /S /Q
 RMDIR .db.output /S /Q
)

.................

Finished testing offset key
Test object identities
Finished testing object identities
Test populated meta-data
Finished testing populated meta-data
Test kinds like behavior
Finished testing kinds like behavior
Benchmark of query cache is skipped
Start unloading query processing database.
Finish unloading query processing database. Unloaded 43035 objects.
Start delete the database data.
Finish delete the database data.
All tests completed

c:\github\Starcounter\Level1\bin\Debug>IF ERRORLEVEL 1 (
ECHO Error: The query processing regression test failed!
 EXIT /b 1
)  else (
ECHO The query processing regression test succeeded.
 EXIT /b 0
)
The query processing regression test succeeded.
```

**Comment by k-rus** [comment] 2016-10-28 08:36
> I specifically tried to reproduce your case by deleting all develop binaries and removing Starcounter, so that there is no StarcounterBin, then I built binaries and started queryprocessing_test.bat from bin/debug, and test succeeded:

If I uninstall Starcounter, I cannot run the test because `clang++.exe` cannot be found. I guess Starcounter searchers for it in `PATH`. Have you started new CMD window where all environment variables were updated after you uninstalled Starcounter?

**Comment by k-rus** [comment] 2016-10-28 08:51
@alemoi It is as difficult for you to get our environment, where we have problems, as for us to get environment where everything works.

I am now rebuilding everything to see if I will still have the warnings. It takes huge amount of time.

**Comment by k-rus** [comment] 2016-10-28 08:58
> I am now rebuilding everything to see if I will still have the warnings. It takes huge amount of time.

I did and still have the warnings.

**Comment by k-rus** [comment] 2016-10-28 09:00
Note that the test succeeds and the warnings are somewhere in the middle or in the first part of the test.

**Comment by k-rus** [comment] 2016-10-28 09:01
The warnings are printed in some other way than normal console output. I cannot redirect them into a file, for example. Thus they cannot be seen in build logs even if they are presented.

**Comment by k-rus** [comment] 2016-10-28 09:05
Here is a screenshot:

![clangwarnings](https://cloud.githubusercontent.com/assets/1726044/19801178/64e213a4-9cfe-11e6-9437-38b381d176b2.png)

**Comment by alemoi** [comment] 2016-10-28 09:24
> If I uninstall Starcounter, I cannot run the test because clang++.exe cannot be found. I guess Starcounter searchers for it in PATH. Have you started new CMD window where all environment variables were updated after you uninstalled Starcounter?

So it eventually succeeded on your machine without Starcounter?

> The warnings are printed in some other way than normal console output. I cannot redirect them into a file, for example. Thus they cannot be seen in build logs even if they are presented.

Yes, this is annoying but the idea is that we don't have any warnings in the generated code. The idea is actually to treat warnings as errors.

**Comment by k-rus** [comment] 2016-10-28 09:27
> If I uninstall Starcounter, I cannot run the test because clang++.exe cannot be found. I guess Starcounter searchers for it in PATH. Have you started new CMD window where all environment variables were updated after you uninstalled Starcounter?
> So it eventually succeeded on your machine without Starcounter?

No, I explicitly wrote that I cannot run the test if Starcounter is not installed. So it is something became broken when new clang was added.



> Yes, this is annoying but the idea is that we don't have any warnings in the generated code. The idea is actually to treat warnings as errors.

So these warnings need to be fixed too.

**Comment by alemoi** [comment] 2016-10-28 09:36
> No, I explicitly wrote that I cannot run the test if Starcounter is not installed. So it is something became broken when new clang was added.

Are you running the queryprocessing_test.bat batch from the output directory with all files?

**Comment by k-rus** [comment] 2016-10-28 09:38
> No, I explicitly wrote that I cannot run the test if Starcounter is not installed. So it is something became broken when new clang was added.
> Are you running the queryprocessing_test.bat batch from the output directory with all files?

yes, from `Level1\bin\Debug\`

**Comment by alemoi** [comment] 2016-10-28 09:54
Here I print `%path%` and `%starcounterbin%` before the test:
```
c:\github\Starcounter\Level1\bin\Debug>echo %path%
C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\P
rogram Files (x86)\nasm\;c:\clang\GnuWin32\GnuWin32\bin\;C:\Program Files (x86)\CMake\bin;C:\Go\bin;C:\Users\Alexey Moiseenko\.dnx\bin;C:\Pr
ogram Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\GitExtensions\;C
:\Program Files\dotnet\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Skype\
Phone\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Alexey Moiseenko\AppData\Local\Programs\Python\Python35-32\Scripts\;C
:\Users\Alexey Moiseenko\AppData\Local\Programs\Python\Python35-32\;c:\Program Files\ConEmu\;c:\BuildTools;c:\Program Files (x86)\Git\bin;c:
\Program Files\nodejs

c:\github\Starcounter\Level1\bin\Debug>echo %starcounterbin%
%starcounterbin%
```
that have no tracks of Starcounter. Test runs fine, so its very strange.

Anyways, in this case I will stick to tests requirements that I created before (https://github.com/Starcounter/AdminTrack/blob/master/build_system.md#test-system):

> Tests should rely on that Starcounter is installed (StarcounterBin variable, installed server, etc), and has EditionLibraries and LibrariesWithDatabaseClasses. You should have this in mind, writing your classes and doing SQL (indexquery and some other tests have a rename of this directories, but this is a historical exception, which will be solved in future).

> So these warnings need to be fixed too.
Yes, the warnings need to be fixed in the generated code, but not by clang suppressing them, I suppose.

**Comment by k-rus** [comment] 2016-10-28 11:45
> that have no tracks of Starcounter. Test runs fine, so its very strange.

Do you run it on develop or pnext? It works fine on pnext for me, but it does not work on develop as stated in OP.



> Tests should rely on that Starcounter is installed (StarcounterBin variable, installed server, etc), and has EditionLibraries and LibrariesWithDatabaseClasses. You should have this in mind, writing your classes and doing SQL (indexquery and some other tests have a rename of this directories, but this is a historical exception, which will be solved in future).

As I always say this is not acceptable. The tests, which do not require Starcounter installation, should work without Starcounter being installed. However they should also not break if Starcounter installed. By pushing requirement for the installing Starcounter you push away testing. If it is much work to do tests, then there will be no tests.



> tests requirements that I created before (https://github.com/Starcounter/AdminTrack/blob/master/build_system.md#test-system):

General comment is that the requirement list is huge and I am not sure if there will be many who will read and keep in mind these requirements. It would be nice to shorten and simplify them in future.

**Comment by alemoi** [comment] 2016-10-28 12:12
> Do you run it on develop or pnext? It works fine on pnext for me, but it does not work on develop as stated in OP.

Yes, develop. Very strange.

> As I always say this is not acceptable. The tests, which do not require Starcounter installation, should work without Starcounter being installed. However they should also not break if Starcounter installed. By pushing requirement for the installing Starcounter you push away testing. If it is much work to do tests, then there will be no tests.

The idea was that's its way simpler to assume that Starcounter is installed for the tests. Anyways, I wonder if the problem fixes for you if you copy clang++.exe into your binary directory for the test (should `be bin/debug/s/queryproc...`)

> General comment is that the requirement list is huge and I am not sure if there will be many who will read and keep in mind these requirements. It would be nice to shorten and simplify them in future.

Regarding local tests these are the main requirements that are very simple, I suppose:

```
Tests are supposed to be run from the location they are in repository, should not require a copy to bin or anything except double-click. Working directory is the same as test file, for example, batch file. We have some current tests that are copied to output directory, but this is just historical compliance.

Tests should rely on that Starcounter is installed (StarcounterBin variable, installed server, etc), and has EditionLibraries and LibrariesWithDatabaseClasses. You should have this in mind, writing your classes and doing SQL (indexquery and some other tests have a rename of this directories, but this is a historical exception, which will be solved in future).
```

**Comment by k-rus** [comment] 2016-10-28 12:31
> I wonder if the problem fixes for you if you copy clang++.exe into your binary directory for the test (should be bin/debug/s/queryproc...)

This requires to add it into weaver.ignore. I checked that adding bin folder to path allows test to run, however I get the warnings. (I didn't get warnings on pnext) So it feels that these two problems are related.

By the way, do you build Blue.sln and SqlProcssor.sln locally?

**Comment by alemoi** [comment] 2016-10-28 12:35
> By the way, do you build Blue.sln and SqlProcssor.sln locally?

Yes, they are both built. I wonder why there is no issue with `scllvm.dll` that should be complained first, before running `clang++.exe`. Do you have it in the folder?

**Comment by k-rus** [comment] 2016-10-28 12:39
> Yes, they are both built. I wonder why there is no issue with scllvm.dll that should be complained first, before running clang++.exe. Do you have it in the folder?

Yes, I have it.

I am currently investigating if it is related to Windows Anniversary update. I rollback to previous version. Let's see what will be the result.

**Comment by alemoi** [comment] 2016-10-28 12:42
Here is the screen from `s/QueryProcessingTest`:
![image](https://cloud.githubusercontent.com/assets/208134/19806673/b2bea51a-9d1c-11e6-978e-481a2586b3af.png)
I don't have the `scllvm.dll` and `clang++.exe` there. Do you have?

**Comment by k-rus** [comment] 2016-10-28 12:44
> I am currently investigating if it is related to Windows Anniversary update. I rollback to previous version. Let's see what will be the result.

No, didn't help.



> I don't have the scllvm.dll and clang++.exe there. Do you have?

No, I don't have them. You asked me to try to copy there and I've got weaver error.

**Comment by alemoi** [comment] 2016-10-28 12:46
Can you please share your bin/debug somewhere? I will download and check it. Thanks.

**Comment by k-rus** [comment] 2016-10-28 12:56
> Can you please share your bin/debug somewhere? I will download and check it. Thanks.

[here](https://www.dropbox.com/s/dri4xbxda4qc57u/Debug.zip?dl=0)
thank you

**Comment by alemoi** [comment] 2016-10-28 13:14
Thanks! Able to reproduce it with your folder. Checking what is the problem.

**Comment by k-rus** [comment] 2016-10-28 13:15
> Thanks! Able to reproduce it with your folder. Checking what is the problem.

wow
Can you check if you see the problem with warnings too? It requires to add bin folder to PATH.

**Comment by alemoi** [comment] 2016-10-28 13:55
I found what the problem can be related to and going to fix it. For now, please add bin to PATH: `set PATH=%PATH%;%cd%`

So thanks for testing on your system!

Regarding the warnings in output, yes I have them. I removed those `register` keywords in Level0 develop branch `developregisterwarn` but not sure if this is the way to go. @bigwad what do you think of those `register` variables?

**Comment by bigwad** [comment] 2016-10-28 14:00
As compiler says - ```register``` keyword is deprecated and to be removed.

**Comment by alemoi** [comment] 2016-10-28 14:03
Ok, then I will test with my patch and merge it. Thanks for the quick resp.

**Comment by alemoi** [comment] 2016-10-28 14:34
I tested with SQL tests and pushed changes to develop Level0, so now @k-rus you should not see the warnings.

**Comment by alemoi** [comment] 2016-10-28 23:23
Thanks for the input! I have produced a patch now for scllvm in develop, so your test should work once you pull the latest develop level0/level1!

**Comment by k-rus** [comment] 2016-10-29 14:55
> Thanks for the input! I have produced a patch now for scllvm in develop, so your test should work once you pull the latest develop level0/level1!

Am I correct that it fixes warnings and necessity for clang in path is still there? Is it different version of scllvm between develop and pnext? Why was the problem only on develop and my installation?

**Comment by alemoi** [comment] 2016-10-29 16:05
> Am I correct that it fixes warnings and necessity for clang in path is still there? Is it different version of scllvm between develop and pnext? Why was the problem only on develop and my installation?

It fixes these particular warnings in the generated code. Clang will still report the new warnings if they come. Eventually we will set the flag treat all warnings as errors, since no warnings should be in generated code.

The new scllvm is only in develop now, but very soon will be in pnext as well. We are finalizing some things.

**Comment by k-rus** [comment] 2016-11-01 07:06
Thanks for the explanation. I forgot that it is new scllvm in develop, while it was just new build of scllvm in pnext. So it explains why I met these problems only in develop.

**Comment by alemoi** [comment] 2016-11-09 01:19
@k-rus I guess this one is fixed. So closing it. If something please reopen.

**Closed by alemoi** 2016-11-09 01:19 UTC
Labels: bug, High prio
