### ISSUE TITLE
Unexpected critical windows error detected

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3631] opened 2016-05-17 13:13 UTC
SC Version 2.2.1834
I just got the following exception with type `Critical` :
`Unexpected critical windows error detected at "unsigned long __cdecl _detach_yield(struct __SH_CTXT *,struct __WT_CTXT *,unsigned __int64)" (error=6).`

**Comment by alemoi** [comment] 2016-05-17 13:21
Thanks for reporting!

We had a couple of issues like that: 
https://github.com/Starcounter/Starcounter/issues/972
https://github.com/Starcounter/Starcounter/issues/3412
https://github.com/Starcounter/Starcounter/issues/2749
https://github.com/Starcounter/Starcounter/issues/2866

all have error number 6.

According to Windows errors its some invalid handle supplied: https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx

cc @eriohl @alexanderstc @bigwad

**Comment by per-samuelsson** [comment] 2016-05-17 13:24
I don't think we should close this issue until we had a moment to consider it, or it is a straight dup of those others?

**Comment by dan31** [comment] 2016-05-17 13:26
@atifwaqar can you pls provide all log entries preceding this? Is that reproducible? There appears to be a bug in task scheduler which occurs really infrequently. It appear to occasionally reproduce in @atifwaqar environments. @eriohl @bigwad maybe we can supply the machine where it occurs with some advanced crash dump creation so that the problem can be notched further? (@bigwad I again lost the comment where you describe how to turn that on in Windows).

**Comment by dan31** [comment] 2016-05-17 13:27
> I don't think we should close this issue until we had a moment to consider it, or it is a straight dup of those others?
I think this issue is a good umbrella for all those older. Let's keep that one as a main one.

**Comment by dan31** [comment] 2016-05-17 13:31
(depending on what you guys would grasp from this track, we might decide in the end that the issue is addressed in the new scheduler which will appear at some moment in pnext-based Starcounter after 2.3 is released; still this is some time in future, not big, but probably months)

**Comment by atifwaqar** [comment] 2016-05-17 13:52
The snapshot is here
![image](https://cloud.githubusercontent.com/assets/4388707/15324463/d3607e9e-1c46-11e6-8525-e8877d6d5c3e.png)

The log file is here (But it have alot of garbage in it :P ) : 
[Uploading starcounter.0000000000.log.txt…]()

**Comment by bigwad** [comment] 2016-05-18 09:38
Here is no straightforward way to generate crash dump as here is no crash in the first place. What happened is that we have encountered a critical unexpected error from some Win32 API. Then we logged the error message and terminated the process. 
One can investigate this issue analytically by "code review", but getting process dump at the moment of this unexpected error could be of significant help though.
I see two ways to get process dump:
1. Change error handling code so we initiate a crash instead of gracefully terminate the process in case of critical unexpected errors. Will require upgrade on the client machine.
2. Run sccode under supervision of [application verifier](https://www.microsoft.com/en-us/download/details.aspx?id=20028). Doesn't require changes in our code or product upgrade.

Although usually I prefer non-invasiveness of application verifier, in this case I suggest to go with changing error handling, recomplication and upgrade, as making error handling better is right in the long term. 
And yes, this error is related to the legacy scheduling.

**Comment by dan31** [comment] 2016-05-20 09:04
@eriohl do you still consider an idea of replacing the old scheduler with a new scheduler in 2.3+ versions, which we discussed some time ago? If that is still the case, then there is less point to investigate this recurring issue in a legacy scheduler deeper (let's name it "error 6" issue?). But if the legacy scheduler is still with us and we don't want to replace it soon, it means this issue will continue impeding production installations for months hence the issue needs to be addressed (@alemoi can assist @atifwaqar with proper tracking facilities and he will manage to provide evidence for "error 6", which wan't possible in older cases). Which route do you incline to?

**Comment by eriohl** [comment] 2016-05-20 09:22
> @eriohl do you still consider an idea of replacing the old scheduler with a new scheduler in 2.3+ versions, which we discussed some time ago?

I'm not sure what you are asking. Do I still think we should replace the legacy scheduler? Then the answer is yes.

**Comment by dan31** [comment] 2017-03-15 22:58
Since it is not reproducible, I am archiving it. However, we've created a separate topic in 2.4 release dedicated to scheduling.

**Closed by dan31** 2017-03-15 22:58 UTC
Labels: bug, Umbrella
