### ISSUE TITLE
NullReferenceException in the case of protected property

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2520] opened 2015-01-27 11:20 UTC
I have the following application with non-public field:
```c#
using System;
using Starcounter;

namespace StarcounterApplication1
{
    [Database]
    public class MyUser
    {
        public String Name;
		protected String _Description;
    }
	
    public class Program
    {
        static void Main()
        {
            Db.Transaction(() =>
            {
                var user = new MyUser() {Name = "Ivar"};
            });
        }
    }
}
```
I try to run it with latest Starcounter version and I expect a weaver error due to #2508 fix, however I get an exception at binding time:

>Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.TypeInitializationException: The type initializer for 'StarcounterApplication1.MyUser' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Starcounter.Binding.BindingBuilder.VerifyProperty(PropertyInfo propertyInfo, Type returnType) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Binding\BindingBuilder.cs:line 967 at Starcounter.Binding.BindingBuilder.GeneratePropertyBindingNoNullOut(PropertyDef propertyDef, Type bindingBaseType, String methodName, Type returnType, Type thisType) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Binding\BindingBuilder.cs:line 904 at Starcounter.Binding.BindingBuilder.CreateStringPropertyBinding(PropertyDef propertyDef, Type thisType) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Binding\BindingBuilder.cs:line 600 at Starcounter.Binding.BindingBuilder.BuildPropertyBindingList(TypeBinding typeBinding, Type type) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Binding\BindingBuilder.cs:line 228 at Starcounter.Binding.BindingBuilder.CreateTypeBinding() in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Binding\BindingBuilder.cs:line 151 at Starcounter.Binding.Bindings.LockedBuildTypeBindingFromTypeDef(TypeDef typeDef, UInt16[] currentAndBaseTableIds) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Binding\Bindings.cs:line 291 at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(TypeDef typeDef) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Binding\Bindings.cs:line 255 at Starcounter.Binding.Bindings.BuildTypeBindingFromTypeDef(String name) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Binding\Bindings.cs:line 239 at Starcounter.Binding.Bindings.GetTypeBinding(String name) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Binding\Bindings.cs:line 200 at Starcounter.Hosting.HostManager.Starcounter.Hosting.IBackingHost.InitializeTypeSpecification(Type typeSpecType) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Hosting\HostManager.cs:line 63 at Starcounter.Hosting.HostManager.InitTypeSpecification(Type typeSpecification) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Hosting\HostManager.cs:line 54 at StarcounterApplication1.MyUser..cctor() --- End of inner exception stack trace --- at StarcounterApplication1.MyUser..ctor() at StarcounterApplication1.Program.<Main>b__1() in c:\TempProjects\CurrentInvestigation\curInvest.cs:line 19 at Starcounter.Db.Transaction(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Db.cs:line 227 at Starcounter.Db.Transaction(Action action, Boolean forceSnapshot, Int32 maxRetries) in c:\GitRepositories\Starcounter\Level1\src\Starcounter\Db.cs:line 165 at StarcounterApplication1.Program.Main() in c:\TempProjects\CurrentInvestigation\curInvest.cs:line 17 Version: 2.0.0.0. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259. 
 at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__4(CommandTask task) in c:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 171
 at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Action`1 action) in c:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 481
 at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in c:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 104
 at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\GitRepositories\Starcounter\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 261
 ErrorCode=4259
 HResult=-2146233088
 HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259

I guess it is a bug.

Note I run Starcounter installed from local build in Debug configuration. I guess this should not matter.

**Comment by per-samuelsson** [comment] 2015-01-27 11:39
Thanks for reporting

> I try to run it with latest Starcounter version and I expect a weaver error due to #2508 fix.

Just to be picky - it's not implemented in the weaver, but in the binding. But you are right in that you should get an error.

> Note I run Starcounter installed from local build in Debug configuration. I guess this should not matter.

It should not matter.

I'm assuming you are testing this in **develop**, in which case it should trigger the #2508 fix. I will investigate why it doesn't.

**Comment by per-samuelsson** [comment] 2015-01-27 11:57
I confirm this is a bug - I was able to reproduce it. 

The reason is that the #2508 implementation use ```databaseAttribute.IsPublicRead``` (assigned from ```field.IsPublic()```), and that returns **true** for protected members (and I only tested private ones). Hence, if you change the above example to ```private```, you'll get the "correct" error.

I will fix this by instead forcing only REAL public visibiity (which I hope the underlying API's support).

**Comment by per-samuelsson** [comment] 2015-01-27 12:47
Now I fixed my bug, but when I tested after this, the problem remains. It's also quite easy to see the reason - the database binding code and the runtime type binding code doesn't handle protected properties well at all.

For those that know the implementation, the problem is that for any protected field, it adds a ```ColumnDef``` and a corresponding ```PropertyDef```. When the runtime binding are to generate a ```PropertyBinding```, it assumes there is a **public** .NET property with the same name in the reflection type, but it doesn't. So the check fail.

Not sure who is really responsible for this code, and I don't know any quick fix to solve it. As all other stuff, I guess we must consider what we should support and what not. I guess the easiest fix is to just not generate any ```PropertyDef``` for protected fields, which I think should solve this specific case.

**Comment by k-rus** [comment] 2015-01-27 12:58
Should protected fields be treated in a similar way as private fields? I.e., the application should define public read accessors to protected fields as for private fields. I guess the main difference is that the public accessor might be defined in a child class, which makes thing more complicated. Since it is a temporal fix until *next*, we might disregards the difference and treat protected field completely as private fields.

I hope I understood the problem correctly.

**Comment by per-samuelsson** [comment] 2015-01-27 13:00
> I hope I understood the problem correctly.

You did.

> Since it is a temporal fix until next, we might disregards the difference and treat protected field completely as private fields.

And this I tested now locally (using a change in the schema loader). It seem to work. I'm testing it as a personal build now, and if I don't find any problem, I'll push this.

Thanks for the input.

**Comment by per-samuelsson** [comment] 2015-01-27 13:10
This is now fixed, according to previous comments. Its merged to **develop** in https://github.com/Starcounter/Starcounter/commit/89ed06a59a5c0f33e92dbdc0982d074bdeb3034b.

**Closed by per-samuelsson** 2015-01-27 13:10 UTC
Labels: bug, Code host
