### ISSUE TITLE
Query result table header & body scroll is not synchronized

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2987] opened 2015-10-22 12:55 UTC
```sql
SELECT * FROM Starcounter.Metadata.Table
```

![image](https://cloud.githubusercontent.com/assets/6435556/10665646/e2928650-78cc-11e5-9028-d7283c73c87a.png)

**Comment by warpech** [comment] 2015-10-22 14:23
Thanks! Looks like a duplicate of https://github.com/Starcounter/Starcounter/issues/2828. 

@budnix has already prepared a fix for the above, I will check if it fixes this one.

**Comment by warpech** [comment] 2015-10-22 14:53
Seems to not be a duplicate. Will assign this on @budnix

**Comment by warpech** [comment] 2015-10-23 17:57
Problem still reproducible with recent update of Handsontable. @budnix can you please take a look?

**Comment by miyconst** [comment] 2015-12-07 15:04
@warpech can you increase priority of this issue, as it is really annoying and was pointed out by TargetEveryOne guys as well.

**Comment by warpech** [comment] 2015-12-08 11:00
The priority P/Normal is good, but the progress is bad :) I will bump @budnix about it.

**Comment by warpech** [comment] 2016-01-13 09:24
@budnix wrote in an email:

> After introduce new feature preventOverflow to Handsontable (https://github.com/handsontable/handsontable/issues/3071) this should not appear any more.

I confirm that https://github.com/budnix/Starcounter/commit/e258f21c0a9490be9fc3f72dd5d32a2d5c6c6e59 fixes the problem.

I will merge it later.

**Comment by warpech** [comment] 2016-01-13 10:10
Merged

**Closed by warpech** 2016-01-13 10:10 UTC
Labels: Administrator, bug, P/Normal
