### ISSUE TITLE
Building Level1 copies kernel header files into Level0 include

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3002] opened 2015-10-29 10:07 UTC
After I run build of Level1 I see that header files in Level0 include (`level0\src\include\`) folder changed or added. It seems that Level0 copies them from some remote location. Is it so?

An example of modified file is `coalmine.h`and added file is `pluto.h`. In total around 30 files.

cc: @eriohl

**Comment by k-rus** [comment] 2015-10-29 10:25
I unloaded `CopyDependenciesRemote` and the header files are not changed in include any more.

**Comment by eriohl** [comment] 2015-10-29 10:34
Probably the same process that copies the kernel DLLs from build server. The idea is obviously to allow for building level1 without having to build level0. Which is as intended. I guess that what we should do it change the source of the DLLs and header files in level1/pnext branch.

**Comment by k-rus** [comment] 2015-10-29 11:09
Yes, `CopyDependenciesRemote` and `CopyDependenciesLocal` should be fixed for Level1/pnext. The current work around is:

1. Unload/disable `CopyDenepndenciesRemote`
2. Manually copy Level0 output into Level1 output.

I reduce priority of the issue.

**Comment by k-rus** [comment] 2015-10-29 11:50
After talking to @alemoi I made a fix that `CopyDependenciesRemote` and `CopyDependenciesLocal` work with VS2015 and Level0 presented. It does not work correctly if somebody tries to build Level1 pnext without Level0 presented.

The above work around is not needed any more.

The fix pushed to pnext Level1.

**Comment by alemoi** [comment] 2015-11-02 01:29
Since now it seems fixed I will close the issue. Thank you.

**Closed by alemoi** 2015-11-02 01:29 UTC
Labels: Infrastructure
