### ISSUE TITLE
Merged HTML URI gets corrupted in case of multiple handlers in same app

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Starcounter#2192] opened 2014-07-24 11:32 UTC
I tried registering two handlers for the same URL 
in [PolyjuiceBoilerplate/Master.json.cs#L114](https://github.com/Polyjuice/PolyjuiceBoilerplate/blob/29771b06ad381f8614a548bb52375c4c81b081c1/Server/Master.json.cs#L114)

It results with incorrect path for HTML template:
```js
workspaces.0.master.Html = 
"/polyjuice-merger?Noise=/noise.html&PolyjuiceBoilerplate=/noise.html&PolyjuiceBoilerplate=/noise.html"
```

I'm not sure whether it's Starcounter or Launcher issue.

I suspect it may be related to the fact that Launcher attaches all responses to the first one [Launcher.json.cs#L70](https://github.com/Polyjuice/Launcher/blob/a8c834e515a8fa16f897c63839c5e4e45dc717cb/Server/Launcher.json.cs#L70) and this could affect `pp.GetHtmlPartialUrl()` at [StandardJsonSerializer.cs#L197](https://github.com/Starcounter/Starcounter/blob/352c774cfb144286e5d8ce76efaf3f47da821bce/src/Starcounter.XSON/Serializer/Json/StandardJsonSerializer.cs#L197)

It works nice if there is only one handler for URL per app.
```js
workspaces.0.master.Html = 
"/polyjuice-merger?Noise=/noise.html&PolyjuiceBoilerplate=/boilerplate-ingredients.html"
```

**Comment by alemoi** [comment] 2015-05-27 01:03
Registering two handlers with the same URI is now prohibited, so the issue is no longer relevant. Closing the issue.

**Closed by alemoi** 2015-05-27 01:03 UTC
