### ISSUE TITLE
CommitUpdate triggers even if I modify data in my JSON

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3876] opened 2016-10-12 11:26 UTC
lets say my class is 'YetAnotherClass'. I have a 'CommitUpdate' hook for this class.
Now I have a GUI dashboard (Developed in SC) from where i can modify this object. 
For my Dashboard i have 3 files : 
1. dashboard.Json.cs
2. dashboard.Json
3. dashboard.html

In my dashboard.Json i have some code like : 
```
  "$YetAnotherClass": { "Bind": "YetAnotherClass_" },
  "YetAnotherClass": [
    {
      "ObId": "",
      "ObjectID": "",
      "Name$": "",
      "Country": {
        "Name$": ""
      },
      "Domain$": "",
      "Remove$": 0
    }
  ]
```
  
In my dashboard.Json.cs i have code :
```
	public IEnumerable YetAnotherClass_
	{
		get
		{
			return Db.SQL<YetAnotherClass>("SELECT yac FROM AdFenix.Database.YetAnotherClass yac");
		}
	}

```

and my Commit Hook code looks like : 
```
	Hook<YetAnotherClass>.CommitUpdate += (s, obj) =>
	{
		Console.WriteLine("Control enterd here.");
	};

```
	

Now the issue is, when I open my dashboard, the control gets in Commit Hook, where as I have not modified any thing yet. 
How can I fix this issue? or its suppose to work this way?

What I understand is that when we pass 'YetAnotherClass' DB object's data to Json-ViewModel,  Commit Hook is triggered even if we modify the data in Json.

**Comment by miyconst** [comment] 2016-10-12 11:32
@atifwaqar the `CommitUpdate` commit hook should be triggered when there is a change being committed to the database.

If you didn't make any changes and didn't commit them, the commit hook should not fire regardless of binding to the view-model.

cc @per-samuelsson, @chrhol

**Comment by atifwaqar** [comment] 2016-10-12 11:33
@miyconst So you think its a bug in SC Commit Hook?

**Comment by miyconst** [comment] 2016-10-12 11:34
If the behavior you describe is true, then yes, it is a bug in Starcounter, but I will have to check it up first.

**Comment by atifwaqar** [comment] 2016-10-12 11:34
Let me know if you need my help in reproducing it.

**Comment by per-samuelsson** [comment] 2016-10-12 11:37
@atifwaqar 

Thanks for the good sample!

As @miyconst says, the hook should only be called if there are actually updates. 

Otherwise it's a bug. If I would guess, I think the bug is that there is an (appearently unintentional) update somewhere, and that the bug is not in the hooking layer. It still might be a Starcounter bug though, if the update happens somewhere in JSON/patching layer for example.

Let's see what @miyconst come up with. I'm here to assist if needed.

**Comment by per-samuelsson** [comment] 2016-10-12 11:42
> What I understand is that when we pass 'YetAnotherClass' DB object's data to Json-ViewModel, Commit Hook is triggered even if we modify the data in Json.

I missed this the first time around. Are you modifying the bound property? If so, it's bound to the underlying database object(s), and then yeah, you are in fact modifying those. Or I don't understand the bound Typed JSON good enough. @chrhol?

**Comment by atifwaqar** [comment] 2016-10-12 11:45
@per-samuelsson 
If I just open my Dashboard, my control enters in CommitHook `CommitUpdate`. 
In this case im not even modifying any data in Json.

**Comment by miyconst** [comment] 2016-10-12 12:23
@atifwaqar I cannot reproduce the issue. You have to look for the stack trace of what change causes the hook to trigger or prepare a example with minimum code which reproduces the issue.

**Comment by atifwaqar** [comment] 2016-10-12 13:24
Sorry guys, I found the issue. 
It was due to my dirty code. I had a Get constructor in my DB Class. Which was something like following : 
```
    [Database]
    public class YetAnotherClass
    {
        public string ObId { get { return DbHelper.GetObjectID(this); } }
        public string _Name;
        public string Name
        {
            get
            {
                if (String.IsNullOrEmpty(_Name))
                {
                    Db.Transact(() =>
                    {
                        this._Name = "Empty Name...";
                    });
                }
                else
                {
                    Db.Transact(() =>
                    {
                        this._Name = "Name already there";
                    });
                }
                return _Name;
            }
        }
        public int Stock;
    }
```

So whenever i was accessing any object of `YetAnotherClass`, I was making a transaction.

**Closed** 2016-10-12 13:25 UTC
Labels: question
