### ISSUE TITLE
Question : Install SC on 1 machine with 2 user accounts

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3787] opened 2016-08-11 13:51 UTC
I have 2 user accounts in my laptop. And VS + SC is installed. And I can Open/Build/Run the project in only 1 user account.
But when I try to open the same project in 2nd UserAccount, I get "Project not supported" error in VS. Is there a workaround for this sort of issue?

**Comment by miyconst** [comment] 2016-08-11 14:01
Unfortunately this is not supported at the moment.

Closing this issue as duplicate of: https://github.com/Starcounter/Starcounter/issues/2929.

**Closed by miyconst** 2016-08-11 14:01 UTC
Labels: duplicate
