### ISSUE TITLE
WebSocket Error, Launcher and InvoiceDemo

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2580] opened 2015-02-23 13:30 UTC
Hi!

I'm going to build an SPA and wanted to have a look at some existing demos. Anders helped me but I can't get the Polyjuice apps running or the InvoiceDemo. I just keep getting:
Version:2.0.3045.3
Chrome:40.0.2214.111 m

WebSocket connection to 'ws://localhost:8080/__default/wsupgrade/1B10D5BCEEABBA7010000000' failed: Error during WebSocket handshake: Unexpected response code: 400
puppet.js:662 Uncaught Error: 
Could not connect to: ws://localhost:8080/__default/wsupgrade/1B10D5BCEEABBA7010000000
puppet.js:662 Uncaught Error: 1006

**Comment by alemoi** [comment] 2015-02-23 13:39
Thanks for the question! What repositories/apps are you using? What is your version of Starcounter?

**Comment by dan31** [comment] 2015-02-23 15:47
@warpech, take a look, should there be some Chrome flags activated?
@careri, do you take a Polyjuice edition or Starcounter edition?

**Comment by warpech** [comment] 2015-02-23 16:31
Maybe some firewall is blocking WebSocket connection on localhost?

I just checked and it works for me:
- InvoiceDemo: https://github.com/starcounter/InvoiceDemo (current master branch - 90df118)
- Starcounter: 2.0.3045.3 (Starcounter edition and Polyjuice edition)
- Windows 8
- Visual Studio 2012
- Chrome 40, Chrome 43 Canary, Firefox 36

![invoicedemo](https://cloud.githubusercontent.com/assets/566463/6331808/b1c2d6f0-bb81-11e4-93f5-6b2640e45b5e.png)

**Comment by careri** [comment] 2015-02-24 08:29
Starcounter and Chrome Version is in the original issue:
First I tried the Apps:
Launcher, Procurement, Products, SignIn

But when that didn't work i removed all Apps and downloaded the InvoiceDemo. 

The error seems related to puppet.js and not the Apps or the InvoiceDemo?
puppet.js:188 WebSocket connection to 'ws://localhost:8080/__default/wsupgrade/5F444FE9BBD72E4640000000' failed: Error during WebSocket handshake: Unexpected response code: 400
puppet.js:662 Uncaught Error: 
Could not connect to: ws://localhost:8080/__default/wsupgrade/5F444FE9BBD72E4640000000
puppet.js:662 Uncaught Error: 1006 
3
puppet.js:154 WebSocket is already in CLOSING or CLOSED state.
puppet.js:154 WebSocket is already in CLOSING or CLOSED state.

**Comment by careri** [comment] 2015-02-24 08:47
I turned off windows firewall, no dice.

**Comment by careri** [comment] 2015-02-24 08:52
Could it be related to running Starcounter as administrator or not? I started from start menu (not admin)

**Comment by careri** [comment] 2015-02-24 08:54
Hmm, might be something session related? I started a new browser in incognito mode, that works.

**Comment by warpech** [comment] 2015-02-24 09:08
In the incognito mode, browser extensions and cache are disabled. So I
suspect that the problem was in one of the extensions.

Do you have some potential candidate? I would really like to identify the
problem so that we can have a full explanation.

--
Marcin Warpechowski
+48 603 607 801

**Comment by careri** [comment] 2015-02-24 09:22
I did change from Polyjuice Edition to Starcounter Edition as well. Don't know if that could have solved it?

I was running the page in developer mode with the cache disabled. But I only started working when I fired up Incognito.

This time I started from VS2012 with debug (not admin)

**Comment by warpech** [comment] 2015-02-24 09:27
I think that changing Polyjuice to Starcounter edition should not be a problem. At least for me, both worked. I also start apps from VS2012 debug (not admin).

Could you please try Chrome (regular mode) with all the extensions and plugins disabled? If it works, then could you restore the extensions one-by-one. Maybe this method will let us find the conflict.

**Comment by dan31** [comment] 2015-02-24 09:45
@careri, the case when plugin screws up a thing might be very positive. We've already faced with that once, when some plugin added a big bunch of jquery code to everything, and it didn't work good.

**Comment by careri** [comment] 2015-02-24 14:42
I'll check in to that

**Comment by careri** [comment] 2015-02-24 15:18
I disabled everything, including hangouts. Still only works in incognito :(

**Comment by careri** [comment] 2015-02-24 15:24
If I run chrome "as another user" it works as well. So something about me being logged in with my google account makes it fail.

**Comment by careri** [comment] 2015-02-24 15:25
Using the "switch person" in chrome also works.

**Comment by warpech** [comment] 2015-02-24 15:47
Very strange indeed. And I am logged in to Chrome all the time, with no problem. Could we connect on [Hangout](https://plus.google.com/+MarcinWarpechowski) or Skype (warpech) so I can see it?

**Comment by warpech** [comment] 2015-02-27 11:39
It was confirmed today on a Hangout that the problem is when the wsupgrade request contains an arbitrary `Cookie` header with a very long cookie which was set by a different application. I don't have a copy of the cookie, but maybe it is reproducible with any arbitrary cookie.

@alemoi could you please check?

**Comment by alemoi** [comment] 2015-02-27 11:41
Sure, I will check this once merge my current work!

**Comment by alemoi** [comment] 2015-06-02 23:39
I just checked with a really huge cookie (maximum the Firefox allowed me) in `wsupgrade` and could not reproduce the problem. I guess it was fixed after my throughout refactoring of WebSockets. Closing the issue until further notice.

**Closed by alemoi** 2015-06-02 23:39 UTC
Labels: question

**Comment by dan31** [comment] 2015-06-03 06:34
Thanks @alemoi, guys will confirm if it ever happens again.
