### ISSUE TITLE
pnext: LogStreamer regularly reopens transaction log

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#3549] opened 2016-04-29 15:18 UTC
That is bad for performance.

Probably, such log messages point to the root cause:

```
!QUIT expected TMID 30090, got 30097
```

cc @linkdata

**Comment by linkdata** [comment] 2016-04-29 15:28
Out-of-order delivery of transactions indicate a transport layer problem. 
Run with @logfile to get detailed log on both server and client transmissions. You can search the logs to find the transaction with that ID, and inspect the surrounding transactions to see what happened. 

Usually, the client will send in-order, the server network will recieve them in-order, but the SC application on the server gets them out-of-order due to IPC ordering issues.

cc @alemoi

**Comment by alemoi** [comment] 2016-04-29 23:02
As we discussed before the problem was in pushing data from different schedulers (when the order was controlled), and since there are several IPC channels to the gateway one message can arrive faster then another. By architecture, each scheduler has an independent IPC channel to each gateway worker, and because of this design there are certain problems like above. We should think of redesigning this if possible.

**Comment by dan31** [comment] 2016-04-30 06:55
> As we discussed before the problem was in pushing data from different schedulers (when the order was controlled), and since there are several IPC channels to the gateway one message can arrive faster then another. By architecture, each scheduler has an independent IPC channel to each gateway worker, and because of this design there are certain problems like above. We should think of redesigning this if possible.

Currently there are two options. Either we find a fix for this in the existing structure, since the log streamer should be able to work for months and years without any ```kill all``` and so on. Starconuter instances with log streamer must survive nuclear war and all the nuclear winter thereafter. OR (which is a new info which we've discussed just recently with @eriohl and @bigwad) we actually replace an old scheduler with a new (aka dnx) scheduler right in 2.3, and this might change the things you struggle with now. The reason for such idea itself is to unleash fixes and changes in the kernel not being impeded at all by the old stuff in existing scheduler.

**Comment by per-samuelsson** [comment] 2016-05-02 05:53
> OR (which is a new info which we've discussed just recently with @eriohl and @bigwad) we actually replace an old scheduler with a new (aka dnx) scheduler right in 2.3, and this might change the things you struggle with now.

As it looks as our transition to .NET Core (replacing DNX) will likely be delayed because of all the changes happening with RC2, this could be a good alternative. If we design a scheduler API similar to that of the one we plan for in .NET Core and expose it already, the transition later will be smoother.

**Comment by dan31** [comment] 2016-05-02 06:28
> As it looks as our transition to .NET Core (replacing DNX) will likely be delayed because of all the changes happening with RC2, this could be a good alternative. If we design a scheduler API similar to that of the one we plan for in .NET Core and expose it already, the transition later will be smoother.

Yeah, the whole point is that new scheduling is somewhat independent on .NET Core vs .NET 4.6.x. Yes there are details, but they should not be critical. If we do such replacement, we likely unlock normal way to continue developing changes and enhances in kernel and in infrastructure/management. We discussed that option just last week with @eriohl and @bigwad to see what is the best next step to take which makes most sense and doesn't drag us into plethora of workarounds on the old stuff. CC @linkdata.

**Comment by linkdata** [comment] 2016-05-02 07:08
I can certainly evaluate it's feasibility.

It's complicated by the fact that this is not just scheduling (that'd be too easy). The scheduler handles Bluestar scheduler contexts and transactions and thread safety as well, and replacing the current one will obviously affect, oh, around 100% of all existing code. Approximately.

So we need to be careful. Who knows the transaction handling code in pre-DNX best?

**Comment by linkdata** [comment] 2016-05-02 07:22
Hold on. The changes @alemoi did to the scheduling should not let this happen in this instance. The LogStreamer executes all receives on the same SC scheduler. I thought that the latest changes would guarantee that Tasks are started in order?

And this is not off-by-one, this is missing a lot of messages.

**Comment by bigwad** [comment] 2016-05-02 07:49
Probably, LogStreamer receives messages out-of-order due to task yeilding (https://github.com/Starcounter/Starcounter/issues/3388#issuecomment-204304545 and https://github.com/Starcounter/Starcounter/issues/3388#issuecomment-204434409)

**Comment by alemoi** [comment] 2016-05-02 08:06
Thank you @bigwad Just wanted to write about the same possibility.

**Comment by linkdata** [comment] 2016-05-02 08:15
I don't think that applies, as the LogStreamer will only have one Task reading WebSocket messages at a time. And they will all run on the same scheduler.

**Comment by alemoi** [comment] 2016-05-02 08:47
Once again: are you sure that messages arrive in order to the gateway? I thought the problem is with sending from different schedulers which causes out of order arrival. The gateway processes them in order and sends them to the same scheduler in case of the same websocket. If there are several websockets then it might be several schedulers.

**Comment by linkdata** [comment] 2016-05-06 07:03
There is nothing LogStreamer can do in this situation except detect the transport layer error (which it does) and restart the session (which it does).

**Closed by linkdata** 2016-05-06 07:03 UTC
Labels: invalid, performance

**Comment by dan31** [comment] 2016-05-06 07:18
@linkdata @alemoi I think this issue isn't about a logstreamer-s problem. It is about a performance problem that is caused by a specific reason in Starcounter. What should be a resolution? What is that problem in WebSocket transport that has to be fixed? I cannot draw it from this issue. Once the problem is clearly and specifically identified, a separate issue should follow regarding fixing it. @alemoi, seems that it is a question on your side.

**Comment by linkdata** [comment] 2016-05-06 07:31
I don't really see why opening the log file should be such a performance-intensive operation. Parsing the file structure should be a limited by sequential disk I/O in the worst case and shouldn't use a lot of CPU since it's static data in a known format.

If the file format has forward references (as you write the file, you leave blank spaces you can fill in with "skip here to go to this record number") you can basically make it to be the cost for opening the file, reading a few blocks and doing a few seeks.

I've also noticed that the log reader does a lot of allocations for simply parsing static data - usually you want to avoid that like the plague.
