### ISSUE TITLE
Send "Exceptions" to client when running sockets

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#2332] opened 2014-10-14 08:30 UTC
Exception that is thrown on the server is not sent to the client

**Comment by alemoi** [comment] 2015-05-27 00:57
Still have to verify that closing WS connection on the server with provided error message is working on the client in Puppets.

**Comment by warpech** [comment] 2015-05-27 07:40
We can test together. So idea is that the client should see the exception text as the closing frame [`reason`](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) property?

**Comment by warpech** [comment] 2015-06-11 08:51
@miyconst, could you test if this works client-side?

**Comment by miyconst** [comment] 2015-06-12 07:59
>Still have to verify that closing WS connection on the server with provided error message is working on the client in Puppets.

What means `closing connection`? How do I check that? If an exception occurs during WS call, this exception will never reach client, and for client it is like "nothing happened".

**Comment by miyconst** [comment] 2015-06-12 13:20
By @alemoi 

>https://github.com/Starcounter/Starcounter/wiki/Using-websockets
```cs
Disconnecting an active WebSocket (with an error message and/or close code according to RFC6455)
void Disconnect(String message = null, WebSocketCloseCodes code = WebSocketCloseCodes.WS_CLOSE_NORMAL)
```

**Comment by miyconst** [comment] 2015-06-12 13:21
I confirm, that Disconnecting WS message reaches client.

**Comment by dan31** [comment] 2015-06-12 18:30
:+1:

**Comment by warpech** [comment] 2015-06-15 07:39
@miyconst but it seems that the message is not displayed in the client, or I cannot reproduce it. Were you able to see the disconnection error message on the client?

**Comment by miyconst** [comment] 2015-06-15 07:41
Yes, the message is not displayed, I saw it in the `Network` tab of Chrome.

**Comment by warpech** [comment] 2015-06-15 07:46
I created a separate issue for this: https://github.com/PuppetJs/PuppetJs/issues/62

**Comment by warpech** [comment] 2015-06-18 07:41
@alemoi wrote in https://github.com/PuppetJs/PuppetJs/issues/62:

> Throwing an exception does not disconnect the websocket. Disconnect should be called explicitly with a message.

Can this be reconsidered?

The sole purpose of this issue (#2332) was to send runtime Exceptions to the client that is connected using WebSocket, who otherwise has no clue that something went wrong on the server. 

@andwah can you confirm that was your intention?

**Comment by andwah** [comment] 2015-06-18 07:59
@warpech my goal is that an server exception should reach the client (in some kind of error window)

**Comment by alemoi** [comment] 2015-06-18 17:36
I have investigated it and now closing the WebSocket with an error message when there is an uncaught exception. Unfortunately the error message can not contain the stack trace because Chrome by some reason rejects WebSockets with big error descriptions. For this reason I am sending the following error message as a Close event.reason:
`An exception occurred on the server. Please check Starcounter server log for details.`

So the browser now shows:
![image](https://cloud.githubusercontent.com/assets/208134/8237641/21b60b8e-15f1-11e5-911b-cc48495f976e.png)

Pushed via e27709556f3725c38902b13cad124b49b16d1223

I would appreciate for any input regarding this!

**Comment by warpech** [comment] 2015-06-18 17:57
Thanks! Would it be possible to send at least the first line of the exception?

**Comment by alemoi** [comment] 2015-06-18 20:40
That's maximum what I can get: 
```Uncaught Error: WebSocket connection closed1011 System.Exception: here is my message!
   at People.OrganizationPage.Handle(Save Action) in c:\github\Polyjuice\People\s```

**Comment by alemoi** [comment] 2015-06-22 16:35
@warpech do you want it to be like that?

**Comment by warpech** [comment] 2015-06-22 16:37
Could it be without the `Uncaught Error: WebSocket connection closed1011 ` prefix?

**Comment by alemoi** [comment] 2015-06-22 16:39
Its the client that prints this part of the info. Look at the screenshot above.

**Comment by warpech** [comment] 2015-06-22 17:23
My bad! Please commit :)

**Comment by warpech** [comment] 2015-06-25 14:45
Server part works as expected, closing

**Closed by warpech** 2015-06-25 14:45 UTC
Labels: bug, enhancement
