### ISSUE TITLE
App stuck in start Loop SC 2.2.2.3511

### ISSUE THREAD

**Issue by MujahidRashid** [Starcounter/Starcounter#4057] opened 2017-01-21 17:15 UTC
SC Version 2.2.2.3511

All the applications run fine (Launcher, Signin, UserAdmin) but  our app adfenix constantly shows as starting and does not start we get the following message in admin panel. 

Debug 
Recovery completed. 3559 transactions recovered
Starting log writer at address 382901699. Next commit id is 473437739.

Notice
Weaving C:\adfenix-backend\src\bin\Debug\AdFenix.exe failed with code 6066. Retrying without the cache

This is not happening on all our servers but only two of them show this issue.

**Comment by atifwaqar** [comment] 2017-01-21 18:04
Its the same with SC Version 2.2.1.3234.

and this is what we see in SC Admin Logs 

![image](https://cloud.githubusercontent.com/assets/4388707/22176490/5bc24f7c-e00c-11e6-8bd3-300fedb37f3f.png)

**Comment by atifwaqar** [comment] 2017-01-21 18:04
And the weird thing is that we have 8 Live servers, and only 2 servers have this exact issue. Rest of the servers are working fine.

**Comment by atifwaqar** [comment] 2017-01-21 18:16
Also 1 day ago i got this exception. Do you think its relevant ?

![image](https://cloud.githubusercontent.com/assets/4388707/22176570/f95e019e-e00d-11e6-83bf-95964db5de0c.png)

**Comment by per-samuelsson** [comment] 2017-01-21 19:23
@atifwaqar 

Sorry you are experiencing this.

As for weaver error 6066, that is not critical in itself. It's an error possibly indicating the weaver failed to reuse *cached assemblies* and the servers response to that is to try weaving again, without the cache. We discussed this once already:

https://github.com/Starcounter/Starcounter/issues/3628

WTBS, what is important is you can get pass this problem, so we need to find out what is wrong really. It seem to me although we succeed weaving in a second attempt - *not* using the cache - it's still something else that fails. I just need to figure out what.

**Comment by per-samuelsson** [comment] 2017-01-21 19:26
Regarding above, please note that error has the **notice** log level: meaning you should pay attention to it, but it's something we don't consider even worth a warning. Hence, we need to try to find what is really wrong here (I doubt its a weaver error).

**Comment by per-samuelsson** [comment] 2017-01-21 20:42
Some observations so far:

1. It's not necessary to start the entire suite of apps to trigger the hanging condition - starting `AdFenix.exe` alone still trigger it.
2. The code host load `AdFenix.exe` but never invoke its entrypoint - it hangs somewhere in between loading the assembly and before it invoke the entrypoint.
3. When hanging, one thread is busy bootstrapping the app (`Hosting.Loader.ExecuteApplication`) and another one is commiting a transaction (`Internal.TransactionManager.Commit`).

As for [3], it leads me to believe this has something to do with transactional code running as part of bootstrapping an application, possibly a transaction taking place because of automatic schema migration. Still haven't been able to fully confirm this though, since it require symbols of Starcounter to reveal the full stack trace.

**Comment by per-samuelsson** [comment] 2017-01-21 20:47
Here's a snapshot of threads when hanging:

![image](https://cloud.githubusercontent.com/assets/2902045/22177682/20e27e74-e023-11e6-95a0-2ae14ae0f032.png)

**Comment by per-samuelsson** [comment] 2017-01-21 22:49
I having somewhat of a problem resolving source files from PDB's, and I can't create a custom installer as described here:

https://github.com/Starcounter/AdminTrack/issues/211#issuecomment-274291338

I'm trying to get sources over to said server, but its not clear exactly what sources have been used to build that exact version.

As soon as I make any progress on that, I'll update this issue.

**Comment by per-samuelsson** [comment] 2017-01-21 23:32
I've finally been able to install sources and connected them to symbols on said server, and now I can see closer that actually hangs, and this looks like its some bug in Starcounter for sure, even though I dont know what is the cause yet.

Here's the stacktrace:

![image](https://cloud.githubusercontent.com/assets/2902045/22178550/96cd13d6-e039-11e6-87c2-75186634c04b.png)

And FWIW the table name is "AdFenix.Database.Email.Email" and `c` in that context is 1000, which might be something we want to study closer. Still not really a solution for this issue though. 😢

**Comment by per-samuelsson** [comment] 2017-01-22 00:20
Here's the same thing under a mixed-mode debugger:

![image](https://cloud.githubusercontent.com/assets/2902045/22178773/e7390ef4-e040-11e6-8e7d-de264a3baf3f.png)

**Comment by per-samuelsson** [comment] 2017-01-22 00:51
After some off-tracker discussions, our current belief is that this is caused by the same problem causing #3875. We are discussing a solution to that, along with affected parties. Closing this.

**Closed by per-samuelsson** 2017-01-22 00:51 UTC
Labels: bug, High prio
