### ISSUE TITLE
Re-added to multiple start-up project is not started

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1679] opened 2014-03-03 14:02 UTC
I have an [application](https://github.com/k-rus/MultipleAppsIssue1672), which contains four projects, where three of them, `LauncherApp`, `ScApp1` and `ScApp2` are started with F5 or Ctrl-F5 in VS2013, since they are specified as multiple startup projects.
I hit `Ctrl-F5` and all three projects are started. Now, I removed `LauncherApp` from being started by setting its action to `None`. I hit `Ctrl-F5` again and the two projects are started.
Now I add `LauncherApp` to be started back by setting its action to `Start`. I hit `Ctrl-F5` and only two projects are started. The application `LauncherApp` is not started.

**Comment by k-rus** [comment] 2016-01-13 16:19
@per-samuelsson have you looked to this issue already while fixing other issues related to VS?

**Comment by per-samuelsson** [comment] 2016-01-13 19:52
> @per-samuelsson have you looked to this issue already while fixing other issues related to VS?

I have a vague memory I looked in to this long time ago, and fixed it, but it's weird the issue is still open. I'll assign it to me to verify it it still apply.

**Comment by per-samuelsson** [comment] 2016-01-15 13:17
> I'll assign it to me to verify it it still apply.

Tested using F5, and everything works just as expected. Protocol I followed:

1. Created a solution with 3 Starcounter Application projects (App1, App2, App3).
2. Set them all to "Start".
3. Hit F5. All of them start.
4. Hit Stop debugging.
5. Set App2 to "None"
6. Hit F5. App1 and App3 start.
7. Hit Stop debugging.
8. Set App2 to "Start".
9. Hit F5. All of them start.

I'll run it with Ctrl+F5 also. Let see what that does.

**Comment by per-samuelsson** [comment] 2016-01-15 13:21
> I'll run it with Ctrl+F5 also. Let see what that does.

Same thing - everything works just as one would want it to. 

I'll close this issue.

**Closed by per-samuelsson** 2016-01-15 13:21 UTC
Labels: bug, Follow-up, Visual Studio
