### ISSUE TITLE
Include Polymer 1.2 support into develop

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#3384] opened 2016-02-17 15:42 UTC
I use this issue as a reference point in steering 2.2 release.
Please feel free to add any cross-references.
CC @warpech @miyconst @tomalec

**Comment by warpech** [comment] 2016-02-17 16:33
@malx122 did you manage to try out SysUpgrade?

@dan31 what is the expected timeframe? I propose to merge SysUpgrade to Starcounter develop at least few days before releasing 2.2 stable.

**Comment by warpech** [comment] 2016-02-17 16:35
Related: https://github.com/Starcounter/Starcounter/issues/3022, https://github.com/Starcounter/Starcounter/issues/2922

**Comment by warpech** [comment] 2016-02-19 11:25
Current status: Polymer 1.2 changes are available in https://github.com/StarcounterSamples/SysUpgrade repo that is being tested by @malx122. After he confirms it works, SysUpgrade can be merged to Starcounter `develop` and issues #3384, #3022, #2922 can be closed.

**Comment by warpech** [comment] 2016-02-24 17:22
Current status: all the known problems in https://github.com/StarcounterSamples/SysUpgrade are fixed and available for another round of tests.

@miyconst has reported some issues with SysUpgrade in FF and IE, which have been fixed now.

Still waiting for a test by @malx122, because he was the main customer requesting the update. If he does not test by the end of tomorrow, I will optimistically include it in Starcounter `develop` because I need to force this test on developers somehow.

**Comment by miyconst** [comment] 2016-02-25 11:43
@warpech please make sure the changes also go into pnext branch.

**Comment by warpech** [comment] 2016-02-25 14:39
Current status: @malx122 confirmed that SysUpgrade works for him. 

Today I have found one more problem when using SysUpgrade with Launcher and fixed it.

Tonight I will add SysUpgrade to Starcounter `develop`.

**Comment by warpech** [comment] 2016-02-25 16:48
Current status: Merge of SysUpgrade is blocked by https://github.com/StarcounterSamples/Products/issues/8. Investigating.

**Comment by warpech** [comment] 2016-02-26 16:26
All known problems with Polymer 1.2/1.3 are fixed.

Merged SysUpgrade to Starcounter. Should be available in tonight's nightly.

@alemoi could you please merge https://github.com/Starcounter/Starcounter/commit/a47877ed0fd0a879d5daa97b6d714906be34459a, https://github.com/Starcounter/Starcounter/commit/e9d6654a83bba8ff5f8fb9b9f8279cd79ddecd88 to `pnext`?

**Comment by warpech** [comment] 2016-02-26 16:29
Additional improvement is tracked in https://github.com/PuppetJs/puppet-polymer-client/issues/1

**Closed** 2016-02-26 16:29 UTC
Labels: Umbrella

**Comment by warpech** [comment] 2016-03-11 20:06
Today I pushed a change to `develop` that includes major rewrite of our Polymer 1.3 integration. It fixes problems encountered by @malx122 (https://github.com/PuppetJs/puppet-polymer-client/issues/12).
