### ISSUE TITLE
500+ threads stuck in Processor.RunMessageLoop

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3850] opened 2016-09-22 09:05 UTC
Starcounter 2.2 (Latest nightly)

I have similar issues as #3733
Around 10 threads that seem to be doing something useful.

And 500+ threads that looks like this:
Not Flagged >   22408   798 Worker Thread   <No Name>   [Managed to Native Transition]  Normal  0

If I double-click the thread to show the location I end up on row 42 in Processor.RunMessageLoop

@chrhol You have the code from yesterday for my application.

**Comment by careri** [comment] 2016-09-22 09:09
I'm starting(F5)/stopping(Shift+F5) my application from Visual Studio.
I also noticed that the code changes I make don't load with F5.

So it seems that the sccode process isn't stopped and restarted

**Comment by dan31** [comment] 2016-09-24 21:23
@chrhol seems like an important reproduction! Should you continue on that or this is related to process management and thus go to @per-samuelsson?

**Comment by chrhol** [comment] 2016-09-26 09:53
It looks like two different issues perhaps? 

One is the huge amount of threads and the other, from the second comment, that code isn't updated and it looks like sccode.exe is not restarting.

I have the app so I can do some initial investigating and see if I can reproduce the behaviour.

**Comment by careri** [comment] 2016-09-26 20:38
I'm guessing it's the same issue? That somehow new threads are spawned within the same sccode.exe?
That's why the new code isn't loaded and I end up with a lot of threads.

But that's just me shooting from the hip

**Comment by chrhol** [comment] 2016-10-03 12:34
I have not been able to reproduce the issue with the codehost not restarting and changes not being reflected. Do you have any way that you can consistently reproduce it @careri, or do you know if you are doing something specific when it happens?

As for the large number of threads, if I understand correctly, a scheduler can spawn additional threads (I think the hard limit is 200 threads per scheduler), and those threads will not be cleaned up while the codehost is running, but other than taking up some resources they will not hinder anything or do any work, unless needed. 

So the following is simply a thread that have been created but is not in use:
```
Not Flagged > 22408 798 Worker Thread [Managed to Native Transition] Normal 0

If I double-click the thread to show the location I end up on row 42 in Processor.RunMessageLoop
```

**Comment by careri** [comment] 2016-10-03 12:41
No, I can't reproduce consistently.
It happends some times, I'll give you a call next time. But it seems to me that the codehost doesn't restart since new code isn't loaded/used.

The debugger is extremly sluggish as well.

**Comment by chrhol** [comment] 2016-12-12 08:56
Closing this issue until we find some way to consistently reproduce it.

**Closed by chrhol** 2016-12-12 08:56 UTC
Labels: bug
