### ISSUE TITLE
Websocket error: one or more reserved bits are on...

### ISSUE THREAD

**Issue by HRidge** [Starcounter/Starcounter#3574] opened 2016-05-09 08:02 UTC
I get this error with Starcounter:

```
WebSocket connection to 'ws://127.0.0.1:8080/__default/F2ABF9EFD1A7C2F520000050' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1
```

**Comment by miyconst** [comment] 2016-05-09 08:21
@alemoi take a look please. This error happens only on one machine.

**Comment by alemoi** [comment] 2016-05-09 10:21
Thanks for reporting! Will check it tomorrow!

**Comment by alemoi** [comment] 2016-05-11 13:34
Question: does it happen during handshake? Is there a specific set of steps that leads to this?

**Comment by alemoi** [comment] 2016-05-12 00:07
We checked the client today and I have produced a version that contains certain assertions. Can be downloaded here: `\\scbuildserver\ftp\temp\am\Starcounter-DevelopDailyBuilds-2.2.1.2094-Setup.exe`
@HRidge I will help you testing tomorrow.

**Comment by HRidge** [comment] 2016-05-12 07:25
Sorry to say, I do not have access to that path.

**Comment by miyconst** [comment] 2016-05-12 08:12
>Question: does it happen during handshake? Is there a specific set of steps that leads to this?

Yes, it happens during handshake, and it is always like this on @HRidge's machine. I can't download the file as well.

**Comment by alemoi** [comment] 2016-05-12 11:12
Here is the link with ip address:

`\\192.168.200.91\ftp\temp\am\Starcounter-DevelopDailyBuilds-2.2.1.2094-Setup.exe`

**Comment by HRidge** [comment] 2016-05-12 11:21
Sorry, it still doesn't work.

**Comment by HRidge** [comment] 2016-05-12 11:36
Still same error after installing the new database version.

@alemoi

**Comment by alemoi** [comment] 2016-05-12 23:55
@HRidge can you please install Wireshark on your machine, so we can check the WebSocket packets? Thank you.

**Comment by HRidge** [comment] 2016-05-13 06:51
Done!

@alemoi

**Comment by HRidge** [comment] 2016-05-13 07:08
Zipped file with a Wireshark pcapng file in it.

I analyzed the traffic from the point where puppet.js does:
"that._ws = new WebSocket(upgradeURL);"
past the point in the onopen event where the error occurs.

You need more traffic data?

[Winshark Chrome 2016-05-13.zip](https://github.com/Starcounter/Starcounter/files/262661/Winshark.Chrome.2016-05-13.zip)

**Comment by alemoi** [comment] 2016-05-13 09:30
![ws_test](https://cloud.githubusercontent.com/assets/208134/15243783/0f8c79c8-18fe-11e6-9d18-d7d14fd52373.jpg)

**Comment by miyconst** [comment] 2016-05-13 10:32
After long investigation it was discovered that the @HRidge's machine is an issue. A simple WebSocket connection test without Starcounter does not work either.

Closing this issue, big thank to @alemoi and @linkdata.

**Closed by miyconst** 2016-05-13 10:32 UTC

**Comment by alemoi** [comment] 2016-05-13 12:16
Here is the situation: some clients (like Edge on Win 10) are freaking out when the server pushes a message right after the WebSocket handshake (before even client sending anything). This we tested with Go gateway WebSocket server - meaning its not a Starcounter issue. However, if client, after the handshake, sends the WebSocket message first - then everything is fine. That's why Starcounter log in Administrator works fine for @HRidge

**Comment by alemoi** [comment] 2016-05-13 12:16
@HRidge thank you for your patience and help!

**Comment by alemoi** [comment] 2016-05-13 17:32
@warpech asked for some recommendations I can give for app developers to avoid this issue. First, about us, its how we handle the upgrade in `PuppetRestHandler.cs`: right after sending the upgrade on the server, we call `CalculatePatchAndPushOnWebSocket`, which causes the above situation. I'm not sure if this call is really necessary. What do you think @chrhol ?
And for app developers, they should be aware that if their server code pushes WebSocket messages before the client pushed anything, then it can trigger the situation above (at least until Windows fixes this issue).

**Comment by miyconst** [comment] 2016-05-16 09:02
After some more investigation made by @HRidge we discovered that the source of the issue is the antivirus (NOD32), it's a known bug and they have already fixed it. @HRidge switched to the beta channel of NOD32 and the issue has gone.

@alemoi and @linkdata once again a big thank.

**Comment by alemoi** [comment] 2016-05-16 09:29
Wow! :D Question: was it NOD who inserted those strange http headers or its another mystery?)

**Comment by miyconst** [comment] 2016-05-16 09:38
Yes, looks like it was NOD who screw things up. They admin it, and fixed in the beta channel.
