### ISSUE TITLE
Starcounter throws System.ArgumentOutOfRangeException when primitive array in view-model contains strings and ints

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#4055] opened 2017-01-20 14:19 UTC
I am trying to get an array with primitive values which would contain string and int values.

Here is my JSON definition:

```json
{
    "Items": [ [] ]
}
```

And here is the code behind:

```cs
public IEnumerable<object[]> Items
{
    get { return this.SelectItems().Select(x => new object[] { x.Name, x.Count }) };
}
```

```
"System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Starcounter.Json.MarkAsDirty(Int32 templateIndex) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 109
   at Starcounter.Json.System.Collections.IList.Clear() in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 353
   at Starcounter.Json.<>c__DisplayClass220_0.<set_Data>b__0() in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 41
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 70
   at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 506
   at Starcounter.Templates.TObjArr.BoundOrUnboundGet(Json parent) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Templates\TObjArr.cs:line 238
   at Starcounter.XSON.NewtonSoftSerializer.ScopeAndSerializeArray(Json json, Template template, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 289
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 239
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 70
   at Starcounter.XSON.NewtonSoftSerializer.SerializeObject(Json json, JsonWriter writer, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 239
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 70
   at Starcounter.XSON.NewtonSoftSerializer.<>c__DisplayClass10_1.<Serialize>b__0() in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 79
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 70
   at Starcounter.XSON.NewtonSoftSerializer.Serialize(Json json, Template template, TextWriter textWriter, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 82
   at Starcounter.XSON.NewtonSoftSerializer.Serialize(Json json, Template template, JsonSerializerSettings settings) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.XSON\Serializer\NewtonSoftSerializer.cs:line 61
   at Starcounter.Internal.PuppetRestHandler.CreateJsonBodyResponse(Session session, Json root) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 199
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-1407\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
ParamName=index
HResult=-2146233086
"

```

**Comment by miyconst** [comment] 2017-01-20 14:20
Even if I am doing something wrong or it is not supported, the `System.ArgumentOutOfRangeException` exception should caught and delivered with a proper message.

**Comment by chrhol** [comment] 2017-01-20 14:36
Thanks. I think the reason might be that binding data to an untyped/empty array doesn't work. It should definitely work to mix different kinds of instances of json (including json as single values). 

> Even if I am doing something wrong or it is not supported, the System.ArgumentOutOfRangeException exception should caught and delivered with a proper message.

Yeah, agree. Either this should work or be detected earlier with a better exception. 

I will take a look.

**Comment by chrhol** [comment] 2017-01-20 15:15
Linking issue for reviewing current syntax for single values: #2720. This part should also be fixed or the exception improved.

**Comment by chrhol** [comment] 2017-01-22 17:34
Looks like this is an bug somewhere in the dirtycheck. I tried to reproduce it by only returning the json (without having anything stateful, i.e. without a session) and that works fine so the problem is not binding data to an untyped array as I first thought.

Will continue debugging with a stateful json instead.

**Comment by chrhol** [comment] 2017-01-22 18:48
Not really the dirtycheck either (or at least not only the dirtycheck). It's using arrays in arrays that is not working properly for certain conditions. I will have to take a deeper look to make sure it works properly.

**Comment by chrhol** [comment] 2017-01-23 11:38
In the end, it was a rather small fix. The other problems I had yesterday came from some verification method that is only called for debug builds that was not properly implemented.

I have pushed the fixes (the actual bugfix and the fix for the verificationmethod) to `v2.3` and `develop`. The sample in the first comment should work fine.

**Comment by chrhol** [comment] 2017-01-25 07:45
I will consider this issue solved and close it. Please reopen it @miyconst if you find something that still doesnt work with this.

**Closed by chrhol** 2017-01-25 07:45 UTC
Labels: bug, Typed JSON

**Comment by miyconst** [comment] 2017-01-26 14:27
Tested, works. Thanks for fixing.
