### ISSUE TITLE
Support Response.BodyStream property

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#9] opened 2013-04-02 13:50 UTC
When returning large pieces of content or content where not all information is known when starting to respond, the developer should be able to assign a ```System.IO.Stream``` as the HTTP response body.

```
GET("/movie", () => {
   FileStream stream = File.Open("bigfile.mpg", FileMode.Open));
   var r = new Response() {
      r.StatusCode = 100,
      r.StreamedBody = stream
   };
   return r;
)};
```

An example can be found here:

https://github.com/Starcounter/Starcounter/wiki/Responses-%28HTTP%2C-SPDY%2C-etc.%29#returning-a-response-object

**Comment by warpech** [comment] 2015-12-06 16:33
I just found that it is explained in docs as if it was already supported. Removing it from docs and pasting the documentation below:

---

When you create a Response object, you have the choice of setting the body to a `byte[]`, a `string` or a `Stream`.

```cs
    GET("/hello", () => {
        new Response() {
            ContentType="text/plain",
            Body="Hello World"
        };
    });
```

As Starcounter schedules threads in a highly optimised way, it is recommended that you allow Starcounter to handle streaming. This is done by assigning you `stream` to the Response object and then returning the response, relying on Starcounter to read the stream and send the network traffic on its own accord.

```cs
GET("/movie", () => {
   FileStream stream = File.Open("bigfile.mpg", FileMode.Open));
   var r = new Response() {
      r.StatusCode = 100,
      r.StreamedBody = stream
   };
   return r;
});
```

**Comment by alemoi** [comment] 2015-12-06 23:00
This one I have a plan to fix.

**Comment by dan31** [comment] 2015-12-17 10:38
Wow such an old issue. @alemoi promised to address this one before Dec 25 2015. We pray for you, @alemoi, and hope on a very soon resolution :+1:

**Comment by alemoi** [comment] 2015-12-24 16:38
I have added initial support for this. However its quite primitive and not based on network speed. I will fix that later. The documentation is updated: http://starcounter.io/guides/network/handling-responses/#returning-a-streamed-body
API-wise its ready and can be used.

**Comment by alemoi** [comment] 2015-12-27 23:50
Fixed the adaptive algorithms, which scale downloads much better now. API-wise its the same. Any response regarding this would be appreciated!
In addition, I am thinking of throwing a warning when static files are too large (let's say more than 4Mb), or automatically streaming large files by default without notifying the user.

**Comment by mtornwall** [comment] 2015-12-29 14:11
Great work @alemoi! :+1: 

This couldn't have come at a better time for me. The fact that I'm synchronously copying the contents of relatively large files (images) into a buffer in one of my handlers has been bugging me for months.

I updated the handler to use `StreamedBody` on my development machine. Looks good!

**Comment by alemoi** [comment] 2015-12-29 18:31
Big time thank you for testing! How does it work for you in comparison with previous solution? Do you see the improvement? Do you have any problems/suggestions related to it? Thank you again!

**Comment by mtornwall** [comment] 2015-12-29 21:23
I'm working on a benchmarking tool to do some application-specific performance testing. It will need to test the image serving anyway, so I'll try to incorporate some comparative testing of the old solution vs the new one.

**Comment by mtornwall** [comment] 2015-12-30 00:11
OK, as it happens I got around to doing this earlier than expected. :-)

I ran the following (naive) microbenchmark to compare my old (byte buffer shuffling in Starcounter thread) solution vs `StreamedBody`. The testing conditions were:

* Asynchronous HTTP client supporting up to 100 concurrent requests
* Server and client run locally
* 1000 served files, chosen at random per request, each of 10 KiB
* Average rps computed over 10 second test

I used these three handlers as my test scenarios:

~~~
// Test 1: Files read synchronously.
Handle.GET("/streamtest/sync/{?}", (string fileName) =>
{
    return new Response()
    {
        StatusCode = 200,
        BodyBytes = File.ReadAllBytes(Path.Combine(RootDirectory, fileName))
     };
});

// Test 2: Files streamed asynchronously.
Handle.GET("/streamtest/async/{?}", (string fileName) =>
{
    return new Response()
    {
        StatusCode = 200,
        StreamedBody =
            new FileStream(
                Path.Combine(RootDirectory, fileName),
                FileMode.Open, FileAccess.Read)
    };
});

// Test 3: Files read synchronously, then streamed asynchronously from in-memory buffer.
Handle.GET("/streamtest/hybrid/{?}", (string fileName) =>
{
    return new Response()
    {
        StatusCode = 200,
        StreamedBody =
            new MemoryStream(
                File.ReadAllBytes(
                    Path.Combine(RootDirectory, fileName)))
    };
});
~~~

## Results:

### Test 1:
~~~
Reqs/sec: 1043
Success:  10430
Failure:  0
Total:    10430
~~~

### Test 2:
~~~
Reqs/sec: 56.2
Success:  475
Failure:  87
Total:    562
~~~

As you can see the streaming test only got to about 1/20 of the throughput of the synchronous version. I suspect that the root cause could be that exceptions get thrown for almost 20% of the requests and this slows the whole thing down. The log says:

~~~
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Starcounter.Internal.AppsBootstrapper.<>c.<InitAppsBootstrapper>b__6_4(Request req) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-139\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 152
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-139\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-139\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-139\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 523
HResult=-2146232969
~~~

### Test 3:

I devised this test in order to determine if the behavior of `StreamedBody` as seen above was consistent across all kinds of streams (i.e., both streaming from memory and from disk) or not. Curiously, I couldn't get it to run to completion because the scheduler queue seems to be filling up:

~~~
System.Exception: ScErrInputQueueFull (SCERR1026): Operation failed because the target input queue was full.
Version: 2.1.930.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1026.
   at Starcounter.Hosting.TaskSchedulerImpl.Run(ITask task, Byte schedId) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-139\Level1\src\Hosting\Starcounter.Hosting\TaskSchedulerImpl.cs:line 44
   at Starcounter.DbSession.RunAsync(Action action, Byte schedId) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-139\Level1\src\Starcounter\DbSession.cs:line 121
   at Starcounter.TcpSocket.<SendStreamOverSocket>d__23.MoveNext() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-139\Level1\src\Starcounter.Internal\Http\TcpSocket.cs:line 205
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1026
~~~

**Comment by alemoi** [comment] 2015-12-30 13:02
Thank you for the tests! Do you use Starcounter as a client to the same Starcounter codehost? Because that might be the reason for input queue getting full. Regarding streaming body it should be best for big files, so i expect a decreased performance when serving small. I will write my own tests and we compare the results.

**Comment by alemoi** [comment] 2015-12-30 13:17
When it comes to serving like 1000 streamed files, unless there is something else happening in SC server, it should never produce inputqueuefull exception. That was the point of my new implementation of streaming, which should be very resource friendly.

**Comment by mtornwall** [comment] 2015-12-30 13:24
The client runs outside of Starcounter (but on the same physical machine) and uses `System.Net.HttpClient`.

**Comment by alemoi** [comment] 2015-12-30 13:43
Great! Then if you can publish your hanging test, I will run and investigate it!

**Comment by alemoi** [comment] 2015-12-30 21:56
I could think of one reason which is RunAsync not doing round robin among all schedulers. I will make it do round robin by default and lets see if it helps!

**Comment by mtornwall** [comment] 2016-01-01 18:55
@alemoi I'll try and package the failing test so you can download it tomorrow.

**Comment by alemoi** [comment] 2016-01-09 18:10
After some testing using @mtornwall test, we identified some issues that I fixed. @mtornwall big thanks for testing. The fixed streaming will be in the coming nightly.

**Comment by dan31** [comment] 2016-02-15 17:45
@alemoi @mtornwall is that considered finished?

**Comment by mtornwall** [comment] 2016-02-15 20:13
@dan31 I haven't tested it further since I'm still on 2.1.177, but as far as I know the only remaining bug has been solved.

**Closed** 2016-02-15 21:28 UTC
Labels: guess: todo
