### ISSUE TITLE
Db.Transact, how does Retry work?

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3172] opened 2015-12-11 06:30 UTC
Hi!

I'm trying to figure out what the retry logic does. I have a stress test that runs on thread on each cpu-core (8 cores). I get this exception:
ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated. Index=MQParticipant_UID Key='Carl'.

The default value for the retry-parameter of Db.Transact seems to be 100.
The code looks like this:
```
int attempt = 0;

Db.Transact(() =>
{
    attempt++;
    queue = MQueue.Ensure("Carl", "Direct" + i);
});
```

The funny thing is that attempt=1 when the exception is thrown, shouldn't the retry logic execute the delegate a 100 times before throwing the exception? Maybe I don't understand what the retry logic is all about?

**Comment by k-rus** [comment] 2015-12-11 06:55
Thank you for the question. Retry runs on conflicts. In your example, you have constraint violation, i.e., your input data violate unique constraint by inserting value, which already exist in the index. There is no reason to retry on such error, since it is unlikely existing data will be removed to allow you new insert.

**Comment by careri** [comment] 2015-12-11 09:04
Well my scope first makes a get (SQL), if get returns an object I return it. If Null is returned from get I create a new instance and return that.

I'm running a stress test so 8 threads does this at the same time. Some of the threads will retrieve null from the get and try to create a new instance. The threads then commits and fails for one/many threads. A retry would solve the problem. So I don't agree that a constraint vioilation shouldn't retry

**Comment by k-rus** [comment] 2015-12-11 09:27
> I'm running a stress test so 8 threads does this at the same time. Some of the threads will retrieve null from the get and try to create a new instance. The threads then commits and fails for one/many threads. A retry would solve the problem. So I don't agree that a constraint vioilation shouldn't retry

I don't see how retry will help. I guess two threads find that an object does not exist and try create new instance for the same key. The one, which commit first, succeeds. The other one obviously fails on commit. Retrying the second transaction will never succeed.

**Comment by careri** [comment] 2015-12-11 12:55
I'll show you our ensure pattern in code instead, this recreates the violation every time. If the retry would kick in the second attempt would succeed for the threads that got the constraint violation:
```
namespace EnsureExample
{
    class Program
    {
        static void Main()
        {
            // Create unique index
            Db.SQL("CREATE UNIQUE INDEX PName ON EnsureExample.Person (Name Asc)");

            // Ensure Person on multiple threads. 
            Parallel.For(0, Environment.ProcessorCount, i =>
                {
                    new DbSession().RunSync(() => Db.Transact(() => Person.Ensure("Carl")), (byte)i);
                });
        }
    }

    [Database]
    public class Person
    {
        public string Name;

        internal static Person Ensure(string name)
        {
            var p = Get(name);

            if (p == null)
            {
                p = new Person { Name = name };
            }
            return p;
        }

        public static Person Get(string name)
        {
            return Db.SQL<Person>("SELECT p FROM EnsureExample.Person p WHERE p.Name=?", name).First;
        }
    }
}
```

**Comment by k-rus** [comment] 2015-12-11 13:38
Thank you for providing example. Now your pattern is clear. 
In general retry cannot treat constraint violation as conflict. In your case it is a conflict of two inserts into the same key. This is not handled as conflict in Starcounter. I don't know how it is difficult to have conflict here. @eriohl WDYT?

You can handle your case with your own retry on constrain violation, which is simple. Or may be you can have different design, which depends much on your application.

**Comment by eriohl** [comment] 2015-12-11 14:15
If the conflict exists when the transaction started then you will get a constraint violation (and the transaction is not restarted). If not but is created by a parallel transaction this is a conflict (and the transaction is restarted).

You example is seems to me  should probably generate a few conflicts but not a constraint violation (since you check if the record exists before creating it). So this looks like a bug to me.

**Comment by k-rus** [comment] 2015-12-11 14:28
@eriohl 
Thank you for clarifying! I was not aware about this details. Will you look to the bug? Or who is more appropriate?

**Comment by eriohl** [comment] 2015-12-11 14:32
Sure. I can check it out.

**Comment by eriohl** [comment] 2015-12-11 19:00
I can reproduce it.

**Comment by eriohl** [comment] 2015-12-11 19:43
I know what the problem is: Bug in the constraint check. Working on addressing the problem.

**Comment by eriohl** [comment] 2015-12-13 12:35
Resolved. Fix will be included in the next build. Thank you for reporting this.

**Closed by eriohl** 2015-12-13 12:35 UTC
Labels: bug

**Comment by careri** [comment] 2015-12-14 07:18
Could someone trigger a build? There is no build from tonight.

**Comment by k-rus** [comment] 2015-12-14 07:25
> Could someone trigger a build? There is no build from tonight.

This is due to #3179

**Comment by careri** [comment] 2015-12-14 07:28
Ah, hate when that happens!
