### ISSUE TITLE
Issue in Frontend (or may be in Session or Handlers or WebSocket)

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3784] opened 2016-08-10 19:28 UTC
SC Version : 2.2.1.2850

This is correct behavior. All windows/Chrome-Tabs are opened separately with some time interval. All are different pages, with their separate handlers.  : 
![correct behavior](https://cloud.githubusercontent.com/assets/4388707/17567078/2e6ca058-5f3e-11e6-9834-e51ae9daf25e.jpg)

In following 3 images, I opened all 4 tab together, (Refreshed all windows within half second) :

1 window got wrong data :
![incorrect1](https://cloud.githubusercontent.com/assets/4388707/17567080/327b0d92-5f3e-11e6-894a-62d71f0c5685.jpg)

1 window got wrong data and 2 windows got error :
![incorrect2](https://cloud.githubusercontent.com/assets/4388707/17567081/346f572a-5f3e-11e6-833d-5083acc472ff.jpg)

2 windows have wrong data :
![incorrect3](https://cloud.githubusercontent.com/assets/4388707/17567084/36133c40-5f3e-11e6-9ace-1ac8ca6c281d.jpg)

------------------------------------------------------------------------------------
The same issue happens when I have 2 tabs open.
![image](https://cloud.githubusercontent.com/assets/4388707/17567561/31f75a5e-5f40-11e6-81a0-80e350eb6411.png)

When I check ViewModel/Json using SC-Debugger, I can see the same ViewModel/Json.
![image](https://cloud.githubusercontent.com/assets/4388707/17567555/28df08ae-5f40-11e6-99a1-225c929a08af.png)

**Comment by miyconst** [comment] 2016-08-10 19:35
@atifwaqar could you please explain what means "wrong data" and why it's "wrong". What is the exception message and stack trace?

**Comment by atifwaqar** [comment] 2016-08-11 06:36
By wrong data, I mean wrong page. if you see the urls/handlers, they are different for all 4 pages. but in 2nd image, 2 different urls received same page. 
The expected behavior is in 1st image. 
And there is no stack trace or exception message in SC Admin Log.

**Comment by miyconst** [comment] 2016-08-11 06:47
@atifwaqar please investigate the `Patches` tab of the Starcounter Debug Aid and provide here the reason of disconnection.

>By wrong data, I mean wrong page. if you see the urls/handlers, they are different for all 4 pages. but in 2nd image, 2 different urls received same page. 

It is not possible to debug or check this issue without source code available. Can you create a small application which would reproduce the issue and share it via GitHub?

**Comment by atifwaqar** [comment] 2016-08-11 13:12
Here I reproduced the error on different pages : 
![image](https://cloud.githubusercontent.com/assets/4388707/17589458/3a61ba14-5fd5-11e6-947c-a5e8ce1a688d.png)

Error with Patches open : 
![image](https://cloud.githubusercontent.com/assets/4388707/17589499/75b65246-5fd5-11e6-856c-fbfcddce983e.png)


and creating a small application which would reproduce the issue is gonna take some time, but if you want to check the error yourself in your browser, ping me on Hangout, and I can give you access to one of our live server. where you can reproduce this error and investigate.

**Comment by atifwaqar** [comment] 2016-08-17 12:50
@miyconst Any luck with this issue?

**Comment by miyconst** [comment] 2016-08-17 13:05
@atifwaqar sorry, not yet.

**Comment by atifwaqar** [comment] 2016-08-19 12:21
Ok, Feel free to ping me if you need more details on the issue.

**Comment by miyconst** [comment] 2016-08-19 18:19
@atifwaqar thank you very much for reporting this problem. I was able to reproduce the issue and reported it with right description and steps to reproduce: https://github.com/Starcounter/Starcounter/issues/3798. Closing this one.

**Closed by miyconst** 2016-08-19 18:19 UTC
