### ISSUE TITLE
Gateway throws 404 error without a visible reason

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3556] opened 2016-05-02 10:50 UTC
Testing SWO app I found that reloading same page from time to time causes `404` error:

```
URI not found: [{"op":"replace","path":"/_ver#c$","value":53},{"op":"test","path":"/_ver#s","value":6}]GET /PeopleOnboard/organization-list
```

There are not direct steps to reproduce the issue with 100% guarantee. To cause the issue I open a page and click a link which points to the same page. This sends a `GET` request with `Accept: application/json-patch+json`. At some point `404` returned.

After this `404` response can be seen in response for session URL (`http://localhost:8080/__default/session-id`) and static files.

cc @alemoi

**Comment by alemoi** [comment] 2016-05-02 10:53
Thank you! Looking at it!

**Comment by miyconst** [comment] 2016-05-02 11:56
I have found this issue might be related to: https://github.com/Starcounter/Starcounter/issues/3418.

**Comment by miyconst** [comment] 2016-05-03 14:20
Exactly same setup of Starcoutner + apps + actions do not produce this error any more, and this is really annoying. The error obviously was there, and @alemoi saw it.

I will close this issue if the error doesn't appear in a while.

**Comment by dan31** [comment] 2016-05-03 14:23
@miyconst We have to reproduce it instead, no chance for it to survive. @alemoi maybe there are some log entries relevant to the issue that we can extract from the machine where it occurred by time.

**Comment by miyconst** [comment] 2016-05-04 07:15
@dan31 I would really love to, but in spite of my desperate tries, I am not able to reproduce the issue.

**Comment by miyconst** [comment] 2016-05-09 11:16
I have got this exception again:

```
URI not found: [{"op":"replace","path":"/_ver#c$","value":25},{"op":"test","path":"/_ver#s","value":3}]GET /launcher
```

Happened after an application error and page reload.

**Comment by miyconst** [comment] 2016-05-09 12:21
Once again. And this is not related to `pnext`, happens in develop as well.

```
URI not found: [{"op":"replace","path":"/_ver#c$","value":3},{"op":"test","path":"/_ver#s","value":4}]GET /launcher
```

**Comment by dan31** [comment] 2016-05-09 20:31
@alemoi let's consider this one as high prio.

**Comment by miyconst** [comment] 2016-05-09 20:40
Unfortunately I can't provide reproduce steps, but I can say for sure, that this happens after an error on page which causes connection break while some patches are still not delivered to/from client.

**Comment by miyconst** [comment] 2016-05-10 07:15
Just now this issue happened on @chrhol's machine. And again on mine with fresh app start.

**Comment by miyconst** [comment] 2016-05-10 07:20
Okay, now I have a way to reproduce the issue:

- Install daily build `2.2.1.2075 (May 10, 2016 7:18:51 AM)`.
- Checkout https://github.com/miyconst/Playground/.
- Start the Playground solution.
- Open to `http://localhost:8080/playground`.
- Wait till page opens.
- Reload the page:

```
URI not found: [{"op":"replace","path":"/_ver#c$","value":32},{"op":"test","path":"/_ver#s","value":11}]GET /playground
```

**Comment by miyconst** [comment] 2016-05-10 07:54
Some investigation shows that it happens only with big amount of data and long strings inside. The database is available in my dropbox exchange folder, `playground.7z`.

**Comment by alemoi** [comment] 2016-05-11 01:47
@miyconst thank you for the reproduction scenario! Looking forward to see it behave on my machine! I was busy with some support tonight but will check this as a first thing tomorrow.

**Comment by alemoi** [comment] 2016-05-11 23:59
I tried to reproduce the problem on my machine but no luck: when refreshing I never get 404. Thereby I have produced a special build that contains special assertions. Here you can download it: \\scbuildserver\ftp\temp\am\Starcounter-DevelopDailyBuilds-2.2.1.2094-Setup.exe
Would be really nice if you can test it.

**Comment by miyconst** [comment] 2016-05-12 08:10
The file is no available or I have wrong ip for the scbuildserver. Did you use my database when testing?

**Comment by dan31** [comment] 2016-05-12 08:14
> Did you use my database when testing?

That is a good question. @alemoi @miyconst I think the best would be if you try to reproduce the problems together using the exact environment to operate in conditional probability but not in absolute probability. As I grasp from the current flow, trying to reproduce the problems without actual apps setup and db isn't helpful, since these problems aren't low hanging fruits.

**Comment by alemoi** [comment] 2016-05-12 09:47
My bad. Missed last comment, going to test with database!

**Comment by alemoi** [comment] 2016-05-15 21:34
Status update: me @miyconst and @chrhol tried to reproduce this issue, but no luck so far.

**Comment by miyconst** [comment] 2016-05-16 07:08
Yes, after @chrhol's fixes for Typed JSON I was not able to reproduce the error. Keeping the issue opened for a while.

**Comment by miyconst** [comment] 2016-06-02 11:26
This issue is still there. I catch it from time to time, but only when an exception occurs and I have to restart an app. Also it happens only once, and no way to reproduce it for sure.

**Comment by miyconst** [comment] 2016-06-16 13:17
@alemoi please update the issue status so we don't forget it.

**Comment by alemoi** [comment] 2016-06-16 23:34
Yes, thank you. The problem is identified and i am working on solution already.

**Comment by alemoi** [comment] 2016-06-20 00:50
@miyconst the problem was identified and should be fixed now.

**Closed by alemoi** 2016-06-20 00:50 UTC
Labels: bug, Gateway, High prio

**Comment by miyconst** [comment] 2016-06-20 08:51
Could you please write a bit more, what was the reason? I am just curious.

**Comment by alemoi** [comment] 2016-06-20 11:42
The reason was that Chrome uses the same socket to send different HTTP requests (from old and new tabs) and I was not fully accumulating the requests before sending back 404 - I was sending 404 immediately once I saw a non-matching URI.

**Comment by miyconst** [comment] 2016-06-20 13:34
Were not we able to reproduce the issue with Chrome + FF?
