### ISSUE TITLE
Hiding error messages in the browser

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Starcounter#4034] opened 2017-01-09 15:35 UTC
Is it possible to prevent Starcounter from showing error messages (e.g. stacktrace) in the browser? 

I think that if server is running as production environment from the security and usability point of view there should be some aesthetic message instead of full stacktrace and error log information. 

cc @per-samuelsson @alemoi

**Comment by warpech** [comment] 2017-01-09 17:11
I don't recall us having this feature, at least not documented.

All mature web frameworks have such options. In ASP.NET Core and Ruby on Rails you can specify the environment type (production or development)

- https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling
- http://stackoverflow.com/questions/12849597/rails-turn-off-error-display

In few popular PHP frameworks that I've found there are no environment type switches, but you can change error reporting level in config:

- http://stackoverflow.com/questions/10711517/turning-error-reporting-off-php

I have just found it is a duplicate of https://github.com/Starcounter/Starcounter/issues/2959, nevertheless thanks for reporting @mmnosek.

**Comment by per-samuelsson** [comment] 2017-01-10 07:45
@mmnosek, I'm labeling this a dup and close it, and we can continue discussions in #2959. I agree with your concern in this matter.

**Closed** 2017-01-10 07:45 UTC
Labels: duplicate, question
