### ISSUE TITLE
Create Index

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2941] opened 2015-10-08 12:48 UTC
Hi!

I just moved from pre 2.1 version to **Starcounter Edition 2.1.26.2**

And now I can't create my indexes, I saw at the breaking changes that types should be referred to with fullname on the breaking changes page:
http://starcounter.io/nightly-changes/list-breaking-changes-starting-build-2-1-1-3/

The exception:

```
Failed to process query: 
CREATE UNIQUE INDEX "ComputerGroupMember_Combined" ON "HSM.Concepts.ComputerGroupMember" ("Group" ASC, Computer ASC): Incorrect syntax. 
```

**Comment by dan31** [comment] 2015-10-08 14:09
Hi @careri! Is it that you run on a clean DB or with already existing DB? If the latter, did you remove indices prior to that?

**Comment by careri** [comment] 2015-10-08 19:32
It's on a clean db.
Den 8 okt. 2015 4:09 em skrev "Dan Skatov" <notifications@github.com>:

**Comment by careri** [comment] 2015-10-09 05:49
None of my index declarations work, this is another one without reserved keywords in it:
> CREATE UNIQUE INDEX AuthenticatedRealm_UName ON "HSM.Concepts.AuthenticatedRealm" (Name ASC)

**Comment by careri** [comment] 2015-10-09 05:55
Hmm, if I remove the fullname of the type in the previous comment it works. So that is a bit confusing when SQL requires fullname for queries

**Comment by k-rus** [comment] 2015-10-09 11:43
Thank you for your issue.
As you can see it is a syntax error, so it should not be related with short or long name. I guess the problem is that you double quote identifier with dots. Since you mean number of identifiers, then I suggest you quote each identifier separately.
Let me know if it works or if you need to help to find out what the actual error is.
I am sorry that the error is not verbose. We are fixing this in next version.

**Comment by careri** [comment] 2015-10-13 05:15
Yes, you're right. Quoting each part of the fullname works.

**Comment by warpech** [comment] 2015-10-13 06:47
@k-rus are the quotes neccessary?

Maybe quoting rules should be explained in .io site? E.g. http://starcounter.io/guides/sql/indexes/

**Comment by miyconst** [comment] 2015-10-13 06:51
The quotes are necessary only when class names collide with reserved sql words.

For example this would not work:
```sql
SELECT o FROM Procurement.Order o
```

And this works:
```sql
SELECT o FROM Procurement."Order" o
```

**Comment by k-rus** [comment] 2015-10-13 07:19
@miyconst thanks for explaining.
This is correct. Double quotes are used to specify that an identifier is an identifier and not a keyword, which is needed if an identifier is collide with a keyword. It is not specific to indexes. It is general to SQL and described at [the keyword page](http://starcounter.io/guides/sql/reserved-words/). I updated the page with the detail about a chain of identifiers.
I close the issue. Let me know if not.

**Closed by k-rus** 2015-10-13 07:19 UTC
Labels: question

**Comment by warpech** [comment] 2015-10-13 07:49
Perfect, thanks!
