### ISSUE TITLE
Problem in json data binding and autoupdate.

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#2542] opened 2015-02-05 07:43 UTC
Let say I have a json like this:
```
{
       MyList: [{
               MyProperty: "",
               $MyProperty: {bind : "ACodeBehindProperty" }
       }],
       $MyList: { bind: "SQLreturningPersons" }
}
```
part of CodeBehind ( simplified pseudocode):
```
   ...
    [Example_json.MyList]
     MyListJson: Json, Ibound<Person>
      {
           public String ACodeBehindProperty
           {
                  get
                  {
                         return Data.Name;
                  }
            }
      }
   ...

```
The problem I have is twofold. The first is that the "get" of ACodeBehindProperty gets called way to many times. I can be 3*NumberOfPersons during one single "update". (update = a single web request). The second is worse, sometimes Data == null resulting in exceptions. That can't be the case, the list does not includes any nulls...

**Comment by malx122** [comment] 2015-02-05 11:06
Hm, the problem with "Data == null" probably happens when the list changes so having the "SQLreturningPersons" property pointing at a static SQL question without DB changes will probably not trigger it.

**Comment by chrhol** [comment] 2015-02-05 12:49
Thank you for reporting. I will investigate. 

Do you have a stacktrace or anything from when the second item happens, that Data is null?

**Comment by malx122** [comment] 2015-02-05 12:55
Nah, was a while ago since I last saw it. It still exist, but I have made checks like below on most places. I just remembered to report it when Ivar asked me about it today. (It happened for him yesterday)
```
get
 {
     return (Data != null)? Data.Name: "";
 }
```
Will ask him if we can provide an actual example....

**Comment by ivarbergman** [comment] 2015-02-05 13:11
Here is a stacktrace. Do you need a more reproducible example?

    System.NullReferenceException: Object reference not set to an instance of an object.
     at FastLink.Docs.get_CurrentCB() in c:\Tunity\Project\Tunity-2.0\Tunity.Utils\Document\FastLink\FastLink.json.cs:line 96
     at Starcounter.Templates.Property`1.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 175
     at Starcounter.Json.<SetBoundValuesInTuple>b__5() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 268
     at Starcounter.Transaction.Add(Action action) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter\Transaction.cs:line 287
     at Starcounter.Json.SetBoundValuesInTuple() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 255
     at Starcounter.Json.CallHasAddedElement(Int32 index, Json item) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.GetSetValue.cs:line 240
     at Starcounter.Json._Add(Object item) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.XSON\Class Json\Json.IList.cs:line 339
     at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 297
     at Starcounter.Templates.TArray`1.GetValue(Json parent) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.XSON\Templates\TArray.cs:line 127
     at Starcounter.Json.<>c__DisplayClass3.<LogObjectValueChangesWithDatabase>b__2(Session s) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 205
     at Starcounter.Transaction.Starcounter.Advanced.ITransaction.Add[T](Action`1 action, T arg) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter\Transaction.cs:line 297
     at Starcounter.Json.<>c__DisplayClass3.<LogObjectValueChangesWithDatabase>b__2(Session s) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 207
     at Starcounter.Session.GenerateChangeLog() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 514
     at Starcounter.Internal.JsonMimeConverter.Convert(Request request, Object before, MimeType mimeType, MimeType& resultingMimeType) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\JsonMimeConverter.cs:line 50
     at Starcounter.Json.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.XSON\Class Json\Json.IResource.cs:line 42
     at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.Internal\Http\Response.cs:line 771
     at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.Internal\Http\Request.cs:line 1169
     at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 259
     at Starcounter.GatewayHandlers.HandleHttpRequest(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.2994.3\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 349
     HResult=-2147467261

**Comment by chrhol** [comment] 2015-02-05 13:22
Great, thanks. I think I can reproduce this behaviour.

**Comment by chrhol** [comment] 2015-02-09 15:47
I've found and fixed the exception. Data-property was set after a new item was added when an array was bound, which in turn called bound properties too soon.

I haven't checked the number of calls to a property yet though, will do that. It shouldn't be called more than once for each new item in the array, but maybe something does an extra check.

**Comment by chrhol** [comment] 2015-02-10 10:18
As for your first comment

> The first is that the "get" of ACodeBehindProperty gets called way to many times. I can be 3*NumberOfPersons during one single "update". (update = a single web request).

I can confirm that bound properties gets called alot, I've added a new issue for that one (#2551). Since the exception should be fixed I will close this issue.

**Closed by chrhol** 2015-02-10 10:18 UTC
Labels: bug, Puppets
