### ISSUE TITLE
Concurrent access of typed JSON with Bind directive and Data explictly set to null causes intermittent exception

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#3224] opened 2016-01-05 10:32 UTC
Yes, you read it correctly. The only thing missing from this one is a requirement that it be run on a thursday during full moon.

Basically, using a typed JSON document like this one:

~~~
{
    "BoundProperty": "",
    "$BoundProperty": { 
        "Bind": "_BoundProperty"
    }
}
~~~

Whose code-behind is simply:

~~~
partial class BoundJson : Json, IBound<Test>
{
    public string _BoundProperty
    {
        get
        {
            return "Hello";
        }
    }
}
~~~

Now, here's the interesting part. This works fine until you add the magic ingredients:

1. There must be at least two concurrent requests for a page that contains the JSON document above.
2. The `Data` property must be explicitly set to null.

I used the following snippet to satisfy the criteria above:

~~~
static void Main()
{
    Handle.GET("/bindbug", () =>
    {
        return new BoundJson()
        {
            Data = null
        };
    });

    var client = new HttpClient();
    for (int i = 0; i < 4; i++)
    {
        Task.Run(async () =>
        {
            while (true)
            {
                try
                {
                    await client.GetStringAsync("http://localhost:8080/bindbug");
                }
                catch (HttpRequestException ex)
                {
                    System.Diagnostics.Trace.TraceInformation(ex.ToString());
                }
            }
        });
    }
}
~~~

On my machine Starcounter begins to spit out 500's.

Affects at least Starcounter v2.1.177.

/sub @chrhol

**Comment by chrhol** [comment] 2016-01-05 10:48
Nice testcase :) 

We have some issues concerning TypedJson and concurrent access (#2597) that are not solved so maybe this is something similar, or maybe a bug when determining if an existing databinding can be used or not. I will take a look.

**Comment by chrhol** [comment] 2016-01-05 11:27
Confirmed, it's a problem with synchronization.

> 2 The Data property must be explicitly set to null.

This is the key factor in this case. When `Data` property is set to null, all existing databindings are invalidated, and this together with the concurrent access will sometimes result in a nullreferenceexception

So the proper fix for this is to solve the old issue (#2597). We will start building a roadmap and prioritizing existing issues and this one is quite important I think.

In the meantime I can do an optimization, since bindings to a property in codebehind does not need to be invalidated, to skip these ones when setting `Data` to null. Then it will work for this particular occurence at least.

Also we have #2964, which will simplify the use of bound codebehind properties.

**Comment by mtornwall** [comment] 2016-01-05 11:34
> This is the key factor in this case. When Data property is set to null, all existing databindings are invalidated, and this together with the concurrent access will sometimes result in a nullreferenceexception

OK, then I guess it can be worked around for now by not setting `Data` to null?

> We will start building a roadmap and prioritizing existing issues and this one is quite important I think.

I agree. I discovered the bug while running some performance benchmarks on my application. It's doubly problematic, because it causes a significant number of requests to fail while decreasing throughput because it has to handle exceptions all the time.

> In the meantime I can do an optimization, since bindings to a property in codebehind does not need to be invalidated, to skip these ones when setting Data to null. Then it will work for this particular occurence at least.

Sounds good; that ought to work for me until a complete fix is released.

Thanks @chrhol. :-)

**Comment by chrhol** [comment] 2016-01-07 08:59
Sorry for the delay in pushing the fix. Couldn't get the buildserver to run a succesful build for some reason. 

Anyways it's pushed to develop branch now and will be included in the next nightly build.

**Closed by chrhol** 2016-01-07 08:59 UTC
Labels: bug, Typed JSON

**Comment by chrhol** [comment] 2016-01-07 09:02
Oh, and this should work as well as a workaround: 

> OK, then I guess it can be worked around for now by not setting Data to null?
