### ISSUE TITLE
Python for building pnext

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2781] opened 2015-06-17 13:53 UTC
I am wonder is Python required to build `pnext` or not?
When I run CMake it complains:

> -- Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE)

What is Python used for?

**Comment by alexanderstc** [comment] 2015-06-17 13:58
I always have this warning on my PC, never had python installed.

**Comment by parherman** [comment] 2015-06-17 14:04
I did a build on a new vm to check the dependencies, I did not install python and I do not have python on my laptop and do not get this warning. 

What version of cmake are you running? 
Are you running Windows 8.1?
Have you tried to run in a vs cmd prompt?

**Comment by k-rus** [comment] 2015-06-17 14:06
> Have you tried to run in a vs cmd prompt?

No. I always forgot about this. It is so inconvenient. I will try now.

**Comment by k-rus** [comment] 2015-06-17 14:07
> Have you tried to run in a vs cmd prompt?

but which one? it is 8 different VS command prompts?

**Comment by parherman** [comment] 2015-06-17 14:11
Try native x64 vs2015

But pnext dose not require python, its just a warning, if it was a depend
to build then cmake would abort

**Comment by k-rus** [comment] 2015-06-17 14:16
> Try native x64 vs2015

I tried this one and still get the warning.


> But pnext dose not require python, its just a warning

We try to achieve builds, which are warning free in Starcounter. Therefore, if Python is not used then, imho, it should be excluded from CMake.


> What version of cmake are you running?

Latest (3.3.0)


> Are you running Windows 8.1?

Yes

**Comment by parherman** [comment] 2015-06-17 14:18
Yes we will remove this warning, I just need to reproduce it

**Comment by parherman** [comment] 2015-06-24 05:46
We get this warning because we include gtest in third_party and some of its tests and utility scripts requires python

**Comment by parherman** [comment] 2015-06-24 06:39
This should be solved now, so you should not get a warning that python is missing.

**Comment by parherman** [comment] 2015-06-24 08:41
I will close this now, open it if you see it again!

**Closed by parherman** 2015-06-24 08:41 UTC
Labels: bug, Build System, Infrastructure, question
