### ISSUE TITLE
Cannot build Typed JSON with code behind

### ISSUE THREAD

**Issue by Starcounter-Jack** [Starcounter/Starcounter#2148] opened 2014-07-04 13:34 UTC
### How to reproduce
Build our InvoiceDemo. Change code. Add typed JSON. Recompile. Rebuild.

### Environment
Windows 8.1, Visual Studio 2013. 

### Build error
```
Error	11	Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
The system cannot find the file specified.
	C:\sc\invoice\InvoiceApp\InvoiceApp.json.cs	InvoiceApp
```

**Comment by parherman** [comment] 2015-06-01 12:29
It looks like there are now official NuGet packages for fsharp: https://www.nuget.org/packages/FSharp.Core

**Comment by warpech** [comment] 2015-07-21 15:58
The same error still happens, with almost an empty project.

![image](https://cloud.githubusercontent.com/assets/566463/8805513/de962ff0-2fd1-11e5-80f2-5c268d2d4fd3.png)

My config: Windows 8.1, VS2012, Starcounter 2.0.3268.3

@miyconst says it also happens to him

**Comment by warpech** [comment] 2015-07-21 16:00
Downloading and installing the solution posted by @dan31 does not solve the problem

**Comment by dan31** [comment] 2015-07-22 07:22
@warpech, this is a new behaviour. But if you restart VS and create new project, the same happens? @chrhol, what do you think?

**Comment by chrhol** [comment] 2015-07-22 07:32
Maybe we can try to use the nuget package for this project. I will update it during the day.

**Comment by warpech** [comment] 2015-07-22 09:16
Steps to reproduce are super simple for me:

1. Create a new project in VS2012
 - creates `Program.cs`, builds OK
2. Use solution explorer to add "Starcouter Typed JSON with Code-behind"
 - creates `Message1.json` and `Message1.json.cs`, build fails with the error message:

```
Error	1	Could not load file or assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.	C:\PolyjuiceProjects\warpech\TestGuide4\Message1.json.cs	TestGuide4
```

**Comment by chrhol** [comment] 2015-07-22 11:56
I tried to change the reference and F# build tools to use nuget packages instead and locally it seems to be working fine, however I'm not sure how to download needed nuget packages on the buildservers. The problem might be, I guess, that the F# build tools need to be downloaded before the project can be opened (dependency on a .targets file). Not sure how this is solved for other cases.

I saw these issues: #739 and #1457. Maybe this is needed before we can use F# nuget package.

**Comment by alemoi** [comment] 2015-07-22 12:59
For now we can manually upload Nuget packages to buildserver FTP: ftp://scbuildserver/... Somewhere there their is a packages folder containing existing Nuget packages. I was uploading my working version of packages from Level1/src/packages I think.

**Comment by chrhol** [comment] 2015-07-23 07:47
Thanks for the help @alemoi and @parherman. I copied the needed packages to the ftp and it seems to be working. I will test and see that the installed version works as it should as well before pushing any changes.

**Comment by chrhol** [comment] 2015-07-23 08:51
Everything seems to be working fine. I've pushed the changes to develop now.

NOTE: For those that build level1 the first time after this change you will need to do a couple of steps since the F#-project depends on a targets file, so it cannot be loaded until the f# build tools are downloaded.

1. Open Level1 solution
2. Run nuget package restore (The needed nuget is `FSharp.Compiler.Tools for F# 3.1`)
3. Reload project `Starcounter.XSON.JsTemplateParser` or restart Level1 solution

Ping: @alemoi, @per-samuelsson, @parherman, @k-rus, @dan31, @andwah
Have I forgotten someone?

I will assume this issue is resolved by this and will close it.

**Comment by chrhol** [comment] 2015-07-23 09:49
Was a bit too fast here, I noticed that for some reason running fsharp tools (fsc.exe) from nuget on scbuildserver fails, but works fine on scbuildserver2. 

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyT
oken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.
SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

@alemoi, @parherman: Do you have any idea what could be different between scbuildserver and scbuildserver2? It's a bit strange since it works fine in some places. One thing I can think of is that on scbuildserver2 there are no `FSharp.Core.dll` in gac, but on scbuildserver there are two other versions (not 4.3.1.0 though) so maybe there is some mixup there.

**Comment by chrhol** [comment] 2015-07-23 09:52
Ohh sorry, my bad. scbuildserver2 (and my computer) actually had 4.3.1.0 in gac, so most likely some mixup in loading the correct version on scbuildserver. I hate the gac...

**Comment by alemoi** [comment] 2015-07-23 15:23
So if the DLL is not in GAC but in packages than VS cannot find it during the build?

**Comment by chrhol** [comment] 2015-07-24 07:51
> So if the DLL is not in GAC but in packages than VS cannot find it during the build?

Yeah, still trying to find a correct solution. For now I added the needed dll to gac on the buildserver just to make the builds work. It looks like the FSharp.Core.dll in the f# tools package is only delay-signed and you actually get an exception running fsc.exe (the F# compiler). Maybe there is something I missed.

**Comment by chrhol** [comment] 2015-07-28 07:03
I think that the correct solution is to move away from using F#. There is only one project that uses F#, and that is used to parse the Json-by-example file and using an interface have callbacks to methods that creates a Template. This could be implemented in C# instead.

**Comment by dan31** [comment] 2015-07-28 13:57
@chrhol, that'd be reasonable. Do you think we can reuse some ready-made well-proven parser written in C# and hook into it a bit to do the Template logic?

**Comment by alemoi** [comment] 2015-07-28 22:29
I installed VS 2015 community edition and had problems building Level1 after that, in particular, the F# project ("fsc task was not found"). I've spent some time trying to resolve the issue and ended up installing FSharp tools ver 4.0.0.1 instead of v 3.x that is now used. I'm testing VS plugin installation locally now, but possibly it wil cause problems later. Just sharing my experience :)

**Comment by alemoi** [comment] 2015-07-29 09:06
So I added FSharp.* packages ver 4.0.0.1 to build server FTP. scbuildserver2 builds fine. scbuildserver in comparison throws: `ScErrWeaverFailedStrongNameAsm (SCERR2143): A locally deployed strong-named assembly was detected. Assembly: FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. Consider excluding this file by adding a "weaver.ignore" file to your project.` @chrhol I guess its GAC as you mentioned before. How did you add a DLL to GAC and were there any other steps? Thanks!

**Comment by chrhol** [comment] 2015-07-29 09:09
It was the same problem as I had on scbuildserver (scbuildserver2 worked fine). I added the dll manually using `gacutil`

**Comment by alemoi** [comment] 2015-07-29 09:33
Thanks. I switched now the FSharp project to use Fsharp.* packages version 4.0.0.1. Both build servers are building fine now. Those who use Level1 will have to do nuget packages update, as @chrhol described above.

**Comment by chrhol** [comment] 2015-07-29 11:29
> @chrhol, that'd be reasonable. Do you think we can reuse some ready-made well-proven parser written in C# and hook into it a bit to do the Template logic?

I have not spent that much time into looking into existing parsers, but I guess we could use parts of Json.Net (newtonsoft). They seem to have a `JsonTextReader` class that can be used to enumerate json from some input. I've only tried it briefly and not sure it supports all that we need but maybe. I guess it depends on how standalone we want the XSON project to be. 

The other option is to write a parser ourselves. We have parts of a parser already that is used internally, but that one lacks a bit in errorhandling since we can use the defined template to do alot of the verifications.

**Comment by k-rus** [comment] 2015-08-13 09:33
> So I added FSharp.* packages ver 4.0.0.1 to build server FTP. scbuildserver2 builds fine. scbuildserver in comparison throws: ScErrWeaverFailedStrongNameAsm (SCERR2143): A locally deployed strong-named assembly was detected. Assembly: FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. Consider excluding this file by adding a "weaver.ignore" file to your project. @chrhol I guess its GAC as you mentioned before. How did you add a DLL to GAC and were there any other steps?

I cannot fix this problem. Can anyone give better instructions? I added the assembly to GAC, but I still get the error. It is showstopper for me to investigate a reported bug.

**Comment by k-rus** [comment] 2015-08-13 09:46
> I cannot fix this problem. Can anyone give better instructions? I added the assembly to GAC, but I still get the error. It is showstopper for me to investigate a reported bug.

The missing step for me was to rebuild Level1 solution. So it is resolved for me.

**Closed** 2016-02-16 12:14 UTC
Labels: bug, P/SHOWSTOPPER
