### ISSUE TITLE
Transaction locked on thread in commit hooks

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3490] opened 2016-04-13 04:35 UTC
Wanted to change the data object on a Json when called from a commit hook and then push the changes to the client but just get this error all the time.
(I can't set the Data property, I can't call Session.ScheduleTask e.t.c.)

**Comment by dan31** [comment] 2016-04-13 07:00
@malx122, which version is it? (pls always show the exact one) CC @alemoi @chrhol

**Comment by malx122** [comment] 2016-04-13 07:02
2.1.1658

**Comment by chrhol** [comment] 2016-04-13 07:21
See #2766.
Short answer is that it's not possible to switch transactions in a hook since the commit for the specific transaction is executing.

**Comment by chrhol** [comment] 2016-04-13 07:23
About `Session.ScheduleTask` that should still be possible I guess. Maybe the implementation needs to be refined. It doesn't schedule a task if the scheduler is the same as the current one, it executes the delegate directly which doesn't work in this case.

**Comment by malx122** [comment] 2016-04-13 07:30
Hm, sounds like a quite important missing feature if its not possible to use a commit hook to update client (Ok, you can update as long as you don't update any binded data). 

Maybe put a "forceSchedule" into Session.ScheduleTask?

**Comment by chrhol** [comment] 2016-04-13 08:57
I will take a look at it and discuss with @alemoi to see what can be done.

**Comment by alemoi** [comment] 2016-04-13 14:12
I looked at it and current workaround that we suggest is to call `Scheduling.ScheduleTask` without specifying the scheduler and not waiting for completion, and inside this delegate actually call `Session.ScheduleTask`. Let us know if it works!

**Comment by dan31** [comment] 2016-04-14 15:06
CC @miyconst @chrhol pointed to an issue with question from @miyconst https://github.com/Starcounter/Starcounter/issues/2766. In current issue @alemoi proposes sort of solution. @miyconst, does it resolve your question? @alemoi @chrhol if that is a solution, would there be proposed a nicer way to do it rather than mixing Scheduling.ScheduleTask and Session.ScheduleTask? (Isn't similar name misleading here?)

**Comment by alemoi** [comment] 2016-04-14 15:16
I will explain why its like that: when calling `ScheduleTask` with sync flag on current scheduler - it executes the task immediately, without putting it to the queue. And the reason for that I think its because task can't wait on the same scheduler for the task to finish on this scheduler (I suppose it creates a deadlock). And since task is executed directly - there is a problem with transactions there which @chrhol can explain better.

**Comment by dan31** [comment] 2016-04-14 15:25
@alemoi thanks for explaining, let's see what @miyconst says. My point here is to find more and more ways of how not to force-feed users with all this knowledge of scheduler IDs, how scheduler deals with transactions, thread not attached to a scheduler and all that stuff. Hence I'm trying to smooth out that particular case as well, and to figure out, what the pattern solves and is there a way to let users use better means to achieve the same functionality - it might be just sugaring around what you describe, but if sugaring provides clean way to solve a task - this is a good sugaring.

**Comment by alemoi** [comment] 2016-04-14 15:28
@dan31 im totally on your side regarding this. What I have suggest above is a pure hackintosh and should be considered a bug I would say.

**Comment by miyconst** [comment] 2016-04-14 15:31
Before I can say whether it solves my issue or not, I have to try it out.

**Comment by miyconst** [comment] 2016-04-15 11:27
I have created a test case for commit hooks in my playground: https://github.com/miyconst/Playground, and it ends up that:

- I can assign database objects to JSON view-model from a commit hook.
- I can call `Session.ForAll` from a commit hook.
- This might lead to `The operation failed because of an invalid object access.` error inside Starcounter which stops entire database.

Steps to reproduce:

- Start the playground app.
- Open `/playground` in two browser tabs.
- Press `Add item` to create an item.
- Press `Save changes` to save changes.
- Go to other tab.
- Make sure that the item is visible here as well.
- Press `Remove first item` to remove the item.
- Go to other tab.
- Press `Update first item` to update the item.
- Press `Save changes` to save changes.
- Check the browser's console, there is a connection error. Database crashed.

This happens because the updated item is removed and not accessible in the another scope.

**Comment by chrhol** [comment] 2016-05-03 06:57
With the changes made by @alemoi in #3529, you can now access a session using `Session.ScheduleTask` from a commithook. Tasks are always executed async, although having `waitForCompletion` set to `true` inside a commithook might not be a good idea.

@miyconst: I think your issue is the same as #2140, the dirtycheck needs to handle deleted objects. I will copy your comment to that issue instead. It's a really good case for when it's not working and there is no real workaround I can see.

**Comment by chrhol** [comment] 2016-05-03 07:08
I will consider this issue resolved and close it. If you still have problems with this @malx122, ping me and I will reopen it.

**Closed by chrhol** 2016-05-03 07:08 UTC
Labels: enhancement
