### ISSUE TITLE
Question : How to rollback a transaction

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3557] opened 2016-05-02 14:30 UTC
I have DB transactions and on some locations, I need to rollback everything done in the transaction. An example of what i want to do is :
```
                Db.Transact(() =>
                {
                    Person person = new Person();  
                    person.IsConfirmed = true;
                    person.Name = "No Body";
                    if (a certain condition meets)
                    {
                        //discard everything. and delete the person object.
                    }
                });
```

I tried `this.Transaction.Rollback();` but it looks like this syntax is only for Code Behind Json.

**Comment by per-samuelsson** [comment] 2016-05-02 14:38
@atifwaqar 

AFAIK, rollbacks are normally triggered by raising exceptions from you scope:

```cs
Db.Transact(() => { 
  var person = new Person();
  if (a certain condition meets) {
    //discard everything. and delete the person object.
    throw new Exception("Invalid condition met");
  }
});
```

I'm surprised it's not in our documentation, and maybe we have some other API too, but exceptions like that should work at least.

cc @chrhol ?

**Comment by mtornwall** [comment] 2016-05-02 14:59
> I tried this.Transaction.Rollback(); but it looks like this syntax is only for Code Behind Json.

The JSON view models hold a reference to their transaction. Outside of the view model you don't have this convenience, but you can still get at the transaction using `Transaction.Current`.

**Comment by atifwaqar** [comment] 2016-05-02 15:01
@per-samuelsson I am actually using the same code as you suggested. but i my apps are crashing a lot, and i suspected these "throw exceptions" may be causing any issue. 
and i thought may be i'm roll-backing the wrong way.

**Comment by atifwaqar** [comment] 2016-05-02 15:05
@mtornwall 
Thanks for the syntax.

**Comment by mtornwall** [comment] 2016-05-02 15:11
> [...] and i suspected these "throw exceptions" may be causing any issue. 
and i thought may be i'm roll-backing the wrong way.

They certainly might, if the code that throws the exception is invoked through `Db.RunAsync` or one of the asynchronous `Http` methods without proper top-level exception handling. See #3032.

**Comment by atifwaqar** [comment] 2016-05-02 15:18
@mtornwall This was exactly the case. I was throwing an exception from inside a `Db.RunAsync`. 
Thanks :)

**Comment by dan31** [comment] 2016-05-02 15:30
@chrhol that is a great addition to our recent discussion on transaction management. Could you please allocate a time (probably once working on adopting to changes in transactions) to also put this knowledge into documentation? (I cross-referenced the current issue on a TechComm tracker).

**Comment by atifwaqar** [comment] 2016-05-03 12:13
My DB.Transact code is as following : 
```
Db.Transact(() =>
{
	ca = new AdFenix.Database.Campaign(ad)
	{
		//Sample Code
		CreatedDate = DateTime.Now;
	};
        //Sample Code
        ca.EndDate = DateTime.Now.AddDays(7);
});
```

And I have a constructor for `AdFenix.Database.Campaign` as following (where i have the rollback logic) : 
```
public Campaign(ClassifiedAd classifiedAd)
{
	if (classifiedAd != null)
	{
		this.Name = this.GetName(classifiedAd).Replace("\\","");
	}
	else
	{
		Transaction.Current.Rollback();
		//throw new Exception("Rollback");
	}
}
```

After my rollback code executes, i get the following exception :
(Note : Campaign.cs:line 302 have the code `Transaction.Current.Rollback();`) 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AdFenix.Database.Campaign..ctor(ClassifiedAd classifiedAd, UInt16 tableId, TypeBinding typeBinding, Uninitialized dummy) in c:\adfenix-backend\src\Database\Campaigns\AdFenix\Campaign.cs:line 302
   at AdFenix.Database.Campaign..ctor(ClassifiedAd classifiedAd)
   at AdFenix.Server.Handlers.CustomizedInterfaces.GeneralAPI.GeneralAPI.<>c__DisplayClassd7.<Register>b__b9() in c:\adfenix-backend\src\Server\Handlers\CustomizedInterfaces\GeneralAPI\GeneralAPI.cs:line 427
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-268\Level1\src\Starcounter\Db.cs:line 354
   at AdFenix.Server.Handlers.CustomizedInterfaces.GeneralAPI.GeneralAPI.<Register>b__b6(String token, String domain, CampaignsCreate campaigns, Request r) in c:\adfenix-backend\src\Server\Handlers\CustomizedInterfaces\GeneralAPI\GeneralAPI.cs:line 422
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-268\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-268\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-268\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 598
HResult=-2147467261
```

So my question here is, When I execute the rollback command, isn't the control suppose to get out of the DB.Transact automatically (skipping the "Sample Code" lines)?

**Comment by mtornwall** [comment] 2016-05-03 12:30
> So my question here is, When I execute the rollback command, isn't the control suppose to get out of the DB.Transact automatically (skipping the "Sample Code" lines)?

No. The only way to do non-local return in C# is to throw an exception. Since no exception is thrown, control proceeds as usual after `Transaction.Current.Rollback`.

Based on this small glimpse of your code it looks to me as though the case when `classifiedAd == null` is exceptional (as in `ArgumentNullException`?) and should be handled accordingly. Perhaps you could install a top-level exception handler inside the `Db.Transact`:

~~~
Db.Transact(() =>
{
    try
    {
        ca = new AdFenix.Database.Campaign(ad)
        {
            //Sample Code
            CreatedDate = DateTime.Now;
        };
        //Sample Code
        ca.EndDate = DateTime.Now.AddDays(7);
    }
    catch (Exception ex)
    {
        Transaction.Current.Rollback();
        return;
    }
});
~~~

**Comment by atifwaqar** [comment] 2016-05-03 12:49
@mtornwall Thanks for explaining.

One last question, and I suspect the answer is `1`, but just to confirm, I see `return;` after `Transaction.Current.Rollback();` in your code : 
1. Will this send the control out of Db.Transact only? 
2. Will this send the control outside of the function in which we have Db.Transact?

**Comment by chrhol** [comment] 2016-05-06 08:14
I missed this issue, my apologies.

`Transaction.Current` will always return null inside a `Db.Transact`. The *only* way, currently, to do a rollback from a `Db.Transact` is to throw an exception. 

Now, for the pattern suggested above, the rollback will still happen since calling `Transction.Current.Rollback` will result in a nullreferenceexception.

So the correct pattern to perform a rollback from a `Db.Transact` to avoid any further consequences
is to wrap the call inside a try-catch:

```csharp
try {
    Db.Transact(() => {
        // Db operations here.
        if (classifiedAd == null)
            throw new ArgumentException("...");
    });
} catch (ArgumentException ex) {
    // Db.Transact above is already rollbacked here..
}
```

**Comment by mtornwall** [comment] 2016-05-06 09:15
Wow... I had no idea; clearly this is why my transactions have been rolling back as intended:

> Now, for the pattern suggested above, the rollback will still happen since calling Transction.Current.Rollback will result in a nullreferenceexception.

**Comment by dan31** [comment] 2016-05-30 12:03
Closing this KB issue. The API might get simplified in future to do this without exceptions.

**Closed by dan31** 2016-05-30 12:03 UTC
Labels: Knowledge base, question, Transactions

**Comment by atifwaqar** [comment] 2016-10-26 14:28
@dan31 Have you guys updated anything to have rollback without exceptions?
