### ISSUE TITLE
The operation failed because of an invalid object access

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3765] opened 2016-07-26 07:10 UTC
I am getting this exception on my local machine. I tried to reproduce it on another machine, but couldn't. 

```
Error : ScErrInvalidObjectAccess (SCERR4174): The operation failed because of an invalid object access.
Version: 2.2.1.2706.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4174.

  at Starcounter.Internal.DbState.ReadBoolean(UInt64 oid, UInt64 address, Int32 index) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-391\Level1\src\Starcounter\Internal\DbState.cs:line 158
  at AdFenix.Functions.ActivateCampaignsAutomatically.ActivateCampaign(Campaign campaign, ClassifiedAd classifiedAd) in c:\adfenix-backend\src\Functions\ActivateCampaignsAutomatically.cs:line 14
  at AdFenix.Database.Campaign.<>c__DisplayClass38.<CreateCampaignFromAPI>b__37() in c:\adfenix-backend\src\Database\Campaigns\AdFenix\Campaign.cs:line 961
```

The issue occurres as soon as I enter in `RunAsync(()=>{`

Attached are 2 images. 
1. Everything is fine here. I can see the `ca.ObId` & `ca.IsFacebookAdNeeded`
![first_state](https://cloud.githubusercontent.com/assets/4388707/17128922/3a0d248a-5310-11e6-81d8-5b7fd32be49e.png)
2. I can still see the `ca.ObId` but I can't see the `ca.IsFacebookAdNeeded`
![second_state](https://cloud.githubusercontent.com/assets/4388707/17128927/3d23df88-5310-11e6-8bbc-35bb7919f7f6.png)

**Comment by linkdata** [comment] 2016-08-24 11:55
Seems like a duplicate of https://github.com/Starcounter/Starcounter/issues/3779
Please re-open if you think it's a different bug.

**Closed by linkdata** 2016-08-24 11:55 UTC
