### ISSUE TITLE
Index was out of range exception in Starcounter.XSON

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3816] opened 2016-08-30 19:30 UTC
From time to time I get this error:

```
"System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.System.Collections.IList.get_Item(Int32 index)
   at Starcounter.XSON.JsonProperty.EvalutateCurrent(JsonPointer ptr, ViewModelVersion version, Boolean& nextIsIndex) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-456\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 112
   at Starcounter.XSON.JsonProperty.<>c.<DoEvaluate>b__11_0(JsonProperty prop, JsonPointer ptr, ViewModelVersion pv, Boolean isIndex) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-456\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 82
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3,T4,TResult](Json json, Func`5 func, T1 arg1, T2 arg2, T3 arg3, T4 arg4) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-456\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 231
   at Starcounter.XSON.JsonProperty.DoEvaluate(JsonPointer pointer, Json root) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-456\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 79
   at Starcounter.XSON.JsonProperty.Evaluate(JsonPointer pointer, Json root) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-456\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 59
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-456\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 18
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-456\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 682
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-456\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 522
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-456\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 57
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-456\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-456\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
ParamName=index
HResult=-2146233086
"
```

cc @chrhol

**Comment by chrhol** [comment] 2016-08-31 07:21
Well, it's clearly a bug. These kind of exceptions should not be reported to the user. The question is why the index is incorrect in this case. 

Is there some place or some apps that gets this exception more often than others so I can try to reproduce it before fixing it, or is it just randomly occurring in different places?

**Comment by miyconst** [comment] 2016-08-31 08:23
It happens when navigating to the Launcher app and removing all workspaces. We have a custom Launcher which keeps only one workspace at a time.

Most or the time it happens when navigating from big apps, means removing big view-model from the JSON tree. Not sure it's related though.

**Comment by chrhol** [comment] 2016-09-01 13:44
After some investigation I found that using 'Clear()' on an array in TypedJSON does not work well together with OT. So when a patch is sent from the client for an older version, the server does not correctly detect and reject it. Instead it ends up with a nullreferenceexception.

I will work on a fix.

**Comment by chrhol** [comment] 2016-09-05 11:53
I've pushed a fix for this to develop. Will soon push to pnext.

**Comment by chrhol** [comment] 2016-09-08 07:28
Looks like this issue still persists for some cases.

**Closed** 2016-09-27 10:00 UTC
Labels: bug, Typed JSON
