### ISSUE TITLE
pnext sqlregression test fails at TableCreate.Eval 

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#3123] opened 2015-12-01 11:06 UTC
Just so we can track the current state of issues.
Here is the exception:
```
20151201T115407 Critical sc://scbuildserver2/personal/sqltest Starcounter - System.Exception: ScErrUnspecified (SCERR999): An unspecified error caused the operation to fail.\r\nVersion: 2.3.48.\r\nHelp page: https://github.com/Starcounter/Starcounter/wiki/SCERR999.\r\n   at Starcounter.Binding.TableCreate.Eval() in C:\\BuildAgent\\work\\sc-2.0.1038\\Level1\\src\\Starcounter\\Binding\\TableCreate.cs:line 66\r\n
   at Starcounter.Hosting.Package.CreateOrUpdateDatabaseTable(TypeDef typeDef) in C:\\BuildAgent\\work\\sc-2.0.1038\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 442\r\n   at Starcounter.Hosting.Package.<>c__DisplayClass20_1.<UpdateDatabaseSchemaAndRegisterTypes>b__2() in C:\\BuildAgent\\work\\sc-2.0.1038\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 355\r\n   
at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\\BuildAgent\\work\\sc-2.0.1038\\Level1\\src\\Starcounter\\TransactionManager.cs:line 462\r\n   at Starcounter.Transaction.Scope(Action action) in C:\\BuildAgent\\work\\sc-2.0.1038\\Level1\\src\\Starcounter\\Transaction.cs:line 199\r\n   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\\BuildAgent\\work\\sc-2.0.1038\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 368\r\n  
 at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in C:\\BuildAgent\\work\\sc-2.0.1038\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 259\r\n   at Starcounter.Hosting.Package.Process() in C:\\BuildAgent\\work\\sc-2.0.1038\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 143\r\n   
at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\\BuildAgent\\work\\sc-2.0.1038\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 56\r\n   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\\BuildAgent\\work\\sc-2.0.1038\\Level1\\src\\Hosting\\Starcounter.Hosting\\Processor.cs:line 90\r\nHResult=-2146233088\r\nHelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR999\r\n
```
Can be found in artifacts for the personal build I made: https://scbuildserver/viewLog.html?buildId=32277&buildTypeId=Starcounter_NewPnextDaily&tab=artifacts

**Comment by bigwad** [comment] 2015-12-01 13:55
I believe, it's environmental problem. Due to bad machine performance, scdata failed to start in allocated timeslot (3 sec), so test failed.
During normal host startup, star.exe has been waiting for scdata for 5 sec. So I increased timeout in the script to 5 sec to match star.exe's behavior.
Worth to mention that star.exe is checking for special event during that 5 seconds, so it may stop waiting earlier if scdata is ready. Would be good to have similar ability in command line to improve test performance.

**Comment by bigwad** [comment] 2015-12-01 15:15
Another reason why it fails is the presence of SocietyObjects. Investigating it now.

**Comment by bigwad** [comment] 2015-12-01 16:17
I haven't dig deep enough to point to the problem more closely, but something wrong with metalayer I believe. Host tries to register a table Concepts.Ring1.FixedType that is inherited from Concepts.Ring1.Something. To do so it's looking up for definition of base class (Concepts.Ring1.Something), but it can't find its definition, though base class was successfully registered right before derived.
@alexanderstc, @k-rus

**Comment by bigwad** [comment] 2015-12-01 16:21
Copy the folder "\\scbuildserver\ftp\Temp\EditionLibraries" to your output folder in order to reproduce on local machine.

**Comment by alemoi** [comment] 2015-12-01 18:06
https://github.com/Starcounter/CompanyTrack/issues/156

**Comment by alexanderstc** [comment] 2015-12-02 09:36
I debugged, the order of events is this:

- a table "Concepts.Ring1.Something" is created, with token 281, yielding layout 84
- the transaction is commited
- stari_context_get_layout_infos_by_token() is called with token 281, returning 0 and no layouts found
- the test fails because of no layouts have been found

@eriohl, could you have a look please

**Comment by eriohl** [comment] 2015-12-02 18:27
Should include \scbuildserver\ftp\Temp\EditionLibraries files in SQLTest then?

**Comment by eriohl** [comment] 2015-12-02 18:29
Why does the build server do this?

**Comment by k-rus** [comment] 2015-12-02 18:29
As I understood EditionLibraries folder should be placed in output folder of Level1.

**Comment by alemoi** [comment] 2015-12-02 21:33
> Why does the build server do this?

SO and Simplified are built automatically on the build server, after Level1 and Level0. We, as developers, need to build these repos, first SO, then Simplified (building should be done with StarcounterBin defined so that MsBuild for those projects knows where to output those libraries, should point to your binaries folder):
https://github.com/StarcounterSamples/Society-Objects
https://github.com/StarcounterSamples/Simplified

> Should include \scbuildserver\ftp\Temp\EditionLibraries files in SQLTest then?

I will delete this FTP folder, used it temporary for @bigwad

**Comment by eriohl** [comment] 2015-12-02 21:59
Question was why they where loaded as part of the SQLTest.

**Comment by eriohl** [comment] 2015-12-02 22:02
Anyway: Problem resolved. Token size was not calculated correctly when creating layout so token was not correctly in layout.

Test now fails on some constraint violation creating tables instead. I can check this tomorrow.

**Comment by alemoi** [comment] 2015-12-02 22:18
> Question was why they where loaded as part of the SQLTest.

These libraries are loaded as a part of every codehost, so they are a mandatory part of Starcounter now. I created a separate issue regarding these components: https://github.com/Starcounter/CompanyTrack/issues/156

**Comment by k-rus** [comment] 2015-12-03 06:36
> Question was why they where loaded as part of the SQLTest.
> These libraries are loaded as a part of every codehost, so they are a mandatory part of Starcounter now. I created a separate issue regarding these components: Starcounter/CompanyTrack#156

As I replied there it is incorrect to assume that regression tests are product/system tests. Regression tests also contain unit tests and component tests and they don't assume that Starcounter is installed.

**Comment by alemoi** [comment] 2015-12-03 09:42
That's correct. However no tests should fail when missing components are added.

**Comment by eriohl** [comment] 2015-12-03 10:04
> That's correct. However no tests should fail when missing components are added.

Some tests have hardcoded record ids. Changing the input might change the output obviously.

**Comment by alemoi** [comment] 2015-12-03 10:25
> Some tests have hardcoded record ids. Changing the input might change the output obviously.

I see. Then best would be to use a flag "LoadEditionLibraries": https://github.com/Starcounter/CompanyTrack/issues/156#issuecomment-161584406

I will make sure its working and get back here.

**Comment by alemoi** [comment] 2015-12-03 10:36
I see there is another error with sqlregression test now, which I saw before in other tests:
```
20151203T110758 Critical sc://scbuildserver2/personal/sqltest Starcounter - Starcounter.ConstraintViolationException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.\r\nVersion: 2.3.73.\r\nHelp page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.\r\n   at Starcounter.Db.CreateTable(TableDef tableDef, TableDef inheritedTableDef) in C:\\BuildAgent\\work\\sc-2.0.1063\\Level1\\src\\Starcounter\\Db.cs:line 89\r\n   at Starcounter.Binding.TableCreate.Eval() in C:\\BuildAgent\\work\\sc-2.0.1063\\Level1\\src\\Starcounter\\Binding\\TableCreate.cs:line 59\r\n   at Starcounter.Hosting.Package.CreateOrUpdateDatabaseTable(TypeDef typeDef) in C:\\BuildAgent\\work\\sc-2.0.1063\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 442\r\n   at Starcounter.Hosting.Package.<>c__DisplayClass20_1.<UpdateDatabaseSchemaAndRegisterTypes>b__2() in C:\\BuildAgent\\work\\sc-2.0.1063\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 355\r\n   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\\BuildAgent\\work\\sc-2.0.1063\\Level1\\src\\Starcounter\\TransactionManager.cs:line 462\r\n   at Starcounter.Transaction.Scope(Action action) in C:\\BuildAgent\\work\\sc-2.0.1063\\Level1\\src\\Starcounter\\Transaction.cs:line 199\r\n   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\\BuildAgent\\work\\sc-2.0.1063\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 368\r\n   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in C:\\BuildAgent\\work\\sc-2.0.1063\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 259\r\n   at Starcounter.Hosting.Package.Process() in C:\\BuildAgent\\work\\sc-2.0.1063\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 143\r\n   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\\BuildAgent\\work\\sc-2.0.1063\\Level1\\src\\Hosting\\Starcounter.Hosting\\Package.cs:line 56\r\n   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\\BuildAgent\\work\\sc-2.0.1063\\Level1\\src\\Hosting\\Starcounter.Hosting\\Processor.cs:line 90\r\nErrorCode=8001\r\nHResult=-2146233088\r\nHelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8001\r\n
```

**Comment by eriohl** [comment] 2015-12-03 10:36
I didn't say it was a problem. Just that it migth be optimistic to assume it should not be.

**Comment by alemoi** [comment] 2015-12-03 10:43
> I didn't say it was a problem. Just that it migth be optimistic to assume it should not be.

Sure. I have to fix the proper work of the flag LoadEditionLibraries anyways. Because it will be much simpler for us to run these kind of tests. Right now we rename the EditionLibraries folder in tests scripts, which is a mess :) I will fix this.

**Comment by k-rus** [comment] 2015-12-03 11:17
> I didn't say it was a problem. Just that it migth be optimistic to assume it should not be.
> Sure. I have to fix the proper work of the flag LoadEditionLibraries anyways. Because it will be much simpler for us to run these kind of tests. Right now we rename the EditionLibraries folder in tests scripts, which is a mess :) I will fix this.

Can non-system tests be run before installing Starcounter? Build Level0, run Level0 tests, build Level1, run Level1 tests, install Starcounter and run app and product tests.
Having SO sometimes complicates writing component tests enormously, which leads to bad test coverage, since the tests are not created.

**Comment by alemoi** [comment] 2015-12-03 11:34
> Can non-system tests be run before installing Starcounter? Build Level0, run Level0 tests, build Level1, run Level1 tests, install Starcounter and run app and product tests.
Having SO sometimes complicates writing component tests enormously, which leads to bad test coverage, since the tests are not created.

Unfortunately I would say no. At least with the new test framework. I tried to make the rules as simple as possible to cover most of the use cases needs. Corner cases would need to adopt I suppose. Let's make a discussion on this and get some opinions: @dan31 @per-samuelsson @k-rus @bigwad @chrhol @eriohl

**Comment by eriohl** [comment] 2015-12-03 13:11
Seems like the current problem is a duplicate set specifier if I read the code correctly (the conflict is on the SetSpecifier table index in set spec, column index 2).

Type where the error occurs is Concepts.Ring1.Category. @k-rus or @alexanderstc?

**Comment by alexanderstc** [comment] 2015-12-04 10:43
I'll have a look at this a bit later today and tonight. Will keep you guys posted.

**Comment by alexanderstc** [comment] 2015-12-07 10:32
Workaround with creating additional index on SetSpecifier with column TypeId descending seems to do the trick. Will commit shortly.

**Comment by eriohl** [comment] 2015-12-07 10:52
I'm not sure I understand?

Since character i is sorted after h then naturally is i will come before h if you iterate the index in the reverse order.

But if you search the index with ~h~<infinite> you should not get ~i~ at all.

**Comment by alexanderstc** [comment] 2015-12-07 10:53
@eriohl
> But if you search the index with ~h~ you should not get ~i~ at all.

My point exactly.

**Comment by eriohl** [comment] 2015-12-07 11:00
A bug on descending searches then maybe? Not figured a lot in function tests. I will investigate.

**Comment by alexanderstc** [comment] 2015-12-07 11:01
Thank you!

**Comment by alexanderstc** [comment] 2015-12-07 11:36
@k-rus  a workaround is in pnext, commit 20383a1b39efdd6417f6c733e9364d92d2ff4967.
Should be removed after @eriohl fixes the reverse search.

**Comment by k-rus** [comment] 2015-12-07 12:05
It sounds like we need to add a func test to regression tests, which creates hundreds of tables in an automatic way. This will reproduce this bug without Starcounter installation and will allow to catch it if met in future.

**Comment by eriohl** [comment] 2015-12-08 12:02
@alexanderstc: I added some tests now on this and it seems to work as expected.

See kernel_functest read_write_string_test ("Starts with search on set specifier formatted strings").

Is there an isolates test to reproduce this I can look at see if I can see what is wrong? Currently I can't find anything wrong with this. This is a regular string field we are searching right?

**Comment by alexanderstc** [comment] 2015-12-08 15:10
I have a branch alexander-3123 which fails sqlregression_test.
When you run sqlregression_test.bat, it displays "attach!" and waits.
Gives you a chance to attach your debugger early.
To continue, press, say, a letter, then enter.


The test displays then a bunch of setspecs being inserted, and errors messages eventually.
The error printing comes out of pnext\level0\src\metalayer\metalayer.cpp function LastSetspec(), around line 70.


In that function, basically, a reverse search goes by infinite string "~h~", which erroneously finds "~i~", instead of "~h~b~".


Please let me know if you need more info.

**Comment by alexanderstc** [comment] 2015-12-08 16:19
@eriohl just in case you are missing notifications, please see the comment above.

**Comment by eriohl** [comment] 2015-12-08 21:27
Thank you @alexanderstc. Managed to get it up and running. Investigating further tomorrow.

**Comment by eriohl** [comment] 2015-12-09 12:06
Fixed. Turned out to be a bug in the reverse iterator. (Applies to develop as well, working on addressing it there as well.)

**Comment by alexanderstc** [comment] 2015-12-09 13:17
@eriohl PNext-Daily-Windows has failed.

**Comment by alexanderstc** [comment] 2015-12-09 13:24
@eriohl  I also think I still observe a similar bug with a forward search on a descending column, preparing a test case.

**Comment by alexanderstc** [comment] 2015-12-09 13:57
@eriohl , seemingly another bug with reverse search on a normal column.

Search by infinite ~c~z finds ~c~.

Level0 branch alexander-3123-2. The same drill to debug.

**Comment by eriohl** [comment] 2015-12-09 14:11
That is not incorrect. ~c~ is less then ~c~z~<infinite> but more then NULL which is used in this case (it is the same search right). If you only want things that starts with ~c~z~ the range needs to be ~c~z~ to ~c~z~<infinite>. Not NULL to ~c~z~<infinite>.

**Comment by alexanderstc** [comment] 2015-12-09 14:16
I agree. Sorry for the false alarm. I see no more bugs.

**Comment by eriohl** [comment] 2015-12-09 14:31
Unless there is ~c~a~ or something you are missing of course?

**Comment by alexanderstc** [comment] 2015-12-09 14:39
No, I was missing "no records found" result.
Now I search from infinite string to the same string, instead of from infinite string to null, and everything works as expected. All tests pass, I pushed to pnext already.

**Comment by eriohl** [comment] 2015-12-09 14:48
OK. Great. Close this one then?

**Comment by alexanderstc** [comment] 2015-12-09 15:12
> OK. Great. Close this one then?

Fine with me.

**Closed** 2015-12-09 15:30 UTC
Labels: BAH, bug
