### ISSUE TITLE
Next Nightly fails with ScErrConstraintViolationAbort during Node HTTP1 Big Data Transfers 

### ISSUE THREAD

**Issue by parherman** [Starcounter/Starcounter#2701] opened 2015-05-06 06:17 UTC
[Next Nightly log](https://scbuildserver/viewLog.html?buildId=27704&buildTypeId=Starcounter_NextNightly&tab=buildLog#_focus=5878)

[Next Nightly Debug log](https://scbuildserver/viewLog.html?buildId=27702&buildTypeId=Starcounter_Next_Nightly_Debug&tab=buildLog#_focus=5226)

Full error:

```
Starcounter.ConstraintViolationException: ScErrConstraintViolationAbort (SCERR8001): A transaction was aborted because a constraint was violated.
Version: 2.0.263.8.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR8001.
   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(TypeDef[] unregisteredTypeDefs) in c:\BuildAgent\work\sc-2.0.263.8\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 285
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in c:\BuildAgent\work\sc-2.0.263.8\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 219
   at Starcounter.Hosting.Package.Process() in c:\BuildAgent\work\sc-2.0.263.8\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 144
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\BuildAgent\work\sc-2.0.263.8\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 70
ErrorCode=8001
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8001
```

You can reproduce by running a personal build with SC_RUN_NODE_TEST=True

**Comment by k-rus** [comment] 2015-05-06 08:11
Thanks for reporting.



> You can reproduce by running a personal build with SC_RUN_NODE_TEST=True

It is more important to know how to reproduce it locally. Do you mean that node test is failing? How can it be executed locally?

**Comment by parherman** [comment] 2015-05-06 08:54
You can start the test with:
```
run_node_test.bat -NumEchoesPerWorker=5000 -ProtocolType=ProtocolHttpV1 -AsyncMode=ModeRandom -MaxEchoBytes=50000
```

**Comment by k-rus** [comment] 2015-05-06 08:59
> You can start the test with:
> 
> run_node_test.bat -NumEchoesPerWorker=5000 -ProtocolType=ProtocolHttpV1 -AsyncMode=ModeRandom -MaxEchoBytes=50000

Thank you.
However, I cannot reproduce the issue locally. It is successfully executed.
Furthermore, I see different error in [the build log](https://scbuildserver/viewLog.html?buildId=27704&tab=buildLog&buildTypeId=Starcounter_NextNightly&logTab=tail):
>[04:57:01][Step 1/1] System.Exception: Can't reset counters properly!
[04:57:01][Step 1/1]    at NodeTest.NodeTest.Main(String[] args) in c:\BuildAgent\work\sc-2.0.263.8\Level1\src\Samples\NodeTest\NodeTest.cs:line 948
[04:57:01][Step 1/1] Error occurred during the Node test!

**Comment by parherman** [comment] 2015-05-06 09:46
I can reproduce it on my local machine now, after running two node tests in a row I now get the error all the time

**Comment by alemoi** [comment] 2015-05-06 10:17
I don't think its a problem with SQL. I need to look at the test first, to see if there are any flaws in it.

**Comment by k-rus** [comment] 2015-05-06 10:38
Thank you! I was able to reproduce and know the reason. I am working on fixing it.

**Comment by k-rus** [comment] 2015-05-06 10:39
> I don't think its a problem with SQL. I need to look at the test first, to see if there are any flaws in it.

It's not a problem with SQL. It is problem with database initiation as reported in the stack trace.

**Comment by k-rus** [comment] 2015-05-06 15:12
The bug is fixed and the test succeeds.
However, the test has problem that it continue execution after the first failure with exception. This behaviour caused some lost time in investigation of the actual problem. This needs to be fixed. Thus I assign this issue to @alemoi as I guess he is the owner of the test.

**Comment by dan31** [comment] 2015-05-07 10:10
So it should be fixed in develop as well?

**Comment by parherman** [comment] 2015-05-07 10:27
The test should be fixed in both develop and next, it __might__ be that NodeTest.exe exited with a negative Exit code, and in the bat files we only check if exit code is grater the 0 with IF ERRORLEVEL 1 GOTO TESTFAILED

@alemoi wants to use something else then bat fails for test, because it can be hard to catch issues like this and I agree. Python is one suggestion but while I personally like python I think its not so good that we need to add a new dependency on it. Other alternatives are C# and possibly CMake. Some Polyjuice tests runs Node/js also.

**Closed** 2016-03-23 14:53 UTC
Labels: bug, in-progress, Infrastructure, test
