### ISSUE TITLE
Performance issues on 2.3

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Starcounter#4096] opened 2017-02-20 12:34 UTC
I tried upgrading to 2.3 today, but noticed that my code is running way slower than on 2.2. I wonder if its something wrong with my codebase or the Starcounter version.

The two images below show the performance issue, measured in milliseconds. On 2.2 (lower) my code usually takes less than 1 millisecond. The code does:

1. Parse some JSON
2. Write to the log
3. Get some database objects (bids)
4. Handle these objects
5. Write to the log again
6. Sends a response over UDP. 

These steps have corresponding log statements in the images below. As you can see, all steps take way longer on 2.3 (around 130 ms). Any ideas on how to fix this? I'm happy to set up a hangout if it's of any help.

![2 3](https://cloud.githubusercontent.com/assets/16880339/23125125/8e875b34-f770-11e6-9721-f8047c6e398d.jpg)
![2 2](https://cloud.githubusercontent.com/assets/16880339/23125126/8eac08e4-f770-11e6-8a6d-19fccc7bd502.jpg)

**Comment by erikvk** [comment] 2017-02-20 12:36
I tried 2.3.0.5701, 2.3.0.5705 and 2.3.0.5726 – all with the same results.

**Comment by k-rus** [comment] 2017-02-20 12:50
cc @chrhol 

Can it be due to the changes that transactions are asynchronous behind, which requires to adopt application code to perform better?

**Comment by dan31** [comment] 2017-02-20 12:50
@erikvk this is most likely due to an improvement in durability in 2.3, which might require to adopt code which employs certain patterns.
@bigwad please have a look.

**Comment by bigwad** [comment] 2017-02-20 13:11
@erikvk, do you have any write transactions in the execution path you measure?

If so, please checkout about changes we made to Db.Transact:
`The Db.TransactAsync function` section at https://docs.starcounter.io/guides/transactions/
and `Synchronous vs Asynchronous transactions` at https://docs.starcounter.io/guides/transactions/more-on-transactions/

**Comment by dan31** [comment] 2017-02-20 13:31
@bigwad @erikvk I fix the link, as it should point to an "RC" version of the docs: https://docs.starcounter.io/v/RC/guides/transactions/more-on-transactions/. @bigwad's link points to current stable (2.2.1) and it does not contain the new knowledge.

**Comment by bigwad** [comment] 2017-02-20 13:43
@dan31, actually I checked the links and they worked for me. Probably, it's due to https://github.com/Starcounter/TechComm/issues/290

**Comment by erikvk** [comment] 2017-02-20 13:47
Does this mean, in general, that 2.2-esque Db.Transact() code should be avoided on 2.3?

**Comment by bigwad** [comment] 2017-02-20 14:05
Yes and no. Started from 2.3 it should be avoided like any other synchronous blocking call if an application could benefit from asynchronous.

**Comment by dan31** [comment] 2017-02-20 16:41
@erikvk by default ```Db.Transact``` calls are made syncronous in 2.3, which means that in certain patterns it will be slower than before. We keep the same API and recommend all users to use ```Db.Transact```. In case of short transactions in concurrent environment (with many simultaneous requests processed at a time) the effect of syncronous call is not visible. It becomes visible on high write bursts from a single client, where it might become slow. It is strongly recommended to stick to ```Db.Transact``` unless one really knows how to benefit from ```Db.TransactAsync```.

**Comment by erikvk** [comment] 2017-02-20 16:45
>130X slower seems a bit much though. Any other ideas on what could be causing this?

**Comment by dan31** [comment] 2017-02-20 16:48
@erikvk could you explain your pattern more? How much writes there really are? It might well be that your code needs to be adjusted to the async fashion.

**Comment by dan31** [comment] 2017-02-20 16:54
@bigwad I believe our current doc https://docs.starcounter.io/v/RC/guides/transactions/more-on-transactions/ actually lacks this example with ```.WaitAll```. I expect it to appear here, actually, as an answer to @erikvk question. But let's see.

**Comment by erikvk** [comment] 2017-02-20 16:58
Sure, let's look at the first step, Parse:

All database inserts occur within a single transaction scope.

![screen shot 2017-02-20 at 17 56 02](https://cloud.githubusercontent.com/assets/16880339/23134645/e5ebb4b8-f795-11e6-9496-891b9cb79c37.jpg)

BidRequest.ctor:

![screen shot 2017-02-20 at 17 56 41](https://cloud.githubusercontent.com/assets/16880339/23134670/f68d05b0-f795-11e6-965e-4a8c8b52d298.jpg)

A typical .ToDbX() method:

![screen shot 2017-02-20 at 17 57 42](https://cloud.githubusercontent.com/assets/16880339/23134720/1c95e772-f796-11e6-91f3-0a422857c8cd.jpg)

**Comment by erikvk** [comment] 2017-02-20 16:58
That takes 30 ms to perform on 2.3. 0 ms on 2.2.

**Comment by dan31** [comment] 2017-02-20 18:23
@erikvk thanks for sharing! Let's make sure we are looking to the right direction. If you subs ```.Transact``` with ```.TransactAsync``` (fire and forget), what happens to timings?

**Comment by erikvk** [comment] 2017-02-20 21:26
I'll make sure to try that the next time I upgrade to 2.3 – perhaps next week. Had to go back to 2.2 for the time being. I'll let you know how it goes.

**Comment by bigwad** [comment] 2017-02-21 09:28
@dan31, actually `WaitAll()` is mentioned at https://docs.starcounter.io/v/RC/guides/transactions/more-on-transactions/.  Though I don't it's right in general. Neither in this case. After all `WaitAll()` is a blocking call and the right way to make **high-throughput** app is to avoid blocking calls. The right way is to send response in the continuation scheduled with `ContinueWith()` or similar.
Please note bolded **high-throughput** term. With all this asynchrony we can't speed up single transaction. Single transaction response is physically limited by the hardware. What we do is improving overall throughput.

**Comment by dan31** [comment] 2017-02-23 15:26
@erikvk do you think we can have a hangouts call sometime next week to better understand your code pattern before you move on to test 2.3 again?

**Comment by erikvk** [comment] 2017-02-23 15:33
Sure, just go ahead and invite me whenever it works best for you. I'm probably available :)

**Comment by erikvk** [comment] 2017-03-04 18:11
Update:

I have substituted Db.TransactAsync() for all occurances of Db.Transact() in the code, moving from 2.2 to 2.3. Dan was with me when I did this, and we saw the response time drop significantly from previous 2.3 tests. It was, however, not as fast as 2.2, running the same tests.

2.2 performed the tasks faster than 1 millisecond
2.3 performed the tasks in about 2-3 milliseconds.

![screen shot 2017-03-04 at 19 07 23](https://cloud.githubusercontent.com/assets/16880339/23581073/d6ecf00e-010d-11e7-8059-578e2104f537.jpg)

**Comment by dan31** [comment] 2017-03-04 22:54
@erikvk: thanks for sharing, @bigwad is currently investigating the potential source of this observation. @erikvk just out of curiosity: what happens if you run the same app in "Release" mode?

**Comment by bigwad** [comment] 2017-03-06 14:42
@erikvk, 
unfortunately, I can't reproduce such delay with my tests, so I kindly ask you to collect performance profile of your test system.

Prerequisite: install windows performance toolkit.

How to collect performance profile:
1. start your app
2. start simulating user activity
3. start command shell as administrator
4. start performance profile collection with the command **"%ProgramFiles(x86)%\windows kits\10\windows performance toolkit\wpr.exe" -start GeneralProfile**.
 The command assumes windows performance toolkit is installed into %ProgramFiles(x86)%\windows kits\10\windows performance toolkit
5. wait about 1 minute
6. stop collection with the command **"%ProgramFiles(x86)%\windows kits\10\windows performance toolkit\wpr.exe" -stop \<filename\>**, where *filename* is name of file to store data.
7. wpr will create file named \<filename\> and the folder named \<filename\>.NGENPDB. Send both to us.

Please repeat above steps for both 2.2 and 2.3

Don't hesitate to ask any questions.

**Comment by erikvk** [comment] 2017-03-06 22:23
@dan31 Do you have the profiling data needed?

**Comment by dan31** [comment] 2017-03-06 23:26
@erikvk: @bigwad recommends an enhanced way of taking profiling data. It should give him a lot more insight into what is happening, comparing to the VS perf snapshot we've prepared last Friday. Hence, if it is not too difficult for you, could you please re-do our experiment but now taking the measurements in a way @bigwad recommends? Preferably for both 2.2 and 2.3, as we did too.

**Comment by erikvk** [comment] 2017-03-06 23:32
OK, sure

**Comment by dan31** [comment] 2017-03-06 23:53
@erikvk thanks a lot! Drop a link to your results over e-mail (I guess the output will not be small).

**Comment by erikvk** [comment] 2017-03-07 22:47
I have completed the performance profile for 2.3, available [here](https://1drv.ms/f/s!AkMzDM6Effk89ik8vBK43RiIMQTh). I will update that same directory with a 2.2 folder as soon as I get some time to downgrade

**Comment by erikvk** [comment] 2017-03-07 23:32
The 2.2 folder is uploading right now. I figured a good solution was to downgrade tonight and run the performance profiler, and let you guys check it out tomorrow before I upgrade back again – just in case I need to rerun something on 2.2.

**Comment by bigwad** [comment] 2017-03-08 15:36
@erikvk, thanks for the dumps. 
On the positive side, dumps you provided gave a lot of information, although they miss symbol in some stack traces. I'm not sure why. Probably it's due to virtualization.

On the negative side, nothing in the dumps shows significant delay of 2.3 comparing to 2.2
Do you have starcounter logs of these runs, where I can see delays?

PS.
Seems there was no purpose bothering you with installing windows performance toolkit since wpr.exe is shipped with Windows 10 out of the box.

**Comment by bigwad** [comment] 2017-03-10 13:47
@erikvk, any chance to get those logs I mentioned?

**Comment by erikvk** [comment] 2017-03-10 13:49
Oh, sorry – i forgot to answer. I don't have any logs from for the test runs.

**Comment by bigwad** [comment] 2017-03-10 14:02
Ok, then probably it's better for me to investigate it in your lab or set it up in my lab.
Probably, the former is better as I'm not 100% sure we'll be able to reproduce it on my side.

What do you think?

**Comment by erikvk** [comment] 2017-03-10 14:11
Well, if you can't find anything, maybe we should interpret that as there not being a (critical) problem to fix. I think Dan has a video where we shift between sc versions and see differences in the logs – but who knows how reliable those logs are? In any case – this is not a big problem for us since we managed to improve speeds using TransactAsync.

**Comment by dan31** [comment] 2017-03-15 21:05
Let's close this issue by now. However, it is very curious why there is a consistent difference in the profiling.

**Closed by dan31** 2017-03-15 21:05 UTC
Labels: enhancement, Knowledge base
