### ISSUE TITLE
Creating database Default failed

### ISSUE THREAD

**Issue by bazemaze** [Starcounter/Starcounter#4051] opened 2017-01-19 13:22 UTC
I'm using Windows 7 64x, Visual Studio Community 2015 v14.0.25431.01 Update 3 and Starcounter v2.4.0.661. See image for error message.

![vsproblem3](https://cloud.githubusercontent.com/assets/7026982/22108179/1bef3ccc-de52-11e6-8aa1-54fd99d57249.png)

**Comment by miyconst** [comment] 2017-01-19 13:28
@bazemaze thank you for reporting. I think this is a known issue after installing a newer Starcounter version which is not compatible with the previously installed.

Please try to:

- Uninstall Starcounter.
- Remove Starcounter documents folder.
- Install Starcounter again.
- Try to create database again.

**Comment by miyconst** [comment] 2017-01-19 13:30
Looks like a duplicate of - [pnext: `Personal.server.config` is not updated when upgrading Starcounter versions](https://github.com/Starcounter/Starcounter/issues/3343).

**Closed** 2017-01-19 13:32 UTC
Labels: duplicate

**Comment by per-samuelsson** [comment] 2017-01-19 14:41
@bazemaze 

Sorry to see you suffering from this. It's something we know about that we aim to fix.

The approach @miyconst describe will work, but it might be easier for you to do this instead:

1. Open a prompt and run `staradmin kill all`
2. Then open the file `Personal.server.config`. If you have installed using defaults, it will be under `C:\Users\[yourname]\Documents\Starcounter\Personal\
3. In that file, locate the value of the `<CollationFile>` attribute, change it from **TurboText_en-GB_3.dll** to **TurboText_en-GB_4.dll**

After that, you should be good to go (and the server will restart on demand the next time you do whatever it was you did before).
