### ISSUE TITLE
Cannot restart an app from Visual Studio when 3 apps are running

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#3460] opened 2016-03-24 12:45 UTC
This started to happen to me today, using Starcounter 2.1.1527 and apps: Launcher, Procurement, People (all master branches). It is 100% reproducable.

Steps to reproduce:

1. Start Launcher in VS (F5) and then immediately stop
2. Start Procurement in VS (F5) and then immediately stop
3. Start People in VS (F5) and then immediately stop
4. Start Launcher in VS (F5). This fails with the following error in VS:

```
Severity	Code	Description	Project	File	Line
Error		Unable to attach the debugger to the database process because the database process was not found. Database "default" in process 4876. (ScErrDebugNoDbProcess (SCERR12015))

(Double-click here for additional help)			0
```

Administator log shows an additional exception: 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Starcounter.Hosting.PrivateAssemblyStore.RegisterApplicationDirectory(DirectoryInfo dir) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-229\Level1\src\Hosting\Starcounter.Hosting\PrivateAssemblyStore.cs:line 54
   at StarcounterInternal.Hosting.Loader.ExecuteApplication(Void* hsched, ApplicationBase appBase, Boolean execEntryPointSynchronously, Stopwatch stopwatch) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-229\Level1\src\Hosting\Starcounter.Hosting\Loader.cs:line 153
   at Starcounter.Bootstrap.Management.ExecutablesHandler.OnPOST(Request request) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-229\Level1\src\Starcounter.Bootstrap\Management\ExecutablesHandler.cs:line 56
HResult=-2147467261
```

![2016-03-24 13_44_42-launcher - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/14017267/a1b7b5f6-f1c6-11e5-8313-7ecc3d2eaffb.png)

**Comment by per-samuelsson** [comment] 2016-03-30 05:55
@warpech 

Sorry for not answering sooner, I've been away for a few days.

I think we've had old cases that are similar to this, and it's not easily solved unfortunately. It's again the problem with how our architecture with a single process (host) with multiple startable/stoppable apps don't fit 100% with how to do custom debug attaching from within the IDE (VS).

I'll take a look to see if I can find any of those related issues first, and then we can eventually discuss it.

**Comment by per-samuelsson** [comment] 2016-03-30 05:57
#3406 is a recent one that could be related.

**Comment by per-samuelsson** [comment] 2016-03-30 06:07
#2494 is also experiencing something similar.

**Comment by per-samuelsson** [comment] 2016-04-11 09:30
@warpech 

I'm trying to reproduce this, but I'm not sure if I'm doing the right thing.

Regarding

> ... then immediately stop

are you doing that from within VS too? Hitting the Stop button?

And are you running all three projects in separate VS instances?

**Comment by miyconst** [comment] 2016-04-11 09:45
Might be related: https://github.com/StarcounterSamples/AppStoreClient/issues/7

**Comment by per-samuelsson** [comment] 2016-04-11 10:54
> Might be related: StarcounterSamples/AppStoreClient#7

Thanks. Might be related, but I'm not sure really. And that one is by design, so it's actually not a bug. Whereas this one clearly is.

**Comment by warpech** [comment] 2016-04-11 15:46
> are you doing that from within VS too? Hitting the Stop button?

Yes

> And are you running all three projects in separate VS instances?

Yes

I have just confirmed that the issue is reproducible with the current versions of the Launcher+Procurement+People and current Starcounter nightly (2.1.1690).

I have made a screen recording: 
https://www.dropbox.com/s/xsb04ytdon1w3em/sc-issue-3460.mp4?dl=0

**Comment by per-samuelsson** [comment] 2016-04-11 16:09
> I have just confirmed that the issue is reproducible with the current versions of the Launcher+Procurement+People and current Starcounter nightly (2.1.1690).

Thats what I tried with earlier today too

> I have made a screen recording:

Wow, thanks. Unfortunately (for me), it's the exact procedure that I tested with on my machine earlier too, and twice. Never saw that thing when I started Launcher the second time. :cry: 

It's clearly a problem, so I'll continue investigating it today and tomorrow, because I really want to find the cause for this one.

**Comment by warpech** [comment] 2016-04-11 16:10
I have made a snapshot of my virtual machine. I can provide more info when needed.

**Comment by per-samuelsson** [comment] 2016-04-12 11:51
Since a few hours back, I have now been able to reproduce this, but only in like 1/10 attempts or so. I also start to get a vague idea of what might be the problem. I'll update again once I have something new to report.

**Comment by per-samuelsson** [comment] 2016-04-13 07:19
@warpech You can drop that snapshot. I've figured out the problem yesterday, and it's non-deterministic, cause by a condition where applications are restarted in sequence and when they are to close in time (causing that error, because some shared structures in the host are not properly guarded).

I'm currently doing a redesign to the code host apps bootstrapper, to make sure apps are not affecting each other when started in concert.

**Comment by warpech** [comment] 2016-04-13 08:30
Great, thanks!

**Comment by per-samuelsson** [comment] 2016-04-13 12:31
So this redesign is now made, and I'm quite happy about how it turned out. Let's hope it can stabilize that part of the host.

Merged and pushed in https://github.com/Starcounter/Starcounter/commit/b8b77f024690064eb6ea1d81f706fa177d35142f.

Going to merge it to **pnext** now.

**Comment by per-samuelsson** [comment] 2016-04-13 13:08
> Going to merge it to pnext now.

Done too.

@warpech, I'm thereby closing this, even though I normally would suggest you do that, since you opened it. Just ping me if you have the time to test it and it still seem to fail.

**Closed by per-samuelsson** 2016-04-13 13:08 UTC
Labels: bug, Management, Visual Studio
