### ISSUE TITLE
Access violation (C0000005) detected

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#3532] opened 2016-04-26 08:03 UTC
Hi! Locally on my dev machine, I get this error in the console after upgrading to 2.2.1872.
```
Launcher -> default (starting database .)                                                                               
[09:59:19, Starcounter (default)]
Access violation (C0000005) detected at ..\..\src\sccoredb\sccoredb\sccoredb.cpp:3169 (Thread 1908).
    00000220F0A2DD0B sccoredb!__add_inheriting_definition_to_base_definitions : schemaapi.cpp (3417)
    00000220F0A30EB7 sccoredb!_commit_create_table : schemaapi.cpp (3334)
    00000220F0A2870F sccoredb!recover_create_table : rcvr_table.cpp (45)
    00000220F0A29570 sccoredb!recovery_manager::end_transaction : rcvr_exec.cpp (94)
    00000220F0A291D1 sccoredb!execute_recovery : rcvr_exec.cpp (180)
    00000220F0A0A2A4 sccoredb!_StoreOpen : datastore.cpp (348)
    00000220F0A20CD2 sccoredb!_Startup : startup.cpp (16)
    00000220F09FC6C1 sccoredb!sccoredb_connect : sccoredb.cpp (3132)
    00007FFD7E34170E <unknown>!
    Endless stackwalk detected.
    An error occured during callstack dump.
```

**Comment by ivarbergman** [comment] 2016-04-26 08:12
In the sc log I get this:

```
2016-04-26 10:10:58	Error	#sc://ivarbergmandaa4/personal	Starcounter.Server.Commands	"ScErrServerCommandFailed (SCERR10011): The operation ""Starting database default."" failed.
Version: 2.2.1872.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011."
2016-04-26 10:10:58	Error	#sc://ivarbergmandaa4/personal	Starcounter.Server.Commands	"Starcounter.DbException: ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation. sccode.exe, PID=3976, Database=default, Exitcode=1069
Version: 2.2.1872.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10007.
   vid Starcounter.Server.DatabaseEngine.WaitUntilCodeHostOnline(Process codeHostProcess, Database database) i C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-289\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseEngine.cs:rad 370
   vid Starcounter.Server.Commands.Processors.StartDatabaseCommandProcessor.<>c__DisplayClass2_0.<Execute>b__3(CommandTask task) i C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-289\Level1\src\Server\Starcounter.Server\Commands\Processors\StartDatabaseCommandProcessor.cs:rad 82
   vid Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) i C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-289\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:rad 484
   vid Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) i C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-289\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:rad 510
   vid Starcounter.Server.Commands.Processors.StartDatabaseCommandProcessor.Execute() i C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-289\Level1\src\Server\Starcounter.Server\Commands\Processors\StartDatabaseCommandProcessor.cs:rad 87
   vid Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) i C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-289\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:rad 300
ErrorCode=10007
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10007
---> System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.2.1872.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
"
2016-04-26 10:10:58	Critical	#sc://ivarbergmandaa4/personal/default	Starcounter	"Access violation (C0000005) detected at ..\..\src\sccoredb\sccoredb\sccoredb.cpp:3169 (Thread 3368).
    000001D37BABDD0B sccoredb!__add_inheriting_definition_to_base_definitions : schemaapi.cpp (3417)
    000001D37BAC0EB7 sccoredb!_commit_create_table : schemaapi.cpp (3334)
    000001D37BAB870F sccoredb!recover_create_table : rcvr_table.cpp (45)
    000001D37BAB9570 sccoredb!recovery_manager::end_transaction : rcvr_exec.cpp (94)
    000001D37BAB91D1 sccoredb!execute_recovery : rcvr_exec.cpp (180)
    000001D37BA9A2A4 sccoredb!_StoreOpen : datastore.cpp (348)
    000001D37BAB0CD2 sccoredb!_Startup : startup.cpp (16)
    000001D37BA8C6C1 sccoredb!sccoredb_connect : sccoredb.cpp (3132)
    00007FFD7E33170E <unknown>!
    Endless stackwalk detected.
    An error occured during callstack dump.

"
```

**Comment by k-rus** [comment] 2016-04-26 09:03
cc @eriohl

**Comment by eriohl** [comment] 2016-04-26 09:39
Could I get access to the database (image files and log files)? Should be easy to reproduce then since it happens during recovery.

**Comment by ivarbergman** [comment] 2016-04-26 10:16
Here is a link to db zip.
http://tunitybuild.cloudapp.net:9999/issue_3532_default.zip

(I have locally reverted to an older backup of my database, and now the database can start.)

**Comment by eriohl** [comment] 2016-04-26 10:56
Great. Thank you. I can reproduce the problem. Investigating now.

You don't happen to have the missing log file (DEFAULT.0000000000.log[.bak])? Maybe in your backup? Don't know if it is needed to find what the problem is yet but it might be useful.

**Comment by ivarbergman** [comment] 2016-04-26 11:33
Bummer! I must have missed that file when building the zip. And unfortunate I did "delete permanently", but I can send you the log file from the latest backup as you suggested. 

http://tunitybuild.cloudapp.net:9999/issue_3532_default.log.zip

**Comment by eriohl** [comment] 2016-04-26 11:47
The problem comes from a corrupted metadata structure. Unfortunately the structure is already invalid when data is loaded from the checkpoint. So it won't be all that easy to figure out why the metadata structure went bad in the first place. Question is also why the original operation succeeded while the recovery of the operation failed.

Would it be possible to get access to the backup that you are running now so I can see if this one also has the bad metadata structure?

**Comment by ivarbergman** [comment] 2016-04-26 11:58
This is the backup I reverted to, that works.

http://tunitybuild.cloudapp.net:9999/intranet_db.zip

(However the database is named `intranet` in this zip. Locally I have renamed the db files to `default`)

**Comment by eriohl** [comment] 2016-04-26 13:02
Thank you. The metadata structure is good in the backup. Running the recovery on top of this checkpoint to see if I can see where the problem originally occurs.

**Comment by eriohl** [comment] 2016-04-26 14:58
I managed to recreate the database from scratch using the logs from the bad database plus the additional first one from recovery and doing so I manage to get it to fail in basically the same way. So this should be fixable with the information we have. A lot of operations to go through however so it might take a bit of time.

**Comment by eriohl** [comment] 2016-04-26 20:07
Resolved. Problem was caused by a bug in updating the definition structure on drop table. Fixed will be included in next nightly build (2.2.1878). Thank you @ivarbergman for all your help. Much appreciated.

(Note that the faulty checkpoint isn't repaired because the bug if fixed.)

**Closed** 2016-04-26 20:07 UTC
Labels: bug

**Comment by k-rus** [comment] 2016-04-27 06:01
@eriohl 
Am I correct that the bug was in the metalayer?
By the way, do we merge develop of Level0 into pnext or we maintain them separately?

**Comment by eriohl** [comment] 2016-04-27 09:11
> Am I correct that the bug was in the metalayer?

It was the definition structure (no replaced with layout). So strictly kernel.

> By the way, do we merge develop of Level0 into pnext or we maintain them separately?

I merge develop into pnext on the rare occassions I update level0 for form. Can't remember when last I didn't just drop the updates however. This change will not affect pnext.
