### ISSUE TITLE
Installer window is behind File explorer window

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1972] opened 2014-05-14 11:12 UTC
I downloaded the latest version of Starcounter, which was created by nightly build. I open file explorer on its location and I double clicked on it. Windows asked me for permission to run the installer. After this the focus is on the file explorer, while the installer window is hidden behind it.

**Comment by warpech** [comment] 2016-01-19 13:26
Closing this as a duplicate of #2453. The other issue has more evidence.

**Closed by warpech** 2016-01-19 13:26 UTC
Labels: Follow-up, Installer, Newbie issues
