### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter:

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#64] opened 2017-03-27 13:08 UTC
@chrhol could you please help me debug this?

```
"Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: "". Path '[28].path', line 1, position 4088.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-4113\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 421
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-4113\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 367
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-4113\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 62
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-4113\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-4113\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 796
LineNumber=1
LinePosition=4088
Path=[28].path
HResult=-2146233088
"
```

It does not point to any line of our code, only Starcounter code.

**Comment by chrhol** [comment] 2017-03-27 14:44
It's most likely caused by the other issue you posted: #65. An incomplete message is received on websocket due to the data being fragmented.

**Comment by chrhol** [comment] 2017-03-27 19:15
I'll close this one, with the assumption that the other issue is the cause.

**Closed by chrhol** 2017-03-27 19:15 UTC
Labels: Question
