### ISSUE TITLE
ScErrTableNotFound (SCERR4230) Needs to report table name

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3295] opened 2016-01-25 13:24 UTC
Currently, having a transaction fail with SCERR4230 is frustrating if the transaction touches more than one table. We really need the message to include the name of the missing table.

Re: https://github.com/Starcounter/Replicator/issues/12

**Comment by linkdata** [comment] 2016-02-24 09:49
Would have made debugging https://github.com/Starcounter/Starcounter/issues/3392 trivial.

**Comment by k-rus** [comment] 2016-02-24 09:53
This has nothing to do with the error itself. Log replicator uses the error code to report the error. It should also create a message with all needed information. The main problem is that it uses `Db.LookupTable`, which is not designed for the replicator purpose.
Replicator also should be fixed to not use SQL error codes.

**Comment by linkdata** [comment] 2016-02-24 10:04
> Log replicator uses the error code to report the error. It should also create a message with all needed information. The main problem is that it uses Db.LookupTable, which is not designed for the replicator purpose.

Did you mean "log reader"? The "replicator" (actually "LogStreamer") neither creates SCERR4230 exceptions not does it use `Db.LookupTable()`.

> Replicator also should be fixed to not use SQL error codes.

Again, not sure if you mean `LogStreamer` (ex replicator) or `TransactionLog` (the log reader).

**Comment by k-rus** [comment] 2016-02-24 10:07
> Log replicator uses the error code to report the error. It should also create a message with all needed information. The main problem is that it uses Db.LookupTable, which is not designed for the replicator purpose.
> Did you mean "log reader"? The "replicator" (actually "LogStreamer") neither creates SCERR4230 exceptions not does it use Db.LookupTable().
> 
> Replicator also should be fixed to not use SQL error codes.
> Again, not sure if you mean LogStreamer (ex replicator) or TransactionLog (the log reader).

Sorry, I have no idea how it is called. Please, correct my text to proper component name. The main point is that the problem is not with the error code, but with the code which uses it. So you can correct the title and the issue.

**Comment by linkdata** [comment] 2016-02-24 10:38
> Sorry, I have no idea how it is called. Please, correct my text to proper component name.

No problem. It can stand as is now that I know what you meant.

> The main point is that the problem is not with the error code, but with the code which uses it.

I'm not so sure. Let me explain.

When we omit the table name from the message, we force **all** code that does database operations to explicitly catch the exception and output diagnostic information somehow, or else end up with a useless "you failed" message.

That seems cruel, given the alternative to simply stick the table name in the message itself.

And figuring out which table that was not found may be quite hard. For instance, `LogStreamer` has to perform queries on the meta-data tables and intersect the results with a set of table names.

And if the exception was thrown because some other code or commit hook failed, it's impossible to do and vital information is lost.

**Comment by linkdata** [comment] 2016-02-24 10:40
Just to clarify: This issue is not about any specific use of the exception. It's about why the exception doesn't contain the table name.

**Comment by k-rus** [comment] 2016-02-24 10:45
> When we omit the table name from the message, we force all code that does database operations to explicitly catch the exception and output diagnostic information somehow, or else end up with a useless "you failed" message.

What do you mean by omitting table name from a message? There is only error code with statically connected message in error code xml file. The message has to be created by the creater of the exception. `LogStreamer` (or what appropriate) creates the exception with the error code, but doesn't create any messages with runtime information such as table name.



> Just to clarify: This issue is not about any specific use of the exception. It's about why the exception doesn't contain the table name.

The issue is about specific use of the error code and creating the exception. The exception cannot have table name if you have not created the message with the table name.

[This comment](https://github.com/Starcounter/Starcounter/issues/3392#issuecomment-186121481) by @bigwad says:

>ScErrTableNotFound is thrown by LogApplicator

**Comment by linkdata** [comment] 2016-02-24 10:56
> The issue is about specific use of the error code and creating the exception. The exception cannot have table name if you have not created the message with the table name.

Ok, I think I see what's confusing me here.

Are you saying that you normally get the table name with the exception, but in the particular case of `TransactionLog.LogApplicator`, it's not there. Therefore, it's not a generic problem, but one specific to that assembly.

Is that about right?

**Comment by k-rus** [comment] 2016-02-24 11:22
> Are you saying that you normally get the table name with the exception, but in the particular case of TransactionLog.LogApplicator, it's not there. Therefore, it's not a generic problem, but one specific to that assembly.
> 
> Is that about right?

Not really. There is no exception `SCERR4230`. `SCERR4230` is just an error code (a number) with associated default static message stored in git repo. The thrown exception is just an instance of `Exception` class or its child. It is responsibility of the developer, who uses the error code in the code to create a message with runtime information. I cannot say where else the error code used without inspecting entire Level1 and Level0 source code.

Note that `TransactionLog.LogApplicator` creates the exception. Here its code:

```c#
throw ErrorCode.ToException(Error.SCERRTABLENOTFOUND)
```
As you can see it does not create any messages with the table name, which it is aware of.

You can read the guideline for errors written by @per-samuelsson and placed in `errorcodes.xml`.

**Comment by linkdata** [comment] 2016-02-24 11:33
Thanks for clarifying.

I'll leave this open until @bigwad fixes this in the `TransactionLog.LogApplicator`, as that was indeed my motivation for opening the issue. @bigwad, have a look at what `RuntimeDelegate.cs` does:

`throw ErrorCode.ToException(Error.SCERRTABLENOTFOUND, string.Format("Table: {0}", typeName));`

**Comment by bigwad** [comment] 2016-02-26 18:49
done

**Closed by bigwad** 2016-02-26 18:49 UTC
Labels: ScError
