### ISSUE TITLE
Consider excluding this file by adding a "weaver.ignore" file to your project. (ScErrWeaverFailedStrongNameAsm (SCERR2143))

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3884] opened 2016-10-13 08:23 UTC
### SC Version : 
2.2.2.3422

### How to reproduce the bug : 
1. Open your project in VS (i'm using 2015)
2. Make sure you have some DLLs in your project
3. Clean the solution and run it (it should work fine)
4. Stop the DB
5. Make a tiny change in your code, and build it again (Do not clean this time)
6. Try to run the project again (this time you will have an error related to `weaver.ignore`)

### Reason behind the issue : 
When I build the project without Cleaning it, the weaver.ignore in debug folder is cleaned up, and it will have only `Newtonsoft.Json.dll`.

### When the issue started?
I installed Last Stable build `Starcounter-2.2.1834`, and it does not have this issue.
I installed Latest Stable build `Starcounter-2.2.1.3234` and then Latest nightly build both have the same issue.

**Comment by dan31** [comment] 2016-10-13 08:57
CC @per-samuelsson Pls have a look, appears to be a regression.

**Comment by per-samuelsson** [comment] 2016-10-13 09:05
@atifwaqar 

Thanks for reporting this. 

Based on versions specified that are problematic, I think this relates to recent changes on our part, mainly #3811. It's related in history to #1620.

I'll make sure we take action on this ASAP.

**Comment by per-samuelsson** [comment] 2016-10-13 09:06
@chrhol 

Is #3811 pushed and part of those versions @atifwaqar mention that have this failure?

**Comment by chrhol** [comment] 2016-10-13 09:07
> Is #3811 pushed and part of those versions @atifwaqar mention that have this failure?

No no, I haven't pushed it, and it will not be pushed to current develop.

**Comment by per-samuelsson** [comment] 2016-10-13 09:11
> No no, I haven't pushed it, and it will not be pushed to current develop.

OK, thanks. Then something else that influence this must have been pushed between those versions. Weird. I'll see if I can find what the problem could be.

**Comment by chrhol** [comment] 2016-10-13 09:13
Unless I messed something up really bad, of course, and committed stuff in the wrong branch...

**Comment by per-samuelsson** [comment] 2016-10-13 12:53
I havent had any success reproducing this although I've tried many times and alternatives. I really want to help you @atifwaqar and see what the problem is, because clearly it's something that happens in a certain condition.

The setup I've tried:

1. Create a new Starcounter Application project.
2. Add a reference to `Newtonsoft.Json`, via NuGet.
3. Making sure I'm using both Starcounter and NewtonSoft (see sample code below).
4. Run project (F5). Result: I get recommendation to add a `weaver.ignore`. This is by design.
5. Add a `weaver.ignore` to project, following [Weaver: How to exclude a file from being processed](http://starcounter.io/guides/tools/weaver/#how-to-exclude-a-file-from-being-processed) (see file below).
6. Clean the project.
7. Run the project again (this time it works).
8. Stop database.
9. Modify source code.
10. Run again.

**Program.cs**
```cs
using Newtonsoft.Json;
using Starcounter;
using System;

namespace Issue3884
{
    class Program
    {
        static void Main()
        {
            Console.WriteLine(Application.Current.Name);

            var json = JsonConvert.SerializeObject(new Program());
            Console.WriteLine(json);
        }
    }
}
```

**weaver.ignore**
```
Newtonsoft.Json.dll
```

**Comment by atifwaqar** [comment] 2016-10-13 12:59
@per-samuelsson try adding any dll, other than Newtonsoft.Json.dll

**Comment by per-samuelsson** [comment] 2016-10-13 13:04
> @per-samuelsson try adding any dll, other than Newtonsoft.Json.dll

OK, just a reference to whatever file you mean? The thing is that for the weaver to reject it, it must be strong-named.

**Comment by per-samuelsson** [comment] 2016-10-13 13:19
> @per-samuelsson try adding any dll, other than Newtonsoft.Json.dll

Now I did that too, and made that a strong name assembly.

So the full story is the 10 steps from above, and then

* Create a new Class Library project ("ClassLibraryWithStrongName").
* Made sure "ClassLibraryWithStrongName" is signed when it's built.
* Set my application to reference the "ClassLibraryWithStrongName" project.
* Run (F5). I get an error, saying I should add "ClassLibraryWithStrongName" to weaver.ignore.
* Added ClassLibraryWithStrongName to weaver.ignore
* Run (F5). Works.

Can you provide any additional hints on what I do different from you @atifwaqar?

**Comment by atifwaqar** [comment] 2016-10-13 14:29
@per-samuelsson there is something wrong with my newly created project. Im guessing this is another Bug or may be im not doing something right.

SC version 2.2.2.3422

Here is what I am facing : 
1. Create a new Starcounter Application project.
2. Add a reference to Newtonsoft.Json, via NuGet. and add another dll `Twilio.Api.dll`
3. Making sure I'm using both Starcounter, NewtonSoft and Twilio (see sample code below).
4. Run project (F5). Result: I get recommendation to add a weaver.ignore. 
5. Add a weaver.ignore to project
6. Clean the project.
7. Run the project again. and this is what I see : 
![image](https://cloud.githubusercontent.com/assets/4388707/19352895/de1f1350-9161-11e6-8cf6-de889c871546.png)


No matter how many times I clean and build the solution, the Weaver file is not being created in folder `C:\TestHooks\bin\Debug`

**Comment by atifwaqar** [comment] 2016-10-13 14:40
Case 2 (When I'm working on already created `AdFenix` Project. )

SC version 2.2.2.3422

Here is what I am facing : 
1. I open `AdFenix` project.
2. I have lots of Dlls in this project and all are added in `weaver.ignore`
![image](https://cloud.githubusercontent.com/assets/4388707/19353149/b30bbdb6-9162-11e6-8dea-6af5476fd44e.png)
3. I clean the project 
![image](https://cloud.githubusercontent.com/assets/4388707/19353178/cda52270-9162-11e6-88dd-9e050bd08cb2.png)
4. I Build the project, and i can see this 
![image](https://cloud.githubusercontent.com/assets/4388707/19353227/eca766ec-9162-11e6-9ae5-e22269e050de.png)
5. I verify both `weaver.ignore` files are same. (The one in my solution, and the 2nd one in my build folder `C:\adfenix-backend\src\bin\Debug`)
![image](https://cloud.githubusercontent.com/assets/4388707/19353294/21c6a43c-9163-11e6-8582-786dbdd72291.png)
6. I make a tiny change in my program.cs (just add a space in any line)
7. I Build the solution again (without cleaning it)
8. I verify if both of my files are same, but this time they are not same. 
The file on left side is in my Build folder `C:\adfenix-backend\src\bin\Debug\weaver.ignore`
The file on right is from my project folder `C:\adfenix-backend\src\weaver.ignore`
![image](https://cloud.githubusercontent.com/assets/4388707/19353361/764b0f5c-9163-11e6-9ed9-043cc66d2af6.png)

**Comment by per-samuelsson** [comment] 2016-10-13 16:37
@atifwaqar 

Thanks for the first-class samples!

I'll continue working on this for sure, and won't stop until we've found and solved your problem. I'll let you know of any progress ASAP.

**Comment by per-samuelsson** [comment] 2016-10-13 18:39
@atifwaqar 

Regarding the first case, where the **weaver.ignore** don't end up in the project output directory - could it be that you have forgot to configure it to be copied to the output directory? If you right-click the file in VS and check the value of the "Copy to output directory" - it should be either "Copy if newer" or "Copy always". It's part of [How to exclude a file from being processed](http://starcounter.io/guides/tools/weaver/#how-to-exclude-a-file-from-being-processed).

And for the second case, can you just try these two things so we can rule them out:

1. Set **weaver.ignore** file "Copy to output directory" to "Copy always".
2. Make sure there are no blank lines at the the beginning or end of it (we have a known bug that I will fix ASAP about that: #3712).

Meanwhile, I'll continue check your setup tomorrow to see if I can come up with something else.

**Comment by atifwaqar** [comment] 2016-10-13 22:19
> for the second case, can you just try these two things so we can rule them out:
1. Set weaver.ignore file "Copy to output directory" to "Copy always".
2. Make sure there are no blank lines at the the beginning or end of it.

@per-samuelsson this fixed both of my issues. I had totally forgot about this `Copy to output directory` property. I still dont understand why this problem appeared after latest stable build, because previously `Copy to output directory` was set to `Copy if newer` for my `weaver.ignore` file.

Anyway, Thank you very much for the solution. :)

**Comment by per-samuelsson** [comment] 2016-10-14 05:07
> @per-samuelsson this fixed both of my issues.

Great!

>  I still dont understand why this problem appeared after latest stable build, because previously Copy to output directory was set to Copy if newer for my weaver.ignore file.

That beats me as well. We certainly don't do anything with this setting - it's just an advice from us, not something we will or can enforce.

We know quite a few things seem to have happened in this recent Windows anniversary update, including stuff they fiddle with that affect Visual Studio. Maybe that could have something to do with it, but it's hard to say for sure.

I'll keep this open for a short while still, to spend a little time thinking if we could do anything that makes it easier to help users later on.

Thanks for the patience and all the feedback you have provided. Let us know if there is anything else we could do regarding this to help you.

**Comment by atifwaqar** [comment] 2016-10-14 06:47
@per-samuelsson Its ok with us. 
We have no issue in setting weaver.ignore file "Copy to output directory" to "Copy always".
I think its pointless to spend time in fixing this issue :P So feel free to close this.

**Comment by per-samuelsson** [comment] 2016-10-15 05:07
> I think its pointless to spend time in fixing this issue :P So feel free to close this.

I did spend some time last night thinking about what could be done to improve this, and the only thing I could come up with is to add to the error message a reminder to copy it to the output folder. I'm adding that to 2.3+ at least. 

I'll also mark this "Knowledge base", witch I intend to some day make a FAQ from.

**Closed** 2016-10-15 05:13 UTC
Labels: Knowledge base, usability, Visual Studio, Weaver
