### ISSUE TITLE
Invalid Session.Current treatment

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3798] opened 2016-08-19 18:17 UTC
This issue was originally reported by @atifwaqar at https://github.com/Starcounter/Starcounter/issues/3784.

Now I have made a very simple example in my [Playground](https://github.com/miyconst/Playground/) which reproduces the issue.
- Clone the application.
- Start Playground project.
- Open `http://localhost:8080/playground/child/apple`.
- Quickly click on all links on the page with middle mouse button (opens in new tab).
  - This step should be performed immediately after page load.
- **Look at all new tabs, one of which will contain a title different from passed value in URL.**
- If there is no wrong tabs, repeat the test.

I have no idea where the error happens, the session id on each tab is unique, but somehow a change in one session is propagated into another.

cc @alemoi, @chrhol

**Comment by miyconst** [comment] 2016-08-19 18:34
After some more investigation and logging I found the following:

On middle mouse click Chrome opens a new tab and establishes connection, but does not finish request. As soon as user navigates to a newly opened tab Chrome finishes the request.

Somehow it happens, that the last opened tab (established connection) is treated as the only one.

**Comment by miyconst** [comment] 2016-08-19 18:36
New steps to reproduce:

- Clone the application.
- Start Playground project.
- Open http://localhost:8080/playground/child/apple.
- Click on `Apple` and `Orange` links with middle mouse button (opens in new tab).
- **Focus the first opened tab (`/playground/child/apple`), the title says Orange**.
- You can do the same thing for any other two tabs.

**Comment by miyconst** [comment] 2016-08-19 18:37
This issue is also reproducible in FireFox, so this is not a Chrome issue for sure.

**Comment by miyconst** [comment] 2016-08-19 19:00
Even deeper investigation shows the following:

- User opens page `A`.
- Browser requests page `A`.
- Server creates session `A` and sets cookie `Session = A`.
- Chrome loads HTML and the cookie.
- Open page `B`.
- Browser requests page `B`.
- Server creates session `B` and sets cookie `Session = B`.
- Chrome loads HTML and the cookie.
- User focuses page `A`.
- Chrome starts to execute JavaScript on the page.
- PuppetJs reads the cookie and requests `/__database/cookie_session_id`.
- **At this point the `cookie_session_id` is `B`.**

So, this is more like client side issue, we can't rely on cookies to deliver session id to client from server.

cc @warpech, @tomalec

**Comment by miyconst** [comment] 2016-08-19 20:12
I have made a local fix for the issue which contain the following:

- Update `PartialToStandaloneHtmlProvider` to set `remoteurl` or `<puppet-client>` element.
- Update `puppet-polymer-client` to use `remoteurl` attribute: `remoteUrl: this.remoteUrl || this.getAttribute("remoteUrl")`.
- Update `PuppetDOM` to do not use location set by cookie if the location was set by parameter.

The fix is not pushed to repositories, but available for test in my [Playground](https://github.com/miyconst/Playground/), see the last attached commit.

**Comment by warpech** [comment] 2016-08-20 11:53
Thank you for investigating this.

I'd really love to see a solution that does not require custom generated HTML documents. 

But then additional hit for the HTTP handler on the server would be needed, so the cost is high.

**Comment by miyconst** [comment] 2016-08-20 12:17
What is the solution with additional request?

**Comment by warpech** [comment] 2016-08-22 09:28
Right now, after 1 request to my app's HTTP handler, 2 requests to `/__database` and 1 cookie , we have a session and WS established

Request #1:

```
GET /myapp
Accept: text/html
```

Response #1:

```
Content-Type: text/html
Set-Cookie: Location=/__database/cookie_session_id
<puppet-client>
```

Request #2:

```
GET /__database/cookie_session_id
Accept: application/json
```

Request #3:

```
GET ws://inside.starcounter.com/__database/cookie_session_id
Upgrade: websocket
```

Sometimes I fall to think that Response #1 is cacheable, because the content is the same for every response. 

In reality, it is not completely cacheable, because it needs a regenerated `Set-Cookie` each time.

Your alternative removes the cookie but also keeps Response #1 uncacheable:

Request #1:

```
GET /myapp
Accept: text/html
```

Response #1:

```
Content-Type: text/html
<puppet-client remote-uri="/__database/cookie_session_id">
```

Request #2:

```
GET /__database/cookie_session_id
Accept: application/json
```

Request #3:

```
GET ws://inside.starcounter.com/__database/cookie_session_id
Upgrade: websocket
```

My alternative (below) is different because Response 1 is fully cacheable. But it requires two hits to `/myapp`. @chrhol, @alemoi and @tomalec remember it well, because it used to be like that a while ago.

Request #1:

```
GET /myapp
Accept: text/html
```

Response #1:

```
Content-Type: text/html
<puppet-client>
```

Request #2:

```
GET /myapp
Accept: application/json
```

Response #2:

```
Content-Type: application/json
X-Location: /__database/cookie_session_id
```

Request #3:

```
GET /__database/cookie_session_id
Upgrade: websocket
```

I think that the alternative proposed by you is the least problematic, so let's give it a shot, unless there are some strong objections from anyone?

**Comment by miyconst** [comment] 2016-08-22 13:18
@warpech I don't see a way how could the last proposed solution be implemented.

We need to get view-model to figure out what HTML to return in response to the first request.
**Now, how do we know which view-model to use when the second request comes?**

It would be possible if we would declare two handlers like this:

```cs
Handle.GET("/myapp", "text/html", () => {
    return new FileResponse("/Myapp/viewmodels/IndexPage.html");
});

Handle.GET("/myapp", "application/json", () => {
    return new IndexPage();
});
```

But in this case we would have to completely rethink our client-server workflow and partials implementation.

I also don't like to keep the session id in the HTML, as the response becomes impossible to cache, but this was the only one solution I could come up with to fix the issue and don't do much of rework.

Maybe HTTP PUSH can help us? So the session id will be pushed?

**Comment by warpech** [comment] 2016-08-22 17:33
> Now, how do we know which view-model to use when the second request comes?

We don't. The result of the first request is discarded. The second request creates the new instance of the view-model. This is how it worked for few months in the past. 

I am not advocating it, just presenting it as the only solution that comes to my mind, which has a cacheable first response.

**Comment by miyconst** [comment] 2016-08-22 17:47
Okay, but unfortunately we can't rely on it, as there is no guarantee, that the view-model created in both requests will actual return the same HTML.

**Comment by warpech** [comment] 2016-08-22 17:58
We can change [PartialToStandaloneHtmlProvider](https://github.com/Starcounter/Starcounter/blob/c959d78a43766fa92deccf7bb694e8ea014abcd8/src/Starcounter/Middleware/PartialToStandaloneHtmlProvider.cs) to actually return the HTML document without forwarding the request to the HTTP handler in the app. That would solve it, wouldn't it?

**Comment by miyconst** [comment] 2016-08-22 18:03
No it won't, because the "partial" will still be created, and the HTML will be read from the view-model. And there is no way to guarantee that the HTML been read from the view-model in the first request will be the same as in the view-model created for the second request.

**Comment by warpech** [comment] 2016-08-22 18:22
If we make a change in `PartialToStandaloneHtmlProvider` to be a request filter instead of response filter, it can be like that: 

If the request has `Accept: text/html` mime type, `PartialToStandaloneHtmlProvider` returns implicit HTML without forwarding the request to the app. If the request has some other mime type (`Accept: application/json`), it passes through this middleware. The app handler will then be only hit once.

**Comment by miyconst** [comment] 2016-08-22 19:50
Sorry @warpech, but I really don't see how it can work. The name `PartialToStandaloneHtmlProvider` itself means that it converts a partial to HTML. The partial is not available in the request filter, as the app has not yet received the request and has not yet created the partial.

What partial or more precise what HTML will be returned in this request filter?

**Comment by warpech** [comment] 2016-08-23 17:19
Commit is worth a thousand words: https://github.com/StarcounterSamples/HelloWorld/commit/49a8e95323b4f271de71de8647f44d3ff278444f

The example linked above uses `PuppetJsProvider`, which implements the idea explained in https://gist.github.com/warpech/422b553d95d47f3dee6da8fa0c85178f

It does not use `HtmlFromJsonProvider` nor `PartialToStandaloneHtmlProvider` and is much simpler than these middlewares.

Please let me know if this makes sense to you.

cc @per-samuelsson

**Comment by miyconst** [comment] 2016-08-23 17:31
@warpech this does make sense for me, and thank you for the example, because I thought that you want to read the `.Html` property of a partial somehow in the middleware.

Also, I like the `PuppetJsProvider` over `HtmlFromJsonProvider` + `PartialToStandaloneHtmlProvider` even if the two would not have any issues.

**Comment by miyconst** [comment] 2016-08-30 08:01
We are being hit by this issue in MM as well. We have to resolve it in either way.

**Comment by miyconst** [comment] 2016-08-30 08:55
I have moved the `Database.Inti()` call from `SignIn` and `QFD` apps into the `Test` project. Available under `/palma/init` handler.

**Comment by warpech** [comment] 2016-09-13 12:08
This issue is stuck and is quite important.

@chrhol, @per-samuelsson do you have an opinion about the solution proposed in https://github.com/Starcounter/Starcounter/issues/3798#issuecomment-241807109 ?

**Comment by atifwaqar** [comment] 2016-09-27 12:20
Hello guys, Any luck with this issue?

**Comment by chrhol** [comment] 2016-09-30 08:20
> This issue is stuck and is quite important.

> @chrhol, @per-samuelsson do you have an opinion about the solution proposed in #3798 (comment) ?

Sorry, totally missed your comment. Good thing you bumped it @atifwaqar. 

Haven't really followed this issue. I'm going to need a little time to read through and test it to give an opinion.

**Comment by chrhol** [comment] 2016-09-30 11:29
I tried to use `PuppetJsProvider` together with Playground, but I'm not sure exactly how it's supposed to work. How can you determine in the request-filter that what the client asks for is actually the standalone page? You only know that when we have the actual response.

**Comment by warpech** [comment] 2016-10-04 15:18
`PuppetJsProvider` assumes that any request with `Accept: text/html` to any of your `Handle.*` asks for a standalone page.

If you don't like that behaviour, you can wrap `PuppetJsProvider` with a conditional middleware.

**Comment by atifwaqar** [comment] 2016-10-25 08:45
Guys, Any luck on this one ?

**Comment by miyconst** [comment] 2016-10-25 09:06
@chrhol, @warpech, this has been marked as `bug` and `High prio` for more than two months, we should solve it in any possible way.

**Comment by chrhol** [comment] 2016-10-25 12:32
I'm having a hard time to grasp this issue, and by that to have an opinion. As I understand, the problem is that when puppetjs reads the sessionid from the cookie, the sessionid sometimes have already been overwritten with another sessionid? And we're trying to do a workaround by hijacking incoming get-requests with a specific mime-type to avoid session being created when the html is returned. Is that correct?

Then I guess it should work, if we make sure that we document the behaviour so that the ones developing the apps are aware of that they have to add their own conditional middleware if some get-request for `text/html` should be let through.

**Comment by dan31** [comment] 2016-11-17 15:01
CC @warpech @chrhol This is currently disturbance for @atifwaqar. Could you address it in the foreseeable time? I guess there is an opened question from @chrhol to @warpech in the last comment.

**Comment by miyconst** [comment] 2016-11-17 15:04
@chrhol please read my [comment](https://github.com/Starcounter/Starcounter/issues/3798#issuecomment-241105968), it should be clear what is happening, and why it is an error.

**Comment by warpech** [comment] 2016-11-24 09:27
As commented in this thread, my solution (https://github.com/Starcounter/Starcounter/issues/3798#issuecomment-241807109) has two significant drawbacks:

1. Every PuppetJs initialization will result in 2 calls to the GET handlers (`text/html` and `application/json`). The first result is only needed to determine the HTML. The session and view-model created for he first request will be ditched.
2. Developers will have to add their own conditional middleware is they want some `text/html` request to be let through.

I will think of alternative solution that hardcodes session ID in the main HTML on the fly.

**Comment by warpech** [comment] 2016-11-24 10:20
**Alternative, more obvious solution:** Middleware provides Session URL as part of the Standalone HTML. See the code: https://github.com/StarcounterSamples/HelloWorld/commit/8a52c8ee17de46c74fe6fdaf8f8593ba3562e604

The above code will only work if we remove the selected code from puppet-dom: https://github.com/PuppetJs/PuppetJs/blob/d939cb38bc49561ac30f3801247b349f90f8f3d1/src/puppet-dom.js#L31-37

@miyconst any idea why the code is there? It was added by you ([https://github.com/PuppetJs/PuppetJs/commit/180630987dff8812ccc43eb1e95108f601b50cb4]) with no reference to an issue.

cc @chrhol, @tomalec please share your thoughts if we can apply it. If you agree, then we can actually deprecate Location cookie.

**Comment by miyconst** [comment] 2016-11-24 10:29
>@miyconst any idea why the code is there? It was added by you 

As I remember, it was a discussion between me, @warpech, and @tomalec, where it was decided to get the remote location from the cookies with higher priority.

**Comment by tomalec** [comment] 2016-11-24 15:37
I would vote for https://github.com/Starcounter/Starcounter/issues/3798#issuecomment-241807109

I would only change https://github.com/StarcounterSamples/HelloWorld/commit/49a8e95323b4f271de71de8647f44d3ff278444f#diff-87c09a2539c61810ea5c8adeb5f54d09R53 to add check for lack of `SessionId` so the app developers will be able to provide stateful HTML, if they really need.

**Comment by warpech** [comment] 2016-11-24 21:19
Today we have discussed with @tomalec that the solution from https://github.com/StarcounterSamples/HelloWorld/tree/puppetjsprovider-middleware is the cleanest. 

So here's a proposed plan if you all agree:

1. @chrhol takes `PuppetJsProvider.cs` from https://github.com/StarcounterSamples/HelloWorld/tree/puppetjsprovider-middleware and adds it into middleware included in Starcounter (need to change namespace to `Starcounter`).
2. @miyconst reverts https://github.com/PuppetJs/PuppetJs/commit/180630987dff8812ccc43eb1e95108f601b50cb4 and releases a new version of PuppetJs, includes that in Starcounter. Notes:
   - Right now, the URL proided in `remote-url` attribute/`remoteUrl` parameter must have priority over the cookie. 
   - Add information that Location cookie is deprecated and will be removed in future versions of   PuppetJs.

**Comment by chrhol** [comment] 2016-11-25 06:51
Alright, then we have finally reached a decision for this issue :smile_cat: I will move the middleware first thing when I start working today (still trying to wake up...).

**Comment by warpech** [comment] 2016-11-25 08:13
I have just added one note to https://github.com/StarcounterSamples/HelloWorld/blob/puppetjsprovider-middleware/PuppetJsProvider.cs comment in the top of the file: `PuppetJsProvider` does not return the desired HTTP status (always 200).

On the other hand https://github.com/StarcounterSamples/HelloWorld/blob/PartialToStandaloneHtmlProviderWithSessionUrl/PartialToStandaloneHtmlProvider.cs returns the desired HTTP status.

Do you find this to be a big constraint?

**Comment by chrhol** [comment] 2016-11-25 08:14
Pushed to pnext now.

@warpech: I see that you updated some comments in PuppetJsProvider.cs in your test project. These changes are not included in Starcounter since I already pushed the code earlier (waited for a personal build). Should I update it?

**Comment by warpech** [comment] 2016-11-25 08:17
Yes please, I tried to clarify something that occurred to my while I was sleeping :)

**Comment by miyconst** [comment] 2016-11-25 09:04
>@miyconst reverts PuppetJs/PuppetJs@1806309 and releases a new version of PuppetJs, includes that in Starcounter.

I am not sure I will be able to do it in time. I am offline today, and will have to take some off days next week.

**Comment by warpech** [comment] 2016-11-25 09:11
>I am not sure I will be able to do it in time. I am offline today, and will have to take some off days next week. 

I can do that if you agree that this is desired.

----

@miyconst, @tomalec WDYT about the tradeoffs explained in https://github.com/Starcounter/Starcounter/issues/3798#issuecomment-262902031? To wrap up:

- https://github.com/StarcounterSamples/HelloWorld/blob/puppetjsprovider-middleware/PuppetJsProvider.cs has fixed HTTP status (always 200) but is cacheable
- https://github.com/StarcounterSamples/HelloWorld/blob/PartialToStandaloneHtmlProviderWithSessionUrl/PartialToStandaloneHtmlProvider.cs has the correct HTTP status but is not cacheable

I think that having the correct HTTP status is more important than being cacheable.

**Comment by warpech** [comment] 2016-11-28 11:16
Today on the app team bi-weekly meeting I will present the solution https://github.com/StarcounterSamples/HelloWorld/blob/PartialToStandaloneHtmlProviderWithSessionUrl/PartialToStandaloneHtmlProvider.cs to the team. In case there are no comments, I will ask @chrhol to merge.

**Comment by warpech** [comment] 2016-11-28 11:23
This will require to remove setting the `Location` cookie in Starcounter. @chrhol or @alemoi could you pls do that in a feature branch?

**Comment by chrhol** [comment] 2016-11-28 11:28
> This will require to remove setting the Location cookie in Starcounter. @chrhol or @alemoi could you pls do that in a feature branch?

You mean right away so you can get a version with this included? Or do this together with merging the middleware?

**Comment by miyconst** [comment] 2016-11-28 12:19
>... has the correct HTTP status but is not cacheable

I also think, this is more important, but we would have to think up a way how to get it work and still be cacheable.

**Comment by warpech** [comment] 2016-11-28 12:29
> You mean right away so you can get a version with this included? Or do this together with merging the middleware?

Together with merging of the middleware. Let's make a 3798-related feature branch. It will contain:

- middleware changes (@warpech, then @chrhol)
- removal of the Location cookie (@chrhol)
- client side changes in PuppetJs (@warpech, code reviewed by @tomalec)

**Comment by chrhol** [comment] 2016-11-28 17:53
> removal of the Location cookie (@chrhol)

I'm not really sure what to remove here. Is it only `Set-Cookie: Location=x`? There is also some setting on the session, `session.UseSessionCookie` that sets another `Set-Cookie` (instead of location): `Set-Cookie: ScSessionCookie=sessionId` that is set instead of location if enabled.

**Comment by chrhol** [comment] 2016-11-29 06:44
The changes are in branch `issue/3798` (for pnext). I didn't touch the other setting (`UseSessionCookie`). Should I start and upload a daily build with these changes or do you build locally?

**Comment by warpech** [comment] 2016-11-29 09:05
I think that `UseSessionCookie` should be removed as well. @alemoi do you agree?

**Comment by warpech** [comment] 2016-12-02 14:41
PuppetJs will not be aware of cookies at all after #3798, so I think `UseSessionCookie` becomes useless.

That said, we still need a universal mechanism to tell a non default client "dude, your session is available at such URL". We should re-introduce some sort of `X-Location` header.

 So maybe let's change `UseSessionCookie` to:

- `bool UseSessionHeader` (default true)
- `string SessionHeaderName` (default "X-Location")

**Comment by chrhol** [comment] 2016-12-02 14:51
> So maybe let's change UseSessionCookie to:

Sounds good. I will make these changes then in both develop and pnext.

**Comment by chrhol** [comment] 2016-12-02 16:38
Missed to link the commit for adding `UseSessionHeader` and `SessionHeaderName` and making UseSessionCookie obsolete.

For develop (in branch `issue/3798-develop`): 5a5d25ac98e5c0848f2eae9910949b03a3c2cb18
Will merge the latest changes to the branch in pnext (`issue/3789-pnext`) now

**Comment by chrhol** [comment] 2016-12-02 16:48
Alright, so the changes have been done in two branches

`issue/3798-develop`
`issue/3798-pnext`

I have not tested anything at all, other than that it compiles yet, but maybe we can add the needed changes for PuppetJs and try it out after that.

**Comment by warpech** [comment] 2016-12-06 14:33
PuppetJs changes from branch https://github.com/puppetjs/puppetjs/tree/remove-location-cookie are pushed to `issue/3798-develop`.

I have made a build for further (auto and manual) testing: https://scbuildserver/viewType.html?buildTypeId=Starcounter_DevelopNightly&branch_Starcounter=issue%2F3798-develop&tab=buildTypeStatusDiv

**Comment by warpech** [comment] 2016-12-06 14:51
Good news, the basic tests are passing! I have tested HelloWorld in Chrome, Firefox, Safari and Edge.

There is some problem in Launcher though. I am investigating.

I have noticed that the session header (`X-Location`) is escaped, which I think is wrong:

```txt
HTTP/1.1 200 OK
Server: SC
Content-Type: text/html;charset=utf-8
Date: Tue, 06 Dec 2016 14:41:34 GMT
Cache-Control: no-store
X-Location: %2F__default%2F97E7CFA39C41B52210000010
Content-Length: 912
```

**Comment by warpech** [comment] 2016-12-06 15:22
To release notes:

After this fix, every master HTML template that bootstraps the PuppetJs connection should hardcode the session URI in the HTML (`<puppet-client remote-url="...">` attribute). Otherwise this will cause two requests to the entry URL instead of one request.

**Comment by chrhol** [comment] 2016-12-07 07:32
> The problem is due to the escaped session header (X-Location) value 

Ahh yes, I copied this old code where it was escaped. I will change it to not be escaped.

**Comment by chrhol** [comment] 2016-12-07 07:42
Fixed. 

On another note, I tried to merge everything from develop (since there been some changes there) and got a conflict in bower.js fpr puppetjs. I wasn't sure what the correct way to fix it was so I canceled the merge instead.

**Comment by warpech** [comment] 2016-12-07 07:52
Np., I will merge `develop` > `issue/3798-develop`

**Comment by warpech** [comment] 2016-12-07 07:55
Merged `develop` > `issue/3798-develop`. Triggering a nightly build for testing of the sample apps.

**Comment by warpech** [comment] 2016-12-07 10:46
Fix works in Launcher, thanks @chrhol! I think this can be merged to `develop` and `pnext`.

**Comment by warpech** [comment] 2016-12-07 10:47
Fix works in Launcher, thanks @chrhol! I will make a new release of PuppetJs and then it can be merged to `develop` and `pnext`. I will let you know.

**Comment by warpech** [comment] 2016-12-07 13:56
@chrhol PuppetJs version pushed in `issue/3798-develop`. Ready for merging to `develop` and `pnext`.

**Comment by chrhol** [comment] 2016-12-07 14:00
> @chrhol PuppetJs version pushed in issue/3798-develop. Ready for merging to develop and pnext.

Awesome, I will do it in a few minutes.

**Comment by chrhol** [comment] 2016-12-07 14:30
Merged and pushed to develop and pnext now. 

I guess the documentation at https://starcounter.io/guides/web/sessions/ needs to be updated. How do we handle removed or obsoleted documentation? Separate sections or separate pages or something else?

**Comment by warpech** [comment] 2016-12-07 16:42
> Merged and pushed to develop and pnext now.

Great, thanks!

> I guess the documentation at https://starcounter.io/guides/web/sessions/ needs to be updated. How do we handle removed or obsoleted documentation? Separate sections or separate pages or something else?

We don't handle it yet. In future these should be static pages that are versioned... But we won't get that unless we move away from WordPress.

Right now we handle this by separate sections:

- https://starcounter.io/guides/apps/ontology-mapping/
- https://starcounter.io/guides/json/json-data-binding/

cc @Mackiovello

**Comment by warpech** [comment] 2016-12-07 17:10
Closing as done

**Closed by warpech** 2016-12-07 17:10 UTC
Labels: bug, High prio, Puppets

**Comment by atifwaqar** [comment] 2016-12-09 11:35
@warpech is this fix in SC version 2.3.0.5282?

**Comment by warpech** [comment] 2016-12-09 12:19
No, it is in `2.3.0.5328`/`2.3.0.5331` and higher. See "Develop" and "Staging" channels at http://downloads.starcounter.com/

**Comment by atifwaqar** [comment] 2016-12-09 13:00
It works. Thanks guys for fixing this. :)

**Comment by chrhol** [comment] 2016-12-09 16:09
> It works. Thanks guys for fixing this. :)

Awesome! It only took us around 4 months and 60+ comments 😀

**Comment by atifwaqar** [comment] 2016-12-09 16:58
Its ok. Good thing is that its fixed now. 
And now I can start developing Dashboards that will be exposed to end-users.
