### ISSUE TITLE
Weaver can't handle removed properties when type is removed.

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3184] opened 2015-12-14 12:57 UTC
I have a class looking like this:
```
public class ExampleClass
{
     public MyEnum Property1;
}
public MyEnum
{
   test1,
   test2
}
```
I create a couple of instances of ExampleClass in the DB.
Then I change my Code to:
```
public class ExampleClass
{
}
```
I remove the MyEnum type BUT ALSO removes the property using it. I still get a weaver error
(Concepts.Ring8.Tunity.GanttAccessLevel is the removed enum):
```
"ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 6066.
Arguments=--nocache --maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave ""c:\Projects\Github\SignIn\bin\Debug\SignIn.exe"" --outdir=""C:\Users\David\Documents\Starcounter\Personal\Temp\Default\Default-20150209T090910668\weaver\6441CB423C2BCA45A9438CDCD529EF25C1A8A9BE""
Output:
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.1.656.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> PostSharp.Sdk.CodeModel.BindingException: Cannot find the type 'Concepts.Ring8.Tunity.GanttAccessLevel' in assembly 'Concepts.Ring8.Tunity, Version=1.0.0.0, Culture=neutral'.
   at PostSharp.Sdk.CodeModel.AssemblyEnvelope.GetTypeDefinition(String typeName, BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.TypeRefDeclaration.GetTypeDefinition(BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.TypeRefDeclaration.BelongsToClassification(TypeClassifications typeClassification)
   at Starcounter.Internal.Weaver.ScAnalysisTask.InspectLoadFieldAddress() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 1560
   at Starcounter.Internal.Weaver.ScAnalysisTask.Execute() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 534
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\CodeWeaver.cs:line 316
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\CodeWeaver.cs:line 224
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\Program.cs:line 205
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\Program.cs:line 156
   at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\Program.cs:line 36
   --- End of inner exception stack trace ---A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.1.656.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> PostSharp.Sdk.CodeModel.BindingException: Cannot find the type 'Concepts.Ring8.Tunity.GanttAccessLevel' in assembly 'Concepts.Ring8.Tunity, Version=1.0.0.0, Culture=neutral'.
   at PostSharp.Sdk.CodeModel.AssemblyEnvelope.GetTypeDefinition(String typeName, BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.TypeRefDeclaration.GetTypeDefinition(BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.TypeRefDeclaration.BelongsToClassification(TypeClassifications typeClassification)
   at Starcounter.Internal.Weaver.ScAnalysisTask.InspectLoadFieldAddress() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 1560
   at Starcounter.Internal.Weaver.ScAnalysisTask.Execute() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\Starcounter.Internal.Weaver\ScAnalysisTask.cs:line 534
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\CodeWeaver.cs:line 316
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\CodeWeaver.cs:line 224
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\Program.cs:line 205
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(ApplicationArguments arguments) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\Program.cs:line 156
   at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-106\Level1\src\scweaver\Program.cs:line 36
   --- End of inner exception stack trace ---

Version: 2.1.656.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030."
```

**Comment by malx122** [comment] 2015-12-14 12:59
I actually just renamed both the enum and the property. I know that I should loose the value that way but needed to be done. However, I can't see why the weaver should fail.

**Comment by malx122** [comment] 2015-12-14 13:00
Clearing the cache has been tested without luck!

**Comment by per-samuelsson** [comment] 2015-12-14 21:02
@malx122 

Thanks for reporting this. It looks like a clear bug. What you did or didn't do in terms of creating instances in the database is totally irrelevant. The weaver operate on (the binary) code only, trying to validate and transform it. The weaver has nothing to do with the database data at all.

What you are trying shouldn't be any problem either. I'd say its a standard case. But I guess it has produced some state (i.e. cached artifacts) that makes it fail. Hard to say for sure what without the possibility to run it myself though. 

Can I either do a hangout with you to try to debug it, or could you try zipping the whole \bin folder of the app you are trying to run to see if I can reproduce it?

Also: can you go to the folder where your `.exe` reside (the output of your project, not the temp one we create under the server repository). When in that folder, open a prompt and run `scweaver --nocache [your.exe]` and see how it behaves. Thanks.

**Comment by per-samuelsson** [comment] 2015-12-15 11:15
I talked this through with @malx122 off-tracker, and we suspect there was something situational in that environment, and its not stratightforward to reproduce. Most likely depended on orphaned old artifacts.

I'm closing this. Let us know if you want this reopened @malx122.

**Closed by per-samuelsson** 2015-12-15 11:15 UTC
