### ISSUE TITLE
PushSocketDataToDb Assertion failed

### ISSUE THREAD

**Issue by ivarbergman** [Starcounter/Starcounter#2738] opened 2015-05-28 09:22 UTC
Hi! 

(Using the latest Starcounter-DevelopNightlyBuilds-2.0.3184)

From time to time (after I updated to 2.0.3184). I get the following crash message, both in the Starcounter log and in the error console of VS:

    Error	2	ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated.
    
    (Double-click here for additional help)		0	0	
    Error	1	Process exitcode: 1070
    
    (Double-click here for additional help)		0	0	
    Error	3	Assertion failed (sched_id < num_schedulers_) at OurSources\worker_db_interface.cpp:497 (Data 0).
        000007F8A01D11D3 sccoredbg!_DumpCallstack : callstack-win.cpp (120)
        000007F8A01D114C sccoredbg!do_handle_assertion_failed : assert-win.cpp (77)
        000007F8A01D1039 sccoredbg!handle_assertion_failed : sccoredbg.cpp (29)
        000007F7EB25F5BD scnetworkgateway!starcounter::network::WorkerDbInterface::PushSocketDataToDb : worker_db_interface.cpp (497)
        000007F7EB25B7D1 scnetworkgateway!starcounter::network::GatewayWorker::PushSocketDataToDb : worker.cpp (1966)
        000007F7EB2525D6 scnetworkgateway!starcounter::network::HttpProto::AppsHttpWsProcessData : http_proto.cpp (893)
        000007F7EB25270B scnetworkgateway!starcounter::network::AppsUriProcessData : http_proto.cpp (947)
        000007F7EB2540B6 scnetworkgateway!starcounter::network::RegisteredUri::RunHandlers : http_proto.cpp (140)
        000007F7EB2538A6 scnetworkgateway!starcounter::network::HttpProto::HttpUriDispatcher : http_proto.cpp (666)
        000007F7EB253E0B scnetworkgateway!starcounter::network::OuterUriProcessData : http_proto.cpp (941)
        000007F7EB254706 scnetworkgateway!starcounter::network::PortHandlers::RunHandlers : handlers.cpp (22)
        000007F7EB2341A1 scnetworkgateway!starcounter::network::GatewayWorker::RunReceiveHandlers : worker.hpp (527)
        000007F7EB25CAD8 scnetworkgateway!starcounter::network::GatewayWorker::WorkerRoutine : worker.cpp (1750)
        000007F7EB240E18 scnetworkgateway!starcounter::network::GatewayWorkerRoutine : gateway.cpp (2431)
        000007F8A5B21832 KERNEL32!
        000007F8A7FDD609 ntdll!
    
    
I have not yet found a solid way to reproduce the error. I will update this issue if I find something that could help investigation.

Does the stack trace provide any hint on what the problem could be?

**Comment by alemoi** [comment] 2015-05-28 09:56
Thanks for reporting! The problem is definitely related to recent changes but hard to guess right now. I will investigate!

**Comment by alemoi** [comment] 2015-05-28 12:11
The problem should be fixed via 82a471ffe5ff0d60705f3a99c59cbf5dde8e6e10
Please let us know how it goes!

**Comment by ivarbergman** [comment] 2015-05-29 06:21
Hi! Problem seems to be solve. I have not encountered the error after I upgraded to latest starcounter.
Thx!

**Comment by per-samuelsson** [comment] 2016-04-08 15:07
This specific issue is old and seem resolved. I'm closing it.

**Closed by per-samuelsson** 2016-04-08 15:07 UTC
