### ISSUE TITLE
Staradmin list app does not take --database parameter

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3521] opened 2016-04-20 20:11 UTC
Was trying to use `staradmin --database list app` to list running apps for a certain database but it lists all running apps in all databases totally ignoring the `--database` parameter (And it presents it in a VERY hard form to parse for a GUI admin app)

**Comment by dan31** [comment] 2016-04-20 21:14
Thanks @malx122! CC @per-samuelsson

**Comment by per-samuelsson** [comment] 2016-04-21 05:00
@malx122 

> Was trying to use `staradmin --database list app` to list running apps for a certain database but it lists all running apps in all databases totally ignoring the `--database` parameter.

That's clearly a bug and I can confirm it. Thanks for reporting that.

> And it presents it in a VERY hard form to parse for a GUI admin app

We could of course support additional formats. The single format supported now is intended for users reading the console, not for parsers. We could support a switch to support additional formats. I'll bring that suggestion up internally, to see how to prio it.

**Comment by malx122** [comment] 2016-04-21 06:06
The format is ok for me if the --database parameter work.

**Comment by per-samuelsson** [comment] 2016-06-03 11:53
Done. Pushed and merged to **develop** in https://github.com/Starcounter/Starcounter/commit/bc0163d742926192b1f8823904a158bc78418ebe, and then merged to **pnext**.

And with this, 

```
staradmin list apps
```

will list all running applications across all databases,

```
staradmin -d=default list apps
```

will list all apps running in the default database, and

```
staradmin -d=foo list apps
```

will list all apps running in database "foo".

@malx122, if you find this doesn't work to your satisfaction, please let us know!

**Closed** 2016-06-03 11:54 UTC
Labels: bug, Command-line
