### ISSUE TITLE
Develop nightly build failed on AppHostTest

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3028] opened 2015-11-05 10:37 UTC
See [the log](https://scbuildserver/viewLog.html?tab=buildLog&buildTypeId=Starcounter_DevelopNightly&buildId=31539#_focus=5566):

>[02:49:36][Step 1/1] System.Exception: ScErrInvokeApplicationHost (SCERR2150): Failed to create/invoke the application host. See IApplicationHost documentation on its constraints.
[02:49:36][Step 1/1] Version: 2.1.362.
[02:49:36][Step 1/1] Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2150.
[02:49:36][Step 1/1]    at Starcounter.Hosting.Package.ExecuteHost(Application application) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-66\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 511
[02:49:36][Step 1/1]    at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-66\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 250
[02:49:36][Step 1/1]    at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-66\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 143
[02:49:36][Step 1/1]    at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-66\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
[02:49:36][Step 1/1]    at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-66\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 71
[02:49:36][Step 1/1] HResult=-2146233088
[02:49:36][Step 1/1] HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2150
[02:49:36][Step 1/1] ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[02:49:36][Step 1/1]    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
[02:49:36][Step 1/1]    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
[02:49:36][Step 1/1]    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
[02:49:36][Step 1/1]    at System.Activator.CreateInstance(Type type)
[02:49:36][Step 1/1]    at Starcounter.Hosting.Package.ExecuteHost(Application application) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-66\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 505
[02:49:36][Step 1/1] HResult=-2146232828
[02:49:36][Step 1/1] ---> Starcounter.DbException: ScErrNoTransactionAttached (SCERR4003): Operation must be performed in the context of a valid transaction
[02:49:36][Step 1/1] Version: 2.1.362.
[02:49:36][Step 1/1] Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4003.
[02:49:36][Step 1/1]    at Starcounter.Internal.DbState.Insert(UInt16 tableId, UInt64& oid, UInt64& address) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-66\Level1\src\Starcounter\Internal\DbState.cs:line 118
[02:49:36][Step 1/1]    at TestIApplicationHost.Program..ctor(UInt16 tableId, TypeBinding typeBinding, Initialized dummy)
[02:49:36][Step 1/1]    at TestIApplicationHost.Program..ctor(UInt16 tableId, TypeBinding typeBinding, Uninitialized dummy)
[02:49:36][Step 1/1]    at TestIApplicationHost.Program..ctor()
[02:49:36][Step 1/1] ErrorCode=4003
[02:49:36][Step 1/1] HResult=-2146233088
[02:49:36][Step 1/1] HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4003
[02:49:36][Step 1/1] 
[02:49:36][Step 1/1] 
[02:49:36][Step 1/1] Error: IApplicationHostTest failed!

**Comment by per-samuelsson** [comment] 2015-11-05 12:44
Thanks @k-rus, I can take a look what could have caused this.

**Comment by per-samuelsson** [comment] 2015-11-05 12:54
> I can take a look what could have caused this.

I can see right away what the problem is, its a combination of #3011 and this thing I did to support legacy applications for Heads. Its quite easily fixed, just got to decide on the best way.

**Comment by per-samuelsson** [comment] 2015-11-05 14:07
Resolved, and I've ran the apps tests successfully in a personal build. Merged and pushed in https://github.com/Starcounter/Starcounter/commit/f0f0e8f92b4f3c6dbad11f4af62fa775c4159035.

Comes with a new mini-feature too: transient interfaces. With such, you can define an interface as transient. When applied to a class in a database context (for example when the class is in a database assembly, configured or tagged on assembly level), the class itself becomes transient. Then making the IApplicationHost interface transient fixed the problem.

Not triggering any explicit nightly for this, since its late in the day, and no one really suffers from this problem (except our tests, which are now fixed).

**Closed by per-samuelsson** 2015-11-05 14:07 UTC
Labels: P/SHOWSTOPPER
