### ISSUE TITLE
System.Exception: Written size (###) is larger than estimated size (###)

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3735] opened 2016-07-07 07:29 UTC
I am getting this exception on one of my servers. We dont understand the issue clearly, may be it is related to our code. So just to confirm, i am posting it here. Is this exception SC related or we have to fix our code somehow?

SC Version : 2.2.1.2631 (Jun 28, 2016 5:07:42 AM)

```
System.Exception: Written size (7810) is larger than estimated size (7677)
REQUEST {
URI: /adfenix/api/tracker?url=http://gulasidorna.eniro.se/f/hornbach-bygg-tr%C3%A4dg%C3%A5rdsmarknad:7818302&time=0
HEADERS

}
RESPONSE {
HEADERS
Location: https://www.facebook.com/tr?id=321885497985613&ev=CompanyListingPage&dl=http%3a%2f%2fgulasidorna.eniro.se%2ff%2fhornbach-bygg-tr%c3%a4dg%c3%a5rdsmarknad%3a7818302&rl=&ts=1467795457232&cd[categories]=Trädgårdsmaskiner%2F -redskap Verktyg Byggvaror Trävaror&cd[keywords]=Allmogefönster Jord Inredning Innertak Högtryckstvättar Handtag Grillar Elverktyg Marksten Lärkträ Lås och beslag Lås Laminat Kök Klinkers Järnvaror Takplåt Takpannor Stuprör Snickerier Skärmväggar Väggar Våtrumsfärg VVS-produkter VVS%2F Värme Ventilation Sanitet Virke Verktyg och maskiner Utomhusfärg Utebelysning Trädgårdsverktyg Trädgårdsmöbler Trädgård Tryckimpregnerat trä Trimmers Trappor Takrännor Skruv Sibirisk lärk Regelvirke PVC-produkter Oljefärg Mosaik Dörrar Duschar Båtfärg Byggskivor Bygg och virke Braskaminer Golvvärme Golv Gipsplattor Garageportar Fönsterfärg Fönster Färg och tapet Fasadfärg Bad och VVS Badrum Blandare Badrumstillbehör Arbetskläder Bygg Trä Zoo Byggvaruhus Bygghandel Byggmarknad Bacho Benders Bosch Dala Floda Finja Gardena Grohe Hultafors Weibulls%2F Econova Garden Velux Skil Sika Paroc Nordsjö Mirro Knauf Isover IFÖ IDO Gustavsberg Grabber FM Mattsson Ebeco Casco Black &amp; Decker Miljöcertifierad av FSC%2F Forest Stewardship Council American Express Visa Eurocard Hemleverans Allmoge Diplomat Diplomati Fm Halle Hornbach Kanallisten Lindab Markslöjd Mattsson Stala Kärcher Finsåg Fixertång Flat pensel Fogspruta Fogsvans Frövagn Padda Slagkloss Akryl Alg- och mögeltvätt Alifatnafta Antimossmedel Fogsnöre Fogspackel Folieremsa invändigt / utvändigt Frostskyddsmaterial Fuktspärr Färdig betong Färdigblandad finbetong Fästklammer Fästmassa Väggkakel Väggspackel Växter Ångbromsfolie Ångspärr Fästmassa till blockstenarna Fästskruvar Fönsterbleck Fönsterbrädesskruv med lock Fönstersilikon Förkomprimerad tätningsremsa Förstärkningsprofiler Förzinkad stål som förstärkning 6 mm tjocka GARDENA Pipeline-anslutningsuttag för vatteninmatning GARDENA Pipeline-installationsrör som vattenledning GARDENA Pipeline-vattenuttag med stoppventil GARDENA skruvklämmor för rörfixering GARDENA System-slang GARDENA System-snabbkoppling Gatstensbeläggning Gipsskivor Gipsskruv Gjutform Glasull Golvclips Golvskenor Granitterrassplattor Grindblad Gräsfröblandning Gräsmattegödsel Gummihammare Gummihandskar Gummiskrapa Gångplattor Gångvägsplattor HT-rör (DN 50) till avloppet Hörnförbindningslist Hörnskydd Isolering Järn &amp; metallfärg Kakel Kakellim Kakelram till inspektionslucka Kakelskärare Kakeltång Kantband Kantsten Kantstenar Karmskruv Kartuschpistol Kilar Kiselsten som underbyggnad Kitt Klinkerplattor Klossar/kilar Klämringskopplingar Knäskydd Komposteringsmedel Konsoler Kopparrör Kopplingar Kortlingar Krossad kalksten Krossade stenskärvor Kryss (om man använder murbruk) Kulventiler Kvartssand Köksblandare Köksbänkskiva Lagningsbruk LimLister Liten kakelhammare Ljuddämpningsband Långa spikar Läkt Makadam Maskeringstejp MDF-skiva Metallkarmsplugg Metallprimer Monteringsdetaljer (skruv och plugg eller skruvstift) Monteringskil Monteringslim Monteringsskruvar Monteringsskum Murbruk Målarremsa Målartvätt Möbelvinklar Najtråd Nivålister Non-woven lim Non-woven tapeter Nätspännare Nätstag Ogräsbekämpningsmedel OSB-skiva PE-folie 0 2 mm Penseltvätt Plan PVC-list med läppförsedd Plan PVC-list med tätningsremsa Planteringskorg Planteringssäck Plasthink Pluggar 8 mm Primer Problemlösare Profillister i plast Pump Putsfärg PVC-list vinkel 20x40 mm Pålar Ramprofiler (UW)Reglar Rengöringsmedel för PU Rostfria skruvar med försänkt huvud Rostfritt stål Rostskyddsgrund Rundsnöre för drevning Rörisolering passande till värmerör Rörisoleringstejp Rörmanschetter Sand Sanitärsilikon Sektionsport Silikatfärg Silikatgrund Silikon Silikontätmassa Singel eller annat fyllnadsmaterial Skiljeväggsskivor Skruv samt bricka Skruvar i rostfritt stål Skruvar och plugg Skurblock med handta Slaglina Snabbskruvar Snabbskruvar med borrspets Snickerifärg Snickerigrund Snickerispackel Spackel Sparrvirke Specialgödsel för gräsmattor Spik Spånskiva Spärrfärg Stag Staketelement Staketstolpe Staketvinkelbeslag Sten Stenläggning Stenull Stolphållare Stolpkåpor Stolpspjut Stålreglar Stödhylsor Svamp Sättgrus Sättsand T-/ L-kopplingar eller förbindelse för avgrening T-lister Takfärg Takfönster Takskenor Tandspackel Tapetbårder Tapeter Tapetklister Tapetlim Tapetlösare Tejp Terrassbrädor Terrasskruv Tjärpapp Trallbrädor Trådnätstaket Träskruv Tumstock Tvättställ Tvättställsblandare Täckram Tätmassa Tätning Tätning för dusch Tätningslist Tätningsremsa Underhållsprodukter Underkonstruktion Underlagsfoam Undertaksskydd Utläggningssand Vatten Vattenlås Vattenpass Vertikala profiler CW Vindavledare Vinkelverktyg Vipport Visp VP-rör Våtrumssilikon Väggfärg Avloppsdelar Badkar Badkarsfötter Badkarsstöd i hårdskum Betongplattor Betongskruv Blocksten Blyertspenna Borrmaskin Bottningslist (drevlist) Bruksslev Brädd- och avloppsgarnityr Bräddavloppsventil Brädor Bårdlim Bärande bjälkar Cement Cement/grus (1:6) Dammfolie Dekormaterial Diskbänk Distansklossar Djupgrund Drevmaterial (mineralull Fogskum m.fl.) Dörrkarmar El-dosa Elastikemulsion Fasadtvätt Fastsättningsmaterial Fiberduk Flytspackel Fogbruk Fogkryss Byggskyffel Putsverkyg Putsbruk C Murbruk C Primer membran Självklistrande membran Flytmembran Optidrainskiva Optiwebduk Skyddskappa Topptäcklist Butylmassa Slipkloss Slipmaskin Slippapper Slipsvamp Snöre Snörslå Spackelspade Spade Spanness Spatel Specialsågblad Spetsvinkel Spännremmar Stege Stenborr Sticksåg Stålborste Stållinjal/stålskena Såg Såg (fintandad) Såg för blocksten Sänklod Tapetbord Tapetborste Tapetkniv Tapetkniv med reservblad Tapetlinjal Tapetlod Tapetsax Tapetverktyg Teleskopskaft Termokompostkärl Trasa Tråg Träborr Trädgårdsslang Trädgårdsvält Träkilar Träklossar Träpålar Träribba Träsåg Täckfilt Täckpapp Täckplast Vinkelhake Ytvibrator Bygghink Borr 5 5 mm Borste Papegojtång Penna Pensel Penslar Plasthammare Plastpåsar Plattång Plåtsax Polygrip Pålborr Rep Riktbräda Riktsnöre Roller Rund pensel Röravskärare Silikonpistol Skarvrulle Skiftnyckel Skottkärra Skrapa Skruvdragare Skruvmejsel Skruvnyckel Skruvtving Skumgummirulle Skurblock med handtag Skurborste Skyddsglasögon Skyddsoverall Skyffel Skärunderlag Slagborrmaskin Slagjärn Isoleringskniv Jordborr Järnsåg Kakelborr Kakelsnöre Kanthyvel Karmnyckel Kittpistol Klibbduk Klubba Kniv Kniv (ca 30 cm) Kombitång Kompostkvarn Kompostlåda Kompostsåll Kratta Kryssmejsel Körnare Limroller Markvibrator Metallborr Metallborr 5 mm Metallbygelsåg Metallinjal/avrivare Metallskena Metallsåg Munskydd Murarslev Murarsnöre Murslev Målarvantar Måttband Måttstock Oval pensel Färgroller Färgskrapa Färgtråg Gaffelnyckel 10/13 Geringslåda Glasborr Golvskyddspapp Grep Gräsklippare Grävgrep Halvrundfil Hammare Hammare (tung) Hink HSS-borr/kakelborr Hålsåg Häftapparat Högtrycktvätt Industrirakblad Arbetshandskar Batteridriven skruvdragare Betongblandare Betongpackare Bevattningsanordning Borr (10 mm större än rören) Borr 8 mm Borr för trä/metall/betong Bruksvisp Brytbladskniv Bygel Byggnadsställning Byggpenna Bågfil Cutterkniv Distanshållare DistansklossarDistansklossar i trä Djupgrundningsborste Dosfräs Ersättningsrullar Fasadpenslar Fasadroller Fickkniv Figursåg Filtrulle&cd[city]=ARLÖV&cd[Time]=0
Set-Cookie: uid=8227144699117130611&end;path=/; expires=Fri, 10-Jun-2016 11:58:18 GMT;HttpOnly

COOKIES
uid=8227144699117130611&end;path=/; expires=Fri, 10-Jun-2016 11:58:18 GMT;HttpOnly
}

   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-379\Level1\src\Starcounter.Internal\Http\Response.cs:line 788
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-379\Level1\src\Starcounter.Internal\Http\Request.cs:line 1241
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-379\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 812
HResult=-2146233088
```

**Comment by per-samuelsson** [comment] 2016-07-07 07:42
Might relate to #3608.

cc @chrhol @alemoi

**Comment by chrhol** [comment] 2016-07-07 07:42
Thank you for reporting this and adding the exception output! 

This is definitely a bug in Starcounter, and a quite serious one at that. At first glance, the `Location` header is quite long, maybe we miscalculate something there (especially when it contains å, ä, ö)

I will take a look right away.

**Comment by chrhol** [comment] 2016-07-07 07:58
I did a quick unittest using the same `Location` header as in the exception and got the same problem, the needed size is calculated incorrectly. 

We will work on a fix for this ASAP.

**Comment by atifwaqar** [comment] 2016-07-07 10:28
That would be great. Thanks

**Comment by chrhol** [comment] 2016-07-07 12:24
Pushed a fix to develop and soon pnext that addresses the error in this issue.
Will be available in the next nightly. Maybe it should go into the next planned stable as well @dan31?

And as @per-samuelsson pointed out above, it is likely that the access violation in the other issue is caused by this. I will close the other issue for the time being, and keep this open.

**Comment by atifwaqar** [comment] 2016-07-07 12:30
Thanks @chrhol for the quick fix. 
Should I install the latest nightly build on my live server to test if the code fix works as expected?

**Comment by chrhol** [comment] 2016-07-07 12:37
Well, I think that would be good. I haven't started a new build though, so next nigthly that will have the fix will be available tomorrow.

You're already running quite a new version so hopefully upgrading will not be a problem. Although I guess confirming that it works as it should might take some time, since the original problem doesn't happen that often.

**Comment by atifwaqar** [comment] 2016-07-07 13:23
I cleared the SC logs a couple of hours ago, and now I can see 3 exceptions. So the original problem occurs quite often on one of my server. 
I'll install the latest SC version tomorrow. and hopefully we'll see the result on Monday. Thanks for the quick fix. :)

**Comment by chrhol** [comment] 2016-07-08 06:18
A new nightly build is available now that have this fix. Please let me know how it goes!

Link: http://downloads.starcounter.com/download/Starcounter/DevelopNightlyBuilds/latest

**Comment by atifwaqar** [comment] 2016-07-08 09:02
SC version 2.2.1.2685 also have the same code?

**Comment by chrhol** [comment] 2016-07-08 09:38
> SC version 2.2.1.2685 also have the same code?

No, that version does not include the fix.

**Comment by chrhol** [comment] 2016-07-08 09:38
You want this one: `2.2.1.2697 (Jul 8, 2016 5:06:57 AM)` (or later)

**Comment by atifwaqar** [comment] 2016-07-08 10:28
Installed. 
We'll have to wait for couple of hours or may be a day to see the result.

**Comment by chrhol** [comment] 2016-07-11 07:41
Have you had any chance to see if you got this exception during the weekend, or if it's (finally) been solved?

**Comment by atifwaqar** [comment] 2016-07-11 09:59
Looks like its solved. I cant see this error anymore.

**Comment by chrhol** [comment] 2016-07-11 10:02
Awesome! Then lets consider this issue as resolved :raised_hands:

**Closed by chrhol** 2016-07-11 10:02 UTC
Labels: bug
