### ISSUE TITLE
pnext: When deleting a database, archived transaction logs are not deleted

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter#3642] opened 2016-05-20 15:16 UTC
I would expect the archived transaction logs to be deleted along with the database.

**Comment by bigwad** [comment] 2016-05-20 15:39
Actually, they do. Either using web ui or with staradmin command. What is your way to delete database?

**Comment by linkdata** [comment] 2016-05-20 16:09
staradmin -d=dbname delete db

**Comment by bigwad** [comment] 2016-05-20 16:12
This exact command works for me. Are you sure you run admin server from pnext branch?

**Comment by linkdata** [comment] 2016-05-20 16:16
Daily build from wednesday. Had to manually delete subdirectories of "data"
to clean it up. The staradmin command deleted some of the database files,
but there was still a few gigabytes of stuff in "archive" subfolders.
fre 20 maj 2016 kl. 18:12 skrev bigwad <notifications@github.com>:

**Comment by per-samuelsson** [comment] 2016-05-20 20:45
I think *maybe* this could be caused by something related to changes done in **pnext**.

Or that logs are treated somehow as "temporary" artifacts, and those are not always deleted along with the database, as described by old isses (umbrellad by #1690).

I'll assign it to me to investigate further, and possibly fix.

**Closed** 2016-08-24 12:01 UTC
Labels: bug, Management
