### ISSUE TITLE
Fix the "Cache-control" response header

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#1801] opened 2014-03-31 12:56 UTC
At the moment all http responses has the ```cache-control``` header set to ```public,max-age=31536000```.

We should investigate about using headers like ```ETag```, ```If-None-Match``` and ```If-Modified-Since```.

**Comment by mtornwall** [comment] 2015-12-26 14:42
+1

**Comment by dan31** [comment] 2016-04-19 07:53
Closing this one as a duplicate of #3427 as reported by @warpech.

**Closed by dan31** 2016-04-19 07:53 UTC
Labels: enhancement, HTML, P/Low
