### ISSUE TITLE
Restart of an app stops other running apps

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2608] opened 2015-03-09 14:00 UTC
I have two VisualStudio instances.

Launcher solution in the first instance. It started without debugging (Ctrl + F5).
People solution in another instance.

When I start People solution for the first time, everything works as expected.
But when I restart People solution with (F5) or without (Ctrl + F5) debugging then Launcher solution gets stopped and I have to launch it again.

**Comment by warpech** [comment] 2015-03-10 08:59
This may be similar to case which I had. One Visual Studio solution with multiple projects. Starting a project stops all Starcounter applications in that case.

In case of a single Visual Studio with a single solution + single project, works as expected (stopping/starting a project does not stop other apps running in Starcounter).

**Comment by per-samuelsson** [comment] 2015-03-13 12:30
@miyconst 

Thanks for reporting this. I'm currently trying to understand the case here, to see if it is "by design" or a flaw we can improve on.

Assigning this to me right now.

**Comment by per-samuelsson** [comment] 2015-03-13 12:46
> This may be similar to case which I had. One Visual Studio solution with multiple projects. Starting a project stops all Starcounter applications in that case.

They don't relate 1-1. Your case was different, and fixed.

**Comment by per-samuelsson** [comment] 2015-03-14 09:46
I have found the problem now, and I have an idea how to solve it.

**Comment by alemoi** [comment] 2015-03-15 01:45
:+1:

**Comment by per-samuelsson** [comment] 2015-03-16 05:33
> I have found the problem now, and I have an idea how to solve it.

I think I will be able to push this today. I can't see any real problems with the new design.

**Comment by per-samuelsson** [comment] 2015-03-16 10:41
I think I now have solved this. Its merged and pushed to develop in https://github.com/Starcounter/Starcounter/commit/45002fc1d814d9f33115e16f798de691cd6b3550.

Let me know if there is something that does not work still, @miyconst.

**Closed by per-samuelsson** 2015-03-16 10:41 UTC
Labels: Newbie issues

**Comment by miyconst** [comment] 2015-03-18 10:27
@per-samuelsson, it looks like the issue is solved.
Thank you.
