### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3736] opened 2016-07-07 07:38 UTC
SC Version : 2.2.1.2628 (Jun 27, 2016 5:05:54 AM)

My apps crashed and I can see the following in Logs : 
Type : Critical
Source : Starcounter
Host : Administrator

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Timers.Timer.UpdateTimer()
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
HResult=-2147467261
```
Right after the above exception i got this : 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Timers.Timer.UpdateTimer()
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
HResult=-2147467261
```
Other than the above 2, i can see lots of warnings aswell :
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Timers.Timer.UpdateTimer()
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
HResult=-2147467261
```
This is how it looks in SC Admin Panel's logs :
![image](https://cloud.githubusercontent.com/assets/4388707/16645716/1bd40892-4426-11e6-9bb3-6f14c02e992f.png)

**Comment by chrhol** [comment] 2016-07-08 07:03
Missed this one yesterday. Unfortunately the stacktraces doesn't say that much. 

Do you use any timers in your code? I guess two possible reasons could be (but this is purely a guess :)) that it either is some concurrency issue where a times is stopped or disposed at the same time it's triggered, or that it might be caused by the other reported issue (#3735) where parts of the .Net memory gets corrupted.

Lets start by updating the Starcounter version and see if the other issue is solved and see if you still get this one.

**Comment by chrhol** [comment] 2016-07-11 10:04
Has this one occurred again after we fixed #3735?

**Comment by atifwaqar** [comment] 2016-07-25 10:35
I'm not sure, give me 24 hours to verify it, as i have cleared the logs today. So if I see the error again, i'll update you.

**Comment by chrhol** [comment] 2016-09-30 08:29
@atifwaqar: have you seen this again? Otherwise I will close this issue for now.

**Comment by atifwaqar** [comment] 2016-09-30 10:37
You can close this issue. Thanks.

**Closed** 2016-09-30 10:41 UTC
Labels: bug
