### ISSUE TITLE
Commit hooks on base class

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3503] opened 2016-04-15 06:49 UTC
I know we have talked about this one but can't find an issue.
We need to be able to do commit hooks on a base class and have it called for every derived class as well.

(In our example we have a `Notification` class that is never used directly. Instead there are maybe 20 different classes that is derived from it. It gets impossible for our notification app to listen to them all)

**Comment by malx122** [comment] 2016-04-15 06:52
Hm! while writing this I realize that this might be a totally bad design for the DB since Indexes is not inherited as well...

**Comment by per-samuelsson** [comment] 2016-04-15 07:15
As you point out, we have discussed this before, and hooks are not polymorphic. I've already opened an issue about it last year: #3151.

I'm closing this one in favor of, and as a duplicate of, #3151.

**Closed by per-samuelsson** 2016-04-15 07:15 UTC
Labels: duplicate
