### ISSUE TITLE
Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3358] opened 2016-02-10 15:07 UTC
We are facing the error and then sccode.exe crashes : 

System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 113
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 68
HResult=-2146233033

**Comment by miyconst** [comment] 2016-02-10 15:08
cc @alemoi

**Comment by alemoi** [comment] 2016-02-10 17:57
Hi @atifsheikh ! Thanks for reporting! Do you have any hints on how to reproduce the problem? Any specific changes in your code that could cause this?

**Comment by per-samuelsson** [comment] 2016-02-10 18:19
@atifsheikh 

Anything useful in the [error log](http://starcounter.io/guides/tools/error-log/)?

**Comment by mtornwall** [comment] 2016-02-10 18:28
@atifsheikh The *crash itself* is probably related to #3032 -- see that issue thread for a possible workaround.

**Comment by per-samuelsson** [comment] 2016-02-10 21:25
> @atifsheikh The *crash itself* is probably related to #3032 -- see that issue thread for a possible workaround.

Yeah, sounds like that actually. And then the log is not really meaningful if I remember correctly, since I think one flaw was that errors were not even logged.

About the actual error, it looks like a standard .NET error when working with the .NET [Uri](https://msdn.microsoft.com/en-us/library/z6c2z492(v=VS.100).aspx) type. To get pass that, make sure you only ever assign it a valid URI. (If it's not steming from some API of ours, relying on that type, but I don't think we do often, if at all).

**Comment by per-samuelsson** [comment] 2016-02-10 21:27
> The UriFormatException is thrown by the Uri class constructor if the supplied URI could not be correctly parsed. The format for a valid URI is defined in RFC 2396.

**Comment by per-samuelsson** [comment] 2016-02-12 07:36
@atifsheikh 

Any news on the status of this? Anything we can help you with?

**Comment by atifsheikh** [comment] 2016-02-12 10:38
:+1: This was the issue. Thanks a lot guys.

**Comment by alemoi** [comment] 2016-02-12 11:08
And in what part of Starcounter API did this happen? So we can understand the absence of stack trace.

**Comment by atifsheikh** [comment] 2016-02-15 10:43
Actually the issue is still there, we had the URI issue in part of our code, we fixed the issue with URI format. and it looked like the issue was fixed, and exception/Crashes disappeared for a while, but it looks like the issue is still there. I'll debug my code this week, and update you guys aswell if i find something useful.

**Comment by alemoi** [comment] 2016-02-15 15:09
We would really appreciate if you post the part of Starcounter code that was throwing this exception.

**Closed** 2016-06-03 17:32 UTC

**Comment by atifwaqar** [comment] 2016-06-08 15:07
Sorry for the delayed response.

The code fix was in my code, we were making post/get requests on invalid urls, I modified the code to verify if the string is a valid url or not. So now the code makes the post/get requests only if the string is a valid url.
