### ISSUE TITLE
Administrator log table shows only warnings

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3379] opened 2016-02-17 09:04 UTC
In the latest pnext administrator log page shows only warnings without errors.

![image](https://cloud.githubusercontent.com/assets/6435556/13104481/a749769c-d55d-11e5-951b-0118f21d3004.png)

This is how the same page looks when I disable the Warnings button:

![image](https://cloud.githubusercontent.com/assets/6435556/13104495/c150c0c2-d55d-11e5-85c6-5dd4724b998e.png)

Not sure whether this issue exists in dev branch.

cc @andwah, @warpech

**Comment by per-samuelsson** [comment] 2016-02-17 09:15
I've already reported this. Duplicate of #3307.

**Closed by per-samuelsson** 2016-02-17 09:15 UTC
Labels: Administrator
