### ISSUE TITLE
Db.Transact signature improvments

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3185] opened 2015-12-15 08:00 UTC
Is there any chance of adding a few overrides to Db.Transact so it operates more like Db.Scope?
I mainly refer to the ability to provide arguments to the called function and also using Func to return values
```
public static void Scope(Action action, bool isReadOnly = false);
public static TResult Scope<TResult>(Func<TResult> func, bool isReadOnly = false);
public static void Scope<T>(Action<T> action, T arg, bool isReadOnly = false);
public static TResult Scope<T, TResult>(Func<T, TResult> func, T arg, bool isReadOnly = false);
public static void Scope<T1, T2>(Action<T1, T2> action, T1 arg1, T2 arg2, bool isReadOnly = false);
public static TResult Scope<T1, T2, TResult>(Func<T1, T2, TResult> func, T1 arg1, T2 arg2, bool isReadOnly = false);
public static void Scope<T1, T2, T3>(Action<T1, T2, T3> action, T1 arg1, T2 arg2, T3 arg3, bool isReadOnly = false);
```

**Comment by chrhol** [comment] 2015-12-15 08:04
Duplicate of https://github.com/Starcounter/Starcounter/issues/2822. I will close this one and keep the other one.

**Closed by chrhol** 2015-12-15 08:04 UTC
Labels: duplicate, enhancement
