### ISSUE TITLE
Investigate a potential problem with process shut-down

### ISSUE THREAD

**Issue by dan31** [Starcounter/Starcounter#2246] opened 2014-08-28 10:07 UTC
@malx122 experiences random hangs/shut-offs, Starcounter might be a source of it. The type of problem we haven't experience yet. @malx122, at first point, can you describe the pattern here? At least, time in between SC processes start-up and shut-down, what processes are missing after the shut-down, how do you resurrect from the case.

**Comment by alemoi** [comment] 2015-07-15 17:46
I think this issue was fixed during the last month. Closing.

**Closed by alemoi** 2015-07-15 17:46 UTC
Labels: bug

**Comment by dan31** [comment] 2015-07-15 22:06
@alemoi, what was the related issue number?

**Comment by alemoi** [comment] 2015-07-15 22:11
I'm not sure if @chrhol created an issue related to some problem in JSON serialization because that was the cause of the issue, as I understood. @chrhol what do you think?
