### ISSUE TITLE
Could Db.Transaction delegate have return value?

### ISSUE THREAD

**Issue by niklasbjorkman** [Starcounter/Starcounter#653] opened 2013-07-02 13:15 UTC
Is there a reason why Db.Transaction is always a void?

It seems to generate a lot of boiler-plate code just to return something.
Ideally something like 
   
    return Db.Transaction<IEnumerable<Account>>(() => { return Db.SQL<Account>(“select a from accounta”); });

would be awesome. The IEnumerable<Account> would be inferred, and all it will take is a Transaction<T>(Func<T> func) overload.

**Comment by per-samuelsson** [comment] 2016-04-08 14:29
@chrhol, isn't this an old duplicate of what you recently implemented? Close it if so.

**Comment by chrhol** [comment] 2016-04-08 14:50
Nice catch! It's implemented and I will close it.

**Closed by chrhol** 2016-04-08 14:50 UTC
Labels: /nib, enhancement, question
