### ISSUE TITLE
System.NullReferenceException in StaticWebServer

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2698] opened 2015-05-04 07:59 UTC
Today while playing with Starcounter 2.0.3146.3 and current (master) version of People and Products app, for few times the request froze for a long time. In the log I saw the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Internal.Web.StaticWebServer.GetFileResource(Response cached, String relativeUri, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter.Hypermedia\StaticWebServer.File.cs:line 90
   at Starcounter.Internal.Web.StaticWebServer.GetStaticResponseClone(String relativeUri, Request request) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter.Hypermedia\StaticWebServer.cs:line 131
   at Starcounter.Internal.Web.AppRestServer.ResolveAndPrepareFile(String relativeUri, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 137
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 112
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 318
HResult=-2147467261
```

**Comment by miyconst** [comment] 2015-05-05 08:25
Getting same exception, could not figure out when and how. Most of the time happens after I start two/three apps then change an app and restart it with `Ctrl + F5`.

VisualStudio hangs and I have to kill all sc processes with `staradmin kill all`.

The log entries:

```
"Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. Failed to process query: SELECT * FROM JuicyTiles.JuicyTilesSetup WHERE Key LIKE ?: Unknown class JuicyTiles.JuicyTilesSetup. Unknown property or alias Key. Incorrect arguments of types unknown, any and string to comparison operator like. 
End position: -1

Version: 2.0.3146.3.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 451
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 196
   at Starcounter.Hosting.Package.Process() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 132
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 66
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 436
HResult=-2146232828
---> Starcounter.SqlException: Failed to process query: SELECT * FROM JuicyTiles.JuicyTilesSetup WHERE Key LIKE ?: Unknown class JuicyTiles.JuicyTilesSetup. Unknown property or alias Key. Incorrect arguments of types unknown, any and string to comparison operator like. 
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter\Query\QueryPreparation.cs:line 67
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 123
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter\Mock\Db.cs:line 126
   at Starcounter.Db.SQL(String query, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter\Mock\Db.cs:line 81
   at People.DefaultStyles.ApplyIfEmpty() in e:\GitHub\People\src\People\Helpers\DefaultStyles.cs:line 8
   at People.Program.Main() in e:\GitHub\People\src\People\Program.cs:line 29
ScErrorCode=0
BeginPosition=-1
EndPosition=-1
HResult=-2146233088
"
```

```
"System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Internal.Web.StaticWebServer.GetFileResource(Response cached, String relativeUri, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter.Hypermedia\StaticWebServer.File.cs:line 90
   at Starcounter.Internal.Web.StaticWebServer.GetStaticResponseClone(String relativeUri, Request request) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter.Hypermedia\StaticWebServer.cs:line 131
   at Starcounter.Internal.Web.AppRestServer.ResolveAndPrepareFile(String relativeUri, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 137
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 112
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3146.3\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 318
HResult=-2147467261
"
```

```
Image file writer unable to acquire the SE_MANAGE_VOLUME_NAME privilege.
```

**Comment by k-rus** [comment] 2015-05-05 08:34
@miyconst, thank you for reporting the additional stack trace.
I see two issues:

1. Incorrect behaviour of StaticWebServer in the case of an exception.
2. Actual problem with the old query processor.

It would be nice to be able to reproduce the query processor error. The error is reported by the prolog part, so I guess it is related to the prolog process and/or database schema files. Unfortunately, I cannot say more.

I am wonder what is the source of the query, which looks for me a kind of strange. I can expect that such query is submitted from Administrator, but not from any other codes. And from the stack trace it seems that the query is submitted not from Administrator.

**Comment by miyconst** [comment] 2015-05-05 08:40
The People app sends the query.

Take a look at https://github.com/Polyjuice/People/blob/master/src/People/Helpers/DefaultStyles.cs, the idea is to check, whether db has any styles for People app, and if no styles then insert default values.

I have reproduced same error for five times in a row, I can share my screen if needed.

**Comment by alemoi** [comment] 2015-05-05 08:42
I will investigate the static file server problem! Thank you for reporting.

**Comment by k-rus** [comment] 2015-05-05 08:46
My guess is that `JuicyTiles.JuicyTilesSetup` class is not loaded. How can I reproduce it locally? Can you describe steps to set up the environment and applications?

In general it is a bad practice to do projections such as `select *` instead of selecting objects in Starcounter. It, of course, should work, but it will not perform well.

**Comment by alemoi** [comment] 2015-05-05 08:49
> My guess is that JuicyTiles.JuicyTilesSetup class is not loaded.

Yes, that's probably it. The difference with previous versions is that Launcher now is an independent application that is started separately and that is loading the JuicyTiles class. @k-rus thank you for investigating, I think its on us now.

2 questions:

1. Is JuicyTiles a part of current Launcher or Polyjuice?
2. Why there is a code related to JuicyTiles in People app?

**Comment by miyconst** [comment] 2015-05-05 08:50
My environment:

1. Launcher project under VS 2013.
2. People project under VS 2013.
3. Start Launcher with `Ctrl + F5`.
4. Start People with `Ctrl + F5`.
5. Open browser and do some staff.
6. Change some Launcher code in VS.
7. Restart Launcher with `Ctrl + F5`.
8. VS hangs, three log entries in the admin panel.

I am not sure that the steps 5, 6 are required, currently the exception appears without them, but the first time it was like that.

**Comment by miyconst** [comment] 2015-05-05 08:55
@k-rus, in the query I don't need any any data at all, just need to know are there such rows. `SELECT COUNT(*)` is the fastest way to get rows count in `MS-SQL`, what would be the fastest way for SC?

**Comment by k-rus** [comment] 2015-05-05 09:24
> @k-rus, in the query I don't need any data at all, just need to know are there such rows. SELECT COUNT(*) is the fastest way to get rows count in MS-SQL, what would be the fastest way for SC?

There is no fast way to do row count in Starcounter. Do you need row count or do you need to check if any record exists? (The code, referenced above, does the second)
In any case I suggest always retrieve actual object, which is the cheapest. For example:
```c#
Db.SQL("SELECT j FROM JuicyTiles.JuicyTilesSetup j WHERE Key LIKE ?", "/People/%").First;
Db.SQL("SELECT COUNT(j) FROM JuicyTiles.JuicyTilesSetup j WHERE Key LIKE ?", "/People/%").First;
```
The second query is much more expensive than the first one.

**Comment by miyconst** [comment] 2015-05-05 09:28
@k-rus thank you. I will avoid `*` and all of the sql operators.

What about those two queries:
```sql
Db.SQL("SELECT j FROM JuicyTiles.JuicyTilesSetup j WHERE Key LIKE ?", "/People/%").First;
Db.SQL("SELECT j FROM JuicyTiles.JuicyTilesSetup j WHERE Key LIKE ? FETCH ?", "/People/%", 1).First;
```
Does `FETCH 1` saves some time?

**Comment by k-rus** [comment] 2015-05-05 15:18
> @k-rus thank you. I will avoid * and all of the sql operators.

The main idea is to retrieve objects and then access properties of the object in C# code. I believe this also is easier from programming point of view and gives flexibility in implementation.

> What about those two queries:
> 
> Db.SQL("SELECT j FROM JuicyTiles.JuicyTilesSetup j WHERE Key LIKE ?", "/People/%").First;
> Db.SQL("SELECT j FROM JuicyTiles.JuicyTilesSetup j WHERE Key LIKE ? FETCH ?", "/People/%", 1).First;
> Does FETCH 1 saves some time?

No, I guess it will add additional overhead. Having `.First` is enough, since the execution will retrieve only one object.

**Comment by alemoi** [comment] 2015-05-05 23:04
Static file server error should be fixed via: 6e6d42e74767c0cc1d3ea4197b1ba6b5d8029c43
There is some request with unrecognizable mime type that causes this exception.
I also moved JuicyTiles class definitions (but not handlers) back to Polyjuice project, so the SQL exception should not occur anymore in People application.

**Comment by warpech** [comment] 2015-05-06 10:47
> There is some request with unrecognizable mime type that causes this exception.

Do you know which one?

**Comment by alemoi** [comment] 2015-05-06 12:26
> Do you know which one?

That was `application/font-woff2` for fonts.

**Closed** 2015-05-27 00:32 UTC
