### ISSUE TITLE
Response merging from multiple apps should be always ON

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2861] opened 2015-08-28 12:24 UTC
As part of https://github.com/Starcounter/CompanyTrack/issues/92, we need to turn "Polyjuice" functionality into the core functionality. This includes removing of PolyjuiceDatabaseFlag.

One of the features enabled by the flag nowadays is response merging from multiple apps.

As discussed with @Starcounter-Jack, this should be a default behaviour, not an opt-in behaviour.

In case a `Self.GET` handler must perform an internal (not-mergable/not-namespaced) request, there *could* be a `HandlerOptions` flag for that, but let's not do it as part of this issue. We don't have such use case so far.

**Comment by per-samuelsson** [comment] 2015-08-28 20:20
> One of the features enabled by the flag nowadays is response merging from multiple apps.

It also governs if additional, SO-libraries should be brought in and be part of the schema, no? And if it does, having it always turned "on" (i.e. by removing it), we will surely suffer from a lot more clashes once SO grows and/or more developers join in.

Consider classes like Person, Event, etc. With SO part of any application, doing a `SELECT e FROM Event e` in a smallish application with an Event class will raise an error (ambiguity). Won't it be hard for the developer to understand the cause of that? Or have you guys found some solution to this already?

Maybe we can enhance the binding layer to look for such things. That is, if there is an application-level class X whose short name clash with SO class X, the application define class gets precedence? Querying on just X will assume the application define X, and to query for SO X, the fully qualified name must be used. (Even though I see some problems with this, e.g. that we must consider the context of the query, or else SO classes querying X will hit application defined X, which is very much incorrect). :hammer:

**Comment by k-rus** [comment] 2015-08-29 11:57
> Consider classes like Person, Event, etc. With SO part of any application, doing a SELECT e FROM Event e in a smallish application with an Event class will raise an error (ambiguity). Won't it be hard for the developer to understand the cause of that?

Ambiguity is raised in SQL only if user's `Event` was declared in a namespace. I.e., user needs always specify namespace and cannot omit it, which probably is not big deal for users.

**Comment by dan31** [comment] 2015-08-29 18:36
@k-rus @per-samuelsson Is it possible to change the binding layer in 2.0 so that it resolves ambiguity towards a local model? I.e., ```SELECT e FROM Event e``` will resolve to a local app's Event, if it is present, otherwise – up to the closest in hierarchy through facets/Simplified models/up to SO. This behaviour is aligned with a vision of AppIOS, and it is non-intrusive for hello-world apps that @per-samuelsson describes. Alternative behaviour: resolve towards local model, if local class with a given name isn't presented – the ambiguity error should be raised. Important note: what we want to achieve now is a coherent behaviour which lets Starcounter 2.0 be AppIOS by design (every Starcounter application you create is an App), but doesn't kick developers with limitations hard to understand, so that the learning curve is smooth.

**Comment by k-rus** [comment] 2015-08-29 19:34
Am I understand correctly that short name of a table  can be used only with local data model? I.e., `select e from event e` will resolve to user defined table `UserNamespace.Event`or will return error if no tables with name `Event` were defined even that the database contain class `SO.Ring1.Event`?

I don't know how much work is required and if it is possible without looking into source code of binding and database schema file generation for Prolog.

**Comment by per-samuelsson** [comment] 2015-08-30 08:12
> @k-rus @per-samuelsson Is it possible to change the binding layer in 2.0 so that it resolves ambiguity towards a local model? I.e., SELECT e FROM Event e will resolve to a local app's Event, if it is present, otherwise – up to the closest in hierarchy through facets/Simplified models/up to SO. This behaviour is aligned with a vision of AppIOS, and it is non-intrusive for hello-world apps that @per-samuelsson describes

Yes, this is exactly the thing I proposed. Its basically "just" having the short name generation be aware of different contexts - in the first version two is fine I guess: user application and underlying SO-model. For classes with same short name, user application gets preceedence. 

If two user applications use same short name, it needs to be fully qualified in queries (if we can't always pin to a app-context, in which case we could use the one from the given application). From tools such as web administrator, clashes can only be solved by fully qualified names.

**Comment by dan31** [comment] 2015-08-30 20:31
> Yes, this is exactly the thing I proposed. Its basically "just" having the short name generation be aware of different contexts - in the first version two is fine I guess: user application and underlying SO-model. For classes with same short name, user application gets preceedence.

Yeah, that's true! So there are two ways – climb to the tower from local model to uppers in resolution, or just search in local and produce error if not found. I incline to the latter, since it emphasises app locality. @per-samuelsson I see you incline to it as well for the first version (we can change it later on, now we want to probe it in real use).

> If two user applications use same short name, it needs to be fully qualified in queries (if we can't always pin to a app-context, in which case we could use the one from the given application). From tools such as web administrator, clashes can only be solved by fully qualified names.

@per-samuelsson You mean in Admin queries? Since apps are independent, it should always be the case that one app never ignites exception in the other app like namespaces misuse in SQL. One app can only ignite reflections in other apps by mapping mechanisms. We assume that Admin user actually knows what apps he is running and, in general, unaware of local models of other apps. If he is app developer, he is aware of his local models. Always an Admin user is aware of SO models, which are an important subject of querying in Admin for a developer familiar with SO concepts. We can imagine more sophisticated mechanism for visualisation the current state of SO, since it isn't about rows and tables really, it is about current state of concepts from SO and their interaction in time.

**Comment by per-samuelsson** [comment] 2015-08-31 06:25
> @per-samuelsson You mean in Admin queries?

I mean that if I do `SELECT p FROM Person p` from within a method within say "app1", it should be easy to get the right result even if there is Person classes in running apps "app1", "app2" plus underlying SO. I just pick the one closest to my local model (i.e. `app1.Person`) in this case.

Doing the same query from the web administrator would raise an error though, since quieries there are *scoped by database*, not by application (but we could of course allow that too, scoping the context in web admin to a single application / local model, just by letting the user choose which to query against, similar to how we allow that on databases today).

However, if we chose the approach that we enforce queries from the SO-layer to always qualify by full name (i.e. `SELECT p FROM RingX.Foo.Bar.Person p`), then we could resolve even queries from the web administrator, as long as there are not two ambiguous names from parallel running apps.

**Comment by warpech** [comment] 2015-08-31 17:13
> It also governs if additional, SO-libraries should be brought in and be part of the schema, no? And if it does, having it always turned "on" (i.e. by removing it), we will surely suffer from a lot more clashes once SO grows and/or more developers join in.

Maybe then there should be another database flag "Load SO libraries", and let it be "on" by default?

Ideally, as the app developer I should not be forced to put my class names in a namespace at all (because isolation from other apps is assumed). When I use an ambiguous table name in a query, could SQL go through the class definitions in the current app's code? In most cases I will have only one definition of a Person and I will not have SO imported to my project.

FWIK, @Starcounter-Jack proposed to prohibit making direct CRUD operations on SO in apps. But still, we should be able to do CRUD on SO in maps.

**Comment by dan31** [comment] 2015-08-31 17:20
I vote for @warpech suggestion. It would be good to prohibit SO operations in apps, I think today it isn't that critical. Critical would be to have that local model name resolution. The same time, SO is not really yet another DLL, but an essence of future AppIOS. Future internals of SO (should it be not C#-based class hierarchy, but somewhat closer to kernel and language-agnostic) inside Starcounter is discussible.

**Comment by warpech** [comment] 2015-08-31 18:07
Would creating a "Load SO libraries" flag and keeping it "on" by default solve the objections in this issue?

Other topics should be most probably be separated from this issue:
- solving the table name ambiguity
- siloing of the app data

**Comment by per-samuelsson** [comment] 2015-08-31 18:14
> Ideally, as the app developer I should not be forced to put my class names in a namespace at all (because isolation from other apps is assumed). When I use an ambiguous table name in a query, could SQL go through the class definitions in the current app's code? In most cases I will have only one definition of a Person and I will not have SO imported to my project.

Yes, this is the very essence of this whole matter, and more or less what we have proposed above (with somewhat different approaches). The clause

> as the app developer I should not be forced to put my class names in a namespace at all (because isolation from other apps is assumed).

should be our guiding star IMO. We should strive hard to achive that, and when we have several options, go back to that for guidance.

**Comment by per-samuelsson** [comment] 2015-08-31 18:17
> Would creating a "Load SO libraries" flag and keeping it "on" by default solve the objections in this issue?

Not really. We must implement the other stuff too, most importantly this thing that we favor the short name of types in the local model, and don't consider them ambiguous when coliding with classes from "built in layers" (like SO and/or simplified mappings).

**Comment by warpech** [comment] 2015-08-31 18:49
> Not really. We must implement the other stuff too, most importantly this thing that we favor the short name of types in the local model, and don't consider them ambiguous when coliding with classes from "built in layers" (like SO and/or simplified mappings).

Polyjuice is the default edition linked on .io, so for our intended usage ambiguity is not a new problem. 

It will only be a new problem for the legacy users, but they can be asked to set the "Load SO libraries" flag to off.

-----Original Message-----

**Comment by alemoi** [comment] 2015-08-31 22:15
The MergeJsonSiblings flag is added locally (Polyjuice flag removed). The problem of having SO in one installer still persists. As I understood from the discussion, even if we prefix all SO SQL names with "So", e.g. Person -> SoPerson we will still have problems when one app defines a class "Person" and another app does the same. This problem with SO is quite urgent right now.

**Comment by dan31** [comment] 2015-08-31 22:24
@k-rus, we now centre our hopes in you, can you please check if there is a way to add that ambiguity resolution with local model priority to 2.0?

**Comment by k-rus** [comment] 2015-09-02 13:57
> @k-rus, we now centre our hopes in you, can you please check if there is a way to add that ambiguity resolution with local model priority to 2.0?

Sorry for the late answer. Can you explicitly specify which ambiguity resolution you are out for? If just exclude predefined namespaces, such as SO from the ambiguity with short name, then it is doable and quite simple. If it requires to resolve to current app, then I am afraid it is not realistic, since database schema provided to parser is global.

**Comment by dan31** [comment] 2015-09-02 17:22
@k-rus, since that is what we've discussed yesterday with @alemoi and you, the answer has come yesterday already :) Today I discussed with @warpech as well, so: it is quite okay right now to require developers write explicit namespaces with app name inside (to avoid ambiguities when you launch apps non-standalone). This is not how we want it to be, however, but old SQL processor is an obstacle to change name resolving to local model. @k-rus showed us some places in processor to change the name resolving, @alemoi believes we can  try and tackle it together with him to change resolver (I believe as well). However, this is not much priority now.

**Comment by warpech** [comment] 2015-09-16 11:09
Please keep in mind that the entire discussion in this thread is off-topic, because the OP was about default merging and namespacing of `Self.GET` responses.

The discussion following OP is about implicit short table names that are useless if SO is loaded. @dan31, @alemoi perhaps this should be tracked as a separate issue?

The umbrella for merging all Polyjuice functionality into Starcounter is here https://github.com/Starcounter/CompanyTrack/issues/92

**Comment by alemoi** [comment] 2015-09-24 22:01
Now by default merging is always on and there is a flag `MergeJsonSiblings` for this.

**Closed** 2015-10-04 16:17 UTC
