### ISSUE TITLE
Syntactical error for transitive closure in parenthesis

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2581] opened 2015-02-24 08:16 UTC
Branch *RestrictiveGraphSyntax2* fixes graph syntax with requiring to use parenthesis around, e.g., transitive closure as decided. The syntaxes are desired at [this wiki page](https://github.com/Starcounter/Starcounter/wiki/Graph-Syntax). [This section](https://github.com/Starcounter/Starcounter/wiki/Graph-Syntax#non-ambiguity-wrt-arithmetic-expressions) presents `x.([a]*)[b]`, which does not work in the branch.

I tested two queries and both failed at transitive closure operator `+`:
```sql
SELECT b.([Father]+)[Name] FROM Person b WHERE b[Name] = 'Bob'
SELECT b.([Father]+).Name FROM Person b WHERE b[Name] = 'Bob'
```

**Comment by andan342** [comment] 2015-02-25 01:47
That's right! Closure operators cannot be used after closing bracket ']', even inside the round brackets. The correct syntax variants for this query (I just checked that they work):

```SQL
SELECT b.[Father+][Name] FROM Person b WHERE b[Name] = 'Bob'
SELECT b.[Father+].Name FROM Person b WHERE b[Name] = 'Bob'
```

On the referred wiki page, section 4 is very clear about this syntax feature. Maybe section 3 should be updated as well (it was intended to be informal, but not misleading).

**Comment by k-rus** [comment] 2015-02-25 08:37
Is there any particular reason why transitive closure cannot be used in parenthesis? In my opinion it is not good that `b.([Father]+)` does not work. Semantic meaning of square brackets is navigation for a property on the object, thus using transitive closure is exceptional as syntactic sugaring.

**Comment by andan342** [comment] 2015-02-25 09:45
I think I made it deliberately like this - otherwise it would be possible to write `b.([Father+]+)`, which is meaningless.

Every such example, where you want to put `+` directly after square brackets, would (by precedence rules) apply transitive closure to that single property. For example `b.([Father][Friend]+)` would apply transitive closure to `Friend` property only. So one of the benefits of moving `+` inside square brackets is making it more clear.

If one wants a transitive closure on a chain of two properties, the syntax `b.(([Father][Friend])+)` will work.

**Comment by andan342** [comment] 2015-02-25 09:47
If you do not agree, I can investigate how simple it is to allow the syntax you suggested.

**Comment by k-rus** [comment] 2015-02-25 15:07
> If you do not agree, I can investigate how simple it is to allow the syntax you suggested.

Can you investigate how it is difficult to support the constructions like `b.([Father]+)`?

**Comment by andan342** [comment] 2015-03-25 20:52
Fixed in branch RestrictiveGraphSyntax2.

[Grammar Synopsis](https://github.com/Starcounter/Starcounter/wiki/Graph-Syntax#4-grammar-synopsis) wiki page updated

**Comment by k-rus** [comment] 2015-03-26 07:33
I tested the changes and found some old queries do not work. I get syntactical error on:
```sql
SELECT x FROM Person x WHERE x.(Friend|Employer.^Employer)*.Name = 'Alice'
```
This query is presented on [wiki page](https://github.com/Starcounter/Starcounter/wiki/Graph-Syntax#4-grammar-synopsis) describing the graph syntax.
I found another problem on the wiki page. It contains syntax of using square brackets after dot, which if I don't mistake does not suppose to work:
```sql
SELECT a.[Parent+].[Friend*] FROM Person a 
 WHERE a.Name = 'Alice' 
```

**Comment by andan342** [comment] 2015-03-26 21:01
Yes, we have disabled the use of '*' outside round brackets - the example (h) on wiki page was updated at that time, test cases should also be updated.

I have fixed the other example (i) - that was certainly a mistype

**Comment by k-rus** [comment] 2015-03-27 06:31
> Yes, we have disabled the use of * and + closure operators outside round brackets - the example (h) on wiki page was updated at that time, test cases should also be updated.

Thank you for clarification! I missed to notice that the example has transitive closure outside parenthesis. I will fix the example and test again.



> I have fixed the other example (i) - that was certainly a mistype

Thank you!

**Comment by k-rus** [comment] 2015-03-27 07:05
> Thank you for clarification! I missed to notice that the example has transitive closure outside parenthesis. I will fix the example and test again.

I tested that it works. I will merge as soon the build server is working.

**Closed** 2015-03-27 14:59 UTC
Labels: bug, document, question, SQL
