### ISSUE TITLE
Clean build fails

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Starcounter#4087] opened 2017-02-09 13:55 UTC
Clean build of Level1 fails on project Starcounter.Extensions.Tests with: 
`
The "Starcounter.Weaver.MsBuild.Weave" task could not be loaded from the assembly C:\projects\starcounter\pnext\level1\src\Starcounter.MsBuild\..\..\bin\Release\Starcounter.Weaver.dll. Could not load file or assembly 'file:///C:\projects\starcounter\pnext\level1\bin\Release\Starcounter.Weaver.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.			
`

cc @per-samuelsson

**Comment by per-samuelsson** [comment] 2017-02-09 14:15
AdminTrack maybe?

I'll see if I can spot it. Clean, then Build solution, right?

**Comment by bigwad** [comment] 2017-02-09 14:22
>AdminTrack maybe?

I'm always unsure on this matter. Level1.sln is in this repo, hence is the issue. I can move it though.

>Clean, then Build solution, right?

I removed the entire output directory then built.

**Comment by per-samuelsson** [comment] 2017-02-09 14:27
> I'm always unsure on this matter. Level1.sln is in this repo, hence is the issue.

Yeah, it's not crystal clear. If we wouldn't depend on VPN so users actually could build it, I'd say it would belong here for sure. Anyway, leave it here for now.

> I removed the entire output directory then built.

I'll see what I can find.

**Comment by per-samuelsson** [comment] 2017-02-09 14:34
I get an error two, same project, but slightly different:

> Could not load file or assembly 'Starcounter.Weaver, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)	Starcounter.Extensions.Tests	C:\Users\Per\Git\Starcounter\Develop\Level1\src\Starcounter.MsBuild\Starcounter.MsBuild.targets	73	

Investigating.

**Comment by per-samuelsson** [comment] 2017-02-09 14:38
Bah, think I know what's wrong. Again stupid dependency of this `StarcounterBin` variable. I thought I had fixed that everywhere. 😢 

```xml
<!-- 
      The path to where assemblies implementing our custom tasks reside.
      Defaults to installation directory.
    -->
    <TaskAssembliesPath Condition="( '$(TaskAssembliesPath)' == '' )">$(StarcounterBin)</TaskAssembliesPath>
```

Anyway, setting StarcounterBin pointing to output directory should work until I have fixed it.

**Comment by per-samuelsson** [comment] 2017-02-09 16:53
I found now where I had fixed it, described [here](https://github.com/Starcounter/AdminTrack/issues/223#issuecomment-275775070). Seem there is still some flaw in that approach though. I need to consider it more.

**Comment by per-samuelsson** [comment] 2017-02-09 18:27
@bigwad 

As for my problem, I found the cause. It was due to me having StarcounterBin set to a 2.3 installation on my machine, causing resolving of the `Starcounter.Weaver` assembly to that, despite the path pointed to output folder. Not still sure why.

Two questions:

1. When you experience the problem, did you have StarcounterBin set, and if so, to what?
2. You have pulled latest bits, right? I know I fixed some dependency problems some time ago, and in your case it looks like there could be a dependency problem w/ `Starcounter.Extensions.Tests`. Can you check that it has a dependency set up to `Starcounter.Weaver`?

**Comment by bigwad** [comment] 2017-02-10 07:59
> When you experience the problem, did you have StarcounterBin set, and if so, to what?

To the output folder. It fails worse if it points to 2.2 binaries.


>You have pulled latest bits, right? I know I fixed some dependency problems some time ago, and in your case it looks like there could be a dependency problem w/ Starcounter.Extensions.Tests. Can you check that it has a dependency set up to Starcounter.Weaver?

I'm working with the latest develop and Starcounter.Extensions.Tests doesn't depend on Starcounter.Weaver.

**Comment by per-samuelsson** [comment] 2017-02-10 08:07
> I'm working with the latest develop and Starcounter.Extensions.Tests doesn't depend on Starcounter.Weaver.

That is weird, and I noticed I don't either. Let me again look over this.

**Comment by per-samuelsson** [comment] 2017-02-10 09:20
@bigwad 

I've now made a few tweaks that I think should get you pass this. Can you please try again?

However, it does *not* solve weirdness experienced when building Level1 with StarcounterBin set pointing to some other installation (like 2.3, 2.2). To be honest, I can't see how that can be solved in any other way than what I have proposed before: we move out all application-like code from Level1 completely, because right now its frankly quite a mess. 😢 Have no idea how that should be prioritized though (if at all).

What should work now: building Level1

* w/o StarcounterBin being set at all
* with StarcounterBin set pointing to shared output directory

**Comment by bigwad** [comment] 2017-02-10 09:51
@per-samuelsson,

No, it didn't help. And it didn't help to https://github.com/Starcounter/AdminTrack/issues/236 either, which I consider as a more severe issue than this one.

**Comment by per-samuelsson** [comment] 2017-02-10 10:02
> No, it didn't help.

😢 You still experience the error that says `Starcounter.Weaver.dll` was not found?

> And it didn't help to Starcounter/AdminTrack#236 either, which I consider as a more severe issue than this one.

I'm taking that one after this. I can just do one at a time.

**Comment by bigwad** [comment] 2017-02-10 10:05
>😢 You still experience the error that says Starcounter.Weaver.dll was not found?

Yes, but it just for the very first build. It's not that critical.
And I still don't see Starcounter.Extensions.Tests being dependent on Starcounter.Weaver. Did you try to achieve it with your latest commit?

**Comment by per-samuelsson** [comment] 2017-02-10 10:14
> And I still don't see Starcounter.Extensions.Tests being dependent on Starcounter.Weaver. Did you try to achieve it with your latest commit?

Yes, but via Starcounter.MsBuild, which seemed like the most correct thing to do.

**Comment by per-samuelsson** [comment] 2017-02-10 10:46
This is now down to occasional. I never have seen it, and @bigwad experience it from time to time on his supermachine. I vote we close it, to grab some more urgent tasks. Reopen if you think that's wrong @bigwad.

**Closed by per-samuelsson** 2017-02-10 10:46 UTC
Labels: bug

**Comment by dan31** [comment] 2017-02-11 19:56
> I'm always unsure on this matter. Level1.sln is in this repo, hence is the issue. I can move it though.

This public repo is meant mainly for the customer's eyes - questions, bug reports and so on, we use it as our work items tracker only historically. There have been times when, literally, a broken lightbulb in the projector was discussed on that tracker too. Customers have no interest to know about our failing builds, dust in a server or a broken lightbulb - hence ```AdminTrack```. In the future, the repository "Starcounter" will contain no code and will only be used for issues from customers, the working items themselves will go to their corresponding repos.
