### ISSUE TITLE
Setting view-model Array.Data adds new items instead of replacing all of them

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3458] opened 2016-03-24 10:57 UTC
In my launcher I like to display a list of groups the user is associated with. To do this I set the `UserRoleNames` list in my CommitHook class.

```csharp
page.UserRoleNames.Data = user.Groups.Select(_ => _.Name);   
```

and this is the associated HTML snipped
```
<template is="dom-repeat" items="{{model.UserRoleNames}}">
    <span>- {{item}}</span><br/>
</template>
```

but if I log out with my first user and log in with the next user I still see all the groups of the last user plus the groups of the new user. It seams like the old values won't be replaced.

If I add `page.UserRoleNames.Clear();` one line before the property assignment it works.

My Starcounter Version is: `Starcounter-PnextNightlyBuilds-2.3.1081 (Mar 22, 2016 3:00:44 AM)`

**Comment by miyconst** [comment] 2016-03-24 11:05
As I found, the issue is not related to client side at all.

On server side replacing `Data` object of an array does not remove existing items.

```cs
this.Items.Clear();

Console.Log(this.Items.Count); // 0

this.Items.Data = new object[] {
    new { Name = "Reset item 0" },
    new { Name = "Reset item 1" }
};

Console.Log(this.Items.Count); // 2

this.Items.Data = new object[] {
    new { Name = "Reset item 0" },
    new { Name = "Reset item 1" }
};

Console.Log(this.Items.Count); // 4
```

@chrhol, @alemoi is it a documented feature or a bug?

**Comment by dan31** [comment] 2016-04-15 13:29
> @chrhol, @alemoi is it a documented feature or a bug?

Ping guys!

**Comment by miyconst** [comment] 2016-05-02 11:10
@chrhol this is really annoying, could you please take a look?

**Comment by chrhol** [comment] 2016-05-03 07:13
> @chrhol this is really annoying, could you please take a look?

Sorry, missed this one. I think this should be considered a bug. Setting the `Data` property on an unbound array should have the same result as setting a queryresult directly.

These two snippets should be equal:
```csharp
this.Items = Db.SQL("SELECT x FROM y");
```

```csharp
var result = Db.SQL("SELECT x FROM y");
this.Items.Data = result;
```

I will fix it.

**Comment by chrhol** [comment] 2016-05-03 11:00
Pushed a fix for this to develop and pnext. When setting a new dataobject, existing items are removed.

**Comment by dan31** [comment] 2016-09-27 11:37
Since no feedback awhile, let's consider this closed. Please reopen if you still experience the issue.

**Closed by dan31** 2016-09-27 11:37 UTC
Labels: bug, Typed JSON

**Comment by jwillmer** [comment] 2016-09-27 11:44
@dan31 you know there is a [GitHub bot](https://github.com/twbs/no-carrier) that can do this for you? Just noticed that you closed a couple of old issues.
