### ISSUE TITLE
TransactionAbortedException when running several Apps

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Starcounter#2624] opened 2015-03-20 22:15 UTC
I was running Cartographer, People and Launcher together, until I starting getting this exception that:
```c#
20150320T224249 Error sc://alemoi/personal/default Starcounter.Host 8006 Starcounter.TransactionAbortedException: ScErrInvalidObjectAccessAbort (SCERR8006): The transaction was aborted because of an invalid object access.\r\nVersion: 2.0.0.0.\r\nHelp page: https://github.com/Starcounter/Starcounter/wiki/SCERR8006.\r\n   at Starcounter.Internal.DbState.ReadString(UInt64 oid, UInt64 address, Int32 index) in c:\\github\\Starcounter\\Level1\\src\\Starcounter\\Internal\\DbState.cs:line 601\r\n   at Simplified.Ring3.Address.get_Street() in c:\\github\\Polyjuice\\Simplified\\Ring3\\Address\\Address.cs:line 11\r\n   at Starcounter.Templates.Property`1.Checkpoint(Json parent) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Templates\\Foundation\\Property.cs:line 157\r\n   at Starcounter.Json.<CheckpointChangeLog>b__0(TObject tjson) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 62\r\n   at Starcounter.Internal.TransactionManager.Scope[T](TransactionHandle handle, Action`1 action, T arg) in c:\\github\\Starcounter\\Level1\\src\\Starcounter\\TransactionManager.cs:line 460\r\n   at Starcounter.Advanced.XSON.JsonExtension.Scope[T](Json json, Action`1 action, T arg) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\JsonExtension.cs:line 32\r\n   at Starcounter.Json.CheckpointChangeLog(Boolean callStepSiblings) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 57\r\n   at Starcounter.Templates.TObjArr.Checkpoint(Json parent) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Templates\\TObjArr.cs:line 121\r\n   at Starcounter.Json.<CheckpointChangeLog>b__0(TObject tjson) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 62\r\n   at Starcounter.Internal.TransactionManager.Scope[T](TransactionHandle handle, Action`1 action, T arg) in c:\\github\\Starcounter\\Level1\\src\\Starcounter\\TransactionManager.cs:line 460\r\n   at Starcounter.Advanced.XSON.JsonExtension.Scope[T](Json json, Action`1 action, T arg) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\JsonExtension.cs:line 32\r\n   at Starcounter.Json.CheckpointChangeLog(Boolean callStepSiblings) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 57\r\n   at Starcounter.Json.CheckpointChangeLog(Boolean callStepSiblings) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 72\r\n   at Starcounter.Templates.TObject.Checkpoint(Json parent) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Templates\\TObject.cs:line 78\r\n   at Starcounter.Session.UpdateValue(Json obj, TValue property) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Sessions\\Session.cs:line 446\r\n   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__2(Session s, Json json, Boolean css) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 191\r\n   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\JsonExtension.cs:line 60\r\n   at Starcounter.Json.LogObjectValueChangesWithDatabase(Session session, Boolean callStepSiblings) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 176\r\n   at Starcounter.Json.LogValueChangesWithDatabase(Session session, Boolean callStepSiblings) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 105\r\n   at Starcounter.Json.LogArrayChangesWithDatabase(Session session, Boolean callStepSiblings) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 154\r\n   at Starcounter.Json.LogValueChangesWithDatabase(Session session, Boolean callStepSiblings) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 103\r\n   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__2(Session s, Json json, Boolean css) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 209\r\n   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\JsonExtension.cs:line 60\r\n   at Starcounter.Json.LogObjectValueChangesWithDatabase(Session session, Boolean callStepSiblings) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 176\r\n   at Starcounter.Json.LogValueChangesWithDatabase(Session session, Boolean callStepSiblings) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Class Json\\Json.Object.ChangeLog.cs:line 105\r\n   at Starcounter.Session.GenerateChangeLog() in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Sessions\\Session.cs:line 493\r\n   at Starcounter.XSON.JsonPatch.CreateJsonPatchBytes(Session session, Boolean flushLog, Boolean includeNamespace, Byte[]& patches) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.XSON\\Sessions\\JSON-Patch\\JsonPatch.cs:line 90\r\n   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.Apps.JsonPatch\\BuiltInRestHandlers\\PuppetRestHandler.cs:line 58\r\n   at Starcounter.Internal.PuppetRestHandler.<RegisterJsonPatchHandlers>b__6(String s, WebSocket ws) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.Apps.JsonPatch\\BuiltInRestHandlers\\PuppetRestHandler.cs:line 144\r\n   at Starcounter.Internal.WsChannelInfo.DetermineAndRunHandler(WebSocket ws) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.Internal\\Http\\WsManager.cs:line 125\r\n   at Starcounter.Internal.AllWsChannels.RunHandler(UInt16 id, WebSocket ws) in c:\\github\\Starcounter\\Level1\\src\\Starcounter.Internal\\Http\\WsManager.cs:line 284\r\n   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in c:\\github\\Starcounter\\Level1\\src\\Starcounter\\Apps\\GatewayHandlers.cs:line 623\r\nErrorCode=8006\r\nHResult=-2146233088\r\nHelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR8006\r\n
```
Hard to say how to reproduce though.

**Comment by chrhol** [comment] 2015-03-23 07:25
I've been trying to reproduce it but with no luck. Until we find some way to do it, I guess we just keep our eyes open for it to happen again.

**Comment by dan31** [comment] 2015-06-28 23:05
Any new evidence there?

**Comment by chrhol** [comment] 2016-10-03 12:54
Over a year since the last comment. I will close this one, haven't seen or heard anything of the problem described here.

**Closed by chrhol** 2016-10-03 12:54 UTC
Labels: .NET, bug, Web Components (Polymer)
