### ISSUE TITLE
Very slow and unstable Windows Mobile 10 clients

### ISSUE THREAD

**Issue by niklasbjorkman** [Starcounter/Starcounter#3989] opened 2016-12-01 11:44 UTC
We have a customer that would like to use a rugged Windows 10 Mobile device in their warehouse. When we run our application it runs very, very slow and it is unstable with errors. The reason for selecting Windows is to control the device using their implemented AD

Chrome, Firefox or any other browser besides Edge is unavailable on the OS. Any suggestions on what we can to to make it work in Edge on Win 10 mobile? Other devices works fine (android/iOS) but they can run chrome app.

**Comment by per-samuelsson** [comment] 2016-12-01 11:56
cc @warpech @miyconst @tomalec ?

**Comment by warpech** [comment] 2016-12-01 12:38
We have a lot of potential gains in terms of client-side performance. So far the focus was on developers productivity, not performance optimisation.

My first suggesting: Removing `starcounter-debug-aid` from the master HTML template is a big performance boost.

Can I take a look at the code? That would give me more information.

**Comment by niklasbjorkman** [comment] 2016-12-01 12:48
Thanks for the reply. You have a full dev. environment somewhere in Poland set-up earlier this week for testing purposes. We will try remove the flag.

**Comment by niklasbjorkman** [comment] 2016-12-01 12:57
Removing starcounter-debug-aid only marginally increased the performance, so it is not the culprit. I do not find a way to see the error message we randomly get either.

**Comment by warpech** [comment] 2016-12-01 21:39
What is the error message? What is the Edge version? (try http://www.whatsmybrowser.org/)

**Comment by niklasbjorkman** [comment] 2016-12-05 09:12
Edge Mobile 13. I cannot find the debug console on the mobile device, but running Edge on PC throws an error as well:

SCRIPT5022: Assertion failed
webcomponents.js (979,9)

**Comment by warpech** [comment] 2016-12-05 09:47
That is most likely the issue that was fixed in Edge 14: https://github.com/webcomponents/webcomponentsjs/issues/575

Any chance of upgrading to Edge 14?

**Comment by niklasbjorkman** [comment] 2016-12-05 11:26
I've get the error on my dev. machine using Edge 38.14393.0.0, so it does not seem like it's been fixed. And sadly, no, the version cannot be updated until this summer according to Panasonic and that is 6 month after go-live at the customer ...

**Comment by warpech** [comment] 2016-12-05 11:37
I will try to reproduce it.

My best recommendation right now though is: switch to Android if you can. With old Mobile Edge, there might be more problems after fixing this one.

**Comment by niklasbjorkman** [comment] 2016-12-05 12:07
Yes, but the request for windows is from our (largest) customer. I can accept that they need to be able to control the HHC the same way as their other computers on the domain. It is for large-scale companies with evolved IT policies that windows is mandatory.

**Comment by warpech** [comment] 2016-12-05 13:03
I will do more research tomorrow to see how big of a problem this is. I have the files.

**Comment by warpech** [comment] 2016-12-06 12:55
@niklasbjorkman I have replied by email. 

The problematic app uses a mix of webcomponents.js, Polymer, jQuery, jQuery UI, Bootstrap and AdminLTE, which are two worlds not fully compatible. On top of that an outdated browser.

Closing this thread, because it is too general. We can report more specific problems as they are nailed down.

**Closed by warpech** 2016-12-06 12:55 UTC

**Comment by warpech** [comment] 2017-01-17 12:27
For future reference: 

The problems discussed here happen in Edge Mobile on Windows 10 Mobile (EdgeHTML 13.10586). This version is available in the VM images dated `20160322` from [this archive list](https://gist.github.com/zmwangx/e728c56f428bc703c6f6), specifically:

- https://az792536.vo.msecnd.net/vms/VMBuild_20160322/VirtualBox/MSEdge/MSEdge.Win10TH2.VirtualBox.zip
- https://az792536.vo.msecnd.net/vms/VMBuild_20160322/Parallels/MSEdge/MSEdge.Win10TH2.Parallels.zip

The above are VMs with Windows 10 Enterprise, not Mobile, so there might be significant differences though.
