### ISSUE TITLE
SynonymousTo better error message

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3677] opened 2016-06-02 11:16 UTC
Hi! I've been refactoring, and can't figure out what field/property I have assigned an erroneous SynonymousTo attribute to.

Would be nice to now the failing type at least.

The error:
> System.Exception: ScErrUnspecified (SCERR999): An unspecified error caused the operation to fail. Illegal element for the SynonymousTo attribute Version: 2.2.1834. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR999. <,0,0>
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__2(CommandTask task) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-283\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR999

**Comment by per-samuelsson** [comment] 2016-06-02 11:22
Hi @careri 

Sorry we never get the chance to improve on this. We are kind of low on resources, and also have discussions on and off if we really should keep synonyms around or not (I've always wanted to drop them).

Can I close this is a duplicate of #2629 (which is also yours, sadly)?

**Comment by careri** [comment] 2016-06-02 11:51
I did seach the issues for an error related to this. But just couldn't find it.
I'm guessing I've done the exact same error. 
The funny thing was that I once again compiled the weaver and tried to debug it. Couldn't even remember doing that before.

You can close either of them :)

**Comment by careri** [comment] 2016-06-02 11:54
Nice of me to solve the issue the last time, had done the same error again :)

**Comment by careri** [comment] 2016-06-02 12:06
@per-samuelsson Pull request for making the error log a little more verbose:
https://github.com/Starcounter/Starcounter/pull/3678

**Comment by careri** [comment] 2016-06-02 12:10
The output looks like this:
ScErrUnspecified (SCERR999): An unspecified error caused the operation to fail. Illegal element for the SynonymousTo attribute: HSM.Concepts.ServerMQStatefulItem/LastWrite

**Comment by per-samuelsson** [comment] 2016-06-02 12:19
> Pull request for making the error log a little more verbose: 

Wow, I'll definitely bring it in. I'm going to add a specific error code to it to. Thanks a lot!

**Comment by per-samuelsson** [comment] 2016-06-03 05:13
Fixed by the merging of #3678.

**Closed by per-samuelsson** 2016-06-03 05:13 UTC
Labels: bug, ScError
