### ISSUE TITLE
NullReferenceException in MetadataPopulation when starting app

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Starcounter#3193] opened 2015-12-16 14:28 UTC
I have 2 projects in my solution, 1 is working and running fine. but the 2nd one is crashing, and as soon as i run it, it stops the rest of the solutions. I am getting the following error in the StarCounter Error Log : 

"System.NullReferenceException: Object reference not set to an instance of an object.
 at Starcounter.SqlProcessor.MetadataPopulation.<>c__DisplayClass4.<PopulateClrMetadata>b__3() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter\SqlProcessor\MetadataPopulation.cs:line 76
 at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter\Db.cs:line 205
 at Starcounter.SqlProcessor.MetadataPopulation.PopulateClrMetadata(TypeDef[] typeDefs) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Starcounter\SqlProcessor\MetadataPopulation.cs:line 94
 at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(TypeDef[] unregisteredTypeDefs) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 348
 at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 196
 at Starcounter.Hosting.Package.Process() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 132
 at Starcounter.Hosting.Package.Process(IntPtr hPackage) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
 at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void\* hsched) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3226.3\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 73
 HResult=-2147467261"

**Comment by per-samuelsson** [comment] 2015-12-16 14:43
@atifsheikh 

Thanks for reporting this. Its not easy to say exactly why this happens just from tha stacktrace, but lets try finding that out.

First, regarding this

> [...] and as soon as i run it, it stops the rest of the solutions.

can you be more specific what a) exactly is happening add b) what you would expect / want? Is it so that first you start your first application and that suceeds, and then you start the second one, which crash, and that stops the first one too? Whats the status of database / host after this? You can find out by opening a prompt and run `staradmin list db`. That will show you something like:

```
default
  Running         True
  Host process ID 7776
  Applications    3
```

**Comment by per-samuelsson** [comment] 2015-12-16 14:48
And about the actual crash, can you find any pattern in your application as is described in #2428, i.e. do you have some database class with just private data?

There's also an old issue #2547 that experience something similar, but I'm not sure it applies here.

**Comment by atifsheikh** [comment] 2015-12-17 16:15
i am using 3 of your apps : 
1. Launcher
2. UserAdmin
3. SignIn

they launch perfectly, but when i try to launch my AdFenix App, every thing is closed : 
default
  Running         True
  Host process ID n/a
  Applications    n/a

I have another project nammed OneKey, when i launch that one after launching your 3 apps, i get this :
default
  Running         True
  Host process ID 10236
  Applications    4

So something is wrong with AdFenix solution i think

**Comment by per-samuelsson** [comment] 2015-12-17 20:10
Thanks for providing that feedback, @atifsheikh! Sorry to see you experience this.

> So something is wrong with AdFenix solution i think.

That most definitely sound so. But even if it is, we should do better to help you understand what goes wrong. We are constantly trying to improve on this area, but we are clearly not where we want to be yet.

> they launch perfectly, but when i try to launch my AdFenix App, every thing is closed

And I guess you don't see an error message either?

There are two concerns I have here:

1. When your failing app start, and then crash, we have code that should restart the other apps, so that the state you get back to is the same as before your failing application started. That clearly doesn't seem to work in this case, and I want to find out why.
2. You should see some kind of error.

The 3 apps you are starting before the failing app, are they from an AppStore? So that you have installed them from there and they started like that? And how do you start your failing app - from a Starcounter application project, just pressing F5 in Visual Studio?

Also, if you look in the [server log](http://starcounter.io/guides/tools/error-log/), do you see any errors that could be of help?

**Comment by atifsheikh** [comment] 2015-12-17 21:13
Yes you are right, i dont see any message. 
But i missed an important information, I updated Starcounter to the latest version, and then i had to downgrade it back to version 2.0.3226.3 (as my Frontend code is not fully update for polymer 1.0). so after downgrading, this issue started.

1. When the AdFenix app crashes on launch, nothing is restarted again. So the default DB is down after the crash
2. I see no error. but when i go to Server Logs in Starcounter Admin Panel, i can see an error, which i had posted in the 1st comment.

the 3 apps are Starcounter app, We got them from your Github.
and about launching my crashing app, i have tried launching it in every way, by hitting f5 / using Batch file / using SC Admin Panel, it crashes in all cases.

**Comment by per-samuelsson** [comment] 2015-12-17 21:20
OK, thanks a lot for that information.

> When the AdFenix app crashes on launch, nothing is restarted again. So the default DB is down after the crash.

I'll try set up something similar like this, and see if I can reproduce it. If I can, I'll report a separate issue about it. I'll let you know in any case.

And a final question about this

> the 3 apps are Starcounter app, We got them from your Github.

Does it mean you build them locally? And run them from within Visual Studio? Or with provided scripts (like `run.bat`)?

> But i missed an important information, I updated Starcounter to the latest version, and then i had to downgrade it back to version 2.0.3226.3 (as my Frontend code is not fully update for polymer 1.0). so after downgrading, this issue started.

That sounds like it could be something that is related to the error you get. I don't know for sure, but I'll try think it through and see what I can come up with.

**Comment by atifsheikh** [comment] 2015-12-17 21:27
we always use Run.bat to run your 3 apps. never launched them from Visual Studio.

And thank you for the quick and late night response :) i really appreciate that.

**Comment by per-samuelsson** [comment] 2015-12-17 21:31
> we always use Run.bat to run your 3 apps. never launched them from Visual Studio.

OK, great. Thanks. Then I know the whole story here, and it should be enough for me to get started trying to provoke it. I'll update you on any progress as soon as we have any!

**Comment by atifsheikh** [comment] 2015-12-17 21:39
Great. Thanks :)

**Comment by per-samuelsson** [comment] 2015-12-18 05:35
> When the AdFenix app crashes on launch, nothing is restarted again. So the default DB is down after the crash.

I can now confirm this. I'm able to reproduce it. If I run an application outside of Visual Studio, then start an application project (in VS), the former does not restart, and neither do the code host. Just as @atifsheikh describe.

If I do the same pattern, running the crashing app using `star app.exe`, everything work as expected (the first app and the code host restart). So this is a VS bug. Lets see what we can do about it. I'll open a separate issue about it.

**Comment by per-samuelsson** [comment] 2015-12-18 05:41
> I'll open a separate issue about it.

#3201.

**Comment by per-samuelsson** [comment] 2015-12-18 05:52
@k-rus 

Do you have a take on the acual error in the OP? From looking at the code, I can just tell that it occurs somewhere in `MetadataPopulation.PopulateClrMetadata`, likely when processing properties.

But since there are no error checking at all (just a bunch of `Debug.Assert`s, but these naturally are out of scope since this is no debug build), it's kind of hard to understand what actually fails.

If I'd take a guess, its the raw column fetched here:

https://github.com/Starcounter/Starcounter/blob/develop/src/Starcounter/SqlProcessor/MetadataPopulation.cs#L71

that is **null**, but I have no guess why, and the code hasn't changed for almost a year, so nothing recent either.

**Comment by per-samuelsson** [comment] 2015-12-18 14:06
@atifsheikh 

I've posted some content related to the process management things in #3201.

About the exception, we are discussing it internally. We have a few ideas, but they all boil down to one thing: we need an environment to tell for sure. That would be your bin folder, and the database files. Something that is currently not easy to just retreive. We've been discussing providing some tooling that could easily "snapshot" these, but we haven't such still.

If you are really stuck on this, and if you don't have any data you need to preserve in your development database, we are rather sure you can get around it by running your apps in another, new/empty database. And/or delete/recreate the "default" database.

Are any of these an option for you, until we can get further on the real problem?

If you want to run your application in a new database, all you have to do is to provide `star` with the `-d` option.

```cmd
star -d=testdb yourapp.exe
```

If you want to do the same in VS, just open `Project | Properties | Debug` and write `-d=testdb` in the `Command line arguments`.

If you need the prefabs (launcher, signin, useradmin) to test, you can run those in that database too. Just look at their `run.bat` (as I guess you are normally using to start them) and adapt them accordingly.

Please let us know what you think about these suggestions!

**Comment by atifsheikh** [comment] 2015-12-18 15:22
I dont have any important data in default database. as this issue is on my local machine, so for now i can use the new Clean-DB for my local computer tests and debugging.

**Comment by per-samuelsson** [comment] 2015-12-18 18:14
> I dont have any important data in default database. as this issue is on my local machine, so for now i can use the new Clean-DB for my local computer tests and debugging.

OK, so this get you past the most immediate problem at least? 

You know you can delete databases with `staradmin delete db` (to delete the default one), or `staradmin -d=[database_name] delete db`? The next time an application start, the database get recreated on the fly.

**Comment by k-rus** [comment] 2015-12-19 08:48
It is good that you can run your application code on an empty database. Do you remember if you changed anything in database classes at the same time when you were upgrading Starcounter? We experienced similar situations when both Starcounter and application code was updated. Previous corner cases were fixed. This one is new and we don't exactly what is the problem without ability to reproduce it.

**Comment by atifsheikh** [comment] 2015-12-19 12:06
@per-samuelsson i have some data for my other projects in Default DB. so i dont think i will delete the Default DB. 
and since the other projects are working fine, so its ok for me to use a new DB for AdFenix project.

**Comment by atifsheikh** [comment] 2015-12-19 12:08
@k-rus Im not sure if there were any changes in the upgraded starcounter. but if you guys want to take a closer look at this issue, i can bring my laptop to your office on monday.

**Comment by per-samuelsson** [comment] 2015-12-19 12:25
> @per-samuelsson i have some data for my other projects in Default DB. so i dont think i will delete the Default DB.

I totally understand that. Actually, I'd like to get my hands on that database at some point, so we can diagnose what could have happened. I just started creating a simple tool that can collect application and database artifacts for these kind of cases. Maybe I can pilot it on you next week, if I succeed implemening a working first version by then. :sunglasses:

**Comment by atifsheikh** [comment] 2015-12-19 14:20
Sounds good. so i'm keeping the DB. ;)

**Comment by careri** [comment] 2015-12-21 07:18
I got the same error. I think what I did was to by mistake launch in default db, which hosts and app launched from cmd. I noticed that I forgot to change db and did so. Now I get this error every time I hit F5 in VS.

**Comment by per-samuelsson** [comment] 2015-12-21 07:28
> Now I get this error every time I hit F5 in VS.

Really? In the latest version? And have you done something similar to what @k-rus describe [here](https://github.com/Starcounter/Starcounter/issues/3193#issuecomment-165961326)?

**Comment by careri** [comment] 2015-12-21 07:48
Only a few rows of new code for a test of websocket. Launched in default, stopped launched in it's own db.

Strange thing is that the db isn't marked as running i administrator. But if I try to delete it i get this error:
> Starcounter.DbException: ScErrDatabaseRunning (SCERR10031): The database is running. Database: 'sc://headsutv180.innowait.se/personal/testss'.
Version: 2.1.836.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10031.
   at Starcounter.Server.Commands.DeleteDatabaseCommandProcessor.CheckPrerequisites(Database& database, DeleteDatabaseCommand& command) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-123\Level1\src\Server\Starcounter.Server\Commands\Processors\DeleteDatabaseCommandProcessor.cs:line 77
   at Starcounter.Server.Commands.DeleteDatabaseCommandProcessor.Execute() in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-123\Level1\src\Server\Starcounter.Server\Commands\Processors\DeleteDatabaseCommandProcessor.cs:line 26
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity8\buildAgent\work\sc-develop-nightly-123\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=10031
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10031

Deleting from cmd with force parameter deleted the DB. Seems to be working now

**Comment by per-samuelsson** [comment] 2015-12-21 08:19
> Strange thing is that the db isn't marked as running i administrator. But if I try to delete it i get this error.

Yeah, thats a bit confusing, but it can be explained. In adminstrator, you see the status as *not running* when the *code host* isn't running. But the database manager (i.e. `scdata.exe`) could still be. And that hinders you from deleting the database.

Next time, as an experiment, test `staradmin list db`. That will show you the paired status. You will see there that the database process is running (while the code host is not).

**Comment by per-samuelsson** [comment] 2015-12-21 13:15
@atifsheikh @careri 

The next time you experience the metadata error, and if you have time to pioneer this little thing we are just trying out, it would be cool to see you try #3212. 

It means you have to give us access to your databases, and its a bit rough in the edges for sure, but we would really appreciate to get our hands on an environment where we could reproduce this, to see if there is something we can fix.

Let us know if you're interested in that! :bow:

**Comment by atifsheikh** [comment] 2015-12-21 13:38
Sure, i'd love to help :)

**Comment by careri** [comment] 2015-12-21 14:29
Sure, I'll try that the next time

**Comment by dan31** [comment] 2017-03-15 22:54
Archived.

**Closed by dan31** 2017-03-15 22:54 UTC
Labels: bug, Code host, Management
