### ISSUE TITLE
UDP Handler - Assertion failed

### ISSUE THREAD

**Issue by peterbergman** [Starcounter/Starcounter#2688] opened 2015-04-23 19:21 UTC
I have registered a UDP handler in one of my Starcounter apps. When receiving datagrams in the handler, I sometime get an error that causes the app to crash:

Assertion failed (cur_offset < num_available_bytes) at utils.cpp:88 (Data 0). 00007FF86F4C11D3 sccoredbg!_DumpCallstack : callstack-win.cpp (120) 00007FF86F4C114C sccoredbg!do_handle_assertion_failed : assert-win.cpp (77) 00007FF86F4C1039 sccoredbg!handle_assertion_failed : sccoredbg.cpp (29) 00007FF86E9A4305 bmx!sc_bmx_plain_copy_and_release_chunks : utils.cpp (91) 00007FF8182B3DF1 <unknown>

It seems like it happens when the datagram contains more than 232 byte of data. Is this a bug?

Handler registration:

```C#
Handle.Udp(5555, (IPAddress clientIp, UInt16 clientPort, Byte[] datagram) =>
{
    ...
}
```

**Comment by alemoi** [comment] 2015-04-23 19:35
Thanks for the report! Probably is a bug! I will fix it next week!

**Comment by ivarbergman** [comment] 2015-05-21 11:43
Hi! Any news on this? 
I use Starcounter edition 2.0.3139.3 and experience the same issue.

**Comment by alemoi** [comment] 2015-05-21 11:53
My apologies, I have overlooked this one. Will check it as soon as possible and notify you! Sorry to keep you waiting!

**Comment by ivarbergman** [comment] 2015-05-21 12:28
Super! Thanks!

**Comment by alemoi** [comment] 2015-05-22 15:57
The issue is now fixed! Now incoming UDP datagrams with maximum size of 30000 bytes are supported (however user code can send datagrams up to 65000 bytes).
Automatic tests for different sizes of datagrams are added.
Available in following nightly build.
Thank you very much for reporting!

**Closed by alemoi** 2015-05-22 15:57 UTC
