### ISSUE TITLE
Visual studio: NPE when generating code

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter#3626] opened 2016-05-16 15:02 UTC
1. Download code from https://github.com/StarcounterPrefabs/Launcher/blob/bug_report
1. Build fails with message `Object reference not set to an instance of an object. | Launcher_AcceptanceHelperOne | C:\Users\Joozek\dev\Launcher\test\Launcher_AcceptanceHelperOne\Launcher_AcceptanceHelperOnePage.json.cs`

Note that `Launcher_AcceptanceHelperTwo\Launcher_AcceptanceHelperTwoPage.json.cs` class is identical (only the name is different) and yet it builds fine.
Resharper also fails to resolve basically any symbol in this file (even `System.Linq`)

**Comment by chrhol** [comment] 2016-05-16 17:14
Thank you for reporting this. I get the same exception using the branch above. Will investigate and see what goes wrong.

**Comment by joozek78** [comment] 2016-05-16 17:41
@chrhol Can you give me some hints at working around this issue? It blocks the work I intend to pick up tomorrow

**Comment by chrhol** [comment] 2016-05-16 18:13
Yes, really weird error. The problem was the attribute on the nested class. It's missing `_json` in the attributename in the end. `[Launcher_AcceptanceHelperTwoPage.SharedValue]` should be `[Launcher_AcceptanceHelperTwoPage_json.SharedValue]`

```csharp
[Launcher_AcceptanceHelperTwoPage_json.SharedValue]
public partial class SharedItem : Json, IBound<Something> {
[...] 
```

I will link this issue to the issue for rewriting code-behind parser to make sure we produce a better compile-error for this case.

**Comment by per-samuelsson** [comment] 2016-05-16 18:30
> I will link this issue to the issue for rewriting code-behind parser to make sure we produce a better compile-error for this case.

Well, as I understand it, this is one of the problems with those code-generated attributes. How could we provide a better error message when we can't for sure

1. say the class is to be mapped (if we choose that not-so-strict model we have now, where classes may or may not be mapped), and neither
2. tell if the attribute is one of the mapping attributes - since we can just investigate it using a string, and we allow other attributes.

Regarding [2], to clarify, the now failing `[Launcher_AcceptanceHelperTwoPage.SharedValue]` might as well be `[Conditional("TRACE"]` or whatever. We can report that as an error.

Please go and give your say on #3625, guys. :smile:

**Comment by joozek78** [comment] 2016-05-16 18:33
> Well, as I understand it, this is one of the problems with those code-generated attributes. How could we provide a better error message when we can't for sure

Code generator throws NPE, so we probably can improve on error reporting here :)

**Comment by per-samuelsson** [comment] 2016-05-16 18:37
> Code generator throws NPE, so we probably can improve on error reporting here :)

Well, of course, surfacing exceptions like this is of course to be considered a bug. It's still not trivial to produce pinpointed errors in all these cases with the model we currently employ.

**Comment by chrhol** [comment] 2016-05-16 18:39
> > Well, as I understand it, this is one of the problems with those code-generated attributes. How could we provide a better error message when we can't for sure

> Code generator throws NPE, so we probably can improve on error reporting here :)

Yes, that was what I meant as well. Currently this case is not handled at all in the parser. Should have described the actual problem a bit more :)

The problem is, that when the `Handle` method (inside the class with the faulty attribute) is detected later, the parser just assumes that it has information of the class that implements it. But since the attribute is not detected there is no such info and instead of detecting that and produce some errormessage it just fails with a nullreference.

> Regarding [2], to clarify, the now failing [Launcher_AcceptanceHelperTwoPage.SharedValue] might as well be [Conditional("TRACE"] or whatever. We can report that as an error.

This is the reason for the strange prefix `_json` on these attributes. And also the attribute has the same name as the name of the JSON-by-example file. 

But I agree, it's difficult to be exact since we dont have the full type-tree. I just wanted to make sure we handle this case.

**Comment by per-samuelsson** [comment] 2016-05-16 18:53
> The problem is, that when the Handle method (inside the class with the faulty attribute) is detected later, the parser just assumes that it has information of the class that implements it. But since the attribute is not detected there is no such info and instead of detecting that and produce some errormessage it just fails with a nullreference.

Thanks for clarifying that. I'll see if I can get that into the new Roslyn parser somehow.

Just so I'm sure I understand this correctly. This code fails:

```cs
[Launcher_AcceptanceHelperOnePage.SharedValue]
public partial class SharedItem : Json, IBound<Something> {
  public void Handle(Input.Description action) {
  }
}
```

because the class is not mapped to anything in the JSON, but we **still parse** the `Handle` method, and try to generate some code? I thought we just allowed any arbitrary class, and didn't even touch it if it was not mapped?

As I see it, I have two options to re-implement this:

1. I fail earlier, because the class is not mapped (that's a strategy I've already implemented in my branch; you'll get an error message saying what class is not mapped and where it is in the code-behind).
2. I don't ever consider that `Handle` method, because the class is not mapped, and hence we don't bother about it at all (if we choose to make the code-behind less strict and allow any kind of class)

**Comment by per-samuelsson** [comment] 2016-05-16 18:58
> This is the reason for the strange prefix _json on these attributes. And also the attribute has the same name as the name of the JSON-by-example file.

Yes, I know that.

It's a bit off-topic, but I've always thought it would be more straightforward to use a dedicated JSON mapping attribute, instead of a code-generated one, like:

```cs
[JsonPath("Foo")]
partial class Foo {
}
[JsonPath("Foo.Bar")]
partial class Bar {
}
```

Did you ever consider that? Whats the pros/cons compared to `[Foo_json]` and `[Foo_json.Bar]`?

**Comment by chrhol** [comment] 2016-05-16 19:05
> because the class is not mapped to anything in the JSON, but we still parse the Handle method, and try to generate some code? I thought we just allowed any arbitrary class, and didn't even touch it if it was not mapped?

Yes, that was what I thought as well, and obviously this doesn't work in all cases. I like number 1. but that assumes that we are going for a more strict approach.

> Did you ever consider that? Whats the pros/cons compared to [Foo_json] and [Foo_json.Bar]?

To be honest, I don't know. This is a part of the codegeneration that haven't been touched since the very early prototype was implemented. I can only make a guess and that is that codegenerated attributes was added as a nice addition to avoid spelling errors without thought on how it should be parsed and detected and this have just lived on after that. Maybe @Starcounter-Jack remembers the reason (if any) or if the attributes you have as example ever was considered.

**Comment by joozek78** [comment] 2016-05-16 19:38
> > Did you ever consider that? Whats the pros/cons compared to [Foo_json] and [Foo_json.Bar]?

> ...a nice addition to avoid spelling errors...

I second that. It's not only spelling errors, but also making sure that my code works after a rename (or fails to compile with informative error)

**Comment by per-samuelsson** [comment] 2016-05-16 20:05
> It's not only spelling errors, but also making sure that my code works after a rename (or fails to compile with informative error).

Yeah, good point. That's one candidate to keep that "uglier" syntax IMO, not turning to a string-based one. 

On the other hand, we still parse the JSON tree and we could still validate stings inside a predefined, compile time attribute (like I sample above) against nodes in that tree and provide the same information-level in errors based on that I think.

**Comment by chrhol** [comment] 2016-09-30 08:39
The NPE doesn't occur anymore after the switch to Roslyn. Closing.

**Closed by chrhol** 2016-09-30 08:39 UTC
Labels: bug, Typed JSON
