### ISSUE TITLE
Create C# meta-data classes from JSON file

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2728] opened 2015-05-26 07:15 UTC
The meta-shema is described in `metaschema.json`, which is the source of truth for all components. This file is already used to generate C code, which is used to create initial meta-data schema in the database and populate with initial data. To avoid redundancy and, therefore, mistakes the same file should be used to generate C# classes representing meta-data, since the classes should be available at compilation time. Other code hosts can also use this file if they cannot wait until a database is initialised with the meta-data.

**Comment by k-rus** [comment] 2015-05-26 12:08
This issue will require to fix all hardcoded places into using the input. I know about the following places:

1. Actual Class files as mentioned above with additional static methods.
2. Initialisation calls in `AddBasePackage` in `Loader.cs`.
3. Initialisation calls in `InitTypeSpecifications` in `Package.cs`.

**Comment by k-rus** [comment] 2015-05-27 05:26
This issue is only related to DNX track, thus the above comments were modified or deleted.

**Comment by k-rus** [comment] 2015-10-30 10:21
Now this issue needed for current work on 2.x. @per-samuelsson is it feasible to do it? Can you estimate how much time will it take for you?

**Comment by per-samuelsson** [comment] 2015-10-30 12:08
> This issue is only related to DNX track, thus the above comments were modified or deleted.

So I guess this no longer hold true? We need it in 2.x as well?

I guess if I'd do it in 3.x, I'd use Roslyn, but there are sufficient stuff in 2.x to do this quite easily as well, a little bit depending on the complexity of the result. I estimate it to somewhere in the range 1-3 days.

@dan31, @k-rus , can you prioritize this within the current context. I'm having a hard time seeing how important this one is considering our current focus.

@k-rus Maybe you and I could sit down for a moment and go through this some? You know, just see what we have and what we need to solve more preciecely. You can assign it to me from now.

**Comment by k-rus** [comment] 2015-10-30 12:20
> @dan31, @k-rus , can you prioritize this within the current context. I'm having a hard time seeing how important this one is considering our current focus.

Any changes in the schema requires update json file and meta-data classes in Level1. Now I am doing this work to sync the two files in pnext. This is double work, which I have to do, and which easily produces bugs. @per-samuelsson already experienced once when he needed to update meta-data schema himself.
Now I am fixing the interfaces already and we can leave with current solution for a while, however I suspect new changes will be needed before we move to DNX. When we will meet need to do changes, implementing this issue will be too late. So I vote to fix this issue as soon as possible.



> @k-rus Maybe you and I could sit down for a moment and go through this some? You know, just see what we have and what we need to solve more preciecely. You can assign it to me from now.

Definitely. I am in the issue now. So next week when we are both in the office we can do it. I will be definitely on Tuesday and Wednesday.

**Comment by per-samuelsson** [comment] 2015-10-30 13:07
> I will be definitely on Tuesday and Wednesday.

Great. Then I'll aim to be there at least one of those days too, and we can look through it.

**Comment by per-samuelsson** [comment] 2015-10-30 13:10
@k-rus btw, where's the JSON metadata schema file at this very point? somewhere in bluestar i assume, can you just give me the relative path, so i can take a glipse at it? thanks.

**Comment by k-rus** [comment] 2015-10-30 13:14
> @k-rus btw, where's the JSON metadata schema file at this very point? somewhere in bluestar i assume, can you just give me the relative path, so i can take a glipse at it? thanks.

It is copied into Level1 output folder that you can use it. It is in branch pnext. The name is `metaschema.json`.

**Comment by per-samuelsson** [comment] 2015-10-30 13:42
> It is copied into Level1 output folder that you can use it. It is in branch pnext. The name is metaschema.json.

Thanks.

I discussed this with @dan31. I'll bring it on beginning of last week. We can just have a short online session on it, and then I should be good to go I think.

**Comment by k-rus** [comment] 2015-10-30 13:44
> I discussed this with @dan31. I'll bring it on beginning of next week. We can just have a short online session on it, and then I should be good to go I think.

Great! Just call me. I am usually online.

**Comment by per-samuelsson** [comment] 2015-11-01 20:21
@k-rus 

We are generating these classes into the Starcounter assembly, right? I was thinking maybe we should host them in there own assembly, but I'm not sure. Do you have any opinion on that?

Also: my idea is a generate them as partials. Because when I do, we can mix it up if we need some programming, i.e. implementing some methods on them. I can't see any problem with that. Can you?

**Comment by k-rus** [comment] 2015-11-02 09:34
> We are generating these classes into the Starcounter assembly, right? I was thinking maybe we should host them in there own assembly, but I'm not sure. Do you have any opinion on that?

Yes, we generate the classes for Starcounter assembly.
It's fine to do the simplest way now. But I think it would be nice not to add more assemblies. We know that the classes are always needed for .NET Starcounter to work.



> Also: my idea is a generate them as partials. Because when I do, we can mix it up if we need some programming, i.e. implementing some methods on them. I can't see any problem with that. Can you?

I don't see any problems with it.

**Comment by per-samuelsson** [comment] 2015-11-02 09:52
> But I think it would be nice not to add more assemblies. We know that the classes are always needed for .NET Starcounter to work.

Yeah, I considered this some more, and then changed my mind. Lets stick to what we decided.

I'm currently doing progress now, and I think it will take a few days to get the whole thing working, if you deliver the stuff on you (fixing Pnext Level1 and the output of the JSON), which I'm sure you will.

**Comment by per-samuelsson** [comment] 2015-11-02 12:53
@k-rus 

So whats the take on columns that need to map to a certain high-level type that is not 1-1? The most concrete sample being `bool` (e.g. `Column.AlwaysUnique`, `Property.Get`, `Property.Set` etc). As you know, the kernel type set is much narrower.

I guess either we can introduce some kind of simple (hard-coded) configuration in the tool. Or we can try a strategy where we define high-level accessors, casting the generated accessor. The bad thing with both is that we get away from "single point of truth". :cry: 

Or can we somehow use the "cast type" thing to hint on this?

The only alternative I can come up with that keep the single-point design goal is that we simply let the metadata API's support only the kernel types, but that will really make the high-level experience suffer badly (i.e. bools will become ulongs).

**Comment by k-rus** [comment] 2015-11-02 13:41
I think we can use cast type. I need to check how we should deal with boolean in the metalayer. I guess it is ok to map them into UInt64 for now. I will be back tomorrow with better suggestion.

**Comment by per-samuelsson** [comment] 2015-11-02 14:03
> I will be back tomorrow with better suggestion.

Great. I will design it so that it use cast type until we decide something else.

**Comment by per-samuelsson** [comment] 2015-11-02 16:10
Another thing (not equally important) is we must have a pattern for what classes should become abstract.

**Comment by k-rus** [comment] 2015-11-02 16:39
> Another thing (not equally important) is we must have a pattern for what classes should become abstract.

We can skip it, it is more as internal assurance that internal code, which is used to create meta-data creates correct objects. I think this assurance is not important and cannot be guaranteed outside .NET host.

**Comment by per-samuelsson** [comment] 2015-11-02 18:01
> We can skip it

Yeah, I was thinking the same. I guess if we can prevent user code from creating metadata entities, that we should. But I think it's not easily done by mistake anyway, since it use the system insert.

**Comment by k-rus** [comment] 2015-11-02 20:38
> I guess if we can prevent user code from creating metadata entities, that we should.

The user is prevented, since all constructors and set properties are internal. (If we don't speak about very sophisticated users, but they will be on their own.)

**Comment by per-samuelsson** [comment] 2015-11-02 21:01
> The user is prevented, since all constructors and set properties are internal. (If we don't speak about very sophisticated users, but they will be on their own.)

Yeah, true. I'm just being paranoid. :frog: 

I made really good progress today. I had an overall design goal to try to introduce no new dependencies, and that has succeeded. 

In its current state, the tool can now

1. Parse and interpret the entire metadata schema (the JSON file) and build up a domain model from it.
2. Generate the full set of metadata classes as a DOM (based on the domain model), including all data types currently in use.
3. Serialize the DOM to a file in a format compatible with that produced by the weaver. This file, we'll integrate in the building of the Starcounter assembly.

Here's a snippet of it:

```C#
namespace Starcounter.Metadata {
    using Starcounter.Internal.Metadata;
    using Starcounter;
    using Starcounter.Internal;
    
    public partial class Type : SystemEntity {
        public String Name{ get { return DbState.ReadString(__sc__this_id__, __sc__this_handle__, __starcounterTypeSpecification.columnHandle_Name);} internal set { DbState.WriteString(__sc__this_id__, __sc__this_handle__, __starcounterTypeSpecification.columnHandle_Name, value);} };
        internal class @__starcounterTypeSpecification {
            internal static ushort tableHandle;
            internal static TypeBinding TypeBinding;
            internal static int columnHandle_Name;
        }
    }
    public partial class DbPrimitiveType : Type {
        public UInt64 PrimitiveType{ get { return DbState.ReadUInt64(__sc__this_id__, __sc__this_handle__, __starcounterTypeSpecification.columnHandle_PrimitiveType);} internal set { DbState.WriteUInt64(__sc__this_id__, __sc__this_handle__, __starcounterTypeSpecification.columnHandle_PrimitiveType, value);} };
        new internal class @__starcounterTypeSpecification {
            internal static ushort tableHandle;
            internal static TypeBinding TypeBinding;
            internal static int columnHandle_PrimitiveType;
        }
    }
    public partial class MapPrimitiveType : Type {
        public DbPrimitiveType DbPrimitiveType{ get { return (DbPrimitiveType)DbState.ReadObject(__sc__this_id__, __sc__this_handle__, __starcounterTypeSpecification.columnHandle_DbPrimitiveType);} internal set { DbState.WriteObject(__sc__this_id__, __sc__this_handle__, __starcounterTypeSpecification.columnHandle_DbPrimitiveType, value);} };
        public UInt64 WriteLoss{ get { return DbState.ReadUInt64(__sc__this_id__, __sc__this_handle__, __starcounterTypeSpecification.columnHandle_WriteLoss);} internal set { DbState.WriteUInt64(__sc__this_id__, __sc__this_handle__, __starcounterTypeSpecification.columnHandle_WriteLoss, value);} };
        public UInt64 ReadLoss{ get { return DbState.ReadUInt64(__sc__this_id__, __sc__this_handle__, __starcounterTypeSpecification.columnHandle_ReadLoss);} internal set { DbState.WriteUInt64(__sc__this_id__, __sc__this_handle__, __starcounterTypeSpecification.columnHandle_ReadLoss, value);} };
        new internal class @__starcounterTypeSpecification {
            internal static ushort tableHandle;
            internal static TypeBinding TypeBinding;
            internal static int columnHandle_DbPrimitiveType;
            internal static int columnHandle_WriteLoss;
            internal static int columnHandle_ReadLoss;
        }
    }
}
```

Whats missing is in terms of core logic is generation of the `CreateTypeDef` method, and constructor generation. Plus that detail with booleans/cast types. But thats all very straight-forward, so the heavy part is done.

I'm hosting the tool under Level1/src/Buildsystem, which I think its the right place. I will set it up to run as a build task, running in the same suite as those "copy depenencies" jobs, and error code generation. Think I got it all figured out.

I will work a little on and off tomorrow, but I think that the total remaining work shouldn't be more than like 4-8 hours, so depending on the time I can spend, we'll have this done within days for sure. 

If you want to take it for a spin, @k-rus, the `issue/2728` branch is the way to go. :fire:  It branches off of Level1 **pnext**.

**Comment by k-rus** [comment] 2015-11-03 07:48
> I think we can use cast type. I need to check how we should deal with boolean in the metalayer. I guess it is ok to map them into UInt64 for now. I will be back tomorrow with better suggestion.

After @alexanderstc's fix I added Cast type to `bool` in `metaschema.json`.

**Comment by per-samuelsson** [comment] 2015-11-03 07:56
> After @alexanderstc's fix I added Cast type to `bool` in `metaschema.json`.

You did? Where, when browsing `/pnext/src/metalayer/metaschema.json` I can't see that?

The two "CastType" I can spot is: `uint8_t` and `uint16_t`. Whats the full range, DYT? Should I try to be future-compatible for that?

**Comment by k-rus** [comment] 2015-11-03 08:00
My pushed failed when I wrote the comment. Now it is pushed.
This is current full range, which is mainly based on the kernel interface. I don't know if there will be more changes.
Can you have a place/file with mapping between C type names and C# type names? Is it possible to have a general solution in the generator that C# type names are used directly without hardcoding?

**Comment by per-samuelsson** [comment] 2015-11-03 08:04
> Now it is pushed.

Yeah, I see. Super.

> Can you have a place/file with mapping between C type names and C# type names?

Yeah, its already a central spot, so it will be very straightforward to change/extend.

**Comment by per-samuelsson** [comment] 2015-11-03 13:28
> It is copied into Level1 output folder that you can use it. It is in branch pnext. The name is metaschema.json.

About the input schema, the above is what you have in mind for the final solution, is it? So when I integrate the tool in the build pipeline, generating the metadata classes before the Starcounter assembly is being compiled, its in **Level1 output directory** I should expect the schema file to be? And should it not exist, I'll fail the build?

**Comment by k-rus** [comment] 2015-11-03 14:52
> It is copied into Level1 output folder that you can use it. It is in branch pnext. The name is metaschema.json.
> About the input schema, the above is what you have in mind for the final solution, is it? So when I integrate the tool in the build pipeline, generating the metadata classes before the Starcounter assembly is being compiled, its in Level1 output directory I should expect the schema file to be? And should it not exist, I'll fail the build?

Yes. I don't see better solution with minimal effort.

**Comment by per-samuelsson** [comment] 2015-11-03 14:57
> Yes. I don't see better solution with minimal effort.

OK, good. Its totally fine by me. I just wanted it confirmed so I can finalize this thing. :smile: Thanks.

**Comment by per-samuelsson** [comment] 2015-11-04 08:43
I've found another detail I can't solve only based on the metadata schema, related to abstract classes: how to generate constructors. Only some types (the non-abstract ones) are to have a ctor that actually insert something.

The only pattern I can find is I should generate one if

1. The type does **not** inherit the root base type (SystemEntity), **AND**
2. No other type extend that type.

It requires some additional work, but is that a working pattern @k-rus?

**Comment by k-rus** [comment] 2015-11-04 08:55
As discussed above no abstract or sealed classes, since it adds unnecessary complexity. Enforcing abstract class is not important, since there is no external users of it. So we skip it.
And there is no pattern, since I have a meta-schema modification in mind, which will break the current patter.

**Comment by per-samuelsson** [comment] 2015-11-04 10:21
> As discussed above no abstract or sealed classes, since it adds unnecessary complexity. Enforcing abstract class is not important, since there is no external users of it. So we skip it.

Yes, we agree on that. But thats not what I asked for.

>And there is no pattern, since I have a meta-schema modification in mind, which will break the current patter. 

What does this mean? I'm soon done with the tool, will I need to redesign it already?

What I asked: how should I know if I should emit a default constructor or not? All default constructors in the currentt version **insert** instances. If I add one in one class, I must be sure that none of the base classes insert too. That kind of thing is critical, not like abstract/sealed discussion.

**Comment by per-samuelsson** [comment] 2015-11-04 10:43
> What I asked: how should I know if I should emit a default constructor or not? All default constructors in the currentt version **insert** instances. If I add one in one class, I must be sure that none of the base classes insert too. That kind of thing is critical, not like abstract/sealed discussion.

You know what, never mind. I'll just figure out something that works, and we can revise it if needed.

**Comment by per-samuelsson** [comment] 2015-11-04 13:39
OK, I'm now done with my part of this. 

The new tool is working and it's integrated in the building of the Level1 solution (builds as part of it, and then runs as part of it, before Starcounter is built). With this, all metadata classes are now generated from the Level0 `metaschema.json`, just as were the requirement.

I'll leave it off with commit 88669715a510a546ee0f83f3c28171af5a4edb42 in branch `issue/2728`, branched off of pnext. To get the final bits working (see below), is the responsibility of @k-rus. I suggest he open up a new issue for that.

There are 176 build errors, all because a few metadata-consuming modules must be refactored to work with the new schema. That, and then merging this branch into **pnext**, is what's left to do.

Here are some hints of what currently fail:

Files:
```
MetadataPopulation.cs
MetadataTests.cs
SqlBugsTest.cs
Loader.cs
Reload.cs
```

Issues:
* References to Materialized-* (Table, Index, Column). These no longer exist.
* SetSpecifier has no reference type (I'm using the new MetadataEntity in the tool)
* Table.Updatable, used as a bool, defined UInt64 (cast type needed?)
* Property.Type does not exist renamed to Column.DataType?
* Property.Polymorphic should be bool? (cast type needed?)
* WriteLoss and ReadLoss is ulong - should be bool? (cast type needed?)
* Column.Type no longer exist - renamed to Column.DataType?

**Comment by k-rus** [comment] 2015-11-05 09:20
@per-samuelsson 
I am trying to merge this branch into pnext, however building Level1 failed due to `Starcounter.Metadata.Table` does not exist:
>Severity	Code	Description	Project	File	Line
Error	CS0234	The type or namespace name 'Table' does not exist in the namespace 'Starcounter.Metadata' (are you missing an assembly reference?)	Starcounter	C:\GitRepositories\Starcounter\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs	588

Is there some special way to build Level1 that the meta-data classes are generated?

**Comment by k-rus** [comment] 2015-11-05 09:21
> @per-samuelsson 
> I am trying to merge this branch into pnext, however building Level1 failed due to Starcounter.Metadata.Table does not exist:
> 
> Severity Code Description Project File Line
> Error CS0234 The type or namespace name 'Table' does not exist in the namespace 'Starcounter.Metadata' (are you missing an assembly reference?) Starcounter C:\GitRepositories\Starcounter\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs 588
> Is there some special way to build Level1 that the meta-data classes are generated?

I found the problem:

>10>  C:\GitRepositories\Starcounter\Level1\bin\Debug\metaschema.json -> C:\GitRepositories\Starcounter\Level1\src\Starcounter\Metadata
10>  System.NotSupportedException: Unknown data type, cant map column ColumnIndex: type STAR_TYPE_ULONG, cast type int16_t
10>     at GenerateMetadataClasses.CodeGenerator.DataTypeMap.MapCastType(DataTypeMap map, Column column) in C:\GitRepositories\Starcounter\Level1\src\BuildSystem\GenerateMetadataClasses\CodeGenerator\DataTypeMap.cs:line 64
10>     at GenerateMetadataClasses.CodeGenerator.DataTypeMap.Map(Column column) in C:\GitRepositories\Starcounter\Level1\src\BuildSystem\GenerateMetadataClasses\CodeGenerator\DataTypeMap.cs:line 17
10>     at GenerateMetadataClasses.CodeGenerator.PropertyGenerator.Generate(Column column) in C:\GitRepositories\Starcounter\Level1\src\BuildSystem\GenerateMetadataClasses\CodeGenerator\PropertyGenerator.cs:line 11
10>     at GenerateMetadataClasses.CodeGenerator.ClassGenerator.Generate(Table table) in C:\GitRepositories\Starcounter\Level1\src\BuildSystem\GenerateMetadataClasses\CodeGenerator\ClassGenerator.cs:line 38
10>     at GenerateMetadataClasses.CodeGenerator.MetadataCodeGenerator.Build(Schema schema) in C:\GitRepositories\Starcounter\Level1\src\BuildSystem\GenerateMetadataClasses\CodeGenerator\MetadataCodeGenerator.cs:line 44
10>     at GenerateMetadataClasses.CodeGenerator.MetadataCodeGenerator.Generate(Schema schema) in C:\GitRepositories\Starcounter\Level1\src\BuildSystem\GenerateMetadataClasses\CodeGenerator\MetadataCodeGenerator.cs:line 18

I will try to figure out how to solve it.

**Comment by per-samuelsson** [comment] 2015-11-05 09:26
> I will try to figure out how to solve it.

It's because you have introduced a new data type:

`
System.NotSupportedException: 
Unknown data type, cant map column ColumnIndex: type STAR_TYPE_ULONG, cast type int16_t
`

Its **int16_t**. That one wasn't part of the original "spec".

Its easy to add support though, just extend this method implementaton:
https://github.com/Starcounter/Starcounter/blob/issue/2728/src/BuildSystem/GenerateMetadataClasses/CodeGenerator/DataTypeMap.cs#L44

**Comment by k-rus** [comment] 2015-11-05 11:12
Great! It was really simple to extend!

I am merging to pnext and fixed build errors and part of the problems with bootstrap, however I cannot fix problem init type specifier thus reopen this issue and ask @per-samuelsson to look at it.
In addition it is necessary to change handcoded initialisation of typedefs (line 81 in Loader.cs) and of type specifiers (line 416 in Package.cs). Note that condition to check if metadata population needs to be changed (lines 324 and 415 in Packages.cs).

**Comment by k-rus** [comment] 2015-11-05 11:25
I forgot to say that the merging branch is `pnextMerge2728` in Level1, and use `pnext` in Level0.

**Comment by k-rus** [comment] 2015-11-05 11:26
So far the problems with bootstrapping were related to the base class `MetadataEntity`. It is probably the biggest difference between hardcoded meta-classes and generated ones.

**Comment by per-samuelsson** [comment] 2015-11-05 11:26
> In addition it is necessary to change handcoded initialisation of typedefs (line 81 in Loader.cs) and of type specifiers (line 416 in Package.cs).

I was under the impression that I was to implement code generation of classes, not messing with how bootstrapping work. especially since jumping back and forth between my work in normal 2.x and **pnext** is pretty expensive in terms of switching problems. The classes are there, can't you guys solve this with reflection for example?

**Comment by k-rus** [comment] 2015-11-05 11:29
@dan31 can you find someone to look into the bootstrapping issue? Otherwise I will have time to do it on Monday instead of the other prioritised ask.

**Comment by k-rus** [comment] 2015-11-05 11:37
> I was under the impression that I was to implement code generation of classes

The breaking change in generated classes is that they extend `MetadataEntity`, which might be a reason for failing bootstrap. Since I don't have knowledge about the bootstrap, I was not able to see problems with introducing the base class when we discussed this.

**Comment by per-samuelsson** [comment] 2015-11-05 11:38
> In addition it is necessary to change handcoded initialisation of typedefs (line 81 in Loader.cs) ...

Pseudo code:

```C#
var metaBase = typeof(MetadataEntity);
var types = metaBase.Assembly.GetTypes().Extending(metabase);
foreach (var t in types) {
  var td = t.GetMethod("CreateTypeDef").Invoke();
}
```

>  [...] and of type specifiers (line 416 in Package.cs).

```C#
var metaBase = typeof(MetadataEntity);
var types = metaBase.Assembly.GetTypes().Extending(metabase);
foreach (var t in types) {
  HostManager.InitTypeSpecification(t.GetType("__starcounterTypeSpecification"));
}
```

**Comment by k-rus** [comment] 2015-11-05 11:39
> Pseudo code:
> 
> var metaBase = typeof(MetadataEntity);
> var types = metaBase.Assembly.GetTypes().Extending(metabase);
> foreach (var t in types) {
>   var td = t.GetMethod("CreateTypeDef").Invoke();
> }
> [...] and of type specifiers (line 416 in Package.cs).
> var metaBase = typeof(MetadataEntity);
> var types = metaBase.Assembly.GetTypes().Extending(metabase);
> foreach (var t in types) {
>   HostManager.InitTypeSpecification(t.GetType("__starcounterTypeSpecification"));
> }

I will try this.

**Comment by per-samuelsson** [comment] 2015-11-05 11:41
> I will try this.

You know what, I'll switch over again trying to fix the bootstrap instead. I think its faster. Will do it when I'm at some point where I can do the context switch. 

You have made everything compile now at least?

**Comment by per-samuelsson** [comment] 2015-11-05 11:43
> You have made everything compile now at least?

Ah, thats this one?

> the merging branch is pnextMerge2728 in Level1

**Comment by k-rus** [comment] 2015-11-05 11:46
> Ah, thats this one?
> 
> the merging branch is pnextMerge2728 in Level1

correct

**Comment by per-samuelsson** [comment] 2015-11-05 12:21
> correct

Thanks. I've opened #3029 for the redesign and assigned it to me.

**Closed by per-samuelsson** 2015-11-05 12:21 UTC
Labels: .NET, Code host, enhancement
