### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by atifsheikh** [Starcounter/Starcounter#3368] opened 2016-02-15 10:40 UTC
We have a situation on one of our server. as soon as i run my application all 4 applications crash : 
1. Launcher
2. SignIn
3. UserAdmin
4. AdFenix

and we can see the following exception in SC Admin Panel:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.SqlProcessor.MetadataPopulation.<>c__DisplayClass4.<PopulateClrMetadata>b__3() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\SqlProcessor\MetadataPopulation.cs:line 76
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Db.cs:line 203
   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 324
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 261
   at Starcounter.Hosting.Package.Process() in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 143
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 75
HResult=-2147467261

**Comment by k-rus** [comment] 2016-02-15 10:42
Thank you for your report! Which version of Starcounter are you running? Is it pnext?

Related to #3359

**Comment by atifsheikh** [comment] 2016-02-15 10:45
Version 2.1.177, and i am not sure what is pnext.

**Comment by atifsheikh** [comment] 2016-02-15 10:49
and the weird thing is that I am not able to reproduce the error on my local machine, the same build works fine on my machine, but not on the server. 
(and the error in on Starcounter Basement Server 82.xx.7.11, I think you guys have access to this server.)

**Comment by k-rus** [comment] 2016-02-15 11:11
Thank you for the information. Have you done any changes in the application on the server? For example, were code of any app updated? If you had a database on your server and updated some database classes in one of the app, then Starcounter might not do handle your special case of upgrade correctly. This will also explain why you cannot reproduce locally.
So can you provide information what kind of changes happened?

Another question: are the app source code available somewhere online, like some GitHub repo? I have no idea, since I don't work with apps, but I am interested to look into the problem.

**Comment by atifsheikh** [comment] 2016-02-15 11:23
Yes code of apps was changed, i can see a lot of changes in DB, but i can not see any thing removed from DB, only new attributes/Columns are added in tables. 

And We have GitHub repo, and it is not publicly accessible. But if you have access to your server "82.99.7.11" we have our code hosted there.
But if you want to take a look on the server where we have the crash, i can share the credentials with you on your email.

**Comment by atifsheikh** [comment] 2016-02-15 11:37
When i try to debug the issue, and put a breakpoint on first line of code (in Program.cs Main() function's first line). The control never get here, and sccode.exe crashes.

**Comment by dan31** [comment] 2016-02-15 12:00
Hi @atifsheikh! I have a read-only access to your repo. However, without the data it would be difficult to reproduce the exact issue. On the other hand, @k-rus I found two similar issues, one from @atifsheikh as well https://github.com/Starcounter/Starcounter/issues/3193, but the other one is 1 year back: https://github.com/Starcounter/Starcounter/issues/2547. @k-rus I believe they are all three of a kind.

**Comment by dan31** [comment] 2016-02-15 12:04
@k-rus For me it seems that #3193 gives more insights on the reproduction, and it seems to be an isolated case. @atifsheikh does #3193 still take place for you? Could you upgrade #3193 with a resolution statement please?

**Comment by k-rus** [comment] 2016-02-15 12:10
> When i try to debug the issue, and put a breakpoint on first line of code (in Program.cs Main() function's first line). The control never get here, and sccode.exe crashes.

The exception happens during bootstrap, which utilises information about defined database classes, and before calling your main code.

Now I see two things, which are necessary to do:

1. Reproduce on a smaller sample to see the failing pattern and fix the bug. Thus access to your repo might help to find the pattern through the history of the changes.
2. Make your operational server back to work. Last time (#3193) you were able to remove the database. Is it still applicable to your case?



> found two similar issues, one from @atifsheikh as well #3193, but the other one is 1 year back: #2547.

The stack trace is the same, so I guess it is the same bug.

> Could you upgrade #3193 with a resolution statement please?

To my understanding #3193 was never resolved.

**Comment by atifsheikh** [comment] 2016-02-15 12:13
@dan31 Yes it looks like the same issue in #3193. but this is a live server, so i can not start a new DB, as i have customer data in this Server's DB. Previously i had that issue in my local machine, and i fixed it by using a new DB Name.
But in this case, we have to use the same DB and we need to access all of its Data

**Comment by atifsheikh** [comment] 2016-02-15 12:16
@k-rus 
1. @dan31 Have read access to our Repo
2. That solution is not suitable in our case. We need to access the entire Data, as this is a live server.

And yes #3193 was never resolved for me, i got a workaround by Creating a new db, but that workaround is not applicable in my current scenario.

**Comment by dan31** [comment] 2016-02-15 12:23
I also suggest #3193 is the same bug, so @atifsheikh if you can reproduce it (without having your big database) that would simplify diagnostics and resolution for us. @k-rus, situation looks also similar to https://github.com/Starcounter/Starcounter/issues/3359, perhaps they are also of a kind (logically) as you suggested.

**Comment by k-rus** [comment] 2016-02-15 12:25
> 1. @dan31 Have read access to our Repo

I am not @dan31 and don't have access. Can you clarify that you cannot give me a read access? In this case, instead of cloning of your repos I will need to make a physical copy of repos from his machine to my machine, which is more difficult then just cloning your repos.



> 2. That solution is not suitable in our case. We need to access the entire Data, as this is a live server.

How big is the database? We need to find out how to bring your database up and running. Some data will help.

Do you have any back up of your server with data and working version of apps that you can bring to operation? (Just a recommendation test any app changes or new version Starcounter on a copy of your operational server with the same data before updating the server in production. It does not help in this case, but might help to avoid down time in future)

**Comment by atifsheikh** [comment] 2016-02-15 12:25
@dan31 I tried to reproduce it on my localmachine, without the Big DB. But i could not reproduce it.

**Comment by k-rus** [comment] 2016-02-15 12:27
> @k-rus, situation looks also similar to #3359, perhaps they are also of a kind (logically) as you suggested.

After looking to stack traces, I really doubt that there is any relationships between them. Note that they are also on different branches.

**Comment by atifsheikh** [comment] 2016-02-15 12:46
@k-rus Sorry for the delay, Actually i dont have admin right to Git Repo. Andre have access to it, and he is not on his seat right now, i'll update you as soon as he give you Access ;)

**Comment by atifsheikh** [comment] 2016-02-15 12:49
And the DB(size of personal folder) is 5.85 GB

**Comment by k-rus** [comment] 2016-02-15 12:57
Thank you for the reply! While waiting for the access. Can you describe which versions of the apps were running before the update, and which you applied to hit the issue?

My idea for steps to reproduce:

1. Create a new database and start the apps from the previous versions.
2. Change apps to new version.

Have you tried these steps when you tried to reproduce the issue locally?

@atifsheikh or @dan31 
May be you can fork the repos. However, I don't know if forks preserve the history.

**Comment by k-rus** [comment] 2016-02-15 13:22
By the way, how large is the database, which you preserved in #3359?

**Comment by atifsheikh** [comment] 2016-02-15 13:49
@k-rus i tried your suggested steps on my local machine, but i could not reproduce the error.

For now i have fixed the server. I am using a DB backup from 2 days ago, and i am using my AdFenix app from 2 days ago. Everything works fine till this point. As soon as i update the AdFenix exe file with the latest one, the DB crashes, and after that even if i use the AdFenix app from 2 days ago, the db does not respond.

**Comment by k-rus** [comment] 2016-02-15 14:24
> @k-rus i tried your suggested steps on my local machine, but i could not reproduce the error.

Thank you. The data are also needed. Is it the same data size in #3359?



> s soon as i update the AdFenix exe file with the latest one, the DB crashes, and after that even if i use the AdFenix app from 2 days ago, the db does not respond.

Thank you for trying this. 

> But if you have access to your server "82.99.7.11" we have our code hosted there.

Does this server reproduce the issue? Or is it the operational server, which is now up and running?

**Comment by dan31** [comment] 2016-02-15 14:34
> After looking to stack traces, I really doubt that there is any relationships between them. Note that they are also on different branches.

I know, therefore my short note "logically the same", in a sense both happen at a startup in a metadata layer. Might here be some logical assumption violated in both develop and pnext then. Only a guess though.

**Comment by k-rus** [comment] 2016-02-15 15:01
> I know, therefore my short note "logically the same", in a sense both happen at a startup in a metadata layer. Might here be some logical assumption violated in both develop and pnext then.

In this issue, which is in develop, population of logical schema meta-data (`RawView`) do not fail, while population of runtime meta-data (`ClrClass`) fails. In the other issue the logical schema meta-data population fails. In both cases logical schema meta-data are populated by native code (but different implementations) and runtime metadata are populate in managed code (in pnext did not work for awhile).

**Comment by atifsheikh** [comment] 2016-02-15 15:47
> Thank you. The data are also needed. Is it the same data size in #3359?
No my local DB does not have the same data size. i have test data only.

> Does this server reproduce the issue? Or is it the operational server, which is now up and running?
This server is operational server. we have the error on "46.21.99.218:8585" only.

**Comment by k-rus** [comment] 2016-02-15 16:01
> Thank you. The data are also needed. Is it the same data size in #3359?<
> No my local DB does not have the same data size. i have test data only.

May be it is possible to reproduce the issue locally with only this database?

I've got the repo, but it does not contain SO. How do I get SO? Which repo is it?

**Comment by k-rus** [comment] 2016-02-15 16:02
> I've got the repo, but it does not contain SO. How do I get SO? Which repo is it?

Is it the one included with Starcounter installation?

**Comment by per-samuelsson** [comment] 2016-02-16 07:19
>  However, I don't know if forks preserve the history.

FWIW, they do.

**Comment by k-rus** [comment] 2016-02-17 11:05
@atifsheikh reported that they are not longer experiencing this bug. I also failed to reproduce it.
I will create error message at the place where the null reference exception is experienced. This will affect develop branch and will be included in the corresponding nightly and new stable.

@atifsheikh When you experience it again, can you archive the database (folder Personal) and the application that we can try to reproduce on another machine and I hope to investigate further?

**Comment by atifsheikh** [comment] 2016-02-17 11:27
yes sure, i will do that. 
Thank alot guys.

**Comment by k-rus** [comment] 2016-02-17 14:57
> I will create error message at the place where the null reference exception is experienced. This will affect develop branch and will be included in the corresponding nightly and new stable.

It is pushed into develop.

**Comment by dan31** [comment] 2016-03-17 08:53
Can we consider this be closed, @atifsheikh?

**Comment by atifsheikh** [comment] 2016-03-17 09:24
Yes @dan31 . we no longer have this error.

**Closed** 2016-03-30 14:07 UTC
Labels: bug, Metadata, stability issue
