### ISSUE TITLE
CalculatePatchAndPushOnWebSocket: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3855] opened 2016-09-26 08:22 UTC
```
"System.Exception: ScErrUnhandledException (SCERR1069): An unhandled exception was detected.
Version: 2.2.1.3287.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1069.
   at StarcounterInternal.Hosting.Processor.RunTaskNoScheduling(Action userAction, String appName) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 102
   at Starcounter.DbSession.GetAndExecuteQueuedTasks(Action`2 taskExecutionMethod) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter\DbSession.cs:line 180
   at StarcounterInternal.Hosting.Processor.RunTask(IntPtr hTask) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 149
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 62
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1069
---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Templates.TArray`1.GetValue(Json parent) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Templates\TArray.cs:line 124
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 276
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 141
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 251
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 306
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 141
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 306
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 141
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 368
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 141
   at Starcounter.Json.LogArrayChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 251
   at Starcounter.Json.<LogObjectValueChangesWithDatabase>b__124_0(ChangeLog clog, Json json, Boolean css) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 306
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3](Json json, Action`3 action, T1 arg1, T2 arg2, T3 arg3) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 141
   at Starcounter.Json.LogObjectValueChangesWithDatabase(ChangeLog changeLog, Boolean callStepSiblings) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 275
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog, Change[]& changeArr) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 96
   at Starcounter.XSON.JsonPatch.Generate(ChangeLog changeLog, Boolean includeNamespace, Boolean flushLog, Byte[]& patches) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 115
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace, Byte[]& patches) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 92
   at Starcounter.Session.CalculatePatchAndPushOnWebSocket() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 184
   at MVS.MVSPage.<ScheduleDataLoaded>b__11_0(Session s, String id) in C:\GitHub\MM\PalmaServer\MVS\ViewModels\MVSPage.json.cs:line 188
   at Starcounter.Session.Use(SessionTask action, String sessionId) in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 732
   at Starcounter.Task.Run() in C:\TeamCity\TeamCity10\buildAgent\work\sc-develop-nightly-501\Level1\src\Starcounter\DbSession.cs:line 100
HResult=-2147467261
"
```

Here is the line 188:

``` cs
Starcounter.Session.ScheduleTask(sessionId, (s, id) =>
{
     s.CalculatePatchAndPushOnWebSocket();
});
```

@chrhol please take a look, what is wrong in here?

**Comment by chrhol** [comment] 2016-09-26 09:29
Thanks for reporting! 

Do you have any way to reproduce this issue? The problem is probably not coming from the push itself, but for something when gathering changes.

**Comment by miyconst** [comment] 2016-09-26 10:44
This issue might be the same as this one [Setting Array.Data = null throws exception](https://github.com/Starcounter/Starcounter/issues/3856), but I am not sure, investigating.

**Comment by chrhol** [comment] 2016-10-12 07:57
Do you think this issue was caused by the same thing as in #3856 @miyconst? Or have it occurred again.

**Comment by chrhol** [comment] 2016-12-12 08:52
I will close this with the assumption that it was caused by the same problem as the other mentioned issue.

**Closed by chrhol** 2016-12-12 08:52 UTC
Labels: bug, Typed JSON
