### ISSUE TITLE
Installer automation?

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Starcounter#2771] opened 2015-06-12 09:03 UTC
Is it possible to run the installer automatically, without GUI interaction? I want to use this for automatic deployment of Starcounter instances.

**Comment by alemoi** [comment] 2015-06-12 10:23
Thank you for the question! That was made some time ago, but then we abandoned the feature. We need to recover it now.

**Comment by parherman** [comment] 2015-06-26 09:34
@mtornwall, @alemoi This is a duplicate of #2609, I will close this and we can continue the discussion in that issue!

**Closed by parherman** 2015-06-26 09:34 UTC
