### ISSUE TITLE
Unable to create database class Column

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3482] opened 2016-04-09 10:55 UTC
I have a class:

```cs
[Database]
public class Column {
}
```

Trying to start such application ends with the following error:

```
"Starcounter.SqlException: Failed to process query: select c from column c where c.table = ? and name = ?: Ambiguous class column. Unknown property table of class column. Unknown property or alias name. 
   at Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-254\Level1\src\Starcounter\Query\QueryPreparation.cs:line 67
   at Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-254\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:line 127
   at Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-254\Level1\src\Starcounter\Mock\Db.cs:line 123
   at Starcounter.SqlProcessor.MetadataPopulation.<>c__DisplayClass0_0.<PopulateClrMetadata>b__0() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-254\Level1\src\Starcounter\SqlProcessor\MetadataPopulation.cs:line 71
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-254\Level1\src\Starcounter\Db.cs:line 354
   at Starcounter.SqlProcessor.MetadataPopulation.PopulateClrMetadata(TypeDef[] typeDefs) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-254\Level1\src\Starcounter\SqlProcessor\MetadataPopulation.cs:line 98
   at Starcounter.Hosting.Package.UpdateDatabaseSchemaAndRegisterTypes(String fullAppId, TypeDef[] unregisteredTypeDefs, TypeDef[] allTypeDefs) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-254\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 429
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-254\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 259
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-254\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 143
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-254\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 56
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-254\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 66
ScErrorCode=0
BeginPosition=-1
EndPosition=-1
HResult=-2146233088
"
```

I think all the internal queries like `select c from column c where c.table = ? and name = ?` should contain full class name with namespace.

cc @alemoi, @per-samuelsson

**Comment by k-rus** [comment] 2016-04-09 12:01
Thank you for reporting. I will check and fix all paces in Starcounter's code to use full names.

**Comment by k-rus** [comment] 2016-04-12 12:24
The issue is fixed in develop.

**Comment by k-rus** [comment] 2016-04-12 13:30
Merged in pnext.

**Closed by k-rus** 2016-04-12 13:30 UTC
Labels: bug, Code host, P/High
