### ISSUE TITLE
The debug sequence failed

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#3314] opened 2016-01-28 08:42 UTC
I get this error when starting from VS:

> Error 20  The debug sequence failed. Consult the Visual Studio error list for more information. {"Text":"Stopping 9BA1A4559884CE2EEB543902EF69BBD9FBE98583 failed due to an unexpected problem. (\"Object reference not set to an instance of an object.\").","ServerCode":10016,"Helplink":"https://github.com/Starcounter/Starcounter/wiki/SCERR10016","LogEntry":""} (ScErrDebugFailedReported (SCERR12012))
> (Double-click here for additional help)     0   0   

The second time I hit F5 the debugger launches but shows this error;

> Error 56  Starting HAD in had failed due to an unexpected problem. ("Object reference not set to an instance of an object."). (ScErrUnexpectedCommandException (SCERR10016))
> (Double-click here for additional help)     0   0

**Comment by per-samuelsson** [comment] 2016-01-28 08:46
Thanks for reporting this, @careri.

I'm quite sure this is a duplicate of #3293, #3298, #3310. I know for a fact I saw this same thing in VS in one of those environments too.

**Comment by MLidstrom** [comment] 2016-01-28 09:13
I had these errors prior to 2.1.1135, but I'm not able to reproduce it now. Is it fixed?

**Comment by careri** [comment] 2016-01-28 09:37
Im on:
Version: 2.1.1123.

**Comment by careri** [comment] 2016-01-28 14:20
Yes, seems to be fixed in 2.1.1135

**Comment by careri** [comment] 2016-01-28 20:01
Nah, it's still there:
> "ScErrServerCommandFailed (SCERR10011): The operation ""Starting HAD in had"" failed.
Version: 2.1.1135.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011."
"ScErrUnexpectedCommandException (SCERR10016): Starting HAD in had failed due to an unexpected problem.
Version: 2.1.1135.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Administrator.Server.Managers.ServerManager.ServerModel_Changed(Object sender, EventArgs e) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 301
   at Administrator.Server.Model.Server.OnChanged(Object sender, EventArgs e) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Starcounter.Administrator\Server\Model\Server.cs:line 194
   at Administrator.Server.Model.Database.OnChanged(Object sender, EventArgs e) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Starcounter.Administrator\Server\Model\Database.cs:line 391
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at Administrator.Server.Model.Database.InvalidateApplications() in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Starcounter.Administrator\Server\Model\Database.cs:line 621
   at Administrator.Server.Model.Database.InvalidateModel() in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Starcounter.Administrator\Server\Model\Database.cs:line 603
   at Administrator.Server.Managers.ServerManager.<>c.<RegisterInternalModelApi>b__8_2(String databaseName, Request request) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 281
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1114
   at Starcounter.Self.DoSelfNodeCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Starcounter.Internal\Rest\Self.cs:line 392
   at Starcounter.Self.PUT(String uri, String body, Byte[] bodyBytes, Dictionary`2 headersDictionary, UInt16 port, HandlerOptions ho) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Starcounter.Internal\Rest\Self.cs:line 177
   at Starcounter.Server.PublicModelProvider.UpdateDatabase(Database database) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Server\Starcounter.Server\PublicModelProvider.cs:line 77
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 189
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 483
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 194
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\BuildAgent\work\sc-develop-nightly-168\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2147467261
"
"ScErrServerCommandFailed (SCERR10011): The operation ""Stopping 9BA1A4559884CE2EEB543902EF69BBD9FBE98583"" failed.
Version: 2.1.1135.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011."

**Comment by andwah** [comment] 2016-06-02 11:41
I think this can be closed.  
The problems where in `Session.ScheduleTask` that Administrator used to send messages to the clients, the related issues are already fixed and closed i think.

**Comment by dan31** [comment] 2017-03-15 23:25
I will follow an @andwah advise there.

**Closed by dan31** 2017-03-15 23:25 UTC
Labels: Administrator, bug, duplicate, Management, Visual Studio
