### ISSUE TITLE
Distributing Bison and Flex with Level0

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#1289] opened 2013-11-08 12:08 UTC
Currently, the binaries of Bison and Flex are included into level0 repository. A better mechanism for distribution should be implemented.

**Comment by Starcounter-Jack** [comment] 2015-01-29 22:43
@parherman 
@linkdata 
Do you two agree on this or should we close this (old) issue?

**Comment by parherman** [comment] 2015-02-02 07:00
We can look over this when we move SqlProcessor to cmake in the develop branch, since the binaries are distributed there.

**License for flex:**
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
 1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

**License for bison is GPLv3** 
But I guess that means we only need to be able to provide the source to bison on request?

**Comment by Starcounter-Jack** [comment] 2015-02-02 07:06
We don't distribute the Bison binary, do we?

**Comment by parherman** [comment] 2015-02-02 07:12
Right now it is in the separate repo I have prepared for @k-rus, I guess it would be a good idea to remove it from there

**Comment by parherman** [comment] 2015-02-02 07:34
We only use unmodified binaries of flex and bison that are only used in build steps. I will check in the respective licenses files in the separate SqlProcessor repo.

For level0 i suggest that we remove the binaries and have cmake warn if they are not found during build

**Comment by dan31** [comment] 2015-02-02 21:38
Only results of tools'  work is used (generated code in C language). The code generated by Flex does not depend on any runtime or external library except for a memory allocator from standard library like msvcr or libstdc++ (malloc or a user-supplied alternative) unless the input also depends on it. The code generated by Bison includes significant amounts of code from the Bison project itself. The Bison package is distributed under the terms of the GNU General Public License (GPL) but an exception has been added so that the GPL does not apply to output: https://www.gnu.org/software/bison/manual/html_node/Conditions.html.

**Comment by k-rus** [comment] 2015-02-04 06:54
> Right now it is in the separate repo I have prepared for @k-rus, I guess it would be a good idea to remove it from there

The repo has nothing to do with our developers.

Bison and Flex are needed to build SqlProcessor, so it is part of developer environment. To avoid unnecessary steps for developers the binaries are distributed together with the source code. This is not recommended way, but no other better way is suggested.

**Comment by dan31** [comment] 2015-02-10 23:46
It's fine to have Bison and Flex stored in a repo as binaries. In confidence, other companies do the same. It's not a recommended way, but you prefer not to compile them from sources. We never redistributed Bison and Flex.

**Closed by dan31** 2015-02-10 23:46 UTC
Labels: Build System, Infrastructure, SQL
