### ISSUE TITLE
Modeling JSON entity and a collection of such entities

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#4178] opened 2017-03-23 09:01 UTC
Having JSON + code behind such as:

```json
{
  "Foo": "",
  "Bar": [{
    "Baz": 0
  }]
}
```

```csharp
[Fubar_json]
partial class Fubar : Json {}
```

What's the simplest way to declare typed JSON that represent a collection of such entries?

Searched our docs for something to copy-paste as a template, but couldn't find any relevant info on this. Isn't it a quite common case, and something we want documented?

**Comment by per-samuelsson** [comment] 2017-03-23 09:11
To clarify further:

I want the simplest way to declare JSON (and, if needed, code-behind) that allow me to programmatically create a collection-like instance that, when serialized to JSON, become a document that is a collection/array of `Fubar` instances.

**Comment by chrhol** [comment] 2017-03-23 09:30
It's not directly documented. Indirectly you can find some info about arrays on this page: https://docs.starcounter.io/guides/typed-json/primitive-arrays-and-single-value-types/, that is: a json-document doesn't have to be an object. You can declare it as any supported value like array.

So, I guess the easiest is like this:
```json
[
  {
    "Foo": "",
    "Bar": [{
      "Baz": 0
    }]
  }
]
```

```csharp
[FubarCollection_json]
partial class FubarCollection {
}
```

One thing to notice in the code above though, is that you don't specify the inheritance on `FubarCollection`. That's because arrays doesn't inherit directly from `Json`. The inheritance will be added in the generated code. (A bit inconsistent from how everything else works...you can specify it yourself but you need to use `Arr<T>` where `T` is the type of the item, in this case `Fubar`)

And then use it like this: 
```csharp
class Program {
     static void Main() {
          var myFubars = new FubarCollection();

          var fubar = myFubars.Add();
          fubar.Foo = "Item1";

          fubar = myFubars.Add();
          fubar.Foo = "Item2";
          fubar.Bar.Add();

          Console.WriteLine(myFubars.ToJson());
    }
```

Output:
```
[{"Foo":"Item1","Bar":[]},{"Foo":"Item2","Bar":[{"Baz":0}]}]
```

**Comment by per-samuelsson** [comment] 2017-03-23 09:49
Aha, so it's kind of the opposite to what I tried (and what you would do in a normal programming language). The common approach there is:

1. Define the element type. This type is not at all aware of that there are collections of it.
2. Create a collection of that element type.

If I understand your example correct, you define the collection type, and *enclosed* in that is the element types. And then, if I want a standalone element instance, I have to do:

```csharp
object CreateFubarInstance() {
  var myFubars = new FubarCollection();
  return myFubars.Add();
}
```

Two questions then:

1. Is there a way to instantiate an element without a collection instance?
2. What is the programming-language type of the element (i.e. how can I type the return value of `CreateFubarInstance` better)?

**Comment by chrhol** [comment] 2017-03-23 09:54
I will add another sample later, that does what you want I think. You asked for the simplest way though, and this in my opinion, the simplest. Perhaps not the best. It depends on what you want to use it for.

**Comment by per-samuelsson** [comment] 2017-03-23 09:55
Maybe I can be even clearer with a very simple code sample (not involving JSON):

```csharp
public class Fubar {
  public string Bar;
}

public class Server {
  
  public Fubar CreateSingleFubar() {
    return new Fubar() { Bar = "Hello" ; }
  }

  public IList<Fubar> CreateCollectionOfFubarsWithOneInstance() {
    return new List<Fubar>(new [] { CreateSingleFubar() });
  }
}

class Client {
  void Main() {
    var server = new Server();

    Console.WriteLine(server.CreateSingleFubar().Foo);
    foreach (var f in server.CreateCollectionOfFubarsWithOneInstance()) {
      Console.WriteLine(f.Foo);
    }
  }
}
```

**Comment by per-samuelsson** [comment] 2017-03-23 10:00
I think what seem quite close from my perspective is **Example 3** in this page:

https://docs.starcounter.io/guides/typed-json/primitive-arrays-and-single-value-types/

But I want to restrict elements of the array to be of `Fubar` type.

**Comment by per-samuelsson** [comment] 2017-03-23 10:17
I found at least one simple approach that seem to work:

Add a new Typed JSON (`FubarCollection.json`) without code-behind, have the only content like this:

```json
[ { } ]
```

Then I can use that such as:

```csharp
void Test() {
  var c = new FubarCollection();
  c.Add(new Fubar());

  Console.WriteLine(c.ToJson());
}
```

**Comment by per-samuelsson** [comment] 2017-03-23 11:00
After some more testing and discussions with @chrhol, we suggest to add this use-case to the [cookbook](https://docs.starcounter.io/cookbook/).

Here's the proposed story:

You have a typed JSON type:

`Person.json`
```json
{
  "Name": "Per"
}
```

`Person.json.cs`
```csharp
using Starcounter;

namespace TypedJSONCollectionSample {
    partial class Person : Json {
    }
}
```

Now, you want to support a strongly typed collection of that type.

First, create a new **Starcounter Typed JSON with code-behind** item, name if "PersonCollection".

Then, adapt content of collection files to this:

`PersonCollection.json`
```json
{
  "Items": [{}]
}
```

`PersonCollection.json.cs`
```csharp
using Starcounter;

namespace TypedJSONCollectionSample {
    partial class PersonCollection : Json {
      static PersonCollection() {
        DefaultTemplate.Items.ElementType.InstanceType = typeof(Person);
      }
    }
}
```

Now, you can create instances of `Person` and collections of such as this:

```csharp
void Main() {
  var p = new Person() { Name = "Per" };
  var c = new Person() { Name = "Christian" };

  var both = new PersonCollection();
  both.Items.Add(p);
  both.Items.Add(c);

  Console.WriteLine(p.ToJson());
  Console.WriteLine(c.ToJson());
  Console.WriteLine(both.ToJson());
}
```

**Comment by Mackiovello** [comment] 2017-03-23 11:16
This look really useful!

> @Mackiovello, at some point, and after @chrhol has had his say, can you realize it?

Of course, I'll take care of it.

**Comment by careri** [comment] 2017-03-23 18:35
I think I'm missing the point of this. In what way is it better than:
''''cs
Arr<Fubar>
''''
Is it harder to serialize an are?

**Comment by chrhol** [comment] 2017-03-24 06:30
>I think I'm missing the point of this. In what way is it better than:

We discussed this as well. I hadn't even considered using `Arr<T>` to specify the type to use for the *template*, which is what happens when you set instancetype as well as typing it to a specific type for the instance. So in short: this needs to be investigated and updated so that it works without sideeffects in XSON. Because of this we decided to use what we know work as intended for our cookbook.

I think though that we can use the same syntax as in the first solution that @per-samuelsson used, `[ { } ]`.

The following is an adaptation of the sample:

`PersonCollection.json`
```json
[{}]
```

`PersonCollection.json.cs`
```csharp
using Starcounter;

namespace TypedJSONCollectionSample {
    partial class PersonCollection {
      static PersonCollection() {
        DefaultTemplate.ElementType.InstanceType = typeof(Person);
      }
    }
}
```

Now, you can create instances of `Person` and collections of such as this:

```csharp
void Main() {
  var p = new Person() { Name = "Per" };
  var c = new Person() { Name = "Christian" };

  var both = new PersonCollection();
  both.Add(p);
  both.Add(c);

  Console.WriteLine(p.ToJson());
  Console.WriteLine(c.ToJson());
  Console.WriteLine(both.ToJson());
}
```

@per-samuelsson, @Mackiovello: is this better or worse? Using an array directly in json-by-example is something that is not common, and that is not well documented so maybe we want to avoid it just because of that?

**Comment by per-samuelsson** [comment] 2017-03-24 07:38
> @per-samuelsson, @Mackiovello: is this better or worse?

For me, it's a very close call, as we discussed yesterday. The second approach is less lines of code, and I like the fact that you can just do `collection.Add(o)` instead of `collection.Items.Add(o)`.

The drawbacks of the second approach:

* It seem less tested / might be unstable
* Like you say: *Using an array directly in json-by-example is something that is not common*.
* It's also uncommon for code-behind not to extend `Json`

At this point, with a gun to my head, I think I'd choose the first approach. I'm totally fine if we don't though. You make the call @chrhol.

**Comment by Mackiovello** [comment] 2017-03-24 07:45
> @per-samuelsson, @Mackiovello: is this better or worse?

I would like to document the most reliable approach and then add a note on the bottom that mentions that it's also possible to use this second approach if they feel adventurous.

**Comment by chrhol** [comment] 2017-03-24 08:07
> I would like to document the most reliable approach and then add a note on the bottom that mentions that it's also possible to use this second approach if they feel adventurous

Yes, let's do that!

**Comment by per-samuelsson** [comment] 2017-03-24 08:08
Considering it some more, there is another advantage of the first approach (i.e "Items"): if you later want to **add** some property to the collection, it's straightforward in that solution:

`PersonCollection.json`
```json
{
  "Items": [{}]
}
```

=>

`PersonCollection.json`
```json
{
  "Items": [{}],
  "LastModified" : "20170324-09.06"
}
```

It's quite complex in the second one, using `Arr<T>`.

**Comment by per-samuelsson** [comment] 2017-03-24 08:09
> I would like to document the most reliable approach and then add a note on the bottom that mentions that it's also possible to use this second approach if they feel adventurous.

Until we know there is actually some great advantage of `Arr<T>`, I think we shouldn't even mention it. Less is more. Multiple suggestion tend to confuse more than offer help.

**Comment by Mackiovello** [comment] 2017-03-24 14:49
Fixed in https://github.com/Starcounter/Docs/commit/7abf7ccb3f273aebb40754e52a4ebafae6f44b5c

**Closed by Mackiovello** 2017-03-24 14:49 UTC
Labels: Knowledge base, question, Typed JSON
