### ISSUE TITLE
Web Administrator SQL is showing null value as zero. (Nullable<Int32>) v2.4.0.1263

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#4155] opened 2017-03-16 21:58 UTC

**Comment by miyconst** [comment] 2017-03-16 22:01
This is a duplicate of - [Allow C# null(able) values in JSON and allow mapping C# null values to JSON omitted field](https://github.com/Starcounter/Starcounter/issues/3694).

Currently Typed JSON does not support nullable numeric data types, that is why NULLs are shown as zeroes.

**Closed by miyconst** 2017-03-16 22:01 UTC
Labels: duplicate

**Comment by SenerDemiral** [comment] 2017-03-16 22:20
But Nullable<DateTime> field can be shown NULL

**Comment by miyconst** [comment] 2017-03-16 22:28
>But Nullable field can be shown NULL

Yes, it is just not implemented.

**Comment by SenerDemiral** [comment] 2017-03-16 22:32
Nullable DateTime field already shown NULL

**Comment by miyconst** [comment] 2017-03-16 22:43
As I already said, yes, it is possible to show `NULL` for nullable numeric values when the value is NULL, it's just not implemented yet. And this issue is a duplicate of an already existing one.

**Comment by SenerDemiral** [comment] 2017-03-17 05:12
Thank you for your patient.
