### ISSUE TITLE
Issues accessing our public website

### ISSUE THREAD

**Issue by aasah** [Starcounter/Starcounter#1533] opened 2014-01-27 12:19 UTC
When I write www.starcounter.com in explorer I get a white screen with the following text "System.IO.IOException: Remote host closed the connection. at Starcounter.NodeTask.PerformSyncRequest()"

**Comment by Starcounter-Jack** [comment] 2015-01-29 22:47
@per-samuelsson 
Status?

**Comment by Starcounter-Jack** [comment] 2015-01-29 22:47
@dan31 Is this fixed?

**Comment by dan31** [comment] 2015-01-29 23:03
If I remember correctly, #2293 was the fix for that particular problem. It was defined and fixed by @alemoi, @per-samuelsson and me. Correct me if I'm wrong, guys.

**Comment by alemoi** [comment] 2015-01-31 21:42
As I remember there was a problem with serving static file resources that could be the cause for the above problem. The problem with static file resource should be already fixed. Closing the issue until it appears again.

**Closed by alemoi** 2015-01-31 21:42 UTC
Labels: bug, can't reproduce

**Comment by dan31** [comment] 2015-01-31 22:19
Okay, now I recalled the case. Concurrent access to a static resource was a cause for it. No test exists for the bug, @alemoi suggested it's not hard to reproduce in test case however (jot down for @parherman).
