### ISSUE TITLE
Unhelpful weaver error when using arrays in database classes

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter#4089] opened 2017-02-10 10:20 UTC
When running code such as this:

```cs
[Database]
public class Person
{
    public Animal[] Pets;
}
```

The following weaver error is displayed:
![weavererror](https://cloud.githubusercontent.com/assets/19392292/22823010/2f67ebf0-ef82-11e6-90e3-f8a24c90a184.PNG)

And the log displays this:
```System.Exception: ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 1
Version: 2.3.0.5651.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030.
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__2(CommandTask task) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-2182\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2030
```

They are not very helpful in finding out what's wrong. The only really useful thing for me here is `Cannot find the method DbState.ReadArray`. It's also not clearly communicated that arrays in database classes are not allowed. 

Could something be done to communicate what's wrong more clearly?

**Comment by per-samuelsson** [comment] 2017-02-10 10:42
> Could something be done to communicate what's wrong more clearly?

Well certainly. It just involves some work, because error propagation is still somewhat of a pain.

**Comment by per-samuelsson** [comment] 2017-03-17 08:13
I looked into this (seeing it was a 2.3 prio) and found the cause: a loooong time ago, we supported arrays to be defined with these premises:
1. Single dimension
2. Type of elements was database types

The implementation was really crappy though (prototype-ish), so probably something got lost in the runtime but the weaver was never informed about it.

I'll take it, and make sure it produce a better error. @Mackiovello, meanwhile, if there is some place where we list supported data types, can you please adapt saying arrays are not at all supported?

**Comment by Mackiovello** [comment] 2017-03-17 08:37
> I'll take it, and make sure it produce a better error. @Mackiovello, meanwhile, if there is some place where we list supported data types, can you please adapt saying arrays are not at all supported?

There seem to be cases when the error above does not show up. When trying to create a new Starcounter Application with the code below, I get this error, which is much better: 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The data type is not supported. The data type of a field or property in an Entity class is not supported by the database. Attribute: Test.Person.strings (System.String[]) (ScErrUnsupportedAttributeType (SCERR4012))
```

```cs
[Database]
public class Person
{
    public string[] strings;
}
```

I'll make a note on the appropriate page of which collections that are supported

**Comment by Mackiovello** [comment] 2017-03-17 08:39
The issue in the OP only occurs when the array is created of database objects.

**Comment by per-samuelsson** [comment] 2017-03-17 08:39
> There seem to be cases when the error above does not show up.

No, you are not doing the same thing. That's what I tried explaining here:

> I looked into this (seeing it was a 2.3 prio) and found the cause: a loooong time ago, we supported arrays to be defined with these premises:
> 1. Single dimension
> 2. Type of elements was database types

**Comment by per-samuelsson** [comment] 2017-03-17 08:40
> The issue in the OP only occurs when the array is created of database objects.

Exactly. See my previous comments. I produce a proper error already for array types we have never supported (like primitives). It's just database class arrays that is flawed.

**Comment by Mackiovello** [comment] 2017-03-17 08:50
> Exactly. See my previous comments. I produce a proper error already for array types we have never supported (like primitives). It's just database class arrays that is flawed.

Is it correct that the only collections that are supported are in the `System.Collections` namespace?  These collections have to be read only to work. Is that how it works? Both `ArrayList` and `IEnumerable` seems to work when they only have a getter.

**Comment by per-samuelsson** [comment] 2017-03-17 08:54
> Is it correct that the only collections that are supported are in the `System.Collections` namespace?  These collections have to be read only to work. Is that how it works? Both `ArrayList` and `IEnumerable` seems to work when they only have a getter.

I'm not sure tbh. I think it has changed quite a bit over time. I can try find out by studying the code I guess. Maybe @chrhol know?

**Comment by per-samuelsson** [comment] 2017-03-17 11:49
> Is it correct that the only collections that are supported are in the System.Collections namespace? These collections have to be read only to work. Is that how it works? Both ArrayList and IEnumerable seems to work when they only have a getter.

I considered this some more, and even looked at code and documentation.

What confused me was that you sounded so sure that we even support *any* collection type, and the answer to that is: we do, and we don't. 😸 

Here's how it works:

In any database class, if you have either

1. a field, or
2. an auto-implemented property

we take some action on it. We analyse it and consider it as you want us to store that in the database. To store things, the data type of that declaration must be supported, or else we'll raise an error.

Now, what you probably referred to with 

> Both `ArrayList` and `IEnumerable` seems to work when they only have a getter.

was when you *explicitly declared a body*, and then yes, then you can declare whatever, i.e

```csharp
public List<string> Branches {
  get { return new List<string>(); }
}
```

At least as far as the weaver is concerned.

Try instead this and you'll see an error:
```csharp
public List<string> Branches { get; }
```

**Comment by per-samuelsson** [comment] 2017-03-17 12:51
Done. Merged and pushed in https://github.com/Starcounter/Starcounter/commit/88d8bb19bc581aa987cb32816dc3c452f36d20a2.

Merge to develop remains, but getting some weird new conflicts there on bower. Then fully done.

**Closed by per-samuelsson** 2017-03-17 12:51 UTC
Labels: ScError, usability, Weaver

**Comment by Mackiovello** [comment] 2017-03-17 15:35
This is now documented on the bottom of [this page](https://docs.starcounter.io/v/2.1.177/guides/database/datatypes/)

**Comment by per-samuelsson** [comment] 2017-03-17 15:41
> This is now documented on the bottom of [this page](https://docs.starcounter.io/v/2.1.177/guides/database/datatypes/)

Great. 

I'm not sure this is correct though:

> they will instead become code properties **that can be accessed in SQL queries**

For primitive types that are not database columns, it should work (but will not do so for sure in future versions). For collection types, I don't think they can be used.

**Comment by Mackiovello** [comment] 2017-03-17 15:45
> For primitive types that are not database columns, it should work (but will not do so for sure in future versions). For collection types, I don't think they can be used.

Then I must have misinterpreted the intro on [this page](https://docs.starcounter.io/guides/database/creating-database-classes/):

> Public fields (e.g., Person.FirstName and Quote.Person), public auto-created properties (e.g., Person.LastName) and public properties getting and setting private fields (e.g., Quote.Text) become database columns. More complex public properties become code properties, which are not stored as columns, but can be accessed in SQL queries (e.g., Person.FullName).

I'll try and see what happens.

**Comment by per-samuelsson** [comment] 2017-03-17 15:51
> Then I must have misinterpreted the intro on this page:

Well, like I wrote, it applies to primitives, but not collection types, which kind of make sense IMO. How could you perform a SQL WHERE on a `IList` for example.

Hence, some like this:

```csharp
public string Version {
  get {
    return File.ReadAllText("version.txt");
  }
}
```

will allow you to query on `Version` in a WHERE clause, but as you can see, it's not a database value. Having some collection type will make the SQL engine helpless though (I think).

**Comment by Mackiovello** [comment] 2017-03-17 15:52
Yea, that is understandable.

This still works, which makes sense:
```cs
 [Database]
public class Person
{
    public string[] Stuff => new string[] { "stuff", "stuff" };
    public string Something;
}
class Program
{
    static void Main()
    {
        Db.Transact(() =>
        {
            new Person
            {
                Something = "somethign"
            };
        });

        Person dude = Db.SQL<Person>("SELECT p FROM Person p").First;
        var dudeStuff = dude.Stuff;
    }
}

**Comment by Mackiovello** [comment] 2017-03-17 16:03
This is correct then https://github.com/Starcounter/Docs/commit/c37b9bcc08c11a5ebb3ff26a13cee015d59bc795?

**Comment by per-samuelsson** [comment] 2017-03-17 16:06
> This still works, which makes sense:

Of course it does. I think you are mixing things up: what works in the *language* and in our language *binding* is not 1-1 what works in the *query language*. In your example, you can't do:

 ```csharp
Db.SQL<Person>("SELECT p FROM Person p where p.Stuff[0] =='stuff'").First;
```

or similar. That is what I'm exclusively try to express in all my above comments.

**Comment by per-samuelsson** [comment] 2017-03-17 16:07
> This is correct then Starcounter/Docs@c37b9bc?

Yes. That fix the concern I had. 👍

**Comment by Mackiovello** [comment] 2017-03-17 16:08
> That is what I'm exclusively try to express in all my above comments.

It's getting clearer. I'm just a little slow at times 😄 Thank you for helping out!

**Comment by per-samuelsson** [comment] 2017-03-17 16:11
> I'm just a little slow at times.

Who aren't? 😄 And most of the time you are exactly the opposite! No worries, and well done as usual.

**Comment by dan31** [comment] 2017-03-21 16:07
Wow, you've addressed it. Awesome job!
