### ISSUE TITLE
Assertion failed, _commit_create_index

### ISSUE THREAD

**Issue by careri** [Starcounter/Starcounter#2951] opened 2015-10-14 06:09 UTC
C:\Program Files\Starcounter\2.1.26.2

Got this exception when I started an existing database, not quite sure of the changes I made since last start. But I don't think I changed database-classes.

**I attached the environment as a 7z. But since uploading a 7z isn't allowed I renamed it to png.**

>Assertion failed (FreeLibrary(hmodule)) at ..\..\src\sccoredb\kernel\SchemaAPI.cpp:2337 (Data 0).
    00007FFEC5E211D3 sccoredbg!_DumpCallstack : callstack-win.cpp (120)
    00007FFEC5E2114C sccoredbg!do_handle_assertion_failed : assert-win.cpp (77)
    00007FFEC5E21039 sccoredbg!handle_assertion_failed : sccoredbg.cpp (29)
    000000422F5659C4 sccoredb!handle_except_creating_sys_index_entry_or_inserting_existing_records : schemaapi.cpp (2337)
    000000422F57240D sccoredb!`_commit_create_index'::`1'::filt$0 : schemaapi.cpp (2376)
    00007FFEB6FCE98B MSVCR110!
    00007FFED938633D ntdll!
    00007FFED9303C00 ntdll!
    00007FFED938544A ntdll!
    00007FFED612A1C8 KERNELBASE!
    000000422F53421F sccoredb!_TTreeInternalInsert<16> : tt_insert.cpp (859)
    000000422F533B3E sccoredb!_TTreeInsert<16> : tt_insert.cpp (128)
    000000422F533ADB sccoredb!_TTreeIndexInsert : tt_index.cpp (658)
    000000422F56EE00 sccoredb!insert_existing_records_into_index : schemaapi.cpp (2172)
    000000422F5712CD sccoredb!_commit_create_index : schemaapi.cpp (2375)
    000000422F56ACAE sccoredb!__commit_create_index : serialized.cpp (1285)
    000000422F56B050 sccoredb!__update_schema_task_execute : serialized.cpp (1030)
    000000422F5C104F sccorelib!pluto_enqueue_and_execute : enqnexec.c (42)
    000000422F56A24F sccoredb!__create_drop_or_alter_schema_object : sccoredb.cpp (4758)
    000000422F56A492 sccoredb!star_create_index : sccoredb.cpp (4657)
    00007FFE6D6727AD <unknown>!

![careri_assertion_failed](https://cloud.githubusercontent.com/assets/4263597/10476069/e2b122e6-724a-11e5-9821-103ed9b387d2.png)

**Comment by chrhol** [comment] 2015-10-14 07:05
Hi Carl, thanks for reporting this.

Is it reproducible so you get it every time you start the database? And do you still have the image and transactionlog files available?

**Comment by chrhol** [comment] 2015-10-14 07:07
Sorry, too early to read correctly apparently :) Just saw that you already attached it

**Comment by careri** [comment] 2015-10-14 07:07
The environment is attached as I wrote above ;)

I deleted my images and continued working.

**Comment by chrhol** [comment] 2015-10-14 07:13
What version of Starcounter are you using?

**Comment by chrhol** [comment] 2015-10-14 08:18
I've been able to reproduce it using the attached app and datafiles, running latest develop debug version of Starcounter and got almost the same stacktrace

> Assertion failed (FreeLibrary(hmodule)) at ..\..\src\sccoredb\kernel\SchemaAPI.cpp:2339 (Data 0).
    00007FFBD903164F sccoredbg!_DumpCallstack : callstack-win.cpp (120)
    00007FFBD903152A sccoredbg!do_handle_assertion_failed : assert-win.cpp (76)
    00007FFBD90312F6 sccoredbg!handle_assertion_failed : sccoredbg.cpp (30)
    0000008BFAF4AAD6 sccoredb!handle_except_creating_sys_index_entry_or_inserting_existing_records : schemaapi.cpp (2339)
    0000008BFAF6691B sccoredb!`_commit_create_index'::`1'::filt$0 : schemaapi.cpp (2378)
    00007FFBC6E2217E MSVCR110D!
    00007FFBE2E7633D ntdll!
    00007FFBE2DF3C00 ntdll!
    00007FFBE2DF21C4 ntdll!
    00007FFBE02FA1C8 KERNELBASE!
    0000008BFAF1D946 sccoredb!__handle_insert_unique_contraint_violation : tt_insert.cpp (927)
    0000008BFAF1F23D sccoredb!_TTreeInternalInsert<16> : tt_insert.cpp (861)
    0000008BFAF1D855 sccoredb!_TTreeInsert<16> : tt_insert.cpp (125)
    0000008BFAF1C86F sccoredb!_TTreeIndexInsert : tt_index.cpp (658)
    0000008BFAF29F02 sccoredb!insert_entry_into_ttree_index : c_postwins.cpp (17)
    0000008BFAF5D5BA sccoredb!insert_existing_records_into_index : schemaapi.cpp (2174)
    0000008BFAF5AAA1 sccoredb!_commit_create_index : schemaapi.cpp (2377)
    0000008BFAF57CD1 sccoredb!__commit_create_index : serialized.cpp (1282)
    0000008BFAF575BE sccoredb!__update_schema_task_execute : serialized.cpp (1030)
    0000008BFAF57439 sccoredb!_create_index_task_execute : serialized.cpp (976)
    00000087FE96110A sccorelib!pluto_enqueue_and_execute : enqnexec.c (42)
    0000008BFAF56D48 sccoredb!__create_drop_or_alter_schema_object : sccoredb.cpp (4754)
    0000008BFAF56973 sccoredb!star_create_index : sccoredb.cpp (4657)
    00007FFB670D691A <unknown>!

Debugging the code and adding a breakpoint for `sccoredb!__handle_insert_unique_contraint_violation : tt_insert.cpp (927)` I can see that it originates from ` 	Heads_BootApp.dll!Heads.BootApp.Startup.DatabaseIndexManager.EnsureIndexes.AnonymousMethod__1() Line 53`

Snippet of the first few lines of debugging stacktrace:
>  	Heads_BootApp.dll!Heads.BootApp.Startup.DatabaseIndexManager.EnsureIndexes.AnonymousMethod__0() Line 39 + 0x33 bytes	C#
 	Heads.Scdb.Commons.dll!Heads.Scdb.Commons.ScdbHelper.RunAttached.AnonymousMethod__3() Line 82 + 0x1b bytes	C#
 	Starcounter.dll!Starcounter.DbSession.RunSync.AnonymousMethod__5() Line 157 + 0x1f bytes	C#
 	Starcounter.dll!Starcounter.Task.Run() Line 76 + 0x1b bytes	C#


I'm not sure why it terminates with an assertion failure instead of returning exception to usercode, @eriohl do you have any idea. Is it a bug in the kernel or are something going wrong in the codehost?

**Comment by eriohl** [comment] 2015-10-14 08:39
It tries and fails to unload the module (DLL) loaded for the index when aborting the index generation. Since in-memory code generation was introduced no DLL is loaded, which is probably the reason for the failure, so this seems some code left since before this was introduced that should have been removed.

So just drop the call to FreeLibrary and it should work better I think.

**Comment by chrhol** [comment] 2015-10-14 08:47
Thanks! I will assign it to @alemoi then.

**Comment by eriohl** [comment] 2015-10-14 11:11
I can check it next week. Or you could use remove call to FreeLibrary and check if is solves the problem when you have the reproduce up and running. There should be no FreeLibrary in the kernel now that in-memory code generation has been adopted.

**Comment by alemoi** [comment] 2015-10-14 11:20
I will fix it! Probably missed a check when unloading modules.

**Comment by alemoi** [comment] 2015-10-14 13:55
Just checked the code and found that for this specific case the NULL value was not checked for module (with in-memory codegen I set hModule to NULL). We tested on @chrhol machine and he will push the fix. Thank you for reporting and thanks for testing @chrhol !

**Comment by chrhol** [comment] 2015-10-14 14:03
Pushed!

**Closed by chrhol** 2015-10-14 14:03 UTC
Labels: bug
