### ISSUE TITLE
Json error happens now and then disconnecting server

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#3801] opened 2016-08-23 07:08 UTC
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.XSON.JsonProperty.EvalutateCurrent(JsonPointer ptr, ViewModelVersion version, Boolean& nextIsIndex) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1986\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 120
   at Starcounter.XSON.JsonProperty.<>c.<DoEvaluate>b__11_0(JsonProperty prop, JsonPointer ptr, ViewModelVersion pv, Boolean isIndex) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1986\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 81
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2,T3,T4,TResult](Json json, Func`5 func, T1 arg1, T2 arg2, T3 arg3, T4 arg4) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1986\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 231
   at Starcounter.XSON.JsonProperty.DoEvaluate(JsonPointer pointer, Json root) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1986\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 79
   at Starcounter.XSON.JsonProperty.Evaluate(JsonPointer pointer, Json root) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1986\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 59
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, IntPtr valuePtr, Int32 valueSize) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1986\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 18
   at Starcounter.XSON.JsonPatch.Apply(Json root, IntPtr patchArrayPtr, Int32 patchArraySize, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1986\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 682
   at Starcounter.XSON.JsonPatch.Apply(Json root, Byte[] patchArray, Boolean strictPatchRejection) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1986\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 522
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(Byte[] bs, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1986\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 57
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1986\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 288
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-daily-1986\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 784
HResult=-2147467261
```

**Comment by chrhol** [comment] 2016-08-23 07:11
Thank you for reporting this. 

Do you have some way to reproduce it? Looking at the code it can be a couple of different things that causes it. Most likely cause is that a property that holds a jsonobject is set to null (which is handled very poorly in all areas currently in TypedJSON).

**Comment by malx122** [comment] 2016-08-23 07:18
Not in any consistent way... but I will keep an eye out for a null next time

**Comment by warpech** [comment] 2016-09-14 14:57
@chrhol these errors happen a lot as you are aware. And they are very hard to track.

Would it be possible to enhance this exception with information what JSON property failed exactly, and what was the patch sequence that caused it to fail?

**Comment by warpech** [comment] 2016-09-14 14:57
@chrhol these errors happen a lot as you are aware. And they are very hard to track.

Would it be possible to enhance this exception with information what JSON property failed exactly, and what was the patch sequence that caused it to fail?

cc @Mnosek

**Comment by chrhol** [comment] 2016-11-30 09:55
I will close this issue since we never found a cause of it. I created another issue for enhancing the message to make it easier to try to find out what happened.

**Closed by chrhol** 2016-11-30 09:55 UTC
Labels: bug, Puppets, Typed JSON
