### ISSUE TITLE
Uninstalled v2.4.0.618 and installed v2.4.0.797

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Starcounter#4068] opened 2017-01-29 14:42 UTC
When try to start personal server:

> Additional information: Could not load file or assembly 'Starcounter.Hosting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf' or one of its dependencies. The system cannot find the file specified.

**Comment by SenerDemiral** [comment] 2017-01-29 15:18
Same error on v2.4.0.787.
On v2.4.0.775 server started, but run with VS2015 fallowing error:

> Severity	Code	Description	Project	File	Line	Suppression State
Error		The data type is not supported. The data type of a field or property in an Entity class is not supported by the database. Attribute: TTDB.Parent.__sc__this_binding__ (Starcounter.Binding.TypeBinding) (ScErrUnsupportedAttributeType (SCERR4012))

I Changed SessionOptions with Session.Flags and worked!

**Comment by per-samuelsson** [comment] 2017-01-30 08:53
@SenerDemiral 

2.4/Develop is our bleeding edge bits and we are in the middle of some rather large redesign work regarding development- and hosting models. The problems you are experiencing are likely caused by that.

We will write some documentation eventually, describing stuff that need to be done in order to make the jump, but we are not really there yet.

**Comment by SenerDemiral** [comment] 2017-01-30 09:02
Thank you.
Is it too early to work in v2.4?

**Comment by per-samuelsson** [comment] 2017-01-30 10:43
> Is it too early to work in v2.4?

It's not at all production-ready of course. But feel free to try out any version we publish. Just  now that the support for such versions will not be prioritized, and the road might be bumpy at times. 😎

**Comment by SenerDemiral** [comment] 2017-01-30 11:14
I wish I knew what was going on.

**Comment by per-samuelsson** [comment] 2017-01-31 09:58
> I wish I knew what was going on.

Regarding the first error its fixed with #4071.

My *guess* is that the other error happen because you haven't rebuilt your app with 2.4 installed, which is a requirement. I'll document that eventually, and we're also about to add some code verifying such cases to help the user, but it's not yet in place.

**Comment by SenerDemiral** [comment] 2017-01-31 19:42
v2.4.0.841 is OK

**Comment by per-samuelsson** [comment] 2017-02-01 06:15
> v2.4.0.841 is OK

👍

**Closed by per-samuelsson** 2017-02-01 06:15 UTC
