### ISSUE TITLE
pnext: Implement schema upgrade

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3142] opened 2015-12-03 18:19 UTC
Now metalayer provides an API function to alter table and add columns. What it does it creates layout and updates metadata. The function returns metalayaer handle. So the schema updates, need to decide about the upgrade, call the metalayer function with columns to add, retrieve layout handle and update .net metadata such as type binding into new layout handle. In Level1 the method is in `Starcounter.SqlProcessor.SqlProcessor` and is:
```c#
internal static unsafe extern uint star_alter_table_add_columns(ulong context_handle,
            string full_table_name, STAR_COLUMN_DEFINITION_HIGH* added_columns,
            out ulong new_layout_handle);
```

**Comment by chrhol** [comment] 2015-12-04 09:35
Thanks, I will start working on this today. 

We have discussed a couple of different approaches when it comes to batch-upgrade of existing objects or not. 

1. The schema is changed and metadata is updated but existing objects will still use the old layout. The first time something is written to an object that have an updated layout, the layout will be changed to the new one. This mean that the managed upgrade code will be less complex and be faster to execute. The downside is that the current implementation of indexes in kernel needs to be changed to handle different layouts in a efficient way. Indexes will still work though, but will be slower. 

2. All existing objects will be updated with the new layout during upgrade and indexes recreated. The managed upgrade code will be a bit more complex, due to the need to keep track of partial upgrades, but indexes will perform as they do today without any changes. 

Making indexes work well with different layouts is something that needs to be done whether or not we do the batch-upgrade, so I will start with doing 1) and then when that is in place we can test and see if we can wait for the changes for index, or need to add batch-upgrade.

cc @eriohl

**Comment by eriohl** [comment] 2015-12-04 09:43
Only add columns?

**Comment by k-rus** [comment] 2015-12-04 09:48
> Only add columns?

Yes. It is realistic, since does not require large amount of work. It is also very close to what available now. The only difference is that the type upgrade will not available. As said earlier it is used not so often in comparison with column rename, which is not supported in current version.

**Comment by eriohl** [comment] 2015-12-04 09:51
Keep in mind then that this new layout may be garbage collected since it won't have any indexes referencing it (and no records initially or course). This will always apply if indexes no longer keeps layouts in future. Should we address this in meta-layer or GC?

**Comment by eriohl** [comment] 2015-12-04 09:53
What if a column is removed then? Should it be kept in the table?

**Comment by k-rus** [comment] 2015-12-04 09:54
> Keep in mind then that this new layout may be garbage collected since it won't have any indexes referencing it (and no records initially or course). This will always apply if indexes no longer keeps layouts in future. Should we address this in meta-layer or GC?

Metalayer will reference new layout immediately. I remember you had an issue to address that layouts referenced from metalayer are not GC.

**Comment by k-rus** [comment] 2015-12-04 09:57
> What if a column is removed then? Should it be kept in the table?

This was never supported, since we never remove data automatically.

This can be supported through the means of dropping table. Fixing it requires to fix drop table implementation in Level1. However, manual upgrade is not trivial.

**Comment by eriohl** [comment] 2015-12-04 10:05
> Metalayer will reference new layout immediately. I remember you had an issue to address that layouts referenced from metalayer are not GC.

We didn't really discuss details on this one. So GC then? Then data manager needs to be aware of the meta-data tables so it can check with layouts are referenced by these.

**Comment by eriohl** [comment] 2015-12-04 10:06
> > What if a column is removed then? Should it be kept in the table?

> This was never supported, since we never remove data automatically.

> This can be supported through the means of dropping table. Fixing it requires to fix drop table implementation in Level1. However, manual upgrade is not trivial.

So what happens now if I remove a field from a C# database class?

**Comment by k-rus** [comment] 2015-12-04 10:18
> So what happens now if I remove a field from a C# database class?

The field becomes unavailable through the C# class, but nothing happens with the database. There were discussion long time ago with decision that we never remove data automatically.



> We didn't really discuss details on this one.

You create issue #3087, which I assumed to reflect your decision.



> So GC then? Then data manager needs to be aware of the meta-data tables so it can check with layouts are referenced by these.

I guess the possible solution in meta-layer is to check during meta-layer initialisation that all layout handles are valid. Will it be enough?



> any indexes referencing it

What do you mean by this? Is it record in index referencing or index header referencing?
Another approach is to update index to refer to new layout handle.

**Comment by eriohl** [comment] 2015-12-04 10:46
> So what happens now if I remove a field from a C# database class?

> > The field becomes unavailable through the C# class, but nothing happens with the database. There were discussion long time ago with decision that we never remove data automatically.

So what happens if you change the type of a column? Exception?

**Comment by k-rus** [comment] 2015-12-07 10:19
> So what happens if you change the type of a column? Exception?

Yes.



> Doesn't say much as you can see. Was more a reminder that it had to be dealt with.

Your issues normally do not say much. Thus it is difficult for external to judge if you meant to do the fix or to discuss. Never mind, it is clear now.



> Should be that the GC checks the meta-data tables. Will be a bit of a hazzle maintainin this however when meta-data tables not available to DM. But think we should go with this anyway.

I understand and thus looking into other possible solutions.



> Index has a reference to a layout. We decided not to recreate the indexes for now which means that it will reference the old one. Thus the new layout can be garbage collected.

I am wonder what will happen if index on new layout and the same set specifier is created and the old index is dropped. Will the new index find all records including those having the old layout? If so, it looks for me to be the best choice at the current moment.

**Comment by eriohl** [comment] 2015-12-07 10:59
> > So what happens if you change the type of a column? Exception?

> Yes.

Maybe we should do the token+type key discussed earlier so that column with same token but different type is treated as a different column?

> I am wonder what will happen if index on new layout and the same set specifier is created and the old index is dropped. Will the new index find all records including those having the old layout?

Of course.

**Comment by k-rus** [comment] 2015-12-07 11:39
> So what happens if you change the type of a column? Exception?
> Yes.
> Maybe we should do the token+type key discussed earlier so that column with same token but different type is treated as a different column?

I don't see why we should put any effort in this, but if you feel to adopt kernel, you are welcome. We will adopt meta-layer accordantly. I am more worry about column rename strategy. Should it be supported in the kernel? Which layouts are/will be compatible?

**Comment by k-rus** [comment] 2015-12-07 11:41
> I am wonder what will happen if index on new layout and the same set specifier is created and the old index is dropped. Will the new index find all records including those having the old layout?
> Of course.

Then, my suggestion is that either meta-layer or managed level recreates the index. Let me know if it is bad idea to create new indexes on new layout and drop indexes on the old layout in meta-layer.

**Comment by eriohl** [comment] 2015-12-07 12:13
> Then, my suggestion is that either meta-layer or managed level recreates the index. Let me know if it is bad idea to create new indexes on new layout and drop indexes on the old layout in meta-layer.

I think we should follow the plan previously discussed for now. I will try to work something out as I said.

**Comment by k-rus** [comment] 2015-12-07 12:44
> Then, my suggestion is that either meta-layer or managed level recreates the index. Let me know if it is bad idea to create new indexes on new layout and drop indexes on the old layout in meta-layer.
> I think we should follow the plan previously discussed for now. I will try to work something out as I said.

I just realise that it will not work in future implementation of  indexes when index will not refer to layout, right?

So there are two alternatives:

1. Check all layout handles on meta-layer initialisation. Here we need to be sure that GC will not remove handle after the meta-layer initialisation.
2. Keep track of reference from meta-layer. The implementation will need to be updated when meta-schema is changed.

For option 1, what is a correct way to check if layout handle is valid, `stari_context_get_layout_info`? What is the error code if not found?

**Comment by eriohl** [comment] 2015-12-07 12:59
There is currently no way to check if a handle is valid. A problem with this also it that handles han be reused. So even if valid it might not be the expected layout.

I think that the best approach is to have the GC check the meta-data tables for references. Should be workable but I have not checked it yet.

**Comment by k-rus** [comment] 2015-12-07 13:38
> There is currently no way to check if a handle is valid. A problem with this also it that handles han be reused. So even if valid it might not be the expected layout.

Right. Thank you for the clarification.

**Comment by eriohl** [comment] 2015-12-07 21:21
I am more worry about column rename strategy. Should it be supported in the kernel?

How do you mean?

**Comment by k-rus** [comment] 2015-12-08 06:45
> I am more worry about column rename strategy. Should it be supported in the kernel?
> How do you mean?

It can be implemented in similar way as you suggest for type change. For example, associate for each column in layout three values: name token, type and column identifier. A column identifier is unique within set specifier. Then type and name can be changed, but column still will be the same.

I am not really advocate for complicating layout to support dynamic schema upgrades. In my opinion it is fine to require batch upgrade of all records when column is renamed or its type is changed. On the other side I don't have good user vision.

**Comment by eriohl** [comment] 2015-12-08 08:14
If you want type specific column tokens you could simply have type specific column tokens. Then you can change the value of the token without it affecting anything else.

I'm not sure your variant will actually hold up but it will at the very least have a huge overhead compared to this.

**Comment by chrhol** [comment] 2015-12-08 08:56
I have a first version of the most basic schema upgrade up and running (not pushed though since I need to do more tests). 

- Removed fields from CLR class is kept in metadata/layout
- Added fields are added using metadata layer
- In case of changed type on column an exception is thrown. This also includes changing from a non-nullable to a nullable value (or the other way around).
- No records are updated.
- Indexes are not touched.

I have some questions:


1. `Db.LookupTable` currently only retrieve one layout and creates a `TableDef` from that one. If there are more then one layout, is there some way to determine which one is the latest (in the result from `sccoredb.stari_context_get_layout_infos_by_token`)? I made the assumption now that the last one is the last one created.

2. About `SqlProcessor.star_alter_table_add_columns`
 > The function returns metalayaer handle. [...] and update .net metadata such as type binding into new layout handle
 
 I'm not quite sure what you mean by the last sentence. Will this be different then the existing code that binds the `TypeDef` and maps the propertydefs to columndefs? 
 
3. Is there some way to get the `sccoredb.STARI_LAYOUT_INFO` from the layout I get from `SqlProcessor.star_alter_table_add_columns`. Currently I retrieve the new `TableDef` using `Db.LookupTable` (hence my first question).

4. We decided that existing indexes should not be recreated, but if I dont add any indexes to the new layout I get the following exception when trying to do a query:

	```
 System.Exception: ScErrSqlInternalError (SCERR7000): Unexpected internal error in SQL module. There is no index for type: StarcounterApplication6.FirstTestObj
	```
Is this supposed to work, or do I need to add one index on objectid (or should metadata layer do this)?

**Comment by k-rus** [comment] 2015-12-08 09:19
> Db.LookupTable currently only retrieve one layout and creates a TableDef from that one. If there are more then one layout, is there some way to determine which one is the latest (in the result from sccoredb.stari_context_get_layout_infos_by_token)? I made the assumption now that the last one is the last one created.

Meta-data contains the expected layout, thus using metadata instead of kernel function will help. We can create an API function, which will provide layout handle for the given full table name.



> About SqlProcessor.star_alter_table_add_columns
> 
> The function returns metalayaer handle. [...] and update .net metadata such as type binding into new layout handle
> I'm not quite sure what you mean by the last sentence. Will this be different then the existing code that binds the TypeDef and maps the propertydefs to columndefs?

I think I am wrong in my comment. Since the type and table defs are being created, then it is important to create them with correct layout handle. And I guess this is the source of the problem you reported:



> if I dont add any indexes to the new layout I get the following exception when trying to do a query:
> 
> System.Exception: ScErrSqlInternalError (SCERR7000): Unexpected internal error in SQL module. There is no index for type: StarcounterApplication6.FirstTestObj
> Is this supposed to work, or do I need to add one index on objectid (or should metadata layer do this)?

This might happen if the type binding is stored for the old layout id. Can you debug the problem?



> Is there some way to get the sccoredb.STARI_LAYOUT_INFO from the layout I get from SqlProcessor.star_alter_table_add_columns. Currently I retrieve the new TableDef using Db.LookupTable (hence my first question).

There is `stari_context_get_layout_info` in the kernel. A high level function can be provided by metalayer.

@chrhol Can you create a list of function API, which you need from metalayer? Can you create as separate issue in Level0 repo?

**Comment by chrhol** [comment] 2015-12-08 09:33
> This might happen if the type binding is stored for the old layout id. Can you debug the problem?

Ahh, yes I will debug it. Then it's probably something I missed. Wanted to make sure before I started investigating.

> There is `stari_context_get_layout_info` in the kernel. A high level function can be provided by metalayer.

Yes. I looked at that one, but couldn't figure out how to provide the correct values (didn't spend that much time on it) so that sounds good.

> @chrhol Can you create a list of function API, which you need from metalayer? 

Alright, will do that. 

> Can you create as separate issue in Level0 repo?

Do you mean CompanyTrack or is there some other place for internal Level0 issues?

**Comment by k-rus** [comment] 2015-12-08 09:41
> I'm not sure your variant will actually hold up but it will at the very least have a huge overhead compared to this.

I was guessing this, but this is how I understood your solution. But now I understand that I was wrong. This your comment clarifies this:



> If you want type specific column tokens you could simply have type specific column tokens. Then you can change the value of the token without it affecting anything else.

Good. This basically means no incompatible changes between version, right?
I assume that the change of the value of the token will require to create new layout, right?
Am I understand correctly that the kernel will be responsible for updating layout of a record from its old layout to the expected layout (on write)? In this case the kernel and meta-layer will be updated to have the same interpretation of column token and meta-layer will expose new API function for schema upgrade.

**Comment by k-rus** [comment] 2015-12-08 09:42
> Can you create as separate issue in Level0 repo?
> Do you mean CompanyTrack or is there some other place for internal Level0 issues?

Level0 is a repo in our internal git server. All issues related to meta-layer, which is part of Level0, are created there.

**Comment by chrhol** [comment] 2015-12-08 09:45
> Level0 is a repo in our internal git server. All issues related to meta-layer, which is part of Level0, are created there.

Aha, I wasn't aware that we were using issuetracker there. I thought we only used the ones on github.

**Comment by eriohl** [comment] 2015-12-08 09:46
> Good. This basically means no incompatible changes between version, right?

Not sure what you mean?

> I assume that the change of the value of the token will require to create new layout, right?

By value of the token I meant the string value in the token table. That you can change without affecting anything in the kernel. Might have some implications for log reader and such however.

You can not change the token in an existing layout. This might break indexes so it can not be allowed.

> Am I understand correctly that the kernel will be responsible for updating layout of a record from its old layout to the expected layout (on write)? In this case the kernel and meta-layer will be updated to have the same interpretation of column token and meta-layer will expose new API function for schema upgrade.

Yes. Records are read and written according to the layout provided by the client. If this is not the same as the actual layout on write then the actual layout of the record will change on commit.

**Comment by eriohl** [comment] 2015-12-08 09:51
> Db.LookupTable currently only retrieve one layout and creates a TableDef from that one. If there are more then one layout, is there some way to determine which one is the latest (in the result from sccoredb.stari_context_get_layout_infos_by_token)? I made the assumption now that the last one is the last one created.

This incorrect. There is no guaranteed order between them. You need to get this from meta-data.

Remember that you need to register a type binding for each layout for the type so that type binding can be looked up on layout handle. Also, you need to change the expected layout in the record reference on record fetch (iterator_next, filter_iterator_next and lookup).

**Comment by eriohl** [comment] 2015-12-09 10:45
Just realized that native filter doesn't handle unexpected layouts (but assumes that all records in the result has a compatible layout). Added an [issue](https://github.com/Starcounter/Starcounter/issues/3159) for addressing this. Should not be too:

**Comment by eriohl** [comment] 2015-12-11 12:55
@chrhol: Which branch is these changes in. I'm fixing the [filtering](https://github.com/Starcounter/Starcounter/issues/3159) and I need to fix the type registration in this code.

**Comment by chrhol** [comment] 2015-12-11 13:01
> @chrhol: Which branch is these changes in. I'm fixing the filtering and I need to fix the type registration in this code.

None yet, I only have it in a local branch. Give me a couple of minutes to remove debug stuff and I will push it.

**Comment by chrhol** [comment] 2015-12-11 13:14
> @chrhol: Which branch is these changes in. I'm fixing the filtering and I need to fix the type registration in this code.

Code is pushed to branch `issue\pnext\3142`.

**Comment by eriohl** [comment] 2015-12-11 14:19
> Remember that you need to register a type binding for each layout for the type so that type binding can be looked up on layout handle. Also, you need to change the expected layout in the record reference on record fetch (iterator_next, filter_iterator_next and lookup).

In ```issue\pnext\3142.```, this is not being done properly for the filter iterator at least. The record reference keeps the actual layout handle rather then the expected one after fetch.

**Comment by chrhol** [comment] 2015-12-11 14:52
> In issue\pnext\3142., this is not being done properly for the filter iterator at least. The record reference keeps the actual layout handle rather then the expected one after fetch.

Yes, this I missed. Will add it.

**Comment by chrhol** [comment] 2015-12-16 08:53
I think I'm just about finished with this issue. I added a regressiontest for testing the parts of the schemaupgrades that we support and that tests that no data is lost. 

Got some weird problem when both SO and Simplified is loaded so want to investigate that a bit before I merge my branch to PNext in case I messed something up.

**Comment by k-rus** [comment] 2015-12-16 09:32
There are schema upgrade regression tests in TestApps, like 3LevelSchemChange. You can use them to test and you can add more regression test based on your current tests in a similar way.

**Comment by chrhol** [comment] 2016-01-11 07:53
I think that everything is solved that we discussed in this issue. I consider it done and will close it.

> There are schema upgrade regression tests in TestApps, like 3LevelSchemChange. You can use them to test and you can add more regression test based on your current tests in a similar way.

I've readded those tests as well as my own test. They are currently running (and succeeding). Can be found in Level1 repo under `src\Tests`

**Closed** 2016-01-11 07:53 UTC
Labels: BAH
