### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by andwah** [Starcounter/Starcounter#2515] opened 2015-01-26 14:47 UTC
Start the launcher and navigate to
```
http://localhost:8080/launcher/workspace/
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Json.UpgradeToStateful() in c:\github\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 309
   at Starcounter.Json.UpgradeToStateful() in c:\github\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 322
   at Starcounter.Json.UpgradeToStateful() in c:\github\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 313
   at Starcounter.Json.UpgradeToStateful() in c:\github\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 322
   at Starcounter.Json.SetParent(Json value) in c:\github\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 298
   at Starcounter.Json.set_Parent(Json value) in c:\github\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 272
   at Starcounter.Templates.TContainer.UpdateParentAndIndex(Json parent, Json newValue) in c:\github\Level1\src\Starcounter.XSON\Templates\Foundation\TContainer.cs:line 148
   at Starcounter.Templates.TObject.SetParentAndUseCustomSetter(Json parent, Json value) in c:\github\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 163
   at Starcounter.Templates.TObject.BoundOrUnboundSet(Json parent, Json value) in c:\github\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 140
   at Launcher.workspacesElementJson.set_master(Json value) in c:\github\Polyjuice\Launcher\obj\x64\Debug\Server\server\Launcher.json:line 34
   at Launcher.WorkspaceResponse(String appName, String uri) in c:\github\Polyjuice\Launcher\Server\Launcher.json.cs:line 209
   at Launcher.<Main>b__9(String appName) in c:\github\Polyjuice\Launcher\Server\Launcher.json.cs:line 125
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegates(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, HandlerOptions handlerOptions) in c:\github\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 230
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req, HandlerOptions handlerOptions) in c:\github\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 139
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\github\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 223
HResult=-2147467261

More information about this error may be available in the server error log.
```

**Comment by chrhol** [comment] 2015-03-19 12:56
Not able to reproduce it using the latest version, so probably fixed already. Will close this issue.

**Closed by chrhol** 2015-03-19 12:56 UTC
Labels: bug
