### ISSUE TITLE
Populate data from other typed JSON object

### ISSUE THREAD

**Issue by peterbergman** [Starcounter/Starcounter#2734] opened 2015-05-26 18:04 UTC
Hi,

I have a use case where I need to populate the data in one typed JSON object with the data from another typed JSON object of the same type. I need to do this from within the code behind class.

The following code worked on Starcounter DevelopNightlyBuilds-2.0.3004.

Code behind for JSON2:
```c#
site.Data = json1.site;
```

JSON1:
```json
{
	id: "",
	site: {
		$: {Reuse: "Protocol.Site"}
	},
	user: {
		$: {Reuse: "Protocol.User"}
	}
}
```

JSON2:
```json
{
	nbr: 0,
	sitenr: 0,
	site: {
		$: {Reuse: "Protocol.Site"}
	}
}

```

However, after upgrading to DevelopNightlyBuilds-2.0.3179 the assignment above throws an InvalidCastException with the following message:  "Unable to cast object of type 'Schema' to type 'Starcounter.Templates.TObject'."  

Maybe assigning site.Data like I have done above is the wrong way of doing it. Is there another way of achieving this?

**Comment by chrhol** [comment] 2015-05-27 06:07
We have not yet fully decided if it should be allowed to use one typedjson as dataobject to another, currently there are no restrictions but this might change later.

It's hard to say if there is a better way to do this, I will have to see a more full sample. Is it possible to just assign/move `json1.site` to `site` instead?

As for the exception, this looks like something I caused when implementing primitive arrays and single values, I will take a look on that one.

**Comment by chrhol** [comment] 2015-05-27 06:51
Could you add the full stacktrace of this exception as well? There are several places that this could happen and I'm having some trouble reproducing it.

**Comment by peterbergman** [comment] 2015-05-27 09:54
Full stack trace:
```
   at Starcounter.Json.<set_Data>b__7(Json j, Object v) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3179.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 42
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3179.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 47
   at Starcounter.Json.set_Data(Object value) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3179.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 38
   at Starcounter.Json.CheckBoundArray(IEnumerable boundValue) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3179.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 337
   at Starcounter.Json.Refresh(Template property) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3179.3\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 260
   at Starcounter.Json.InitBoundArrays(TObject template) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3179.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 133
   at Starcounter.Json.InternalSetData(Object data, TObject template, Boolean readOperation) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3179.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 95
   at Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3179.3\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 47
   at Starcounter.Json.set_Data(Object value) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3179.3\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:line 38
   at DRTB.Protocol.BidRequestInfo.PopulateFromBidRequestOpenRTB(BidRequestOpenRTB json, RequestItemContainer requestItemContainer, Int32 tmaxi) in c:\Users\Peter\Development\Git\DRTB\DRTB\DRTB\Protocol\BidRequestInfo.json.cs:line 23
   at Broadcaster.BroadcasterApp.SendBidRequestInfo(BidRequestOpenRTB json, RequestItemContainer requestItemContainer, Int32 tmaxi) in c:\Users\Peter\Development\Git\DRTB\Broadcaster\Broadcaster\BroadcasterApp.cs:line 184
   at Broadcaster.BroadcasterApp.<>c__DisplayClassb.<HandleBidRequestOpenRTB>b__9() in c:\Users\Peter\Development\Git\DRTB\Broadcaster\Broadcaster\BroadcasterApp.cs:line 77
   at Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3179.3\Level1\src\Starcounter\Db.cs:line 192
```

If I do ```site = json.site``` then I get the same error as with ```site.Data = json1.site```
However, I think I tired that prior to updating to 2.0.3179 and then I got an exception with a message saying something like "Cannot change parent of objects in Typed JSON trees".

**Comment by chrhol** [comment] 2015-05-28 06:08
Thank you! I think I found the place that fails. I will set up a test for it and push a fix a bit later today.

**Comment by chrhol** [comment] 2015-05-28 07:24
I've pushed a fix for this issue to develop now. Was a problem when setting the Data-property and the json was not an object.

> If I do site = json.site then I get the same error as with site.Data = json1.site
However, I think I tired that prior to updating to 2.0.3179 and then I got an exception with a message saying something like "Cannot change parent of objects in Typed JSON trees".

Ahh right, we don't allow moving json between two trees. Maybe this is something we should think of supporting to have a better way to move values like in this example.

**Closed by chrhol** 2015-05-28 07:24 UTC
Labels: bug, Typed JSON

**Comment by peterbergman** [comment] 2015-05-28 08:23
Ok, great, thanks! 

Yes, I think it would make it more flexible to be able to move objects between trees.

**Comment by peterbergman** [comment] 2015-05-28 15:05
I downloaded the latest version (2.0.9733.2) from the DevelopDailyBuilds channel to test this fix. It doesn't throw the exception anymore so thats good. 

But if I have a field with a primitive array in ```Protocol.Site``` then it does not get populated when I do ```site.Data = json1.site``` (even if the array contains values in ```json1.site```). Can you have another look at it?

**Comment by peterbergman** [comment] 2015-06-16 12:33
Any updates on this? @chrhol have you had time to look at my last comment?
