### ISSUE TITLE
pnext: nightly build failed with timeout on load and latency

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#3331] opened 2016-02-02 07:18 UTC
[this build](https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=717#_focus=10024)

**Comment by alemoi** [comment] 2016-02-11 23:13
Thank you for reporting. I looked in the build log and I don't think anything is wrong with the test - it just took more time than allowed (15000 seconds). The database maybe become slower or something. Now since everything is fine with nightly runs - I will close the issue, since its not reproducible.

**Closed by alemoi** 2016-02-11 23:13 UTC
Labels: P/High
